### ISSUE TITLE
Help  throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.U                   UID);

### ISSUE THREAD

**Issue by Flawl3ssSWE** [nfarina/homebridge#1004]
Hi!
I have a problem. The problem is that HomeBridge wont start! I get this long error message:
[Thu Dec 22 2016 19:54:39 GMT+0000 (UTC)] Initializing platform accessory 'Lamp'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.U                   UID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: bbf736b4-992f-431b-8b13-554c5b                   43c233
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Acces                   sory.js:222:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Acc                   essory.js:268:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:77:13)
    at API.emit (events.js:169:7)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:155:8)
    at cmdSwitchPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:67:14)
    at cmdSwitchPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:36:37)
    at emitNone (events.js:67:13)

Is this because I have booth HAP-NodeJS and HomeBridge on my pi. Or do one of you out there know how to fix this error. I am trying to get 433mhz plugs to work with this guide: https://timleland.com/use-siri-to-control-wireless-power-outlets-homebridge/ and https://timleland.com/wireless-power-outlets/comment-page-9/ . So I wonder if someone can help me to fix this error asap.

Pre Thanks!

**Comment by Flawl3ssSWE** [comment]
Solved the problem

**Comment by ehusar** [comment]
Can you tell me how you solved this?  I can start everything up fine the first time. Then after a reboot I get the same message. I know why it is doing it and the only way I can solve it is to delete the persist folder and all files in the accessories folder.   

Please share your solution!

Thanks.

**Comment by fitzage** [comment]
@ehusar: For me, it ended up being some files in the `persist` and `accessories` folders in my homebridge folder that were causing some sort of issue due to caching. After screwing around with configs for hours, I deleted everything in both those folders, restarted homebridge, and all was back to normal.
