### ISSUE TITLE
Having this issue with plugin

### ISSUE THREAD

**Issue by rafacampoamor** [nfarina/homebridge#1034]
I'm getting  this error with the "People" plugin, and after it, the http server of Homebridge stop working and all accessories appear non responsive. Any clue?

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/util/eventedhttp.js:59:19)
    at HAPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:157:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:88:10)
```

**Comment by rafacampoamor** [comment]
This is the error log:

```
tail -f /var/log/homebridge.err
Sun, 01 Jan 2017 23:17:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:17:59 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:17:59 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:17:59 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:17:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:17:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:17:59 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:17:59 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:17:59 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:17:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:19:55 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:19:55 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:19:55 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:19:55 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:19:55 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:19:55 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:19:55 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:19:55 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:19:55 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:19:55 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:19:55 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:19:55 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:19:55 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:19:55 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:19:55 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] New connection from client
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP server listening on port 36546
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP request: /pair-verify
Sun, 01 Jan 2017 23:20:22 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Sun, 01 Jan 2017 23:20:22 GMT HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP Response is finished
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP request: /pair-verify
Sun, 01 Jan 2017 23:20:22 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Sun, 01 Jan 2017 23:20:22 GMT HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2
Sun, 01 Jan 2017 23:20:22 GMT HAPServer [CC:22:3D:E3:CE:30] Client A55CB009-5653-481D-A123-87F5AE8D8B98 verification complete
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP Response is finished
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP request: /accessories
Sun, 01 Jan 2017 23:20:22 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories
Sun, 01 Jan 2017 23:20:22 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP Response is finished
Sun, 01 Jan 2017 23:23:29 GMT EventedHTTPServer [::ffff:192.168.0.162] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sun, 01 Jan 2017 23:23:29 GMT EventedHTTPServer [::ffff:192.168.0.163] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sun, 01 Jan 2017 23:23:29 GMT EventedHTTPServer [::ffff:192.168.0.163] Client connection error: read ECONNRESET
Sun, 01 Jan 2017 23:23:29 GMT EventedHTTPServer [::ffff:192.168.0.163] Client connection closed
Sun, 01 Jan 2017 23:23:29 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP connection was closed
Sun, 01 Jan 2017 23:23:29 GMT EventedHTTPServer [::ffff:192.168.0.163] HTTP server was closed
Sun, 01 Jan 2017 23:23:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:23:59 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:23:59 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:23:59 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:23:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:23:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:23:59 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:23:59 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:23:59 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:23:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished
Sun, 01 Jan 2017 23:23:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics
Sun, 01 Jan 2017 23:23:59 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 01 Jan 2017 23:23:59 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true}]
Sun, 01 Jan 2017 23:23:59 GMT Accessory [Homebridge] Registering Characteristic "Occupancy Detected" for events
Sun, 01 Jan 2017 23:23:59 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished

```

**Comment by Neelrp12** [comment]
try this command
 sudo killall homebridge
than try running it again

**Comment by rafacampoamor** [comment]
It almost work, but suddenly it closes again. I don't see any abnormal error, and in the `tail` i don't get any news, but it's all non responsive again:

```
homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-01-02 00:42:37] Loaded plugin: homebridge-daylight
[2017-01-02 00:42:37] Registering accessory 'homebridge-daylight.Daylight'
[2017-01-02 00:42:37] ---
[2017-01-02 00:42:37] Loaded plugin: homebridge-hdmi
[2017-01-02 00:42:37] Registering accessory 'homebridge-hdmi.TV'
[2017-01-02 00:42:37] Registering accessory 'homebridge-hdmi.AMP'
[2017-01-02 00:42:37] ---
[2017-01-02 00:42:38] Loaded plugin: homebridge-people
[2017-01-02 00:42:38] Registering platform 'homebridge-people.People'
[2017-01-02 00:42:38] Registering accessory 'homebridge-people.PeopleAccessory'
[2017-01-02 00:42:38] Registering accessory 'homebridge-people.PeopleAllAccessory'
[2017-01-02 00:42:38] ---
[2017-01-02 00:42:38] Loaded plugin: homebridge-pi
[2017-01-02 00:42:38] Registering accessory 'homebridge-pi.PiTemperature'
[2017-01-02 00:42:38] ---
[2017-01-02 00:42:38] Loaded plugin: homebridge-samsungtv-control
[2017-01-02 00:42:38] Registering accessory 'homebridge-samsungtv.SamsungTV'
[2017-01-02 00:42:38] ---
[2017-01-02 00:42:39] Loaded plugin: homebridge-ssh
[2017-01-02 00:42:39] Registering accessory 'homebridge-ssh.SSH'
[2017-01-02 00:42:39] ---
[2017-01-02 00:42:40] Loaded plugin: homebridge-synology
[2017-01-02 00:42:40] Registering accessory 'homebridge-synology.Synology'
[2017-01-02 00:42:40] ---
[2017-01-02 00:42:40] Loaded config.json with 4 accessories and 0 platforms.
[2017-01-02 00:42:40] ---
[2017-01-02 00:42:40] Loading 4 accessories…
[2017-01-02 00:42:40] [Diskstation] Initializing Synology accessory…
[2017-01-02 00:42:40] [Temperatura Raspberry PI] Initializing PiTemperature accessory…
[2017-01-02 00:42:40] [Temperatura Raspberry PI] Model BCM2709/a02082 Serial 00000000aae0fcd3
[2017-01-02 00:42:40] [Tele] Initializing TV accessory…
[2017-01-02 00:42:40] [Plex mount] Initializing SSH accessory…
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-01-02 00:42:40] Homebridge is running on port 51826.
Device [RECORDINGDEVICE1] changed from 'unknown' to 'on'
HDMI ready…
Device [TV] changed from 'unknown' to 'on'
Device [CONSOLE] changed from 'unknown' to 'on'
[2017-01-02 00:43:35] [Diskstation] current power state is: true
[2017-01-02 00:43:37] [Diskstation] current power state is: true
[2017-01-02 00:43:40] [Diskstation] current power state is: true
```

**Comment by rafacampoamor** [comment]
Getting this on tail after rebooting:

```
tail -f /var/log/homebridge.err
Sun, 01 Jan 2017 23:48:07 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Sun, 01 Jan 2017 23:48:07 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 01 Jan 2017 23:48:07 GMT Accessory [Homebridge] Got Characteristic "On" value: on
Sun, 01 Jan 2017 23:48:07 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 01 Jan 2017 23:48:07 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 01 Jan 2017 23:48:10 GMT Accessory [Homebridge] Got Characteristic "On" value: true
Sun, 01 Jan 2017 23:48:10 GMT EventedHTTPServer [::ffff:192.168.0.162] Muting event '2.9' notification for this connection since it originated here.
Sun, 01 Jan 2017 23:49:07 GMT EventedHTTPServer [::ffff:192.168.0.162] Client connection closed
Sun, 01 Jan 2017 23:49:07 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP connection was closed
Sun, 01 Jan 2017 23:49:07 GMT EventedHTTPServer [::ffff:192.168.0.162] HTTP server was closed
```

**Comment by rafacampoamor** [comment]
`tail -f /var/log/homebridge.log
    └────────────┘     
                       
[2017-01-02 00:46:03] Homebridge is running on port 51826.
Device [RECORDINGDEVICE1] changed from 'unknown' to 'on'
HDMI ready...
Device [TV] changed from 'unknown' to 'on'
Device [CONSOLE] changed from 'unknown' to 'on'
[2017-01-02 00:48:07] [Temperatura Raspberry PI] Rasperberry Pi CPU/GPU temperature at 65.528
[2017-01-02 00:48:10] [Diskstation] current power state is: true
[2017-01-02 00:51:37] Got SIGTERM, shutting down Homebridge...
`

**Comment by Neelrp12** [comment]
you can try to delete the persist and config folders and then run home bridge again. If that doesnt work the try to install home bridge again.

**Comment by rafacampoamor** [comment]
Tried this. And to just install home bridge again. I can see the homebridge accessory on my home app but all of the other accessories are still non responsive. 

I have noticed that home bridge starts supposedly uninstalled plugins and i don't understand why. I'm pretty sure one of them are causing the issue.

Running it on debug mode i see it all stops working after the CONSOLE accessory its "on" (last line on this code), but i don't know where this accessory comes from.

```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-01-02 20:40:59] Loaded plugin: homebridge-daylight
[2017-01-02 20:40:59] Registering accessory 'homebridge-daylight.Daylight'
[2017-01-02 20:40:59] ---
[2017-01-02 20:40:59] Loaded plugin: homebridge-hdmi
[2017-01-02 20:40:59] Registering accessory 'homebridge-hdmi.TV'
[2017-01-02 20:40:59] Registering accessory 'homebridge-hdmi.AMP'
[2017-01-02 20:40:59] ---
[2017-01-02 20:40:59] Loaded plugin: homebridge-pi
[2017-01-02 20:40:59] Registering accessory 'homebridge-pi.PiTemperature'
[2017-01-02 20:40:59] ---
[2017-01-02 20:40:59] Loaded plugin: homebridge-samsungtv-control
[2017-01-02 20:40:59] Registering accessory 'homebridge-samsungtv.SamsungTV'
[2017-01-02 20:40:59] ---
[2017-01-02 20:41:01] Loaded plugin: homebridge-synology
[2017-01-02 20:41:01] Registering accessory 'homebridge-synology.Synology'
[2017-01-02 20:41:01] ---
[2017-01-02 20:41:01] Loaded config.json with 3 accessories and 0 platforms.
[2017-01-02 20:41:01] ---
[2017-01-02 20:41:01] Loading 3 accessories…
[2017-01-02 20:41:01] [Diskstation] Initializing Synology accessory…
[2017-01-02 20:41:01] [Temperatura Raspberry PI] Initializing PiTemperature accessory…
[2017-01-02 20:41:01] [Temperatura Raspberry PI] Model BCM2709/a02082 Serial 00000000aae0fcd3
[2017-01-02 20:41:01] [Tele] Initializing SamsungTV accessory…
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ***-**-*** │     
    └────────────┘     
                       
  EventedHTTPServer Server listening on port 51826 +0ms
[2017-01-02 20:41:01] Homebridge is running on port 51826.
Device [RECORDINGDEVICE1] changed from 'unknown' to 'on'
Device [TV] changed from 'unknown' to 'on'
HDMI ready…
  EventedHTTPServer [::ffff:192.168.0.162] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.0.162] HTTP server listening on port 36335 +7ms
  EventedHTTPServer [::ffff:192.168.0.165] New connection from client +25ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP server listening on port 37037 +3ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /pair-verify +45ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +26ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +95ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP request: /pair-verify +11ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +4ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP Response is finished +36ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP request: /pair-verify +63ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +9ms
  HAPServer [CC:22:3D:E3:CE:30] Client 374FC9C3-96AF-4DF8-B4AE-2581293C2516 verification complete +14ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP request: /accessories +12ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP Response is finished +17ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /pair-verify +85ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +2ms
  HAPServer [CC:22:3D:E3:CE:30] Client A55CB009-5653-481D-A123-87F5AE8D8B98 verification complete +11ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /accessories +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +10ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP request: /characteristics +45ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":18,"ev":true},{"aid":2,"iid":21,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":14,"ev":true},{"aid":4,"iid":14,"ev":true},{"aid":4,"iid":17,"ev":true}] +5ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +5ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +2ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.165] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +27ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":18,"ev":true},{"aid":2,"iid":21,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":14,"ev":true},{"aid":4,"iid":14,"ev":true},{"aid":4,"iid":17,"ev":true}] +5ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +182ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true},{"aid":2,"iid":12,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true},{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +0ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +0ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +12ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +13ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "On" for events +2ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics +12ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "On" for events +2ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP request: /characteristics?id=4.9 +589ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=4.9 +1ms
  Accessory [Homebridge] Getting value for Characteristic "On" +10ms
[2017-01-02 20:41:04] [Tele] TV is offline: 1
  Accessory [Homebridge] Got Characteristic "On" value: false +72ms
  EventedHTTPServer [::ffff:192.168.0.162] HTTP Response is finished +3ms
**Device [CONSOLE] changed from 'unknown' to 'on'**
```
