### ISSUE TITLE
Home bridge crashes - nest related?

### ISSUE THREAD

**Issue by PencilDH** [nfarina/homebridge#1048]
Hello,

I had my homebridge up and running for about2-3 months

This issues started  happening after New Years 

Now it happens straight after launching homebridge

'''
[1/6/2017, 3:00:14 AM] Current temperature for Hallway Thermostat is: 22.5 C
[1/6/2017, 3:07:43 AM] Current temperature for Hallway Thermostat is: 22 C
/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133
    this._pipeline.processIncomingMessage(message, callback, context);
                  ^

TypeError: Cannot read property 'processIncomingMessage' of undefined
    at instance.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:19)
    at instance._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at instance._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at instance.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at instance.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
'''

**Comment by walz911** [comment]
I'm having the exact same issue on my end with my Nest thermo :(

TypeError: Cannot read property 'processIncomingMessage' of undefined
    at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:19)
    at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)

**Comment by PencilDH** [comment]
If you check homebridge-nest plugin repo you will find many people with the same Issue 
https://github.com/KraigM/homebridge-nest

It seems to be problem Nest and the plugin doesn't handle it well causing home bridge to crash !

**Comment by PencilDH** [comment]
I managed to temporarily fix it as suggested by other users... Remove the Nest token from .json and this will cause the API to switch to the old unsupported Nest API and it will work for the time being

**Comment by simonrb2000** [comment]
That's funny my pi that controls my garage door and Nest has been crashing, must be that! I haven't had time to test yet. Although mine does drop back to legacy API anyways so not sure that helps.

Cheers

On 8 Jan 2017, at 14:22, Pencil DH <notifications@github.com<mailto:notifications@github.com>> wrote:


I managed to temporarily fix it as suggested by other users... Remove the Nest token from .json and this will cause the API to switch to the old unsupported Nest API and it will work for the time being

-
