### ISSUE TITLE
TypeError: service._assignIDs is not a function

### ISSUE THREAD

**Issue by Schnittcher** [nfarina/homebridge#1072]
Hello i am writing my own plugin.

But, I get the following error:

```
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:364
    service._assignIDs(identifierCache, this.UUID);
            ^

TypeError: service._assignIDs is not a function
    at Accessory._assignIDs (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:364:13)
    at Bridge.Accessory._assignIDs (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:371:15)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:456:8)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Can anybody help me?

**Comment by FeBe95** [comment]
Hi, how did you solve this issue?

**Comment by FeBe95** [comment]
Found it out myself:

```
getServices: function () {
    ....
    return [informationService, this.LightService];
},
```
`this.LightService` was missing in my code
