### ISSUE TITLE
Problems on startup

### ISSUE THREAD

**Issue by HairBear22** [nfarina/homebridge#1077]
When I run homebridge in terminal (I'm on mac) I get this error: `Error: Cannot find module 'commander'`

It's worked perfectly fine up until now, I updated some plugins and now it crashes on startup.

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/cli.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by Schnittcher** [comment]
I think the Homebridge use the commander module.
Try to install it by hand.

https://www.npmjs.com/package/commander

**Comment by HairBear22** [comment]
Fixed it - had to install a few dependencies.
