### ISSUE TITLE
Error command "pm2 startup" on Freenas Jail 9.10

### ISSUE THREAD

**Issue by Pierrenato** [nfarina/homebridge#1079]
Hi i follow the guide for install homebridge in Freenas 9.10 and i have error :

root@homebridge:/ # pm2 startup
[PM2][ERROR] Init system not found
/usr/local/lib/node_modules/pm2/lib/API/Startup.js:168
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at module.exports.CLI.startup (/usr/local/lib/node_modules/pm2/lib/API/Startup.js:168:13)
    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:568:9)
    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:458:21)
    at Timeout._onTimeout (/usr/local/lib/node_modules/pm2/bin/pm2:175:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
root@homebridge:/ #

**Comment by conc2017** [comment]
Freenas is based on Freebsd which uses rc.d scripting. Use the "rcd" platform in the pm2 startup as referenced in http://pm2.keymetrics.io/docs/usage/startup/

Try this:
root@homebridge:/ # pm2 startup rcd
root@homebridge:/ # sysrc pm2_enable="YES"

After your config.json file is built:
root@homebridge:/ # pm2 start homebridge -- -D
root@homebridge:/ # pm2 save

BTW if you ever upgrade to a Freenas 9.3, the same error occurs in a Jail.
