### ISSUE TITLE
json error?

### ISSUE THREAD

**Issue by SgtHobNob** [nfarina/homebridge#1094]
Hello,

Homebridge/Pi newb here... i've been trying to get homebridge up and running with my Raspberry Pi 2B and my Nest thermostat. I've encountered a few issues but this one has me stumped, any suggestions would be greatly appreciated!

Thanks in advance :)

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[1/29/2017, 11:38:49 PM] Loaded plugin: homebridge-nest
[1/29/2017, 11:38:49 PM] Registering platform 'homebridge-nest.Nest'
[1/29/2017, 11:38:49 PM] ---
[1/29/2017, 11:38:49 PM] There was a problem reading your config.json file.
[1/29/2017, 11:38:49 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[1/29/2017, 11:38:49 PM] 
/usr/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token   in JSON at position 453
    at Object.parse (native)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

My config file...

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{

	}],

	"platforms": [{
		"platform": "Nest",
		"token" : "c.N9YZ4RqBUr2Aga",
		"clientId": "7c1e9dbe-7105-47d7-a6ae-2c1f********",
		"clientSecret": "guz5vIoE5IwF67SdJ********",
		"code": "66X",
		"username" : "EMAIL,
		"password" : "PASSWORD"  
	}]
}

**Comment by maplesteve** [comment]
The config for the `accessories` is wrong. Just write `"accessories": [],`. The `{}` are only used, if you really want to define an accessory.

**Comment by josephswebpagegames** [comment]
I had a similar issue.  Mine was:
```
[1/29/2017, 8:01:22 PM] Loaded plugin: homebridge-hue
[1/29/2017, 8:01:22 PM] Registering platform 'homebridge-hue.Hue'
[1/29/2017, 8:01:22 PM] ---
[1/29/2017, 8:01:22 PM] There was a problem reading your config.json file.
[1/29/2017, 8:01:22 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[1/29/2017, 8:01:22 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 258
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by josephswebpagegames** [comment]
The config.json is 

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CENSORED",
>         "port": CENSORED,
>         "pin": "CENSORED"
>     },
>     
>     "description": "This is the configuration file for my HomeBridge.",
> 
>     "platforms": [
>     "platform": "Hue",
>     "name": "Hue",
>     "users": {
>       "CENSORED": "CENSORED"
>     }
>   ]
> }
>

**Comment by maplesteve** [comment]
If you have an accessory or platform, then each of them must be a JSON object enclosed by { and }. If not, is simply an empty array [].

Please use the linter which is mentioned in the error message. It'll tell you, what's wrong.

**Comment by Neelrp12** [comment]
SgtHobNob try this config file with you info.

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{

	}],

	"platforms": [{
		"platform": "Nest",
		"token": "c.N9YZ4RqBUr2Aga",
		"clientId": "7c1e9dbe-7105-47d7-a6ae-2c1f********",
		"clientSecret": "guz5vIoE5IwF67SdJ********",
		"code": "66X",
		"username": "EMAIL",
		"password": "PASSWORD"
	}]
}

**Comment by Neelrp12** [comment]
josephswebpagegames try this config file with your info

{
	"bridge": {
		"name": "Homebridge",
		"username": "CENSORED",
		"port": "CENSORED",
		"pin": "CENSORED"
	},

	"description": "This is the configuration file for my HomeBridge.",

	"platforms": [{
		"platform": "Hue",
		"name": "Hue"
	}]
}

**Comment by snowdd1** [comment]
Can you all enclose json code in three back ticks ` in extra lines please?
