### ISSUE TITLE
Devices do not respond

### ISSUE THREAD

**Issue by baakoo** [nfarina/homebridge#1099]
Hi guys,
i run homebridge on a raspberry pi 2. Everything went fine. Since a few days my devices do not respond. I tried to restart homebridge, deleted accessories and persists folder and changed my username in the config.json file. 
What finally helped was to delete my home in home app on iPhone iOS10. Everything went fine for 12 hours and now my devices aren't responding anymore. 

The only thing i changed before that issue was to update npm to version 4.1.2 and homebridge-homematic to 0.0.66

I run homebridge with homematic, sonos and hue plugin. 
In the log (i hope i did it right) i found 
```
****************************************************************************************************************************
[2017-01-30 19:52:27] [HomeMatic CCU] *  Sorry the local port 9090 on your system is in use. Please make sure, that no other instance of this plugin is running.
[2017-01-30 19:52:27] [HomeMatic CCU] *  you may change the initial port with the config setting for local_port in your config.json 
[2017-01-30 19:52:27] [HomeMatic CCU] *  giving up ... the homematic plugin is not able to listen for ccu events on BidCos-RF. until you fix this. 
[2017-01-30 19:52:27] [HomeMatic CCU] ****************************************************************************************************************************
```
But Homebridge starts afterwards and then i get something like

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)

```

and 
Any idea?

**Comment by NorthernMan54** [comment]
The EADDRINUSE with 51826 indicates homebridge was already running.

Do you have a second copy of homebridge already running?

**Comment by baakoo** [comment]
I tried to figure it out but cannot see more than one homebridge. I tried to find it with "top" and tried sudo killall homebridge before running it again.

**Comment by NorthernMan54** [comment]
Try ps -ef | grep homebridge

**Comment by baakoo** [comment]
Thanks
```
pi       15303     1  0 19:36 ?        00:00:01 leafpad /home/pi/.homebridge/config.json
pi       15682     1  0 19:48 ?        00:00:11 leafpad /home/pi/Desktop/homebridgelog.txt
homebri+ 17768     1  5 21:12 ?        00:00:19 homebridge                                       
pi       17966 15122  0 21:18 pts/0    00:00:00 grep --color=auto homebridge

```

**Comment by baakoo** [comment]
Anyone an idea?  To me it looks as in there's only one instance? I'm really stuck

**Comment by snowdd1** [comment]
Yep, the other one died at starting. The one you are seeing is the one that blocks any other from starting.

**Comment by baakoo** [comment]
Sorry, this was my fault. The log crashes, because my default instance is running. When I close this instance, there seems to be know error in the log. Would you need the whole logfile (are there any private data in it)? I will now start homebridge in debug mode and pair make a new home in home kit and we will see what happen.

**Comment by baakoo** [comment]
Same again. After a few hours, home app cannot find the devices. I get 

 ```
 EventedHTTPServer [::ffff:192.168.172.55] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +4ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 192.168.172.65:1400
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

```

**Comment by NorthernMan54** [comment]
This message is saying that your device at 192.168.172.55 is unreachable.  You need to determine why that device is not responding.

**Comment by baakoo** [comment]
Thanks. Yes, i use systemd for startup. The device at 192.168.172.65 is a sonos bridge. Right now it is working again, surprise how long it lasts ... I report back.

**Comment by NorthernMan54** [comment]
Because you are using systemd, homebridge will automatically restart if it crashes, that is why you are getting the address in use error when you are starting manually.

For the problem with your sonos plugin, you should raise an issue with the sonos plugin developer for it crashing homebridge when it can't talk to a device.

**Comment by baakoo** [comment]
After uninstalling sonos Plugin everything seems  to be Fine. I have openend an issue with sonos plugin. Thanks all for your support. I close this issue.
