### ISSUE TITLE
Homebridge Errors

### ISSUE THREAD

**Issue by bachoo786** [nfarina/homebridge#1114]
Hi I am getting this error and not sure what wrong is in my config file as I have used atom editor and made sure json format is mainted. My error log is:

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2/4/2017, 12:39:08 PM] Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'.
[2/4/2017, 12:39:09 PM] Loaded plugin: homebridge-mqttswitch
[2/4/2017, 12:39:09 PM] Registering accessory 'homebridge-mqttswitch.mqttswitch'
[2/4/2017, 12:39:09 PM] ---
[2/4/2017, 12:39:10 PM] Loaded plugin: homebridge-samsungtv2016
[2/4/2017, 12:39:10 PM] Registering accessory 'homebridge-samsungtv.SamsungTV2016'
[2/4/2017, 12:39:10 PM] ---
[2/4/2017, 12:39:10 PM] There was a problem reading your config.json file.
[2/4/2017, 12:39:10 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2/4/2017, 12:39:10 PM] 
/usr/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token }
    at Object.parse (native)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

Can someone please help?

Thanks

**Comment by snowdd1** [comment]
> [2/4/2017, 12:39:10 PM] There was a problem reading your config.json file. [2/4/2017, 12:39:10 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com. 

Just do exactly that.

**Comment by Neelrp12** [comment]
Try this command

sudo killall homebridge

Then run hombridge again

**Comment by bachoo786** [comment]
fresh install of homebridge same error

**Comment by maplesteve** [comment]
Did you validate the config.json as @snowdd1 suggested?
