### ISSUE TITLE
Help needed with config file

### ISSUE THREAD

**Issue by stevens-r** [nfarina/homebridge#1129]
i cant figure how to properly add my wemo switch into the config file here is the error im getting and the file

Robs-Mac-mini:~ Rob$ homebridge
[2/10/2017, 4:10:33 PM] Loaded plugin: homebridge-platform-wemo
[2/10/2017, 4:10:33 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2/10/2017, 4:10:33 PM] ---
[2/10/2017, 4:10:33 PM] Loaded config.json with 1 accessories and 1 platforms.
[2/10/2017, 4:10:33 PM] ---
[2/10/2017, 4:10:34 PM] Loading 1 platforms...
[2/10/2017, 4:10:34 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[2/10/2017, 4:10:34 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'BelkinWeMo' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Robs-Mac-mini:~ Rob$ 

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "accessories": [
        {
            "accessory": "BelkinWeMo",
            "name": "Bedroom"

        }
    ],
    "platforms": [
      {
        "platform": "BelkinWeMo",
        "name": "WeMo Platform",
        "Expected_Accessories": "1"
      }
  ]

}

anyone know what i did wrong

**Comment by stevens-r** [comment]
if i remove the accessory from the config file the light works in the home app but Siri doesn't see any lights 

Robs-Mac-mini:~ Rob$ homebridge
[2/10/2017, 4:35:06 PM] Loaded plugin: homebridge-platform-wemo
[2/10/2017, 4:35:06 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2/10/2017, 4:35:06 PM] ---
[2/10/2017, 4:35:06 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/10/2017, 4:35:06 PM] ---
[2/10/2017, 4:35:06 PM] Loading 1 platforms...
[2/10/2017, 4:35:06 PM] [WeMo Platform] Initializing BelkinWeMo platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2/10/2017, 4:35:06 PM] Homebridge is running on port 51826.
[2/10/2017, 4:35:06 PM] [WeMo Platform] Online: bedroom [B4750E8FABFC]
[2/10/2017, 4:35:06 PM] [WeMo Platform] bedroom - Get state: On
[2/10/2017, 4:35:14 PM] [WeMo Platform] bedroom - Set state: Off
[2/10/2017, 4:35:14 PM] [WeMo Platform] bedroom - Get state: Off
[2/10/2017, 4:35:15 PM] [WeMo Platform] bedroom - Set state: On
[2/10/2017, 4:35:15 PM] [WeMo Platform] bedroom - Get state: On

**Comment by stevens-r** [comment]
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "Expected_Accessories": "1"
        }
    ]
}

**Comment by stevens-r** [comment]
have no idea why but this fixed everything

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"platforms": [
    {
        "platform": "BelkinWeMo",
        "name": "WeMo Platform",
        "Expected_Accessories": "1"
    }
]
}

**Comment by snowdd1** [comment]
Looks as if BelkinWeMo is a platform, not an accessory.
