### ISSUE TITLE
Failed with OSStatus code -6723 (Communication Failure)

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#113]
When Adding an Accessory i got this error message.  I have added this accessory before and it worked perfectly fine, I wonder what went wrong when adding it this time.

**Comment by nzhome** [comment]
oh and its gone out of the list.   I wonder if I got the code wrong by mistake?  now I can't recover... time for another reinstall :(

**Comment by nzhome** [comment]
all came crashing down now.

Server Connection Established 35889
Start Pair M1
Start Pair M3
/home/pi/node_modules/homebridge/node_modules/HAP-NodeJS/node_modules/srp/lib/srp.js:418
      throw new Error("client did not use the same password");
            ^
Error: client did not use the same password
    at Object.checkM1 (/home/pi/node_modules/homebridge/node_modules/HAP-NodeJS/node_modules/srp/lib/srp.js:418:13)
    at Object.processPairStepTwo (/home/pi/node_modules/homebridge/node_modules/HAP-NodeJS/Server.js:278:18)
    at Object.processPairSequence (/home/pi/node_modules/homebridge/node_modules/HAP-NodeJS/Server.js:238:11)
    at IncomingMessage.<anonymous> (/home/pi/node_modules/homebridge/node_modules/HAP-NodeJS/Server.js:39:17)
    at IncomingMessage.emit (events.js:107:17)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)

**Comment by nzhome** [comment]
took 24 minutes to reinstall.  it only does not corrupt if you enter the correct code every time.  if you enter the incorrect code, it gets corrupt and you can not get the accessory back :(

**Comment by nzhome** [comment]
the accessory added fine after I reinstalled homebridge again, I cleared homekit under privacy on the iphone, and I didn't have fat fingers this time and got the add accessory code correct.

**Comment by nfarina** [comment]
Try latest version of homebridge if you can.

**Comment by nzhome** [comment]
@nfarina yes I am using your new version ALWAYS. I would never log an issue unless I was using the latest.
rm -r homebridge, 
npm install homebridge


I will do it all again now.. just in case you changed or published something new in the 3 hours after I logged the issue?

**Comment by nzhome** [comment]
@nfarina, thanks for updating the npm install homebridge..  thats much better now.
"nfarina published 15 hours ago"  new https://www.npmjs.com/package/homebridge  
the new version comes via npm install, thanks.   I will close the issue.
