### ISSUE TITLE
Keep getting SyntaxError: Unexpected token <  even though I have a valid JSON

### ISSUE THREAD

**Issue by dtydings** [nfarina/homebridge#1136]
I haven't changed anything in my config.JSON since weeks ago and it's been working fine until today. Homebridge starts perfectly but the second I swipe up on my iphone to bring up the homekit/homebridge control center page I get this:

undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389197424586]</body></html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster/index.js:59:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Anyone else having this problem or know how to fix this?

**Comment by NorthernMan54** [comment]
Just looking at the error message, and it appears to be from the liftmaster plugin.  Can raise this as an issue there?

Sean

**Comment by dtydings** [comment]
hmm here is the liftmaster portion of my config:

{
			"accessory": "LiftMaster",
			"name": "Garage Door",
			"username": "username",
			"password": "password"
		}

**Comment by erfinb** [comment]
Mine is having the same issue. Wonder if something changed on their side.

**Comment by snowdd1** [comment]
Without having any liftmaster hardware, I would assume that 
```html
<title>Request Rejected</title>Your request has been denied.
```
is the answer of the liuftmaster service (locally or cloud), and as it says *"Your request has been denied"* I would assume that it for some reason is not happy with username/password - or their API has been changed and cannot process the request as it has been doing before.

**Comment by gminevich44** [comment]
Mine is doing the same thing.  In fact I just posted a new issue thread on it before I saw yours.  Is there something we can do?

**Comment by pponce** [comment]
Use homebridge-chamberlain plugin instead.
The api calls it uses appear to be working still.
Have had no issues since installing it.

**Comment by gminevich44** [comment]
That's funny.  I was actually at work today thinking maybe I should try that when I got home.  You're awesome.  Thanks.

**Comment by dtydings** [comment]
Oh great idea! I'd love to use this one, however I'm having trouble starting homebridge after installing the chamberlain one now.  
I used "sudo npm install -g homebridge-chamberlain" and have a valid json. I also updated homebridge and I'm still getting this:

Error: The requested accessory 'Chamberlain' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by gminevich44** [comment]
Post your config.json.  I'm guessing it still says liftmaster.

**Comment by dtydings** [comment]
Nahh I definitely deleted the liftmaster accessory section and added the chamberlain one:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:23:3D:E3:CE:30",
        "port": 51826,
        "pin": "131-45-154"
    },
    

    "accessories": [
     
     {
            "accessory": "Chamberlain",
            "name": "Garage Door",
            "username": "username",
            "password": "password"
     }

     
  
   ],


after this I have platforms, I just didn't include it since I didn't feel like blanking out the tokens and app id's but the JSON is most certainly valid, checked on jsonlint.com.

I just found this at the top of terminal when I scroll up after trying to start homebridge. Hopefully this is enough to figure out what's going on:

[2/16/2017, 9:23:16 AM] ====================
[2/16/2017, 9:23:16 AM] ERROR LOADING PLUGIN homebridge-chamberlain:
[2/16/2017, 9:23:16 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by mrquatsch** [comment]
I'm having the same issue. What version of node.js did you update to?

**Comment by AppleTechy** [comment]
Talked to the developer the plugin "Homebridge-chamberlain" requires node V6 and higher. Try updating node and your problem should be solved

**Comment by mrquatsch** [comment]
Awesome.

Updated to node v6.9.5, npm 3.10.10, rebuild all of my home bridge modules and that did the trick!

Thank you!

**Comment by sats4eva** [comment]
So I have node v 6.9.5
I can get it to show up in the home app but it shows as no response. I triple checked the credentials and it's correct. How did you rebuild and get it to work?

**Comment by sats4eva** [comment]
ok so i finally got it to work. Turns out i had my deviceId's reversed as i have two doors. Hopefully this one doesn't break.

**Comment by adammascherin** [comment]
I noticed the "Request Rejected" error was showing up in my logs a few days ago. I just tried switching to the homebridge-chamberlain plugin by running "sudo npm install -g homebridge-chamberlain" and adding the accessory to my config. After running homebridge, I'm getting the following error:

Error: Multiple controllable devices found: #######, #######, ######

The problem is, I only have 1 garage door. I tried specifying one of the IDs as the deviceId parameter, but it gave another error. Any ideas?

**Comment by dtydings** [comment]
You shouldn't have a deviceId parameter if you only have 1 garage door. Use this in your config instead:

{
  "accessory": "Chamberlain",
  "name": "Garage Door",
  "username": "your mychamberlain.com email",
  "password": "your mychamberlain.com password"
}

**Comment by adammascherin** [comment]
dtydings, as I said, that's what I tried first. And it gave me the "Multiple controllable devices found" error.

**Comment by dtydings** [comment]
Well, it's 26 days later and I've now started having this problem with the chamberlain plugin even though I haven't changed absolutely anything since weeks ago and I still have a valid JSON:

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:103:7)


Maybe something changed on Chamberlain's end?
