### ISSUE TITLE
Issue with Homebridge

### ISSUE THREAD

**Issue by gminevich44** [nfarina/homebridge#1138]
So i was running Homebridge successfully on my Mac for several days, with only a single MiLight platform (2 bulbs) and a single LiftMaster accessory.  Everything was working amazingly... until it just stopped working one day.  I've tried reinstalling everything and I get the same issue.  It seems as though the issue has something to do with the LiftMaster because when I start homebridge in terminal and toggle the lights that doesn't give me a problem, but as soon as I do anything with the garage door I got the following below the "Homebridge is running on port 65371.":

undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389238339283]</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster/index.js:59:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Minevich-Family-iMac:~ Minevich$ 

I've tried uninstalling homebridge-liftmaster and replacing it with homebridge-liftmaster2 but that won't even let me get into homebridge at all.  Has anyone else experienced a problem like this?  Any thoughts?  Thank you!

**Comment by NorthernMan54** [comment]
There have been several reports of the liftmaster plugin not working in the last couple days, rumor is that the API key has been revoked.

**Comment by snowdd1** [comment]
Duplicate to 
#1136  
recommend closing this one
