### ISSUE TITLE
Not detecting Homebridge accessory

### ISSUE THREAD

**Issue by HA-Enthusiast** [nfarina/homebridge#1147]
I've tried fresh installs of even my OS on my RPi3 just to see if I could figure out what was going wrong (Homebridge is the main reason I bought an RPi 3).  

All I have running as a platform in my config.json file is homebridge-nest. I did have Veralink running, but something is screwy with the code, currently. 

I have also tried deleting my Persist and Accessory folders and restarting Homebridge... to no avail. I have deleted my current "Home" in the Home app to see if starting from scratch worked.... to no avail. My Home app still doesn't recognize any accessory when homebridge is successfully running on my RPi 3.  Note: my phone and my RPi 3 are both on the same network, so I don't think that is an issue.  

What am I doing wrong?? Why won't the home app recognize Homebridge as an accessory?? Do I have to let it run for a certain amount of time before it will recognize it?

**Comment by brownad** [comment]
Any logs?

**Comment by HA-Enthusiast** [comment]
Where do I grab the logs? Or, how?

**Comment by brownad** [comment]
Look at the console output when you start it up e.g. homebridge -D it's on the docs how to get the log files 

https://github.com/nfarina/homebridge/wiki/Basic-Trouble-Shooting

**Comment by HA-Enthusiast** [comment]
Is this what you're looking for?

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2/18/2017, 12:52:26 PM] Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'.
[2/18/2017, 12:52:28 PM] Loaded plugin: homebridge-nest
[2/18/2017, 12:52:28 PM] Registering platform 'homebridge-nest.Nest'
[2/18/2017, 12:52:28 PM] ---
[2/18/2017, 12:52:28 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/18/2017, 12:52:28 PM] ---
[2/18/2017, 12:52:28 PM] Loading 1 platforms...
[2/18/2017, 12:52:28 PM] Initializing Nest platform...
[2/18/2017, 12:52:28 PM] Fetching Nest devices.
[2/18/2017, 12:52:28 PM] Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API
    at /usr/lib/node_modules/homebridge-nest/index.js:80:11
    at setupConnection (/usr/lib/node_modules/homebridge-nest/index.js:64:9)
    at Object.accessories (/usr/lib/node_modules/homebridge-nest/index.js:143:3)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[2/18/2017, 12:52:28 PM] Falling back to legacy API.
[2/18/2017, 12:52:29 PM] Away for Nest09AA01AC291514U0 is: false
[2/18/2017, 12:52:29 PM] Temperature unit for Nest09AA01AC291514U0 is: Fahrenheit
[2/18/2017, 12:52:29 PM] Current temperature for Nest09AA01AC291514U0 is: 15.87
[2/18/2017, 12:52:29 PM] Current heating for Nest09AA01AC291514U0 is: 0
[2/18/2017, 12:52:29 PM] Current humidity for Nest09AA01AC291514U0 is: 64
[2/18/2017, 12:52:29 PM] Target heating for Nest09AA01AC291514U0 is: 0
[2/18/2017, 12:52:29 PM] Target temperature for Nest09AA01AC291514U0 is: 19
[2/18/2017, 12:52:29 PM] Initializing platform accessory 'Nest09AA01AC291514U0'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
[2/18/2017, 12:52:29 PM] Homebridge is running on port 51826.

**Comment by brownad** [comment]
Looks like nest is falling back to legacy api, follow the steps correctly to use token instead.  But looks to load correctly.

So you don't see homebridge at all in your HomeKit?

iCloud is correctly setup and with 2fa?

**Comment by HA-Enthusiast** [comment]
The authentication issue with the Nest plugin has always been an issue. I don't really like the new API. 

Otherwise, no. I never see it show up in Homekit. I have 2fa setup and enabled...

Could this be a problem? 

" Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'."

**Comment by brownad** [comment]
Check node version is correct as per homebridge docs.

I assume you've never got this running yet?

**Comment by HA-Enthusiast** [comment]
I did once on my Mac. How do I check Node version?

**Comment by brownad** [comment]
Node -v

In that case follow homebridge setup from beginning and ensure you have right node version running

**Comment by HA-Enthusiast** [comment]
v6.9.5???

Shouldn't it be working with that version?

**Comment by HA-Enthusiast** [comment]
Okay. So I just started from scratch. Node version I am using is v6.10.0.

Homebridge starts just fine. Absolutely no errors. But I'm still having the same problem. My iPhone won't detect the homebridge accessory. I'm not sure what's wrong, here....

**Comment by jdshkolnik** [comment]
Deleting the persist and accessories folders usually gets it working for a little bit but then it invariably fails again.

**Comment by HA-Enthusiast** [comment]
It hasn't even worked once for me...

**Comment by jdshkolnik** [comment]
Shot in the dark but could it be a wifi 2.4ghz vs 5ghz thing?

**Comment by HA-Enthusiast** [comment]
Good question. 

To my knowledge, RPI 3 uses 2.4ghz. My phone is on the same network. I don't think the presence of the 5ghz network should actually affect anything.

**Comment by jdshkolnik** [comment]
I would expect the same, yet some routers have AP isolation which segregates. I've also had instances where my router acts as if isolation is on even when not. It gets even more mangled if you have an extender around.

**Comment by HA-Enthusiast** [comment]
I've gotten this working on the same network using the same router, only running homebridge on a Mac instead of an RPI. 

I honestly think it has less to do with hardware and more to do with some unknown bug or configuration setting.

**Comment by arrikhan** [comment]
I have the same problem, although it doesn't show up PIN in startup comparing my logs to your logs. Any logs or info I can provide to help root out this problem please advise. 

I'm running on an RPi3, have tried changing username, changing PIN, deleting persist dir, uninstalling and reinstalling homebridge. When startup shows the PIN, I can usually see accessories to add to 'home' on phone, but I cannot even get back to that position.

**Comment by rmadrid20** [comment]
Did any of you got this working? I have the same issue....

**Comment by fnchacon** [comment]
The issue is that the Nest API needs to be set to obtain the ProductId, ClientId ProductSecret, Code and Token. Here is a guide on how to do it: 

https://www.studiopieters.nl/apple-homebridge-nest-intergration/
