### ISSUE TITLE
Homebridge is crashing on my Raspberry Pi 3

### ISSUE THREAD

**Issue by Neelrp12** [nfarina/homebridge#1148]
This is what homebridge is going.

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/17/2017, 9:41:04 PM] Loaded plugin: homebridge-homeassistant
[2/17/2017, 9:41:04 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2/17/2017, 9:41:04 PM] ---
[2/17/2017, 9:41:05 PM] Loaded plugin: homebridge-liftmaster
[2/17/2017, 9:41:05 PM] Registering accessory 'homebridge-liftmaster.LiftMaster'
[2/17/2017, 9:41:05 PM] ---
[2/17/2017, 9:41:06 PM] Loaded plugin: homebridge-nest
[2/17/2017, 9:41:06 PM] Registering platform 'homebridge-nest.Nest'
[2/17/2017, 9:41:06 PM] ---
[2/17/2017, 9:41:06 PM] Loaded config.json with 1 accessories and 2 platforms.
[2/17/2017, 9:41:06 PM] ---
[2/17/2017, 9:41:06 PM] Loading 2 platforms...
[2/17/2017, 9:41:06 PM] Initializing Nest platform...
[2/17/2017, 9:41:06 PM] Fetching Nest devices.
[2/17/2017, 9:41:06 PM] [HomeAssistant] Initializing HomeAssistant platform...
[2/17/2017, 9:41:07 PM] [HomeAssistant] Fetching HomeAssistant devices.
[2/17/2017, 9:41:07 PM] Loading 1 accessories...
[2/17/2017, 9:41:07 PM] [Garage Door Opener] Initializing LiftMaster accessory...
[2/17/2017, 9:41:07 PM] [HomeAssistant] Received event: ping
[2/17/2017, 9:41:07 PM] [HomeAssistant] Initializing platform accessory 'Front Door'...
[2/17/2017, 9:41:08 PM] Software version for Upstairs Thermostat is: 5.6-7
[2/17/2017, 9:41:08 PM] Temperature unit for Upstairs Thermostat is: Fahrenheit
[2/17/2017, 9:41:08 PM] Current temperature for Upstairs Thermostat is: 70 F
[2/17/2017, 9:41:08 PM] Current humidity for Upstairs Thermostat is: 45%
[2/17/2017, 9:41:08 PM] Target temperature for Upstairs Thermostat is: 65 F
[2/17/2017, 9:41:08 PM] Target heating for Upstairs Thermostat is: Heating
[2/17/2017, 9:41:08 PM] Away for Upstairs Thermostat is: 0
[2/17/2017, 9:41:08 PM] Software version for Downstairs Thermostat is: 5.6-7
[2/17/2017, 9:41:08 PM] Temperature unit for Downstairs Thermostat is: Fahrenheit
[2/17/2017, 9:41:08 PM] Current temperature for Downstairs Thermostat is: 69 F
[2/17/2017, 9:41:08 PM] Current humidity for Downstairs Thermostat is: 40%
[2/17/2017, 9:41:08 PM] Target temperature for Downstairs Thermostat is: 68 F
[2/17/2017, 9:41:08 PM] Target heating for Downstairs Thermostat is: Heating
[2/17/2017, 9:41:08 PM] Away for Downstairs Thermostat is: 0
[2/17/2017, 9:41:08 PM] Software version for Upstairs Nest Protect is: 3.1rc9
[2/17/2017, 9:41:08 PM] Initializing platform accessory 'Upstairs Thermostat'...
[2/17/2017, 9:41:08 PM] Initializing platform accessory 'Downstairs Thermostat'...
[2/17/2017, 9:41:08 PM] Initializing platform accessory 'Upstairs Nest Protect'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 987-65-432 │     
    └────────────┘     
                       
[2/17/2017, 9:41:08 PM] Homebridge is running on port 51826.
[2/17/2017, 9:41:11 PM] [HomeAssistant] Received event: {"time_fired": "2017-02-18T02:41:11.518717+00:00", "event_type": "state_changed", "data": {"entity_id": "media_player.neels_apple_tv", "new_state": {"entity_id": "media_player.neels_apple_tv", "last_updated": "2017-02-18T02:41:11.518611+00:00", "last_changed": "2017-02-18T02:38:15.882046+00:00", "state": "paused", "attributes": {"supported_features": 21043, "media_title": "No title", "media_position_updated_at": "2017-02-18T02:41:11.518223+00:00", "media_duration": 0, "friendly_name": "Neel's Apple TV", "media_position": 0, "media_content_type": "movie"}}, "old_state": {"entity_id": "media_player.neels_apple_tv", "last_updated": "2017-02-18T02:41:00.531529+00:00", "last_changed": "2017-02-18T02:38:15.882046+00:00", "state": "paused", "attributes": {"supported_features": 21043, "media_title": "No title", "media_position_updated_at": "2017-02-18T02:41:00.531069+00:00", "media_duration": 0, "friendly_name": "Neel's Apple TV", "media_position": 0, "media_content_type": "movie"}}}, "origin": "LOCAL"}
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389366450653]</body></html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster/index.js:59:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

This is my config file

{
	"bridge": {
		"name": "BatHome",
		"username": "AC:BC:32:CF:27:6D",
		"port": 51826,
		"pin": "987-65-432"
	},

	"accessories": [{

		"accessory": "LiftMaster",
		"name": "Garage Door Opener",
		"username": "********",
		"password": "********"
	}],

	"platforms": [{
		"platform": "Nest",

		"token": "********",

		"clientId": "********",
		"clientSecret": "********",
		"code": "********",

		"username": "********",
		"password": "********"
	}, {
		"platform": "HomeAssistant",
		"name": "HomeAssistant",
		"host": "********",
		"password": "********",
		"supported_types": ["fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "switch"]
	}]

}
 

What am I am doing wrong?

**Comment by brownad** [comment]
Check node version is correct as per docs. And try without homeassitant plugin, then eliminate each plugin one by one.

One of them is hurting you

**Comment by snowdd1** [comment]
It's liftmaster, see #1136  

I recommend closing this duplicate.

**Comment by Neelrp12** [comment]
I used a different plugin and it worked.
https://github.com/luisiam/homebridge-liftmaster2
