### ISSUE TITLE
Homebridge not discoverable

### ISSUE THREAD

**Issue by bachoo786** [nfarina/homebridge#1158]
Hi

I cannot find homebridge in my homekit app and as stated in the readme to resolve the issue I changed the username rebooted the pi but had the same issue. So the other solution as per the readme file was to delete the “persist/“ folder which I have and rebooted the pi but still no joy.

Can anyone help me please?

Thanks

**Comment by joshhighet** [comment]
What are the current contents of your .homebridge folder?

**Comment by bachoo786** [comment]
Currently I have accessories folder and config.json

**Comment by bachoo786** [comment]
Right so I ran homebridge manually by typing “homebridge” on my terminal of my raspberry pi and I get the following errors:

Error: EACCES: permission denied, open '/home/pi/.homebridge/persist/AccessoryInfo.AA223DE3CE30.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.persistKeySync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
    at Object.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
    at Object.nodePersist.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:99:29)
    at AccessoryInfo.save (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:161:11)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:439:23)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14)

Also if I type “sudo homebridge” I get the following errors:

[2/23/2017, 7:15:49 PM] config.json (/root/.homebridge/config.json) not found.
Load homebridge-mqtt.mqtt
[2/23/2017, 7:15:49 PM] [homebridge-mqtt.mqtt] config undefined or null!
[2/23/2017, 7:15:49 PM] [homebridge-mqtt.mqtt] storagePath = /root/.homebridge

Mind you I have setup Homebridge to run on boot without any issues and when I check the log by "sudo journalctl -u homebridge” I get no errors. And when I check the status by "systemctl status homebridge” I get the following with no errors: 

● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Thu 2017-02-23 18:53:38 GMT; 23min ago
 Main PID: 505 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─505 homebridge

Can someone please help me?

Thanks.

**Comment by bachoo786** [comment]
I am getting these errors

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51111
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14)

Can someone please help?

**Comment by jdshkolnik** [comment]
For me it turned out to be the open ~/.homebridge/persist folder. Homebridge reappeared as an available accessory once I deleted that folder.
