### ISSUE TITLE
No response after updating

### ISSUE THREAD

**Issue by EVPilot** [nfarina/homebridge#1162]
Hello I just updated my homebridge and accessory plugins. After the update I get no response in HomeKit. All devices are visible just no response. I attempted to delete the persist and remove and re add the homebridge in HomeKit. Any ideas?

**Comment by EVPilot** [comment]
Did you ever solve your problem? I'm having the same issue. I'm going to try reinstalling the plugins.

**Comment by EVPilot** [comment]
Ha I just realized I commented on a post I made. I must be tired. Anyone else out there have a fix?

**Comment by EVPilot** [comment]
So I reinstalled home bridge and the plugins.
Im currently getting this error
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595390708907238]</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster/index.js:59:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by EVPilot** [comment]
Ok I think it was the lift master plugin. I installed it and installed liftmaster2. It worked thanks for the help everyone.
