### ISSUE TITLE
DNS Service error: name conflict

### ISSUE THREAD

**Issue by samuelandersson** [nfarina/homebridge#1166]
Hi!

I know people have had this problem before but their solutions did not seem to work for me, does anyone have any idea why this is happening:

/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

```
Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:539:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)
    at EventedHTTPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1285:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Here is my config.json:

`{
    "bridge": {
        "name": "Homebridge",
        "username": "//snip//",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
    ],

    "platforms": [
        {
            "platform" : "Telldus",
            "name" : "Telldus liv!e",
            "public_key" : "FEH*****U",
            "private_key" : "Z************U6EF",
            "token" : "28ed**********8254",
            "token_secret" : "ce4*************0ca1"
        }
    ]
}
`

**Comment by samuelandersson** [comment]
Issue solved. Changed name of the tells component.
