### ISSUE TITLE
Trouble launching Homebridge

### ISSUE THREAD

**Issue by spartanrob** [nfarina/homebridge#1171]
On a Pi3 and am getting the following error when trying to launch Homebridge.  Any help is appreciated:
SyntaxError: Unexpected string
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by spartanrob** [comment]
Updating with the complete text:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/26/2017, 11:56:06 AM] Loaded plugin: homebridge-netatmo
[2/26/2017, 11:56:06 AM] Registering platform 'homebridge-netatmo.netatmo'
[2/26/2017, 11:56:06 AM] ---
[2/26/2017, 11:56:06 AM] There was a problem reading your config.json file.
[2/26/2017, 11:56:06 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2/26/2017, 11:56:06 AM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected string
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by NorthernMan54** [comment]
Did you follow this step?

> [2/26/2017, 11:56:06 AM] There was a problem reading your config.json file.
> [2/26/2017, 11:56:06 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com <http://jsonlint.com/>

**Comment by spartanrob** [comment]
Yes I did. I simply renamed the sample (removed 'sample' from the file name

**Comment by NorthernMan54** [comment]
As the issue is within your config.json, please share it.

Tks

**Comment by spartanrob** [comment]
after more trial and error, if i run as sudo homebridge, it launches

**Comment by snowdd1** [comment]
You probably installed it globally (as root) and some of the files require now root rights. Especially the configuration files must allow read/write for the current user.  
Do not continually run any software as root!

**Comment by spartanrob** [comment]
Thanks. I may 'start over'
