### ISSUE TITLE
No unexpected errors... Homebridge not Detected

### ISSUE THREAD

**Issue by HA-Enthusiast** [nfarina/homebridge#1180]
My json file is just fine. No problems there. No problems/errors starting homebridge. Have tried deleting my existing "Home" and starting from scratch on my iPhone. No cigar. My nodejs version is v6.10.0. And I'm on the same wifi network with both my phone and RPI 3. 

My Home accessory will not recognize homebridge. I've started over 5 times and still no change. I've deleted persist and accessories folders. No change. 

What am I doing wrong? An interesting thing to note is that I don't have either /var/log/homebridge.log or /var/log/homebridge.err directories. Not sure what that means, but I went looking for them when I read over the troubleshooting page. Any help would be greatly appreciated.

**Comment by snowdd1** [comment]
how do you start homebridge? shell, systemd service, screen, forever,... there too many ways just to guess what you're doing.   

Example logs: If you've set up a proper systemd service (as described in the wiki), then the log is a syslog service and you'll see it in `sudo journald`

**Comment by HA-Enthusiast** [comment]
Thanks for the reply.

I start Homebridge with the standard "homebridge" command. Nothing fancy. When I was using my mac, I used forever, but not in this case (RPI 3). Here is my homebridge running: 

(NOTE: any errors related to Nest are due to me using the legacy API. The new API sucks, IMO. It's fine though because once the program realizes the new API isn't working, it just falls back to the old API, as noted in the log)

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[3/2/2017, 10:10:11 AM] Loaded plugin: homebridge-nest
[3/2/2017, 10:10:11 AM] Registering platform 'homebridge-nest.Nest'
[3/2/2017, 10:10:11 AM] ---
[3/2/2017, 10:10:14 AM] Loaded plugin: homebridge-vera
VeraLink initializing
[3/2/2017, 10:10:14 AM] Registering platform 'homebridge-veralink.Vera'
[3/2/2017, 10:10:14 AM] ---
[3/2/2017, 10:10:14 AM] Loaded config.json with 0 accessories and 2 platforms.
[3/2/2017, 10:10:14 AM] ---
[3/2/2017, 10:10:14 AM] Loading 2 platforms...
[3/2/2017, 10:10:14 AM] Initializing Vera platform...
[3/2/2017, 10:10:14 AM] Initializing Nest platform...
[3/2/2017, 10:10:14 AM] Fetching Nest devices.
[3/2/2017, 10:10:14 AM] Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API
    at /usr/lib/node_modules/homebridge-nest/index.js:80:11
    at setupConnection (/usr/lib/node_modules/homebridge-nest/index.js:64:9)
    at Object.accessories (/usr/lib/node_modules/homebridge-nest/index.js:143:3)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[3/2/2017, 10:10:14 AM] Falling back to legacy API.
we have a switch
we have a switch
we have a switch
we have a switch
we have a switch
we have a switch
we have a switch
Process Device 139: Christmas Tree Lights
Process Device 140: Door Notification
Process Device 141: Doorbell
Process Device 41: Fireplace Lights
Process Device 116: Fireplace Outlet
Process Device 74: Front Door
Process Device 77: Front Porch Lights
Process Device 75: Garage Light
Process Device 132: Kitchen Lights
Process Device 46: Left Deck Light
Process Device 3: Lndry/Grg Deadbolt
Process Device 131: Main Deck Light
Process Device 45: Right Deck Light
Process Device 123: WeMo 1
Process Device 124: WeMo 2
Process Device 53: 10m then Lights Off - Night Mode
Process Device 21: Alarm On > Lights On
Process Device 61: Auto Kitchen Lights OFF
Process Device 32: Auto Lock - Front Door
Process Device 43: Auto Lock - Laundry/Garage
Process Device 18: Auto Sleep Mode
Process Device 39: Chime - Door Open
Process Device 24: Deck Lights Off
Process Device 22: Deck Lights On
Process Device 27: Dyanna home.
Process Device 48: Eric at Home.
Process Device 14: Front Door Opened!
Process Device 46: Garage Light On - Auto
Process Device 60: Kitchen Lights On - Motion
Process Device 47: Late Night Home 2
Process Device 28: Late Night Home w/out Bedroom L
Process Device 54: Matandikas Home
Process Device 26: Miles home.
Process Device 49: Motion Detected
Process Device 52: Motion in Night Mode - Lights On
Process Device 31: Night Time - Deck Lights On
Process Device 23: Sliding Door Intruder Deck Light
Process Device 45: Sunrise - Porch Lights Off
Process Device 44: Sunset - Porch Lights On
Process Device 42: System Disarmed - Day
Process Device 51: System Disarmed - Night
Process Device 50: Temp > 85°F, Cool to 78°F
Process Device 33: Valenzuelas at home.
Process Device 38: Voice - Front Door
Process Device 37: Voice - Porch Door
Process Device 17: Waking Up
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Christmas Tree Lights'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Door Notification'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Doorbell'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Fireplace Lights'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Fireplace Outlet'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Front Door'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Front Porch Lights'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Garage Light'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Kitchen Lights'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Left Deck Light'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Lndry/Grg Deadbolt'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Main Deck Light'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Right Deck Light'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'WeMo 1'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'WeMo 2'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory '10m then Lights Off - Night Mode'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Alarm On > Lights On'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Auto Kitchen Lights OFF'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Auto Lock - Front Door'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Auto Lock - Laundry/Garage'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Auto Sleep Mode'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Chime - Door Open'...
[3/2/2017, 10:10:14 AM] Initializing platform accessory 'Deck Lights Off'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Deck Lights On'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Dyanna home.'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Eric at Home.'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Front Door Opened!'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Garage Light On - Auto'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Kitchen Lights On - Motion'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Late Night Home 2'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Late Night Home w/out Bedroom L'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Matandikas Home'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Miles home.'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Motion Detected'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Motion in Night Mode - Lights On'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Night Time - Deck Lights On'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Sliding Door Intruder Deck Light'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Sunrise - Porch Lights Off'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Sunset - Porch Lights On'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'System Disarmed - Day'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'System Disarmed - Night'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Temp > 85°F, Cool to 78°F'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Valenzuelas at home.'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Voice - Front Door'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Voice - Porch Door'...
[3/2/2017, 10:10:15 AM] Initializing platform accessory 'Waking Up'...
[3/2/2017, 10:10:16 AM] Away for Nest09AA01AC291514U0 is: true
[3/2/2017, 10:10:16 AM] Temperature unit for Nest09AA01AC291514U0 is: Fahrenheit
[3/2/2017, 10:10:16 AM] Current temperature for Nest09AA01AC291514U0 is: 16.39
[3/2/2017, 10:10:16 AM] Current heating for Nest09AA01AC291514U0 is: 0
[3/2/2017, 10:10:16 AM] Current humidity for Nest09AA01AC291514U0 is: 53
[3/2/2017, 10:10:16 AM] Target heating for Nest09AA01AC291514U0 is: 0
[3/2/2017, 10:10:16 AM] Target temperature for Nest09AA01AC291514U0 is: 19
[3/2/2017, 10:10:16 AM] Initializing platform accessory 'Nest09AA01AC291514U0'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘     
                       
[3/2/2017, 10:10:16 AM] Homebridge is running on port 51826.

**Comment by snowdd1** [comment]
Ok, one question solved: if you start homebridge from the shell, the log **is** in the shell. (Otherwise you need to redirect stdout and stderr (goolge helps)). But shell is usually best for troubleshooting anyway. Just be sure to make your scroll back buffer in the terminal large enough.

I did not count them, but might it be more than [99 accessoriers?](#827)

You might try to change the "username" in the config, maybe your homebridge is already blacklisted as [incompliant](https://github.com/nfarina/homebridge/issues/570#issuecomment-197463206).

**Comment by HA-Enthusiast** [comment]
So, I actually only really have 2 accessories: Veralink and Nest. 

Vera is a smarthome hub that has lots of devices and scenes already built into it. That's what you're seeing there. 

How can I un-blacklist it? 

Also, in the thread you linked to, it looks like Nest may have been giving the problem??

**Comment by snowdd1** [comment]
> How can I un-blacklist it?

By changing its primary I'd, which is the username in config.json

That's basically making it a new homebridge for HomeKit

**Comment by HA-Enthusiast** [comment]
Should I delete the Persist and Accessories folders one more time before I start it up?

**Comment by HA-Enthusiast** [comment]
Never mind. I did and they came right back.

So I changed the username and password. No cigar. I removed both platforms (Nest and Veralink) from my json and deleted the persist and accessories folders and restarted. No cigar. Can't understand why this isn't working. I've done everything right. Tried with my iPad and my work phone. Neither of them detect the device either. My personal cell is on iOS 10.3 beta 4 and my work phone is on iOS 10.2.

What is the deal?! Lol

**Comment by HA-Enthusiast** [comment]
I seriously want to get this working and have no idea what I am doing wrong... =\

**Comment by HA-Enthusiast** [comment]
Homebridge is definitely running, too. No errors.

**Comment by HA-Enthusiast** [comment]
No solutions?

**Comment by HA-Enthusiast** [comment]
Welp, since I got no help here, I searched and searched and searched. LOL

I found the answer. In the "/etc/avahi/avahi-daemon.conf" file, ivp6 is enabled alongside ivp4.  I left ivp4=yes and changed ivp6=yes to ivp6=no. Everything is up and running. I will report back here if I have issues with Homebridge shutting down or what not.
