### ISSUE TITLE
Problem with config.json

### ISSUE THREAD

**Issue by iracohen1946** [nfarina/homebridge#1189]
I need help. can't get home bridge to work wit nest thermostat

My config.json file
"description": "JSON API",
	"platforms": [{
		"platform": "homebridge",
		"name": "homebridge",
		"app_id": "590a32ce-69c2-40fc-a516-XXXXXXXXXXXXXXXXXXXX",
		"access_token": "74ac6a07-e63e-43f9-9ee4-XXXXXXXXXXXXXXXXX"
	}, {
		"platform": "Nest",
		"name": "Nest",
		"username": "xxxxxxxxxxx@gmail.com",
		"password": "xxxxxxxxxxx"
	}],
	"accessories": [{
		"accessory": "nest",
		"name": "name",
		"username": "xxxxxxxxxxxxx.com",
		"password": "xxxxxxxxxxxxxx"
	}]
}

Error

TypeError: **Cannot read property 'username' of undefined**
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by snowdd1** [comment]
Your config.json is missing the default bridge section. Restart using the sample from the repository. And the platform you have named "homebridge" might have another name in reality.

**Comment by Neelrp12** [comment]
Try this.

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Nest",
		"name": "Nest",
		"username": "xxxxxxxxxxx@gmail.com",
		"password": "xxxxxxxxxxx"
	}],

	"accessories": [{
		"accessory": "nest",
		"name": "name",
		"username": "xxxxxxxxxxxxx.com",
		"password": "xxxxxxxxxxxxxx"
	}]
}
