### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by felipebraz** [nfarina/homebridge#1198]
What could be happening to get this error while installing it?

root@fuscao:/# npm install -g homebridge --unsafe-perm
/root/.nvm/versions/node/v7.7.2/bin/homebridge -> /root/.nvm/versions/node/v7.7.2/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /root/.nvm/versions/node/v7.7.2/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/root/.nvm/versions/node/v7.7.2/lib/node_modules/homebridge/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: Arquivo ou diretório não encontrado
 #include <dns_sd.h>
                    ^
compilation terminated.
dns_sd_bindings.target.mk:152: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/root/.nvm/versions/node/v7.7.2/lib/node_modules/homebridge/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/root/.nvm/versions/node/v7.7.2/bin/node" "/root/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v7.7.2/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
/root/.nvm/versions/node/v7.7.2/lib
└── (empty)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/root/.nvm/versions/node/v7.7.2/bin/node" "/root/.nvm/versions/node/v7.7.2/bin/npm" "install" "-g" "homebridge" "--unsafe-perm"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

**Comment by felipebraz** [comment]
Solved, missing: build-essential libavahi-compat-libdnssd-dev git
