### ISSUE TITLE
envents.js:85 Error

### ISSUE THREAD

**Issue by cali0028** [nfarina/homebridge#120]
So I started from fresh again but this time getting error...Can't figure out what I am doing wrong.  

Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +85ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventedHTTPServer.listen (/home/pi/homebridge/node_modules/HAP-NodeJS/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/home/pi/homebridge/node_modules/HAP-NodeJS/lib/HAPServer.js:130:20)
    at Bridge.Accessory.publish (/home/pi/homebridge/node_modules/HAP-NodeJS/lib/Accessory.js:342:16)
    at publish (/home/pi/homebridge/app.js:160:10)
    at /home/pi/homebridge/app.js:150:17
    at Request._callback (/home/pi/homebridge/platforms/SmartThings.js:37:9)

**Comment by cali0028** [comment]
I found the issue. i had something running that utilized the ports that EADDRINUSE was trying to use. Killed the process and re-started the home bridge and it worked fine.
