### ISSUE TITLE
Accessories must be created with Non-empty display name

### ISSUE THREAD

**Issue by meluvalli** [nfarina/homebridge#1206]
C:\HomeBridge\node_modules\npm\lib\platformAccessory.js:16
  if (!UUID) throw new Error("Accessories must be created with a valid UUID.");
             ^

Error: Accessories must be created with a valid UUID.
    at new PlatformAccessory (C:\HomeBridge\node_modules\npm\lib\platformAccessory.js:16:20)
    at Server._loadCachedPlatformAccessories (C:\HomeBridge\node_modules\npm\lib\server.js:225:31)
    at new Server (C:\HomeBridge\node_modules\npm\lib\server.js:53:42)
    at module.exports (C:\HomeBridge\node_modules\npm\lib\cli.js:26:16)
    at Object.<anonymous> (C:\HomeBridge\node_modules\npm\bin\homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Is there a fix for this?

**Comment by meluvalli** [comment]
Will leave this open in case it's an error on homebridge side....
