### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory - MagicHome

### ISSUE THREAD

**Issue by applekid92** [nfarina/homebridge#1208]
Hello there, 

I have been using home bridge for a few months flawlessly to control a magic home LED strip, and some TP Link Smart Plugs. I recently got an additional magic home LED and I am trying to set that up in my home bridge. I added the accessory in the config.json file

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "*********"
	},

	"platforms": [{
		"platform": "Hs100"
	}],

	"accessories": [{
			"accessory": "MagicHome",
			"name": "LED Strip",
			"ip": "192.168.1.124",
			"setup": "RGBWW",
			"purewhite": false
		},

		{
			"accessory": "MagicHome",
			"name": "LED Strip",
			"ip": "192.168.1.128",
			"setup": "RGBWW",
			"purewhite": false
		}

	]
}

When Homebridge starts, it immediately crashes:
server:~ Orchard$ homebridge
[3/15/2017, 11:23:19 PM] Loaded plugin: homebridge-camera-ffmpeg
[3/15/2017, 11:23:19 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[3/15/2017, 11:23:19 PM] ---
[3/15/2017, 11:23:19 PM] Loaded plugin: homebridge-hs100
[3/15/2017, 11:23:19 PM] Registering platform 'homebridge-hs100.Hs100'
[3/15/2017, 11:23:19 PM] ---
[3/15/2017, 11:23:20 PM] Loaded plugin: homebridge-ifttt
[3/15/2017, 11:23:20 PM] Registering platform 'homebridge-ifttt.IFTTT'
[3/15/2017, 11:23:20 PM] ---
[3/15/2017, 11:23:20 PM] Loaded plugin: homebridge-magichome
homebridge API version: 2.1
[3/15/2017, 11:23:20 PM] Registering accessory 'homebridge-magichome.MagicHome'
[3/15/2017, 11:23:20 PM] ---
[3/15/2017, 11:23:20 PM] Loaded config.json with 2 accessories and 1 platforms.
[3/15/2017, 11:23:20 PM] ---
[3/15/2017, 11:23:20 PM] Loading 1 platforms...
[3/15/2017, 11:23:20 PM] Initializing Hs100 platform...
[3/15/2017, 11:23:20 PM] Loading 2 accessories...
[3/15/2017, 11:23:20 PM] [LED Strip] Initializing MagicHome accessory...
[3/15/2017, 11:23:20 PM] [LED Strip] Initializing MagicHome accessory...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c6a89034-acaf-44d2-975a-2289c59ea0f9
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:266:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any help you could provide would be greatly appreciated 😃 Thank you!

**Comment by KhaosT** [comment]
Give the second one a different name (instead of "MagicHome", call it "MagicHome 2").
