### ISSUE TITLE
Repeated crashing, about daily

### ISSUE THREAD

**Issue by erpeters3** [nfarina/homebridge#1211]
Here is the error I receive almost daily and have to restart Homebridge.

Unhandled rejection RequestError: Error: connect ENETDOWN 10.0.1.223:3480 - Local (10.0.1.13:59736)
    at new RequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by snowdd1** [comment]
As it crashes in homebridge-vera, I would suggest you open an issue ticket in that repository.
