### ISSUE TITLE
Error: dns service error: unknown on homebridge launch

### ISSUE THREAD

**Issue by Fluo75015** [nfarina/homebridge#1213]
Hello,

I receive this message on homebridge launch.

I tried to investigate but couldn't find any issue that is the same.

Here is my config.json

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 2,
            "mqtt": 0
        }
    ],
    "accessories": []
}

```

And here is the trace 
```

homebridge
[2017-3-17 14:21:01] Loaded plugin: homebridge-edomoticz
[2017-3-17 14:21:01] Registering accessory 'homebridge-edomoticz.eDomoticz'
[2017-3-17 14:21:01] Registering platform 'homebridge-edomoticz.eDomoticz'
[2017-3-17 14:21:01] ---
[2017-3-17 14:21:01] Loaded config.json with 0 accessories and 1 platforms.
[2017-3-17 14:21:01] ---
[2017-3-17 14:21:01] Loading 1 platforms...
[2017-3-17 14:21:01] [eDomoticz] Initializing eDomoticz platform...
[2017-3-17 14:21:01] Loading 0 accessories...
[2017-3-17 14:21:01] [eDomoticz] Initializing platform accessory 'VerandaDroite'...
[2017-3-17 14:21:01] [eDomoticz] Initializing platform accessory 'VerandaGauche'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-3-17 14:21:01] Homebridge is running on port 51826.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/mdns_service.js:18:40)
```

I am on Mac OS X.

Thanks a lot for any help.

Philippe

**Comment by Bluebie** [comment]
I just had a similar error with Homebridge 0.4.16 (npm release) after homebridge had been running fine for a few days on a macOS Sierra 10.12.3 host:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown error code
    at Error (native)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/mdns_service.js:18:40)
```
