### ISSUE TITLE
throw new range error ('index out of range') 

### ISSUE THREAD

**Issue by joey15024** [nfarina/homebridge#1214]
This keeps happing at different times, not sure what to do to fix it ?

buffer.js:821
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:821:11)
    at Buffer.readUInt16LE (buffer.js:867:5)
    at Object.layerDecrypt (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/encryption.js:83:56)
    at HAPServer._onDecrypt (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:257:33)
    at emitThree (events.js:116:13)
    at EventedHTTPServer.emit (events.js:194:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:91:70)
    at emitThree (events.js:116:13)
    at EventedHTTPServerConnection.emit (events.js:194:7)
    at EventedHTTPServerConnection._onClientSocketData (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:242:8)

**Comment by NorthernMan54** [comment]
Can you include a bit more log, with debug output.  I didn't see enough in the log to determine where the problem is.

**Comment by joey15024** [comment]
thats all it gives me kinda new to this stuff can you let me know where i can find the log and debug output?

**Comment by NorthernMan54** [comment]
Easiest method to collect debug output is to run homebridge from the command line like this.  The debug output will show in the terminal


DEBUG=* homebridge
 
[3/21/2017, 6:37:03 PM] Loaded plugin: homebridge-ecoplug
[3/21/2017, 6:37:03 PM] Registering platform 'homebridge-ecoplugs.EcoPlug'
[3/21/2017, 6:37:03 PM] ---
[3/21/2017, 6:37:06 PM] Loaded plugin: homebridge-yamaha
[3/21/2017, 6:37:06 PM] Registering platform 'homebridge-yamaha.YamahaAVR'
[3/21/2017, 6:37:06 PM] ---
[3/21/2017, 6:37:06 PM] Loaded plugin: homebridge-suncalc
[3/21/2017, 6:37:06 PM] Registering accessory 'homebridge-suncalc.Suncalc'
[3/21/2017, 6:37:06 PM] ---
[3/21/2017, 6:37:07 PM] Loaded config.json with 0 accessories and 2 platforms.
[3/21/2017, 6:37:07 PM] ---
[3/21/2017, 6:37:07 PM] Loading 2 platforms...
[3/21/2017, 6:37:07 PM] [EcoPlug] Initializing EcoPlug platform...
[3/21/2017, 6:37:07 PM] Initializing YamahaAVR platform...
[3/21/2017, 6:37:07 PM] Getting Yamaha AVR devices.
[3/21/2017, 6:37:07 PM] Loading 0 accessories...
[3/21/2017, 6:37:07 PM] [EcoPlug] configureAccessory
[3/21/2017, 6:37:07 PM] [EcoPlug] configureAccessory
[3/21/2017, 6:37:07 PM] [EcoPlug] configureAccessory
  ssdp not running +0ms
  ssdp binding to port 1900 for ssdp discovery +7ms
  ssdp server listening 0.0.0.0:1900 192.168.1.214 +8ms
[3/21/2017, 6:37:08 PM] Found Yamaha RX-V1075 - 0AA88593, "Yamaha"
[3/21/2017, 6:37:08 PM] [EcoPlug] Adding: ECO-7801F87E Office 192.168.1.134
[3/21/2017, 6:37:08 PM] [EcoPlug] Getting Status: ECO-7801F87E Office
[3/21/2017, 6:37:08 PM] [EcoPlug] Adding: ECO-7800FF8D Outlet Two 192.168.1.185
[3/21/2017, 6:37:08 PM] [EcoPlug] Getting Status: ECO-7800FF8D Outlet Two
[3/21/2017, 6:37:08 PM] [EcoPlug] Adding: ECO-7800DEAA Outlet One 192.168.1.150
[3/21/2017, 6:37:08 PM] [EcoPlug] Getting Status: ECO-7800DEAA Outlet One
[3/21/2017, 6:37:09 PM] Adding preset 1 - 99.9 true
[3/21/2017, 6:37:09 PM] Adding preset 2 - 102.1 true
[3/21/2017, 6:37:12 PM] Waited 3 seconds, stopping discovery.
[3/21/2017, 6:37:12 PM] Discovery finished, found 3 Yamaha AVR devices.
[3/21/2017, 6:37:12 PM] Initializing platform accessory 'Yamaha'...
[3/21/2017, 6:37:12 PM] Initializing platform accessory 'Preset 1'...
[3/21/2017, 6:37:12 PM] Initializing platform accessory 'Preset 2'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  EventedHTTPServer Server listening on port 51826 +5s

**Comment by joey15024** [comment]
[3/21/2017, 9:32:22 PM] Loaded plugin: homebridge-info
[3/21/2017, 9:32:22 PM] Registering platform 'homebridge-info.Info'
[3/21/2017, 9:32:22 PM] ---
[3/21/2017, 9:32:25 PM] Loaded plugin: homebridge-smartthings
[3/21/2017, 9:32:25 PM] Registering platform 'homebridge-smartthings.SmartThings'
[3/21/2017, 9:32:25 PM] ---
[3/21/2017, 9:32:25 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/21/2017, 9:32:25 PM] ---
[3/21/2017, 9:32:25 PM] Loading 1 platforms...
[3/21/2017, 9:32:25 PM] [SmartThings] Initializing SmartThings platform...
[3/21/2017, 9:32:25 PM] [SmartThings] Fetching Smart Things devices.
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Back Corner, ID 1477f704-2f9c-46cd-b26e-e7a6f526b607
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Back Door, ID 8baf7692-1d0f-45f7-a16e-b249a42501d7
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Back outside light, ID 40663072-d339-40c6-a925-8e1cee3542e5
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Bathroom, ID 186db218-9da8-48ba-aa73-bd532be99b35
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Bathroom Motion Sensor, ID 702ba5a4-3123-4d56-93d1-23a1420ec874
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Bedroom Closet Light, ID a31eb7e0-49c2-4323-8b38-861ae2eec24c
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Bedroom Corner, ID 0cbe50fe-85f8-49e4-b4cb-a7ace9842969
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Bedroom Front Door, ID 7ae8b4d0-b348-4df0-93b7-523b0ff1b666
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Bedroom Lamp, ID 2f383f79-4f69-4ce5-941c-fd8a574df69a
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Bedside Fan, ID e658bae4-f726-4005-9c41-206b78745fbb
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Bedside Light, ID 2c8eae31-00d2-428f-86dd-c7c9767a2b25
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Br Ceiling Light, ID 7b2657a2-854d-4de8-8249-eed1c2800b2e
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Floor Lantern, ID a5c477a8-fd57-4332-a5fc-40c207097530
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Front Corner, ID 4d953b64-d9d5-48c5-b9de-672242d64865
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Front Door Open And Close Sensor, ID 941ef61b-ee9b-4643-9848-4a5bc654d7c8
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Front Door Cam, ID 7842ccb7-199b-4933-80b0-a0a0a844546c
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Front Door Light, ID 0b1e0aa9-231d-490f-8660-8a070074d071
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Hanging Lamp, ID 46ccd587-65a9-4101-b994-d93a91bb025c
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Kitchen, ID a8ca6e03-788a-440d-8bd9-24efab887e6c
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Kitchen Motion Sensor, ID 5b806080-f5df-4726-8552-8bb744ceaef2
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Kitchen Wax Warmer, ID 0e3b11a7-9475-4f45-9244-869a684f43d2
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Mantel Candle Warmer, ID c840c5e0-09b7-4773-bad5-85bf92a21f5d
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Living Room  Motion Sensor, ID 9e2626d1-a8c3-4877-9f99-dc2fd7ef282f
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name Pantry, ID 4405891d-03b8-4dcf-96d1-7685b85d9499
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group lights, Name Pantry Light, ID efbbb1e2-c042-4c9f-bbf2-5760ac1fe97c
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group switch, Name Living Room, ID 7510666f-2994-40fc-8c9a-ea1cb2735d17
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name bedroom window front, ID ba2bd0e1-f698-4385-90f0-2d9059135d5a
[3/21/2017, 9:32:27 PM] [SmartThings] Device Added - Group sensor, Name livingroom window, ID 829f7816-b8b4-4af2-a1af-b7491d9174ae
[3/21/2017, 9:32:27 PM] [SmartThings] Unknown Capabilities: ["Health Check","Light","Outlet","Alarm","Image Capture","Relay Switch","Video Camera","Video Capture"]
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Back Corner'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Back Door'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Back outside light'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bathroom'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bathroom Motion Sensor'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bedroom Closet Light'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bedroom Corner'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bedroom Front Door'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bedroom Lamp'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bedside Fan'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Bedside Light'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Br Ceiling Light'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Floor Lantern'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Front Corner'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Front Door Open And Close Sensor'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Front Door Cam'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Front Door Light'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Hanging Lamp'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Kitchen'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Kitchen Motion Sensor'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Kitchen Wax Warmer'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Mantel Candle Warmer'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Living Room  Motion Sensor'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Pantry'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Pantry Light'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'Living Room'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'bedroom window front'...
[3/21/2017, 9:32:27 PM] [SmartThings] Initializing platform accessory 'livingroom window'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 131-54-451 │     
    └────────────┘     
                       
[3/21/2017, 9:32:27 PM] Homebridge is running on port 51826.
[3/21/2017, 9:32:27 PM] [SmartThings] Direct Connect Is Listening On 192.168.1.42:8000
[3/21/2017, 9:32:27 PM] [SmartThings] SmartThings Hub Communication Established

**Comment by joey15024** [comment]
any luck?

**Comment by shrimaliakash** [comment]
When I check database connection for mssql driver from mysql credeintials but i have get following Error:

**Comment by Dev1an** [comment]
@joey15024 Did you resolve this problem? I am having the same issue.

**Comment by joey15024** [comment]
It ended up being my hdd locking up I never new my Mac would just restart long story short hdd failed I replaced it and set everything back up and it works great 👍🏿
