### ISSUE TITLE
Error: bind EADDRINUSE 0.0.0.0:9898

### ISSUE THREAD

**Issue by astrojetson8** [nfarina/homebridge#1218]
I can't seem to get homebridge to work. Anyone has some suggestions?

This what I'm getting when I try and run homebridge on my mac

[3/21/2017, 9:53:53 AM] Loaded plugin: homebridge-aqara
[3/21/2017, 9:53:53 AM] Registering platform 'homebridge-aqara.AqaraPlatform'
[3/21/2017, 9:53:53 AM] ---
[3/21/2017, 9:53:53 AM] Loaded plugin: homebridge-yeelight
[3/21/2017, 9:53:53 AM] Registering platform 'homebridge-yeelight.yeelight'
[3/21/2017, 9:53:53 AM] ---
[3/21/2017, 9:53:53 AM] Loaded config.json with 0 accessories and 2 platforms.
[3/21/2017, 9:53:53 AM] ---
[3/21/2017, 9:53:53 AM] Loading 2 platforms...
[3/21/2017, 9:53:53 AM] [yeelight] Initializing yeelight platform...
[3/21/2017, 9:53:53 AM] [yeelight] YeePlatform Init
[3/21/2017, 9:53:53 AM] Initializing AqaraPlatform platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 498-72-987 │     
    └────────────┘     
                       
[3/21/2017, 9:53:53 AM] [yeelight] DidFinishLaunching
[3/21/2017, 9:53:53 AM] error, msg - bind EADDRINUSE 0.0.0.0:9898, stack - Error: bind EADDRINUSE 0.0.0.0:9898
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51825
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)

**Comment by NorthernMan54** [comment]
Just looking at the 2 address in use errors you have, could you have a copy of homebridge already running?  Maybe from an autostart script or something similar?

**Comment by astrojetson8** [comment]
I did killall but a restart usually fixes it.
Based on feedback on other threads, looks like I'm not alone with similar issue on mac.

I suppose it's time to move on to raspberry pi.

**Comment by natedlee** [comment]
@astrojetson8 I am having a similar issue and running homebridge on OSX. Maybe an update is breaking Mac setups? You can read my thread here: #1224

**Comment by KhaosT** [comment]
For this one it looks like you probably already have one instance of homebridge running in background (``Error: listen EADDRINUSE :::51825``), are you sure you are not running any other homebridge (like auto startup) on your system?

**Comment by astrojetson8** [comment]
@KhaosT no, i'm not running multiple instances of homebridge.

I was looking at my log file just now, and I've quite a few:
already in device list!

Also, in Home, some sensors at random revert back to default name and default room. And this has happened to me more than dozen or so times.
https://github.com/snOOrz/homebridge-aqara/issues/50

not sure if they are all related to each other?

**Comment by rcorbari** [comment]
I have this issue, cannot figure out why: starting homebridge I have: `Error: bind EADDRINUSE 0.0.0.0:1982
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at dgram.js:214:18
    at nextTickCallbackWith3Args (node.js:448:9)
    at process._tickCallback (node.js:354:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3`

Could you please help me solving this issue? I'm a code rookie :)

**Comment by rcorbari** [comment]
```Error: bind EADDRINUSE 0.0.0.0:1982
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at dgram.js:214:18
    at nextTickCallbackWith3Args (node.js:448:9)
    at process._tickCallback (node.js:354:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3```
