### ISSUE TITLE
Help me troubleshoot please

### ISSUE THREAD

**Issue by natedlee** [nfarina/homebridge#1224]
Can someone point me in the right direction? I'm sure this has been covered but I'm not sure what to look for.  Getting these errors when trying to start homebridge. It was working fine, then stopped. I did updates on everything, but still getting this... Is it just a Hs100 error, or is it more?
```
[3/23/2017, 5:31:32 PM] ---
[3/23/2017, 5:31:32 PM] Loaded config.json with 0 accessories and 4 platforms.
[3/23/2017, 5:31:32 PM] ---
[3/23/2017, 5:31:32 PM] Loading 4 platforms...
[3/23/2017, 5:31:32 PM] Initializing Nest platform...
[3/23/2017, 5:31:32 PM] Fetching Nest devices.
[3/23/2017, 5:31:32 PM] [Homebridge Info Server] Initializing Info platform...
[3/23/2017, 5:31:32 PM] [LiFx] Initializing LifxLan platform...
[3/23/2017, 5:31:32 PM] Initializing Hs100 platform...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9876
     at Object.exports._errnoException (util.js:1034:11)
     at exports._exceptionWithHostPort (util.js:1057:20)
     at Server._listen2 (net.js:1270:14)
     at listen (net.js:1306:10)
     at Server.listen (net.js:1397:7)
     at new InfoPlatform (/usr/local/lib/node_modules/homebridge-info/index.js:63:12)
     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
     at Module._compile (module.js:571:32)
     at Object.Module._extensions..js (module.js:580:10)
     at Module.load (module.js:488:32)
     at tryModuleLoad (module.js:447:12)
     at Function.Module._load (module.js:439:3)
     at Module.runMain (module.js:605:10)
     at run (bootstrap_node.js:427:7)
     at startup (bootstrap_node.js:148:9)
     at bootstrap_node.js:542:3
```

**Comment by SkyJohn** [comment]
There is an issue with the latest HS100 plugin.

The only fix I know of at the moment is to install an older version of the plugin that works as explained here:

https://github.com/plasticrake/homebridge-hs100/issues/17

**Comment by NorthernMan54** [comment]
This is a problem related to the homebridge-info plugin, and not homebridge, and should be raised there.

Without knowing the plugin, the error is indicating something else is using the same port.  Are you running something else related to the info plugin on the machine that may be using the port?

**Comment by natedlee** [comment]
> Are you running something else related to the info plugin on the machine that may be using the port?
@NorthernMan54 Not running anything else using the port. I don't even know what the -info plugin is for. It's just there. Maybe it was added in an update I ran? 

> It looks like you're trying to run two instances of Homebridge at once.
@SkyJohn Yeah I tried killall or launchctl stop and when I run it again I get the same `EADDRINUSE` error. Re Hs100 I'll take a look at that link. Hope it works b/c the plugs are the main reason I use Homebridge.

**Comment by natedlee** [comment]
So I just removed the Hs100 plugin and took the line of out config.json and now I am getting the error below, which obviously shows it's still looking for the Hs100 devices that used to work. I found them referenced in `.homebridge/accessories/cachedAccessories`

> [3/23/2017, 8:10:40 PM] Loaded plugin: homebridge-info
> [3/23/2017, 8:10:40 PM] Registering platform 'homebridge-info.Info'
> [3/23/2017, 8:10:40 PM] ---
> [3/23/2017, 8:10:40 PM] Loaded plugin: homebridge-lifx-lan
> [3/23/2017, 8:10:40 PM] Registering platform 'homebridge-lifx-lan.LifxLan'
> [3/23/2017, 8:10:40 PM] ---
> [3/23/2017, 8:10:40 PM] Loaded plugin: homebridge-nest
> [3/23/2017, 8:10:40 PM] Registering platform 'homebridge-nest.Nest'
> [3/23/2017, 8:10:40 PM] ---
> [3/23/2017, 8:10:40 PM] Loaded config.json with 0 accessories and 3 platforms.
> [3/23/2017, 8:10:40 PM] ---
> [3/23/2017, 8:10:40 PM] Loading 3 platforms...
> [3/23/2017, 8:10:40 PM] Initializing Nest platform...
> [3/23/2017, 8:10:40 PM] Fetching Nest devices.
> [3/23/2017, 8:10:40 PM] [Homebridge Info Server] Initializing Info platform...
> [3/23/2017, 8:10:40 PM] [LiFx] Initializing LifxLan platform...
> Failed to find plugin to handle accessory Sunroom Lights
> Failed to find plugin to handle accessory SmartPlug2
> Failed to find plugin to handle accessory Emily Desk Light
> Failed to find plugin to handle accessory Fireplace Lights
> Failed to find plugin to handle accessory Emily Equipment 
> Failed to find plugin to handle accessory TV Plug
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
>

**Comment by SkyJohn** [comment]
You can deleted the cachedAccessories file and then they shouldn't show up when you start homebridge.

**Comment by natedlee** [comment]
Still gives me this

```
[3/23/2017, 8:26:16 PM] Loading 3 platforms...
[3/23/2017, 8:26:16 PM] Initializing Nest platform...
[3/23/2017, 8:26:16 PM] Fetching Nest devices.
[3/23/2017, 8:26:16 PM] [Homebridge Info Server] Initializing Info platform...
[3/23/2017, 8:26:16 PM] [LiFx] Initializing LifxLan platform...
events.js:163
      throw er; // Unhandled 'error' event
      ^
```

**Comment by natedlee** [comment]
It may be worth noting that in HomeKit Homebridge doesn't say offline and the Accessories just say **Updating**. The note at the top says _No accessories responding._

**Comment by NorthernMan54** [comment]
You need to do a reset on the home app side, in the home app delete homebridge, then add homebridge again. You should be fine.

**Comment by natedlee** [comment]
@NorthernMan54 No dice. I **was** able to remove and re-add homebridge + accessories, but they all end up saying _No Response_ now (vs _Updating_). On the server side, whether I run Homebridge with or without hS100 I am still getting the error below:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^
```

**Comment by KhaosT** [comment]
Your problem is with ``homebridge-info``. It tries to bind a port that's already in use. Try use a different port or disable that plugin.

**Comment by natedlee** [comment]
@KhaosT Why was this closed? The issue isn't completely resolved yet. 

I changed homebridge-info to an known open port and the errors changed, but it still won't start properly. So I changed the homebridge port to 36632 and it starts now, it seems. However, now I can't add homebridge back to my iOS app. 

```
[3/23/2017, 11:02:31 PM] Loaded plugin: homebridge-hs100
[3/23/2017, 11:02:31 PM] Registering platform 'homebridge-hs100.Hs100'
[3/23/2017, 11:02:31 PM] ---
[3/23/2017, 11:02:31 PM] Loaded plugin: homebridge-info
[3/23/2017, 11:02:31 PM] Registering platform 'homebridge-info.Info'
[3/23/2017, 11:02:31 PM] ---
[3/23/2017, 11:02:31 PM] Loaded plugin: homebridge-lifx-lan
[3/23/2017, 11:02:31 PM] Registering platform 'homebridge-lifx-lan.LifxLan'
[3/23/2017, 11:02:31 PM] ---
[3/23/2017, 11:02:31 PM] Loaded plugin: homebridge-nest
[3/23/2017, 11:02:31 PM] Registering platform 'homebridge-nest.Nest'
[3/23/2017, 11:02:31 PM] ---
[3/23/2017, 11:02:31 PM] Loaded config.json with 0 accessories and 4 platforms.
[3/23/2017, 11:02:31 PM] ---
[3/23/2017, 11:02:31 PM] Loading 4 platforms...
[3/23/2017, 11:02:31 PM] Initializing Nest platform...
[3/23/2017, 11:02:31 PM] Fetching Nest devices.
[3/23/2017, 11:02:31 PM] [Homebridge Info Server] Initializing Info platform...
[3/23/2017, 11:02:31 PM] [LiFx] Initializing LifxLan platform...
[3/23/2017, 11:02:31 PM] Initializing Hs100 platform...
[3/23/2017, 11:02:31 PM] [Homebridge Info Server] is listening on: http://192.168.1.28:9879
LIFX Client UDP error
Trace: { Error: bind EADDRINUSE 0.0.0.0:56700
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at _handle.lookup (dgram.js:215:18)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700 }
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:147:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at _handle.lookup (dgram.js:216:14)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
[3/23/2017, 11:02:31 PM] New Plug Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:02:31 PM] Configuring: TV Plug
[3/23/2017, 11:02:31 PM] New Plug Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:02:31 PM] Configuring: SmartPlug2
[3/23/2017, 11:02:32 PM] New Plug Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:02:32 PM] Configuring: Emily Equipment 
[3/23/2017, 11:02:32 PM] New Plug Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:02:32 PM] Configuring: Emily Desk Light
[3/23/2017, 11:02:32 PM] New Plug Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:02:32 PM] Configuring: Fireplace Lights
[3/23/2017, 11:02:32 PM] New Plug Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
[3/23/2017, 11:02:32 PM] Configuring: Sunroom Lights
[3/23/2017, 11:02:33 PM] Software version for Zach Room Camera is: 205-600052
[3/23/2017, 11:02:33 PM] Away for Zach Room Camera is: 0
[3/23/2017, 11:02:33 PM] Initializing platform accessory 'Zach Room Camera'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[3/23/2017, 11:02:33 PM] Homebridge is running on port 36632.
[3/23/2017, 11:03:01 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:03:01 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:03:01 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:03:01 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:03:02 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
[3/23/2017, 11:03:31 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:03:31 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:03:32 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:03:32 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:03:32 PM] Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:03:32 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
HS100 Plug TCP error
Trace: { Error: connect ETIMEDOUT 192.168.1.14:9999
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.14',
  port: 9999 }
    at Socket.socket.on.on.on (/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/plug.js:61:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1289:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[3/23/2017, 11:03:47 PM] { Error: connect ETIMEDOUT 192.168.1.14:9999
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.14',
  port: 9999 }
[3/23/2017, 11:04:01 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:04:01 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:04:01 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:04:01 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:04:02 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
[3/23/2017, 11:04:02 PM] Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:04:31 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:04:31 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:04:31 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:04:31 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:04:32 PM] Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:04:32 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
[3/23/2017, 11:05:01 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:05:01 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:05:01 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:05:01 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:05:02 PM] Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:05:02 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
[3/23/2017, 11:05:31 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:05:31 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:05:31 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:05:31 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:05:32 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
[3/23/2017, 11:05:32 PM] Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:06:01 PM] Online: Emily Equipment  [8006B1C6021500ACC52FD9BB4077FDC1181AFECC]
[3/23/2017, 11:06:01 PM] Online: Emily Desk Light [8006321DD42C9EE63FB694DD59592B2018079828]
[3/23/2017, 11:06:01 PM] Online: TV Plug [80060BBEF5F1C26C4E291B8C3DC82C2B18197899]
[3/23/2017, 11:06:01 PM] Online: SmartPlug2 [80062298D9CF7012D2CBCC80AE35BCA918072E64]
[3/23/2017, 11:06:02 PM] Online: Fireplace Lights [8006732B5CFF37367D519DB48DF62C5D1807CAB4]
[3/23/2017, 11:06:02 PM] Online: Sunroom Lights [800623E747DABB035A2B870B8B70FD9D18078F62]
^C[3/23/2017, 11:06:09 PM] Got SIGINT, shutting down Homebridge...
```

**Comment by snowdd1** [comment]
It was closed as it is not a *homebridge* but a *homebridge-info* issue. Raise your issue in the correct repository, or read their README how to change the port. https://github.com/maplesteve/homebridge-info
