### ISSUE TITLE
Homebridge can't start because of curve25519 

### ISSUE THREAD

**Issue by Burmi66** [nfarina/homebridge#1249]
Please release your last commit like hap-nodejs did already. There is a mismatch caused by curve25519 preventing homebridge from starting!

**Comment by KhaosT** [comment]
@Burmi66 hap-nodejs 0.4.22 is already published. What's the error you are seeing?

**Comment by Burmi66** [comment]
Thnx for reply.

module.js:457
    throw err;
    ^

Error: Cannot find module 'curve25519-n'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/encryption.js:3:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by KhaosT** [comment]
Please make sure you updated dependent hap-nodejs. This should already be fixed in hap-nodejs 0.4.22

**Comment by Burmi66** [comment]
Hmm, ok. Using the docker image benzman81/homebridge-docker:develop.
I think i have to build it by myself.
Thnx again @KhaosT.

**Comment by Burmi66** [comment]
Yes, rebuilding the image solved the problem. Issue can be closed, family has a smart home again ;)

**Comment by KhaosT** [comment]
Good to know :)
