### ISSUE TITLE
HAP-NodeJS can run

### ISSUE THREAD

**Issue by iOSteveReagan** [nfarina/homebridge#1250]
When I run " node Core.js" ,it can't run,like this:
```
root@raspberrypi:/home/pi/HAP-NodeJS# node Core.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at Server.listen (net.js:1392:7)
    at EventedHTTPServer.listen (/home/pi/HAP-NodeJS/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/home/pi/HAP-NodeJS/lib/HAPServer.js:158:20)
    at Accessory.publish (/home/pi/HAP-NodeJS/lib/Accessory.js:503:16)
    at /home/pi/HAP-NodeJS/Core.js:32:13
    at Array.forEach (native)
```

**Comment by KhaosT** [comment]
```
Error: listen EADDRINUSE :::51826
```
Either you already have an instance of HAP-NodeJS running or port 51826 is occupied by some other programs.

**Comment by iOSteveReagan** [comment]
thanks.

**Comment by iOSteveReagan** [comment]
But every time after I reboot my raspberry,I always need to run "kill 602" and "node Core.js" again.How can I solve the problem?
@KhaosT 
![2017-04-09 10 29 35](https://cloud.githubusercontent.com/assets/18232831/24834145/9f1c9e68-1d0f-11e7-8624-d050990d5475.png)

**Comment by KhaosT** [comment]
Did you use something to auto start homebridge?

**Comment by iOSteveReagan** [comment]
Yes rc.local：sudo node /home/pi/HAP-NodeJS/Core.js < /dev/null &

**Comment by KhaosT** [comment]
Then it's already running... Why are you trying to start again after reboot...

**Comment by iOSteveReagan** [comment]
But Home app can't connect to raspberry after reboot

**Comment by KhaosT** [comment]
You need to make sure your auto boot set homebridge's config path to the right one.

**Comment by iOSteveReagan** [comment]
OK thanks
