### ISSUE TITLE
Home bridge Not Starting (WeMo)

### ISSUE THREAD

**Issue by stonedune** [nfarina/homebridge#1256]
I've gone through the installation process and believe everything is installed correct however I am having problems actually running home bridge. I am using a single WeMo Insight switch that has already been configured and named "Swamp Cooler" by the default WeMo setup. Below is the terminal readout I receive after running home bridge as well as my .config.json file. Any help would be greatly appreciated.

**.config.json**
{
	"bridge": {
		"name": "Homebridge",
		"username": "00:00:00:00:00:00",
		"port": 51826,
		"pin": "123-45-678"
	},

	"accessories": [{
		"accessory": "Wemo",
		"name": "Swamp Cooler"
	}],

	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "1",
		"timeout": "25",
		"no_motion_timer": "60",
		"homekit_safe": "1"
	}]
}

**Terminal Readout**

computername:~ username$ homebridge
[4/21/2017, 12:37:06 AM] Loaded plugin: homebridge-platform-wemo
[4/21/2017, 12:37:06 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[4/21/2017, 12:37:06 AM] ---
[4/21/2017, 12:37:06 AM] Loaded config.json with 1 accessories and 1 platforms.
[4/21/2017, 12:37:06 AM] ---
[4/21/2017, 12:37:06 AM] Loading 1 platforms...
[4/21/2017, 12:37:06 AM] [WeMo Platform] Initializing BelkinWeMo platform...
[4/21/2017, 12:37:06 AM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Wemo' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by SkyJohn** [comment]
I think you just need to Change the Wemo to WeMo.

**Comment by kapps7** [comment]
curious which one of the two Wemo plugins are you using ?

**Comment by stonedune** [comment]
SkyJohn- I've corrected it to "WeMo" and no change.
Kapps- I'm using that same one you are. you just have the bridge info on top and the platform definition? I'll try deleting the accessory definition and see what that gets me. 
I didn't add the accessory but found it odd that after an install it had one in there with the same name as my unit.

**Comment by kapps7** [comment]
Yeah I haven't modified anything, absolute default platform json. Some platforms behave where you have to  click the + and Add Accessory and others like this just add em, not sure why.

I even left the Wemo Switch name to its default. To customise I only change the name within the Home app particularly since I only one of them.

**Comment by stonedune** [comment]
Cool, deleting the accessory stuff made it work. Thanks for the help.
