### ISSUE TITLE
./homebridge Missing

### ISSUE THREAD

**Issue by sdorilas** [nfarina/homebridge#1265]
I'm on a Mac and it appears my homebridge directory has disappeared. When I look in my root directory, it isn't there, when I tried to go directly to ./homebridge, my desktop folder opens up. However I can still run homebridge through cmd and it will run just fine. Does anyone have any ideas where I can update my config.json file now?

**Comment by simonrb2000** [comment]
Silly question but have you enabled viewing of hidden files?

Cheers

On 26 Apr 2017, at 23:25, sdorilas <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm on a Mac and it appears my homebridge directory has disappeared. When I look in my root directory, it isn't there, when I tried to go directly to ./homebridge, my desktop folder opens up. However I can still run homebridge through cmd and it will run just fine. Does anyone have any ideas where I can update my config.json file now?

**Comment by sdorilas** [comment]
Lol yes. Even if I didn't have it enabled, I would be able to go directly to it. I'll take any ideas at this point though.

**Comment by sdorilas** [comment]
homebridge
[4/26/2017, 10:00:25 PM] Loaded plugin: homebridge-nest
[4/26/2017, 10:00:25 PM] Registering platform 'homebridge-nest.Nest'
[4/26/2017, 10:00:25 PM] ---
[4/26/2017, 10:00:26 PM] Loaded plugin: homebridge-philipshue
[4/26/2017, 10:00:26 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[4/26/2017, 10:00:26 PM] ---
[4/26/2017, 10:00:27 PM] Loaded plugin: homebridge-platform-myq
[4/26/2017, 10:00:27 PM] Registering platform 'homebridge-platform-myq.MyQ'
[4/26/2017, 10:00:27 PM] ---
[4/26/2017, 10:00:28 PM] Loaded plugin: homebridge-xbox-one
[4/26/2017, 10:00:28 PM] Registering accessory 'homebridge-xbox-one.Xbox'
[4/26/2017, 10:00:28 PM] ---
[4/26/2017, 10:00:28 PM] Loaded config.json with 1 accessories and 3 platforms.
[4/26/2017, 10:00:28 PM] ---
[4/26/2017, 10:00:28 PM] Loading 3 platforms...
[4/26/2017, 10:00:28 PM] Initializing Nest platform...
[4/26/2017, 10:00:28 PM] Fetching Nest devices.
[4/26/2017, 10:00:28 PM] [Philips Hue] Initializing PhilipsHue platform...
[4/26/2017, 10:00:28 PM] [Philips Hue] PhilipsHue Platform Plugin Version 0.0.2
[4/26/2017, 10:00:28 PM] [Philips Hue] Fetching Philips Hue lights...
[4/26/2017, 10:00:28 PM] [MyQ Platform] Initializing MyQ platform...
[4/26/2017, 10:00:28 PM] Loading 1 accessories...
[4/26/2017, 10:00:28 PM] [Xbox] Initializing Xbox accessory...
[4/26/2017, 10:00:30 PM] [MyQ Platform] [20170426220030.299]: found GarageDoorOpener, deviceid=9590464
[4/26/2017, 10:00:30 PM] [MyQ Platform] [20170426220030.302]: found GarageDoorOpener, deviceid=9590463
[4/26/2017, 10:00:30 PM] [MyQ Platform] [20170426220030.304]: found Gateway Device, deviceid=9590462
[4/26/2017, 10:00:30 PM] [MyQ Platform] Initializing platform accessory 'Garage Door Opener'...
[4/26/2017, 10:00:30 PM] [MyQ Platform] Initializing platform accessory 'CG08430987C9'...
[4/26/2017, 10:00:30 PM] [MyQ Platform] Initializing platform accessory 'Home'...
[4/26/2017, 10:00:30 PM] Software version for Dining Room Thermostat is: 5.6-7
[4/26/2017, 10:00:30 PM] Temperature unit for Dining Room Thermostat is: Fahrenheit
[4/26/2017, 10:00:30 PM] Current temperature for Dining Room Thermostat is: 77 F
[4/26/2017, 10:00:30 PM] Current humidity for Dining Room Thermostat is: 35%
[4/26/2017, 10:00:30 PM] Target temperature for Dining Room Thermostat is: 77 F
[4/26/2017, 10:00:30 PM] Target heating for Dining Room Thermostat is: Cooling
[4/26/2017, 10:00:30 PM] Away for Dining Room Thermostat is: 0
[4/26/2017, 10:00:30 PM] Initializing platform accessory 'Dining Room Thermostat'...
/usr/local/lib/node_modules/homebridge-philipshue/node_modules/node-hue-api/node_modules/q/q.js:126
                    throw e;
                    ^

Error: ETIMEDOUT
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/node-hue-api/node_modules/request-util/node_modules/request/request.js:919:15)
    at Timer.listOnTimeout (timers.js:92:15)
home:~

**Comment by sdorilas** [comment]
![screen shot 2017-04-26 at 10 06 44 pm](https://cloud.githubusercontent.com/assets/19697514/25464874/d76ecdb6-2acc-11e7-959b-5a91d124f86f.png)

**Comment by cxlwill** [comment]
Me as well, while I am installing homebridge at Raspberry Pi.
