### ISSUE TITLE
Node Module conflict error on Launch

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1267]
Hi guys,
I tried updating npm because of a plugin dependency. I am now getting the following error. Wonder if someone can push me in the right direction to resolve. Thanks

Edit: I have rolled back to 4.4.5 to fix the conflict but how do I run homebridge on the newer version of node => 7.6.0
> The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by lprhodes** [comment]
If I remember rightly you just need to run the following

npm r homebridge -g
npm i homebridge -g

**Comment by kapps7** [comment]
Did the trick. Thank!
