### ISSUE TITLE
Problem with dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name on Ubuntu (Windows Bash)

### ISSUE THREAD

**Issue by alexij1997** [nfarina/homebridge#1270]
alexij@ALEXEY-PC:~$ sudo homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-5-1 03:27:51] Loaded plugin: homebridge-milight
[2017-5-1 03:27:51] Registering platform 'homebridge-milight.MiLight'
[2017-5-1 03:27:51] ---
[2017-5-1 03:27:51] Loaded config.json with 0 accessories and 1 platforms.
[2017-5-1 03:27:51] ---
[2017-5-1 03:27:51] Loading 1 platforms...
[2017-5-1 03:27:51] [MiLight] Initializing MiLight platform...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Kitchen'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Bedroom'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Hallway'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Living Room'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Downstairs Bedroom'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Dining Room'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Den'...
[2017-5-1 03:27:51] [MiLight] Initializing platform accessory 'Master Bedroom'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:555:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:191:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:191:7)
    at EventedHTTPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)

Thanks for the help! 
(Можно ответить на русском)

**Comment by omp-gluehbirne** [comment]
I am having the same problem with on Arch Linux. So it doesn't seem to be OS related.

**Comment by Gnitset** [comment]
I get this same error when `domain-name` in `avahi-daemon.conf` is not set to local.

The parameters passed to that call was:
`DNSServiceRef { initialized: false, fd: -1 } 0 0 'Homebridge' '_hap._tcp' null null 39297 TXTRecordRef {
  buffer: <Buffer 0d 6d 64 3d 48 6f 6d 65 62 72 69 64 67 65 06 70 76 3d 31 2e 30 14 69 64 3d 43 43 3a 32 32 3a 33 44 3a 45 33 3a 43 45 3a 33 30 04 63 23 3d 32 04 73 23 ... > } [Function: on_service_registered] null`
