### ISSUE TITLE
Homebridge Stops working days later 

### ISSUE THREAD

**Issue by jeylites** [nfarina/homebridge#1286]
Hi- My homebridge keeps breaking after few days of running. Here are the logs. What could be the problem here?
`pi@raspberrypi:~ $ homebridge

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>

*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

[5/12/2017, 5:13:14 PM] Loaded plugin: homebridge-broadlink-rm

[5/12/2017, 5:13:14 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'

[5/12/2017, 5:13:14 PM] ---

[5/12/2017, 5:13:15 PM] Loaded plugin: homebridge-edomoticz

[5/12/2017, 5:13:15 PM] Registering accessory 'homebridge-edomoticz.eDomoticz'

[5/12/2017, 5:13:15 PM] Registering platform 'homebridge-edomoticz.eDomoticz'

[5/12/2017, 5:13:15 PM] ---

[5/12/2017, 5:13:15 PM] Loaded config.json with 0 accessories and 2 platforms.

[5/12/2017, 5:13:15 PM] ---

[5/12/2017, 5:13:15 PM] Loading 2 platforms...

[5/12/2017, 5:13:15 PM] [eDomoticz] Initializing eDomoticz platform...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing BroadlinkRM platform...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'Learn'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'SIDE FAN'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'SIDE POND'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'SIDE POND LIGHTS'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'ROOF LIGHTS'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'KITCHEN EXHAUST FAN'...

[5/12/2017, 5:13:15 PM] [Broadlink RM] Initializing platform accessory 'KITCHEN COUNTER LIGHTS'...

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

                       

    ┌────────────┐     

    │ 031-45-156 │     

    └────────────┘     

                       

events.js:163

      throw er; // Unhandled 'error' event

      ^

Error: listen EADDRINUSE :::51826

    at Object.exports._errnoException (util.js:1050:11)

    at exports._exceptionWithHostPort (util.js:1073:20)

    at Server.setupListenHandle [as _listen2] (net.js:1263:14)

    at listenInCluster (net.js:1304:12)

    at Server.listen (net.js:1402:7)

    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)

    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)

    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)

    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)

    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14)

pi@raspberrypi:~ $ 

`

**Comment by Tiger519** [comment]
This generally means that the port you specified is already in use. So either you have another instance of HomeBridge running already on that port (which maybe has become unresponsive in some which which makes it appear not to be running), or your system for some reason hasn't released that port after HomeBridge has quit. Sorry, I know just enough to be dangerous and can't help much with resolving the actual issue!

**Comment by GeorgeBgk** [comment]
Do `killall homebridge`
