### ISSUE TITLE
Cannot run homebridge on raspberry pie

### ISSUE THREAD

**Issue by sdorilas** [nfarina/homebridge#1289]
installed, config file in place, config file works on my mac:

[5/13/2017, 5:31:41 PM] Loaded plugin: homebridge-liftmaster
[5/13/2017, 5:31:42 PM] Registering accessory 'homebridge-liftmaster.LiftMaster'
[5/13/2017, 5:31:42 PM] ---
[5/13/2017, 5:31:57 PM] Loaded plugin: homebridge-nest
[5/13/2017, 5:31:58 PM] Registering platform 'homebridge-nest.Nest'
[5/13/2017, 5:31:58 PM] ---
[5/13/2017, 5:32:00 PM] Loaded plugin: homebridge-philipshue
[5/13/2017, 5:32:00 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[5/13/2017, 5:32:00 PM] ---
[5/13/2017, 5:32:00 PM] Loaded plugin: homebridge-xbox-one
[5/13/2017, 5:32:00 PM] Registering accessory 'homebridge-xbox-one.Xbox'
[5/13/2017, 5:32:00 PM] ---
[5/13/2017, 5:32:00 PM] Loaded config.json with 0 accessories and 2 platforms.
[5/13/2017, 5:32:00 PM] ---
[5/13/2017, 5:32:01 PM] Loading 2 platforms...
[5/13/2017, 5:32:01 PM] Initializing Nest platform...
[5/13/2017, 5:32:01 PM] Fetching Nest devices.
/usr/local/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'MyQ' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
pi@raspberrypi:~ $

**Comment by andre-dw** [comment]
Npm install -g homebridge-myq

**Comment by sdorilas** [comment]
pi@raspberrypi:~ $ npm install -g homebridge-myq
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated homebridge-myq@1.2.1: This is deprecated in favor of Liftmaster
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└─┬ homebridge-myq@1.2.1 
  └─┬ request@2.81.0 
    ├── aws-sign2@0.6.0 
    ├── aws4@1.6.0 
    ├── caseless@0.12.0 
    ├─┬ combined-stream@1.0.5 
    │ └── delayed-stream@1.0.0 
    ├── extend@3.0.1 
    ├── forever-agent@0.6.1 
    ├─┬ form-data@2.1.4 
    │ └── asynckit@0.4.0 
    ├─┬ har-validator@4.2.1 
    │ ├─┬ ajv@4.11.8 
    │ │ ├── co@4.6.0 
    │ │ └─┬ json-stable-stringify@1.0.1 
    │ │   └── jsonify@0.0.0 
    │ └── har-schema@1.0.5 
    ├─┬ hawk@3.1.3 
    │ ├── boom@2.10.1 
    │ ├── cryptiles@2.0.5 
    │ ├── hoek@2.16.3 
    │ └── sntp@1.0.9 
    ├─┬ http-signature@1.1.1 
    │ ├── assert-plus@0.2.0 
    │ ├─┬ jsprim@1.4.0 
    │ │ ├── assert-plus@1.0.0 
    │ │ ├── extsprintf@1.0.2 
    │ │ ├── json-schema@0.2.3 
    │ │ └── verror@1.3.6 
    │ └─┬ sshpk@1.13.0 
    │   ├── asn1@0.2.3 
    │   ├── assert-plus@1.0.0 
    │   ├── bcrypt-pbkdf@1.0.1 
    │   ├─┬ dashdash@1.14.1 
    │   │ └── assert-plus@1.0.0 
    │   ├── ecc-jsbn@0.1.1 
    │   ├─┬ getpass@0.1.7 
    │   │ └── assert-plus@1.0.0 
    │   ├── jodid25519@1.0.2 
    │   ├── jsbn@0.1.1 
    │   └── tweetnacl@0.14.5 
    ├── is-typedarray@1.0.0 
    ├── isstream@0.1.2 
    ├── json-stringify-safe@5.0.1 
    ├─┬ mime-types@2.1.15 
    │ └── mime-db@1.27.0 
    ├── oauth-sign@0.8.2 
    ├── performance-now@0.2.0 
    ├── qs@6.4.0 
    ├── safe-buffer@5.0.1 
    ├── stringstream@0.0.5 
    ├─┬ tough-cookie@2.3.2 
    │ └── punycode@1.4.1 
    ├── tunnel-agent@0.6.0 
    └── uuid@3.0.1 

npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-myq"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
pi@raspberrypi:~

**Comment by andre-dw** [comment]
Sudo npm install -g homebridge-myq

**Comment by sdorilas** [comment]
Thank you!

**Comment by andre-dw** [comment]
You're welcome. Close the issue please.
