### ISSUE TITLE
Error installing Homebridge on Raspberry Pi 3B

### ISSUE THREAD

**Issue by SR2k** [nfarina/homebridge#1296]
I have already got g++-6, Node.js 6.9.5, and mdns installes on my Raspberry Pi 3B. Yet I cannot install Homebridge using `npm install -g homebridge` or `sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp`.

The error message is something like this:

```
make: Entering directory '/lib/node_modules/homebridge/node_modules/ed25519/build'
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
make: cc: Command not found
ed25519.target.mk:139: recipe for target 'Release/obj.target/ed25519/src/ed25519/keypair.o' failed
make: *** [Release/obj.target/ed25519/src/ed25519/keypair.o] Error 127
make: Leaving directory '/lib/node_modules/homebridge/node_modules/ed25519/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.9-v7+
gyp ERR! command "/bin/node" "/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /lib/node_modules/homebridge/node_modules/ed25519
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/lib
`-- (empty)

npm ERR! Linux 4.4.9-v7+
npm ERR! argv "/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519@0.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ed25519
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/volumio/npm-debug.log
npm ERR! code 1
```

...And something else that may be helpful:
```
pi@SR2k:~$ uname -a
Linux Volumio-SR2k 4.4.9-v7+ #884 SMP Fri May 6 17:28:59 BST 2016 armv7l GNU/Linux
pi@SR2k:~$ cat /proc/version
Linux version 4.4.9-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #884 SMP Fri May 6 17:28:59 BST 2016
pi@SR2k:~$ cat /etc/issue
Raspbian GNU/Linux 8 \n \l
```

**Comment by snowdd1** [comment]
What does `which cc` give you?  Something like this?
```
homebridge-pi@homebridge-dev:~ $ which cc
/usr/bin/cc
homebridge-pi@homebridge-dev:~ $ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: [....]
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10)
homebridge-pi@homebridge-dev:~ $

```

**Comment by bpartridge83** [comment]
@snowdd1 That's exactly my output, with the same issue as @SR2k.

**Comment by niXta1** [comment]
I get the same error...

**Comment by niXta1** [comment]
> @snowdd1 What does which cc give you? Something like this?


```
pi@Rasse:~ $ which cc
/usr/bin/cc
pi@Rasse:~ $ 
pi@Rasse:~ $ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10) 

```

**Comment by snowdd1** [comment]
As all of you are using `sudo`, you should also use sudo with the commands above, otherwise you could have a different set of environment variables.
