### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID

### ISSUE THREAD

**Issue by DJay79** [nfarina/homebridge#1316]
Hi there.
Somehow I messed up my homebridge. Don't know how. So I deinstalled all plugins, even homebridge itself. Now I'm installing one plugin after another. i.e. sudo npm install -g homebridge-netatmo
The most installed without any problem, some showed me an error. Other after starting homebridge.
So first..
This happens during installation of **homebridge-nest**
Does somebody know how I can fix **ERR! code 128 npm ERR! Command failed**
I already installed **sudo apt-get install git make**

Another problem I'm facing ist with **homebridge-netatmo**
Installation worked well. But when starting homebridge I get the UUID problem.
I changed the config.json with another username after I deinstalled in the first step homebridge, plugins and then reinstalled. I build the "new" config.json.
How do I get rid of this UUID error? In the config is "platform": "netatmo", "name": "netatmo weather" 
Changing this was not helpful. Also I deleted /home/pi/.homebridge the folders persist and accessories without and success. 

Thanks in advance to somebody who is willing to support me with this problems and is patient with me. ;) I'm a bit desperate at the moment.

[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Deutschherrnufer Wohnzimmer'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Deutschherrnufer Schlafzimmer'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Deutschherrnufer Wintergarten'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Deutschherrnufer Balkon'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Deutschherrnufer Außen'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'BrownLeder Küche'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'BrownLeder Terasse'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'BrownLeder Wohnzimmer'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'BrownLeder Schlafzimmer'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Thermostat'...
[2017-6-3 00:21:48] [netatmo weather] Initializing platform accessory 'Thermostat'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: bfb776c7-bc35-44df-8750-93a0075f6b78
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at NetatmoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/index.js:56:7)
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:3679:13
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:997:17)
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:847:20
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:3676:17
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:339:31
    at /usr/local/lib/node_modules/homebridge-netatmo/index.js:71:13
    at WeatherstationDeviceType.buildAccessories (/usr/local/lib/node_modules/homebridge-netatmo/lib/netatmo-device.js:114:5)
    at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/lib/netatmo-device.js:55:14)
    at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/lib/netatmo-device.js:69:13)
    at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/device/weatherstation-device.js:38:9)
    at netatmo.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/netatmo/netatmo.js:227:14)

**Comment by DJay79** [comment]
After I found in the depth of my hard drive a very old backup of my raspi, I decided to restore this und build the rest from scratch. This worked for me. So this Issue is closed.
