### ISSUE TITLE
Homebirdge wont't run after raspi-config update

### ISSUE THREAD

**Issue by daniel4099** [nfarina/homebridge#1332]
Hello,

I accidentally made update using default raspi configurator.
After this when I run hombirdge I have the fallowing issue:

Please help...

fs.js:745
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^

Error: ENOSPC: no space left on device, write
    at Object.fs.writeSync (fs.js:745:20)
    at Object.fs.writeFileSync (fs.js:1326:24)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
    at Object.nodePersist.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:99:29)
    at AccessoryInfo.save (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:161:11)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:439:23)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19

**Comment by NorthernMan54** [comment]
> Error: ENOSPC: no space left on device, write
> 

Your storage is full!!!

**Comment by djfatal** [comment]
sudo apt-get autoclean

**Comment by toshibochan** [comment]
Please close this issue if you have your answer. Thanks
