### ISSUE TITLE
Errors after updating working homebridge, need  help

### ISSUE THREAD

**Issue by jeroen1973** [nfarina/homebridge#1379]
Hi there,

i had an working set of homebridge with pluginns : homewizard and Nest.

After updating system, homebridge and pluginns a get this error:

@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
[2017-07-07 17:32:27] Loaded plugin: homebridge-homewizard
[2017-07-07 17:32:27] Registering platform 'homebridge-homewizard.HomeWizard'
[2017-07-07 17:32:27] ---
[2017-07-07 17:32:29] Loaded plugin: homebridge-nest
[2017-07-07 17:32:29] Registering platform 'homebridge-nest.Nest'
[2017-07-07 17:32:29] ---
[2017-07-07 17:32:29] Loaded config.json with 0 accessories and 2 platforms.
[2017-07-07 17:32:29] ---
[2017-07-07 17:32:29] Loading 2 platforms...
[2017-07-07 17:32:29] Initializing HomeWizard platform...
[2017-07-07 17:32:29] Automatic refresh every 5 mn
[2017-07-07 17:32:29] Initializing Nest platform...
[2017-07-07 17:32:29] Fetching Nest devices.
[2017-07-07 17:32:29] Loading 0 accessories...
[2017-07-07 17:32:29] Listening UDP IPv4 0.0.0.0:33333
events.js:141
throw er; // Unhandled 'error' event
^

Error: listen EADDRINUSE :::8087
at Object.exports._errnoException (util.js:870:11)
at exports._exceptionWithHostPort (util.js:893:20)
at Server._listen2 (net.js:1236:14)
at listen (net.js:1272:10)
at Server.listen (net.js:1368:5)
at new NotificationListener (/usr/local/lib/node_modules/homebridge-homewizard/dist/notificationListener.js:58:8)
at new HomeWizardPlatform (/usr/local/lib/node_modules/homebridge-homewizard/dist/platform.js:61:21)
at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:134:18)
at node.js:962:3

Can anyone tell me how to fix this?

**Comment by snowdd1** [comment]
`Error: listen EADDRINUSE :::8087` means that something is already using port 8087 on IPv6 on localhost. Are you sure you are not trying to run two instances?

**Comment by EdwinJS** [comment]
Yeah this often occurs if the system process wasn't stopped or if you start homebridge twice and it attempts to run an instance on the same port. Easiest fix is to run the command **killall homebridge**

This will force close all instances and you can just run the command **homebridge** like usual to start, or even start up your system service if you have set that up. 😊

**Comment by jeroen1973** [comment]
Thanks for the help, the "Killall" and restart did the trick!
