### ISSUE TITLE
SyntaxError: Unexpected token   in JSON at position 185

### ISSUE THREAD

**Issue by chezpaul** [nfarina/homebridge#1382]
Thank you all for writing this little piece of sweetness.

I get this error when I launch

pi@raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[7/12/2017, 4:56:43 AM] Loaded plugin: homebridge-vera
VeraLink initializing
[7/12/2017, 4:56:43 AM] Registering platform 'homebridge-veralink.Vera'
[7/12/2017, 4:56:43 AM] ---
[7/12/2017, 4:56:43 AM] There was a problem reading your config.json file.
[7/12/2017, 4:56:43 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[7/12/2017, 4:56:43 AM] 
/usr/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token   in JSON at position 185
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

My config.json

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Vera",
		"name": "Vera",
		"veraIP": "192.168.1.110" 
	}]
}

What did I do wrong?

**Comment by maragelis** [comment]
Try this 
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"pin": "031-45-154"
	},
	"accessories": [],
	"platforms": [{
		"platform": "Vera",
		"name": "Vera",
		"veraIP": "192.168.1.110"
	}]
}

**Comment by chezpaul** [comment]
You da man.  ;-)
Thanks

**Comment by aycgit** [comment]
Please close this issue for cleanup.
