### ISSUE TITLE
homebridge only runs with sudo

### ISSUE THREAD

**Issue by matthieunelmes** [nfarina/homebridge#1397]
Was previously working fine without the need for sudo. 

Since installing a plugin (which I've since removed to see if this was the problem) I now see this whenever I run homebridge. Has anyone come across this before? Really appreciate some help.

`Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:517:19)
    at LocalStorage.parseDirSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:610:35)
    at LocalStorage.parseDataDirSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:545:21)
    at LocalStorage.initSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:145:14)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:31:20)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)`

**Comment by matthieudu06** [comment]
I had the same issue. I'm using sudo every time now, working well tho...

**Comment by matthieunelmes** [comment]
Don't particulate feel comfortable on using sudo every time. I must've messed up permissions at some point when installing plugins so re-flashed my raspberry Pi install and reinstalled homebridge from scratch. Works fine now
