### ISSUE TITLE
YamahaAVR error 

### ISSUE THREAD

**Issue by luxus** [nfarina/homebridge#140]
Thank you @SphtKr for adding the YamahaAVR support.
i have a brand new RX-A1050.
but the discovery of the avr is not working

i add the yamaha config stuff to my config.json
```json
   {
     "platform": "YamahaAVR",
    "play_volume": -35,
      "setMainInputTo": "AirPlay"
    }
```
homebridge stops after this:
```
Loading 2 platforms...
[Phillips Hue] Initializing PhilipsHue platform...
[Phillips Hue] Fetching Philips Hue lights...
[undefined] Initializing YamahaAVR platform...
[undefined] Getting Yamaha AVR devices.
Loading 0 accessories...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo -3008
    at errnoException (/home/pi/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/home/pi/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/home/pi/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by SphtKr** [comment]
Awesome catch! Thanks!
