### ISSUE TITLE
crash after update

### ISSUE THREAD

**Issue by sirdir1972** [nfarina/homebridge#1400]
Hi!
I just updated homebridge and now it's not working anymore (also disabling the certificate check for homeassistant doesn't work anymore, so I just put the 'official' hostname instead of the IP), but the mian problem is this: 

`/usr/local/lib/node_modules/homebridge-homeassistant/accessories/sensor.js:107
  } else if (data.attributes.unit_of_measurement.toLowerCase() === 'lux' || data.attributes.homebridge_sensor_type === 'light') {
                                                ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at HomeAssistantSensorFactory (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/sensor.js:107:49)
    at request (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:179:23)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:96:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by mu3** [comment]
Bug fix https://github.com/home-assistant/homebridge-homeassistant/releases/tag/2.2.1

**Comment by sirdir1972** [comment]
Thank you
