### ISSUE TITLE
can't start homebridge or ps4-waker

### ISSUE THREAD

**Issue by noaboa97** [nfarina/homebridge#1411]
Hello,

I'm trying to install the homebridge on my raspberry pi 2 but it ain't working.
I installed the nfarina homebridge as described. 

and i get error messages when i try to start the homebridge or the ps4-waker:

**pi@raspberrypi:~ $ homebridge**
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility la                 yer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=                 libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is                  not supported (or only supported partially) in the Apple Bonjour compatibili                 ty layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=                 libdns_sd&e=nodejs&f=DNSServiceRegister>

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Camera.js:28
  let options = {
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap                 -nodejs/index.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**pi@raspberrypi:~ $ ps4-waker**

/usr/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

My Node version 
pi@raspberrypi:~ $ node -v
v0.10.48

and I also installed the libavahi-compat-libdnssd-dev package (avahi)

Can someone help me?

many thanks in advance

**Comment by NebzHB** [comment]
Upgrade nodejs that's a very old version, the LTS is now version 6.x

**Comment by noaboa97** [comment]
thanks for your respond
yeah already tried that but didn't help

pi@raspberrypi:~ $ node -v
v6.11.1

**Comment by EdwinJS** [comment]
It may be beneficial in restarting the process of installing home bridge and assuring the latest version of nodejs is installed first, before the rest of the configuration goes through.

**Comment by LOCOSP** [comment]
root@raspberrypi:~# ps4-waker

/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
root@raspberrypi:~# node -v
v0.10.29
root@raspberrypi:~# 

It's from Rpi, any ideas?

**Comment by plasticrake** [comment]
Closing this issue. @LOCOSP you're still running a very old version of node.. upgrade to at least v4. And please keep on topic to homebridge, ps4-waker is another project.
