### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sh4545** [nfarina/homebridge#1412]
Hi,
I'm having this error

# homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[7/27/2017, 1:27:10 PM] Loaded plugin: homebridge-homeseer
[7/27/2017, 1:27:10 PM] Registering accessory 'homebridge-homeseer.HomeSeer'
[7/27/2017, 1:27:10 PM] Registering platform 'homebridge-homeseer.HomeSeer'
[7/27/2017, 1:27:10 PM] ---
[7/27/2017, 1:27:10 PM] Loaded config.json with 1 accessories and 1 platforms.
[7/27/2017, 1:27:10 PM] ---
[7/27/2017, 1:27:10 PM] Loading 1 platforms...
[7/27/2017, 1:27:10 PM] [HS3] Initializing homebridge-homeseer.HomeSeer platform...
[7/27/2017, 1:27:10 PM] [HS3] Fetching HomeSeer devices.
/usr/local/lib/node_modules/homebridge-homeseer/index.js:247
        for( var i=0; i<this.config.accessories.length; i++ ) {
                                               ^

TypeError: Cannot read property 'length' of undefined
    at Object.HomeSeerPlatform.accessories (/usr/local/lib/node_modules/homebridge-homeseer/index.js:247:48)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
root@ubuntu:/home/user1# nano /root/.homebridge/config.json
root@ubuntu:/home/user1# nano /root/.homebridge/config.json
root@ubuntu:/home/user1# homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[7/27/2017, 1:33:02 PM] Loaded plugin: homebridge-homeseer
[7/27/2017, 1:33:02 PM] Registering accessory 'homebridge-homeseer.HomeSeer'
[7/27/2017, 1:33:02 PM] Registering platform 'homebridge-homeseer.HomeSeer'
[7/27/2017, 1:33:02 PM] ---
[7/27/2017, 1:33:02 PM] Loaded config.json with 1 accessories and 1 platforms.
[7/27/2017, 1:33:02 PM] ---
[7/27/2017, 1:33:02 PM] Loading 1 platforms...
[7/27/2017, 1:33:02 PM] [HS3] Initializing homebridge-homeseer.HomeSeer platform...
[7/27/2017, 1:33:02 PM] [HS3] Fetching HomeSeer devices.
/usr/local/lib/node_modules/homebridge-homeseer/index.js:247
        for( var i=0; i<this.config.accessories.length; i++ ) {
                                               ^

TypeError: Cannot read property 'length' of undefined
    at Object.HomeSeerPlatform.accessories (/usr/local/lib/node_modules/homebridge-homeseer/index.js:247:48)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by NebzHB** [comment]
Dear,
As you can read, the problem is with homebridge-homeseer, please go there ;)
