### ISSUE TITLE
(HOMEBRIDGE MAC OS) There was a problem reading your config.json file.

### ISSUE THREAD

**Issue by GenreDown** [nfarina/homebridge#1415]
Hi guys,
after hours of researching (i'm a novice) I can't get my homebridge to work on OSX. I followed a guide  to control an ESP8266+relay with homebridge. I used this config.json : 

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        
    ],

    "accessories": [
        {    "accessory": "Http",
            "name": "PowerTail",
            "on_url": "http://192.168.1.110/gpio/1",
            "off_url": "http://192.168.1.110/gpio/0",
            "http_method": "GET"
        },
       
    ]
}

but I always have this error : 

[2017-7-28 19:27:41] Loaded plugin: homebridge-http
[2017-7-28 19:27:41] Registering accessory 'homebridge-http.Http'
[2017-7-28 19:27:41] ---
[2017-7-28 19:27:41] Loaded plugin: homebridge-hue
[2017-7-28 19:27:41] Registering platform 'homebridge-hue.Hue'
[2017-7-28 19:27:41] ---
[2017-7-28 19:27:41] There was a problem reading your config.json file.
[2017-7-28 19:27:41] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2017-7-28 19:27:41] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token ] in JSON at position 633
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

I pasted the code on JSONLint and here is what it returned : 

Error: Parse error on line 21:
...thod": "GET"		},	]}
--------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ']'

I tried editing my config.json file with several text editor (textwrangler, sublimetext, brackets,textedit).

Can someone help me find what's wrong please ?

**Comment by GvnCampbell** [comment]
My guess is the comma at the end of your accessories list.

**Comment by GenreDown** [comment]
@GvnCampbell ... I'm feeling so dumb right now ! Thank you very much I got homebridge working :)
But my iPhone can't find the device...

**Comment by GvnCampbell** [comment]
@GenreDown I usually find that when I have problems like I can fix them by shutting down homebridge.  Clear out the accessories and persist folders.  Launch homebridge and verify you see the box with the homekit code.  Then it usually works.  (Make sure iPhone and homebridge are on the same network).

If you don't see the box with the homekit code when you launch homebridge then a plugin is holding it up.  Clean out the config.json and put a basic one in.  Then add back the plugins until you find the one.

**Comment by daniel2029** [comment]
paste your config.json file into the box on http://jsonlint.com/ and it tells you where the error is.
