### ISSUE TITLE
Error running homebridge - module.js:471 throw err;

### ISSUE THREAD

**Issue by janforth** [nfarina/homebridge#1419]
Hi,

after an update via npm I always receive the error message shown below, whenever I try to run homebridge. A complete and new installation from GitHub via wget doesn't help. What can I do?

Thank you.

Best, Jan

 

module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by iCarl** [comment]
cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild

**Comment by noaboa97** [comment]
Got the same error after an update via npm. iCarl solution didn't work for me. Still got the same error message.

**Comment by noaboa97** [comment]
Ok i found a solution ! You need to do` sudo npm install --unsafe-perm mdns` and `sudo npm rebuild --unsafe-perm` at `/usr/local/lib/node_modules/homebridge`

**Comment by MarkusTec** [comment]
Hi, unfortunately I'm still running into a module.js:471 error.
I've tried #noaboa97 suggested solution to no avail.  After I type in "homebridge" to launch...the 471 error appears.  Any thoughts on this?

**Comment by JonSeale** [comment]
Make sure you're in the correct directory. in my case is was /usr/lib/node_modules/homebridge
