### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jvannoyx4** [nfarina/homebridge#1422]
Not sure whats going on with this thing I appreciate help with this matter. All I did was restart my computer which is running Homebridge and when I attempted to start it again I get this error.

### `User-MacBook-Pro:~ user$ homebridge
[8/9/2017, 10:29:02 PM] Loaded plugin: homebridge-camera-isight
[8/9/2017, 10:29:02 PM] Registering platform 'homebridge-camera-isight.Camera-iSight'
[8/9/2017, 10:29:02 PM] ---
[8/9/2017, 10:29:03 PM] Loaded plugin: homebridge-homeassistant
[8/9/2017, 10:29:03 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[8/9/2017, 10:29:03 PM] ---
[8/9/2017, 10:29:03 PM] Loaded plugin: homebridge-http-securitysystem
[8/9/2017, 10:29:03 PM] Registering accessory 'homebridge-http-securitysystem.Http-SecuritySystem'
[8/9/2017, 10:29:03 PM] ---
[8/9/2017, 10:29:03 PM] Loaded plugin: homebridge-mqtt-switch-tasmota
[8/9/2017, 10:29:03 PM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[8/9/2017, 10:29:03 PM] ---
[8/9/2017, 10:29:04 PM] Loaded plugin: homebridge-mqttlightbulb
[8/9/2017, 10:29:04 PM] Registering accessory 'homebridge-mqttlightbulb.mqttlightbulb'
[8/9/2017, 10:29:04 PM] ---
[8/9/2017, 10:29:04 PM] Loaded plugin: homebridge-people
[8/9/2017, 10:29:04 PM] Registering platform 'homebridge-people.People'
[8/9/2017, 10:29:04 PM] Registering accessory 'homebridge-people.PeopleAccessory'
[8/9/2017, 10:29:04 PM] Registering accessory 'homebridge-people.PeopleAllAccessory'
[8/9/2017, 10:29:04 PM] ---
[8/9/2017, 10:29:04 PM] Loaded plugin: homebridge-people-plus
[8/9/2017, 10:29:04 PM] Registering accessory 'homebridge-people-plus.PeoplePlus'
[8/9/2017, 10:29:04 PM] ---
[8/9/2017, 10:29:04 PM] Loaded plugin: homebridge-server
[8/9/2017, 10:29:04 PM] Registering platform 'homebridge-server.Server'
[8/9/2017, 10:29:04 PM] ---
[8/9/2017, 10:29:04 PM] Loaded config.json with 0 accessories and 4 platforms.
[8/9/2017, 10:29:04 PM] ---
[8/9/2017, 10:29:04 PM] Loading 4 platforms...
[8/9/2017, 10:29:04 PM] [HomeAssistant] Initializing HomeAssistant platform...
[8/9/2017, 10:29:04 PM] [HomeAssistant] Fetching HomeAssistant devices.
[8/9/2017, 10:29:04 PM] [Homebridge Server] Initializing Server platform...
[8/9/2017, 10:29:04 PM] [iSight Camera] Initializing Camera-iSight platform...
[8/9/2017, 10:29:04 PM] Initializing People platform...
[8/9/2017, 10:29:04 PM] Initializing platform accessory 'Joshua'...
[8/9/2017, 10:29:04 PM] Initializing platform accessory 'Test Person'...
[8/9/2017, 10:29:04 PM] Initializing platform accessory 'Anyone'...
[8/9/2017, 10:29:04 PM] WebHook: Started server on port '51828'.
[8/9/2017, 10:29:04 PM] Loading 0 accessories...
[8/9/2017, 10:29:04 PM] [Homebridge Server] is listening on: http://10.0.1.2:8765
[8/9/2017, 10:29:04 PM] iSight Camera is running on port 51070.
[8/9/2017, 10:29:04 PM] [HomeAssistant] Received event: ping
undefined:1
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:96:38)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by jvannoyx4** [comment]
This is my Config.json 

`
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is User's Homekit Server.",
    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://10.0.1.99:8123",
            "password": "password",
            "supported_types": [
                "binary_sensor",
                "climate",
                "cover",
                "device_tracker",
                "fan",
                "group",
                "input_boolean",
                "light",
                "lock",
                "media_player",
                "scene",
                "sensor",
                "switch"
            ],
            "logging": true
        },
        {
            "platform": "Server",
            "port": 8765,
            "name": "Homebridge Server",
            "log": "systemd",
            "restart": "<COMMAND_TO_EXECUTE>"
        },
				{

           "platform": "Camera-iSight",
           "name": "iSight Camera",
           "fps": 30
        },
        {
            "platform": "People",
            "threshold": 15,
            "anyoneSensor": true,
            "nooneSensor": false,
            "webhookPort": 51828,
            "cacheDirectory": "./.node-persist/storage",
            "pingInterval": 10000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "User",
                    "target": "10.0.1.4",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Test Person",
                    "target": "10.0.2.77",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
        }
    ],
    "accessories": []
}
`
