### ISSUE TITLE
Updating my Homebrdige?

### ISSUE THREAD

**Issue by sdorilas** [nfarina/homebridge#1429]
Can anyone assist me with the following error?

====================
[8/12/2017, 5:03:52 PM] ERROR LOADING PLUGIN homebridge-arlo:
[8/12/2017, 5:03:52 PM] Error: Plugin /usr/local/lib/node_modules/homebridge-arlo requires a HomeBridge version of >=0.4.1 which does not satisfy the current HomeBridge version of 0.3.4. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:112:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:108:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:43:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[8/12/2017, 5:03:52 PM] ===================

home:~ sdorilas$ npm homebridge -v
5.3.0

┌─────────────────────────────────────────────────────────────┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) /Users/sdorilas/.config │
└─────────────────────────────────────────────────────────────┘
home:~ sdorilas$

**Comment by pdlove** [comment]
the version 5.3.0 is the npm version.
To see homebridge version:
`homebridge -V`
to update:
`npm update --global homebridge `

**Comment by sdorilas** [comment]
Thank you @pdlove. I was able to update it but still getting the following:

ERROR LOADING PLUGIN homebridge-arlo:
[8/16/2017, 10:35:43 AM] ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by robboz4** [comment]
On my RPi3 versions there is no -v option on homebridge: 

homebridge -v
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

  error: unknown option `-v'

So how do we find the version installed?

**Comment by Samfox2** [comment]
Please use -V not -v

**Comment by robboz4** [comment]
Ok thanks that worked.

Is there a published troubleshooting guide anywhere for homebridge?

**Comment by pdlove** [comment]
On the error you're getting now, that appears to be in the plugin homebridge-arlo.
I'm not sure if anyone has created a trouble shooting guide.

**Comment by sdorilas** [comment]
I thought so. Thank you!
