### ISSUE TITLE
Homebridge crashing after a few hours

### ISSUE THREAD

**Issue by noaboa97** [nfarina/homebridge#1430]
Hello, 

So I got my homebridge working but after a few hours it'll crash and I get this error.

errorhub { Error: connect ETIMEDOUT 192.168.1.139:5222
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.139',
  port: 5222 }
errorhub { Error: connect EHOSTUNREACH 192.168.1.139:5222
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.139',
  port: 5222 }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
root@raspberrypi:~# OS~

does anybody have an idea whats wrong?  

thanks in advance

**Comment by pdlove** [comment]
It looks like the harmonyhub plugin is causing this. You might try posting there.
KraigM/homebridge-harmonyhub#70

**Comment by noaboa97** [comment]
Okay thanks 
I Just posted it there but can you tell anything from this error? What maybe helps me?

**Comment by ToddGreenfield** [comment]
This is a known issue with the Harmony Hub itself, and one of the dependencies libraries is not catching the error. Check out issue #84 on that plugin's issues page. There are workarounds but no fixes.

**Comment by noaboa97** [comment]
@ToddGreenfield how is #84 related to my issue to me it seems it absolutly diffrent

**Comment by ToddGreenfield** [comment]
The issue on the homebridge-harmonyhub plugin - https://github.com/KraigM/homebridge-harmonyhub/issues/84

**Comment by noaboa97** [comment]
I read a lot of stuff so I thought I just make sure it's not the connection of the harmony to my router wich fails or somethings with the network. So I placed another router next to my hamrony hub and since then my homebridge hasn't crashed. Although my router is in the living room and I've got my harmonyhub in my room wich is about 3-4 meters away with a wall between and I thought the connection is good but it turned out not to be...
