### ISSUE TITLE
Hombridge 0.4.24 results in issues with homebridge-nest  1.2.2

### ISSUE THREAD

**Issue by DMBlakeley** [nfarina/homebridge#1433]
When updated to Homebridge 0.4.24 / hap-nodejs 0.4.29 I received the following error.  I have fallen back to Homebridge 0.4.22 / hap-nodes 0.4.27 and the issue was resolved.

[8/15/2017, 7:04:33 PM] TypeError: Cannot read property 'on' of undefined
    at NestThermostatAccessory.NestDeviceAccessory.bindCharacteristic (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:65:9)
    at NestThermostatAccessory.NestDeviceAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:10)
    at new NestThermostatAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:35:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:117:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:124:4)
    at /usr/local/lib/node_modules/homebridge-nest/index.js:152:28
[8/15/2017, 7:04:33 PM] Falling back to legacy API.
[8/15/2017, 7:04:34 PM] Away for Nest is: false
[8/15/2017, 7:04:34 PM] Temperature unit for Nest is: Fahrenheit
[8/15/2017, 7:04:34 PM] Current temperature for Nest is: 26.92999
[8/15/2017, 7:04:34 PM] Current heating for Nest is: 2
[8/15/2017, 7:04:34 PM] Current humidity for Nest is: 61
[8/15/2017, 7:04:34 PM] Target heating for Nest is: 2
[8/15/2017, 7:04:34 PM] Target temperature for Nest is: 26.666666666666668
[8/15/2017, 7:04:34 PM] Initializing platform accessory 'Nest'...

**Comment by pdlove** [comment]
It looks like the plugin is setting the "Software Revision" characteristic which Apple removed. Let me review a few areas to see what can be done to help make it more compatible. We added the characteristic so they are available, but it seems that optional characteristics being removed have caused some issues.
I'm looking to see if the code can be safely tweaked to allow adding other characteristics the way that this plugin was adding the optional ones.

**Comment by pdlove** [comment]
Give it a try with Homebridge 0.4.25 which was just updated.

**Comment by DMBlakeley** [comment]
Although Homebridge seems to run OK I am receiving the following warning when initial starting:

HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.


Regards,
Doug

---
Douglas Blakeley
douglas.blakeley@gmail.com

**Comment by pdlove** [comment]
That is expected. HomeKit no longer has Characteristic 54 (Software Version) as an optional characteristic for the the service 3E (Accessory Info). The plugin developer needs to resolve that, but everything should work fine unless Apple starts rejecting that characteristic.  The warning is there to make sure people are aware in case they start having trouble. I'm going to try and determine a simple way to add the textual name, but for now the UUID will have to work.

**Comment by DMBlakeley** [comment]
Hi,

Thanks for the prompt explanation.  Looks like the problem is in the homebridge-nest package.  The error is generated for the Nest Thermostat and then the Nest Protect.  I will post a problem report on the homebridge-nest page.

Regards,
Doug

---
Douglas Blakeley
douglas.blakeley@gmail.com

**Comment by pdlove** [comment]
Make sure you link this issue there as well. Everything should run fine despite the warning.

**Comment by RobotLimeLtd** [comment]
Since upgrading to iOS11, my Nest Thermostat is no longer recognised by the Home app.  There’s an icon, but it has an error against it, and the “Type” is not set.  Could this be related to the “HAP Warning” error (which I am also getting when I start homebridge)?

**Comment by DMBlakeley** [comment]
I have not had an issue with iOS 11 and my Nest Thermostat.  I would suggest restarting your iPhone (restart, not power off/on), restart Homebridge, and then relaunch the Home app on your iPhone.  If you are using an Apple TV or iPad for automations and remote access I suggest that you also restart this device also.

My understanding is that the HAP warning is due to the query on "software version" which is no longer supported by HomeKit and is probably not the cause of your problem.
