### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined - after 0.4.25 (#1436) upgrade

### ISSUE THREAD

**Issue by thusithapk** [nfarina/homebridge#1439]
```
[8/17/2017, 9:12:40 PM] Loaded plugin: homebridge-hs100
[8/17/2017, 9:12:40 PM] Registering platform 'homebridge-hs100.Hs100'
[8/17/2017, 9:12:40 PM] ---
[8/17/2017, 9:12:44 PM] Loaded plugin: homebridge-nest
[8/17/2017, 9:12:44 PM] Registering platform 'homebridge-nest.Nest'
[8/17/2017, 9:12:44 PM] ---
[8/17/2017, 9:12:44 PM] Loaded plugin: homebridge-rm-mini3
[8/17/2017, 9:12:44 PM] Registering accessory 'homebridge-rm-mini3.RM mini3'
[8/17/2017, 9:12:44 PM] ---
[8/17/2017, 9:12:44 PM] Loaded config.json with 3 accessories and 2 platforms.
[8/17/2017, 9:12:44 PM] ---
[8/17/2017, 9:12:44 PM] Loading 2 platforms...
[8/17/2017, 9:12:44 PM] Initializing Hs100 platform...
[8/17/2017, 9:12:44 PM] Initializing Nest platform...
[8/17/2017, 9:12:44 PM] Fetching Nest devices.
[8/17/2017, 9:12:44 PM] Loading 3 accessories...
[8/17/2017, 9:12:44 PM] [TV] Initializing RM mini3 accessory...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:225
      if (myString.length>maxLength) myString = myString.substring(0,maxLength); //Truncate strings that are too long
                  ^

TypeError: Cannot read property 'length' of undefined
    at Characteristic.validateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:225:19)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:273:19)
    at Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:178:32)
    at Object.getServices (/usr/local/lib/node_modules/homebridge-rm-mini3/index.js:63:8)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by Samfox2** [comment]
This happens if the string is empty, e.g. if a Characteristic.Manufacturer is defined but no name is assigned.
As long as there is no validation basic string validation added, values should be predifined in the plugin.

**Comment by thusithapk** [comment]
Yep. Gave a fake value and all good.
Thanks.
