### ISSUE TITLE
Config.json Syntax error unexpected token

### ISSUE THREAD

**Issue by 1davebock** [nfarina/homebridge#1447]
Hi,

Please help!

I have installed Homebridge on Ubuntu 16.04. The syntax looks to be correct however, still getting errors. Could it be that I am missing a library or something?? Error message (it's long) listed below:

Here is my config.json script:
====================
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},
"accessories": [],
"platforms": [{
            "platform": "HomeAssistant",
                        "name" : "HomeAssistant",
                        "host": “http://10.108.14.209:8123”,
                        "password": “passwordhere”,
                        "supported_types": ["input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"],
        }]
}

=====================

ERRORS:
overlord@Red-CommandCentre:~/.homebridge$ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/18/2017, 8:15:46 PM] Loaded plugin: homebridge-homeassistant
[8/18/2017, 8:15:46 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[8/18/2017, 8:15:46 PM] ---
[8/18/2017, 8:15:46 PM] There was a problem reading your config.json file.
[8/18/2017, 8:15:46 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[8/18/2017, 8:15:46 PM]
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

Error: EACCES: permission denied, open '/home/overlord/.homebridge/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:28)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by shidevil** [comment]
Run "sudo homebridge" and also ur config file is wrong. Use the below one.  

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},
"accessories": [],
"platforms": [{
"platform": "HomeAssistant",
"name" : "HomeAssistant",
"host": “http://10.108.14.209:8123”,
"password": “passwordhere”,
"supported_types": ["input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"]
}]
}

**Comment by 1davebock** [comment]
I've inserted the above as:
`{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},
"accessories": [],
"platforms": [{
"platform": "HomeAssistant",
"name" : "HomeAssistant",
"host": “http://10.108.14.209:8123”,
"password": passwordhere,
"supported_types": ["input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"]
}]
}`

Ran as Sudo - same errors apply.

**Comment by shidevil** [comment]
Do a chmod 777 on the config.json and try again

**Comment by 1davebock** [comment]
Ok thanks. Got a step further. Now the config.json is loading but error is as follows:
[8/19/2017, 9:06:46 PM] [HomeAssistant] Please set default_visibility in config.json to "hidden" or "visible".

overlord@Red-CommandCentre:~/.homebridge$ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/19/2017, 9:06:46 PM] Loaded plugin: homebridge-homeassistant
[8/19/2017, 9:06:46 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[8/19/2017, 9:06:46 PM] ---
[8/19/2017, 9:06:46 PM] Loaded config.json with 1 accessories and 1 platforms.
[8/19/2017, 9:06:46 PM] ---
[8/19/2017, 9:06:46 PM] Loading 1 platforms...
[8/19/2017, 9:06:46 PM] [HomeAssistant] Initializing HomeAssistant platform...
[8/19/2017, 9:06:46 PM] [HomeAssistant] Please set default_visibility in config.json to "hidden" or "visible".
[8/19/2017, 9:06:46 PM] [HomeAssistant] Fetching HomeAssistant devices.
[8/19/2017, 9:06:46 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by shidevil** [comment]
Try this

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},
"accessories": [],
"platforms": [{
"platform": "HomeAssistant",
"name" : "HomeAssistant",
"host": “http://10.108.14.209:8123”,
"password": “passwordhere”,
"supported_types": ["input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"],
"default_visibility": "visible"
}]
}

**Comment by 1davebock** [comment]
Thanks that removed the default visibility issue but the second part of the error is still displaying: 
[8/19/2017, 9:06:46 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
if (name.indexOf('.') == -1) {
^

TypeError: Cannot read property 'indexOf' of undefined
at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by shidevil** [comment]
Do u have another plugin? Try this again 

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},
"platforms": [{
"platform": "HomeAssistant",
"name" : "HomeAssistant",
"host": “http://10.108.14.209:8123”,
"password": “passwordhere”,
"supported_types": ["input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"],
"default_visibility": "visible"
}]
}

**Comment by shidevil** [comment]
Do note that the host and password " " must be correct

**Comment by shidevil** [comment]
Welcome!

**Comment by shidevil** [comment]
@1davebock do close this issue if it's fixed.
