### ISSUE TITLE
Can someone tell me whats going on here?

### ISSUE THREAD

**Issue by jimmirehman** [nfarina/homebridge#1463]
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:155:6

**Comment by shidevil** [comment]
Homebridge is already running. 


Sudo killall homebridge

**Comment by jimmirehman** [comment]
ok, but it still happens when i run homebridge


Last login: Sun Aug 27 13:31:28 on ttys000
Jimmis-iMac:~ omega$ Sudo killall homebridge
Password:
Jimmis-iMac:~ omega$ homebridge
[8/27/2017, 1:37:41 PM] Loaded plugin: homebridge-liftmaster2
[8/27/2017, 1:37:41 PM] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[8/27/2017, 1:37:41 PM] ---
[8/27/2017, 1:37:42 PM] Loaded plugin: homebridge-nest
[8/27/2017, 1:37:42 PM] Registering platform 'homebridge-nest.Nest'
[8/27/2017, 1:37:42 PM] ---
[8/27/2017, 1:37:42 PM] Loaded plugin: homebridge-platform-wemo
[8/27/2017, 1:37:42 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[8/27/2017, 1:37:42 PM] ---
[8/27/2017, 1:37:42 PM] Loaded config.json with 0 accessories and 3 platforms.
[8/27/2017, 1:37:42 PM] ---
[8/27/2017, 1:37:42 PM] Loading 3 platforms...
[8/27/2017, 1:37:42 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[8/27/2017, 1:37:42 PM] Initializing LiftMaster2 platform...
[8/27/2017, 1:37:42 PM] Initializing Nest platform...
[8/27/2017, 1:37:42 PM] Fetching Nest devices.
[8/27/2017, 1:37:42 PM] [WeMo Platform] Online: Kitchen LED [94103E3D1710]
[8/27/2017, 1:37:42 PM] [WeMo Platform] Online: Kitchen lights [149182474F48]
[8/27/2017, 1:37:42 PM] [WeMo Platform] Online: Front Roof LED [94103E3BD914]
[8/27/2017, 1:37:42 PM] [WeMo Platform] Online: Frontdoor Lamp [94103E3D3E7C]
[8/27/2017, 1:37:42 PM] [WeMo Platform] Online: Living Room Lamp [B4750E74E97C]
[8/27/2017, 1:37:42 PM] [WeMo Platform] Kitchen lights - Get state: On
[8/27/2017, 1:37:43 PM] Initializing platform accessory 'Garage Door (ID: 63338330)'...
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[8/27/2017, 1:37:44 PM] Software version for Fort Myers Thermostat (Home) is: 5.6.3-1
[8/27/2017, 1:37:44 PM] Temperature unit for Fort Myers Thermostat (Home) is: Fahrenheit
[8/27/2017, 1:37:44 PM] Current temperature for Fort Myers Thermostat (Home) is: 72.86 F
[8/27/2017, 1:37:44 PM] Current heating for Fort Myers Thermostat (Home) is: Cooling
[8/27/2017, 1:37:44 PM] Current humidity for Fort Myers Thermostat (Home) is: 50%
[8/27/2017, 1:37:44 PM] Target temperature for Fort Myers Thermostat (Home) is: 72.86 F
[8/27/2017, 1:37:44 PM] Target heating for Fort Myers Thermostat (Home) is: Cooling
[8/27/2017, 1:37:44 PM] Initializing platform accessory 'Fort Myers Thermostat (Home)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:155:6
Jimmis-iMac:~ omega$

**Comment by shidevil** [comment]
run netstat-ano 

 Find out which pid is using the 51826 port,PID is at the far right. and do a sudo kill -9 <pid>

**Comment by jimmirehman** [comment]
netstat-ano says command not found

nets tat brings up a bunch of stuff but nothing showing 51826

**Comment by shidevil** [comment]
You need to find out which service is using the port.  

Or did you auto run homebridge? systemd?

**Comment by dhruvsahni** [comment]
Simply restart

**Comment by jimmirehman** [comment]
can't i just change the port?

I port forwarded the 51826 in Airport utility and it used to work fine.

I changed the port to 51836 in my config.json and reran home bridge in terminal and it didn't give the error but all my devices show "No response" in the home app. 

I deleted the port forwarding and changed the config.json back to 51826 and reran homebridge and the error comes back

**Comment by Dero99** [comment]
you must have homebridge auto launching in Launchd, so running it manually is starting a second instance.
