### ISSUE TITLE
Unhandled 'error' event?

### ISSUE THREAD

**Issue by jimmirehman** [nfarina/homebridge#1473]
What does this mean?

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:155:6
Jimmis-iMac:~ omega$

**Comment by vsidlu** [comment]
Homebridge is already running.

**Comment by jimmirehman** [comment]
well I've already tried sudo killall homebridge and that doesn't fix the problem. also, none of my devices are accessible. they all say, "No response".

**Comment by vsidlu** [comment]
i do not know which option you use for run homebridge on startup and background but it is possible that after killall it auto starts again. try to use command killall homebridge two times in a row and then run homebridge. see also systemctl status homebridge to see if service is running.

**Comment by jimmirehman** [comment]
I use "launchd" for auto starting homebridge with "com.homebridge.server.plist"...

I ran killall homebridge until, "No matching processes belonging to you were found".

then ran homebridge again, see below:


Jimmis-iMac:~ omega$ killall homebridge
Jimmis-iMac:~ omega$ killall homebridge
Jimmis-iMac:~ omega$ killall homebridge
No matching processes belonging to you were found
Jimmis-iMac:~ omega$ homebridge
[9/4/2017, 2:13:57 PM] Loaded plugin: homebridge-liftmaster2
[9/4/2017, 2:13:57 PM] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[9/4/2017, 2:13:57 PM] ---
[9/4/2017, 2:13:57 PM] Loaded plugin: homebridge-nest
[9/4/2017, 2:13:57 PM] Registering platform 'homebridge-nest.Nest'
[9/4/2017, 2:13:57 PM] ---
[9/4/2017, 2:13:58 PM] Loaded plugin: homebridge-platform-wemo
[9/4/2017, 2:13:58 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[9/4/2017, 2:13:58 PM] ---
[9/4/2017, 2:13:58 PM] Loaded config.json with 0 accessories and 3 platforms.
[9/4/2017, 2:13:58 PM] ---
[9/4/2017, 2:13:58 PM] Loading 3 platforms...
[9/4/2017, 2:13:58 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[9/4/2017, 2:13:58 PM] Initializing LiftMaster2 platform...
[9/4/2017, 2:13:58 PM] Initializing Nest platform...
[9/4/2017, 2:13:58 PM] Fetching Nest devices.
[9/4/2017, 2:13:58 PM] [WeMo Platform] Online: Frontdoor Lamp [94103E3D3E7C]
[9/4/2017, 2:13:58 PM] [WeMo Platform] Online: Front Roof LED [94103E3BD914]
[9/4/2017, 2:13:58 PM] [WeMo Platform] Online: Kitchen light [149182474F48]
[9/4/2017, 2:13:58 PM] [WeMo Platform] Online: Kitchen LED [94103E3D1710]
[9/4/2017, 2:13:58 PM] [WeMo Platform] Online: Living Room Lamp [B4750E74E97C]
[9/4/2017, 2:13:59 PM] Initializing platform accessory 'Garage Door (ID: 63338330)'...
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[9/4/2017, 2:13:59 PM] Software version for Fort Myers Thermostat (Home) is: 5.6.3-1
[9/4/2017, 2:13:59 PM] Temperature unit for Fort Myers Thermostat (Home) is: Fahrenheit
[9/4/2017, 2:13:59 PM] Current temperature for Fort Myers Thermostat (Home) is: 73.94 F
[9/4/2017, 2:13:59 PM] Current heating for Fort Myers Thermostat (Home) is: Cooling
[9/4/2017, 2:13:59 PM] Current humidity for Fort Myers Thermostat (Home) is: 45%
[9/4/2017, 2:13:59 PM] Target temperature for Fort Myers Thermostat (Home) is: 73.94 F
[9/4/2017, 2:13:59 PM] Target heating for Fort Myers Thermostat (Home) is: Cooling
[9/4/2017, 2:13:59 PM] Initializing platform accessory 'Fort Myers Thermostat (Home)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:155:6
Jimmis-iMac:~ omega$

**Comment by vsidlu** [comment]
Somehow service is still running. I do not have any other explanation.

**Comment by Dero99** [comment]
If you use launchd to auto start homebridge, when you "kill" it, it will auto start again.  Then you are starting it again manually with the command giving you the address in use error.
So, I use Activity Monitor on the Mac to force quit Homebridge, you will see the process in the active list.  Wait 1 sec and it will appear on the list again and is running.
