### ISSUE TITLE
Error: Cannot find module '../build/Release/dns_sd_bindings'

### ISSUE THREAD

**Issue by jimmirehman** [nfarina/homebridge#1475]
what does this mean?

Jimmis-iMac:~ omega$ homebridge
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Jimmis-iMac:~ omega$

**Comment by SummerFrog** [comment]
Please refer to [https://github.com/nfarina/homebridge/issues/214](url)

**Comment by rbubley** [comment]
Solution is at #905.
