### ISSUE TITLE
unable to install on mac??

### ISSUE THREAD

**Issue by jat80** [nfarina/homebridge#1481]
I've got Xcode installed on my mac, i've just installed the latest nodejs from the website as per instructions https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS but still getting this after:

homebridge
module.js:491
throw err;
^

Error: Cannot find module '../build/Release/dns_sd_bindings'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
at Object. (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)

I actually had it running fine before and tried another plugin which didn't really work properly so uninstalled that plugin and removed details from my config and now get this.  

Any help would be appreciated, thanks!

**Comment by jat80** [comment]
Fixed it [here](https://github.com/NorthernMan54/homebridge-alexa/issues/27).
