### ISSUE TITLE
iOS 11 GM nothing work

### ISSUE THREAD

**Issue by marcotini** [nfarina/homebridge#1491]
I try several test but with iOS 11 nothing work anymore. Do you know why?

All the sensors and lights are in red status “not responding” and in iOS 10 work perfect.

**Comment by KhaosT** [comment]
Please make sure you update homebridge to latest version. Those problems should be addressed by latest version of homebridge.

**Comment by huseyint** [comment]
I had a similar issue after I have updated to iOS 11 last night, I was turning on a light through Home app, the light turns on just fine. But when I go to home screen iPhone then open the Home app again, the app was showing the light as turned off.

After upgrading to latest homebridge and restarting my raspberry pi, now the states are correct again as in iOS 10.

Note: I am using homebridge with home-assistant

**Comment by nicarley** [comment]
Yes an update, and reboot and my home bridge started working as well.  I have lots of devices connected through smart things.

**Comment by kmisiura** [comment]
For me HomeKit was showing all devices as not responding except homedridge bridge. After updating and restarting everything was not responding. 

So I tried to readd homebridge bridge. But now I cannot add it, HomeKit can’t find it.

**Comment by nicarley** [comment]
@kmisiura I have my files stored in /var/homebridge but yours might be different.  If so stop the homebridge service, delete the accessories and persistant folders and restart homebride.

**Comment by pewtertankard** [comment]
Had the same problem. Deleted the persist and accessories directories and restarted homebridge. Now all good. Thanks for the tip.

**Comment by georgbachmann** [comment]
I just reinstalled everything. Latest version of homebridge, I deleted my old home in the iOS Home app and tried to readd it, but it won't show up :( My Apple TV is on iOS 11 GM as well as my phone. Any ideas?

**Comment by gr4z** [comment]
I am having similar issues with iOS11 from my iPhone/iPad. Tried reinstalling and deleting the persist and accessories folders but to no avail :( My ATV is still on tvOS10 - maybe that is why?

**Comment by dkrizic** [comment]
ATV should be updated to iOS 11 today.

**Comment by georgbachmann** [comment]
But I am already running iOS 11 on all my devices?!? Any idea? It just doesn't show up on iOS when searching.

**Comment by vsidlu** [comment]
try to change config.json "username": "CC:22:3D:E3:CE:30" - just change one nr. or letter - "username": "**BB**:22:3D:E3:CE:30"

**Comment by georgbachmann** [comment]
cool.... will try that when I am at home tonight! thx!

**Comment by marcotini** [comment]
@vsidlu why BB should change something?

**Comment by thejacko12354** [comment]
Hey there, just want to confuse you, because I didn't update homebridge since May (or so) and still with iOS 11 GM everything works. :laughing:

**Comment by vsidlu** [comment]
I noticed that after I deleted home from ios - it do not shows up in add accessories. When I change user and restart homebridge - it shows up.

**Comment by fserruto** [comment]
Changing the username in config.json restored my HomeBridge! Thanks for the tip.

**Comment by sommo** [comment]
What is the right line command to update homebridge?
Also If there are a few let me know.. maybe something like npm update homebridge?
Will i lose my conig.json? Thank you!

**Comment by theo-69** [comment]
having same problem, not working after update to ios 11

**Comment by theo-69** [comment]
using the old Version from backup again and surprise after restarting the PI its working again

**Comment by freddo99** [comment]
Just updated to iOS 11 and all devices showing No Response. All suggestions welcome

**Comment by fserruto** [comment]
Try the above suggestions.

**Comment by freddo99** [comment]
Is there an way without changing config.json & reloading everything?

**Comment by fserruto** [comment]
Not that I’m aware, I had to bite the bullet and do it and now everything is working perfectly.  You get pretty good at it after a while and I have around 20 accessories to configure ;)

**Comment by freddo99** [comment]
Changed config.json info and now getting error 
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory
I have deleted persist & accessory info, but still getting error

**Comment by sommo** [comment]
to me and all of us that are looking how to update plugin, found on wiki homebridge:

Updating plugins

Periodically, Homebridge/plugins may be updated. To see if there are any updates you can run the following command to see what is available:

npm -g outdated

To update a particular plugin or Homebridge itself, run:

sudo npm -g update [homebridge | name-of-plugin]

To force an update, you can re-install it to force the latest version:

sudo npm -g install [homebridge | name-of-plugin]

**Comment by freddo99** [comment]
Thank you,

I have started from the start and reloaded everything. I tried 'npm -g outdated' and I'm getting:-
Package  Current  Wanted  Latest  Location
npm      3.10.10   5.4.2   5.4.2

How do I update NPM to 5.4.2 ?

**Comment by freddo99** [comment]
I have reloaded everything and it works.....until I add the config.json file.
When I use my previous config.json file, I get errors 👎 

Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 21390b92-226c-4da5-a8f1-e61f0e4c1f3b
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at functions.getVeraInfo.then (/usr/lib/node_modules/homebridge-vera/index.js:33:15)
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Any Ideas ?

**Comment by snakedog116** [comment]
Thanks @sommo I tried to follow your instructions and it asked me to update three items: homebridge, node-gyp, hap-nodejs

I tried to update them, but now I get the following error when running homebridge. What did I do wrong, and how do I fix it now?

pi@raspberrypi:~ $ homebridge
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by snakedog116** [comment]
I changed the username, and completed removed and reinstalled homebridge. It wasn't letting me completely reinstall it so I had to run:
sudo npm install -g --unsafe-perm homebridge

It's working now although I had to go to the apple home kit app and delete the bridge and re-import it.

**Comment by sommo** [comment]
after few days, homebridge crash and stop working also if it was updated (see bottom post).
so i followed these steps:
-deleted persistant and accessories folders
-reset homekit by removing home (IOS)
-started homebridge again
-create new home in homekit app (IOS)

after that all is back online. but i have an old ipad as hub (running ios10), and my others iphone running ios11. i'm going to update to a newer ipad to avoid incompatibilities.

i think also homebridge needs few update to get better compatibilities with new homekit.

**Comment by marcotini** [comment]
@sommo yes I think so too, because every single items are unsupported with HomeKit  and result as not certified.

**Comment by theo-69** [comment]
after initial restart my homebridge working great on iPhone, iPad & TV4

**Comment by sommo** [comment]
All devices are running ios11?

Inviato da iPhone

**Comment by theo-69** [comment]
@sommo Yes

**Comment by snakedog116** [comment]
After reinstalling homebridge all of my devices have been working now for a few days without glitch.

**Comment by lrucker1** [comment]
I'm not sure how much homebridge is to blame - I was using iOS 11 beta on an iPod, but didn't have any problems until recently - some time after either the tvOS upgrade, or the Hue hub. And now even with homebridge off and removed from the home I'm still seeing a lot of "unreachable" devices.

**Comment by snakedog116** [comment]
Mine is still working. Have you tried to completely re-install Homebridge?

**Comment by lrucker1** [comment]
I want to get it back to working without homebridge, if that's possible. If not, it's a bug Apple can't brush aside :)

**Comment by snakedog116** [comment]
I don't follow.

Are you saying that things are unreachable in the SmartThings app? or the HomeKit app?

**Comment by joshlawless** [comment]
I've got Homebridge running in a Docker (v4.0) on my Synology.

I've deleted the persist and accessories folder

I've deleted my whole "home" in the Home app

I've changed both the "name" and "username" in my config.json

I can see the updated name of the Homebridge accessory when I go to "add accessory" on my iPhone (though curiously not on my iPad).

If I try to add it, and manually enter the correct (and default) code of 031-45-154, I see a "Pairing HomeBridge" message and then an error "Couldn't add HomeBridge Home couldn't connect to this accessory"

:-(

**Comment by lrucker1** [comment]
They're unreachable in HomeKit - and it's only the bridged things that fail: Hue, Ecobee, a power strip, and of course Homebridge. I've disconnected them in various combinations and nothing helps. The standalone devices are working fine. 

I'm going to roll back the tvOS as soon as I get the right USB cable for it.

**Comment by snakedog116** [comment]
@lrucker1, you said you want to get it working 'without homebridge' and now you are saying that it's now working in Homekit? Are you trying to make homekit work without homebridge? That's not possible. Smartthings doesn't have homekit support and is why you need homebridge.

My experience was that I had to delete homebridge from my raspberry pi, update to the newest homebridge build and restart homebridge. I then re-attached the homebridge 'Bridge' and it's been working perfectly ever since.

Rolling back tvOS won't fix the problem because eventually you'll want to update tvOS. (I had my original homebridge install die without updating tvOS as I only had an appletv3 at the time.)

**Comment by lrucker1** [comment]
I wasn't using homebridge for Smartthings, I was using it for other devices. By "it" I mean Homekit in general - everything that's on a bridge, whether officially sanctioned or not, is "unreachable". There seems to be an Apple bug separate from whether homebridge is running or not, so if anyone else updates homebridge and still has problems, it may be whatever I'm seeing instead of a homebridge problem.

Of course rolling back tvOS won't fix the problem. That's for Apple to do. If rolling back solves my problems, I'll report it and wait to upgrade until they do. There's nothing in tvOS 11 that I can't live without.

**Comment by snakedog116** [comment]
Ok, so to be clear, your setup is that you have homekit with Hue Bridge linked the normal way (not using this Homebridge GitHub code).

So with Homekit and the Hue bridge you are finding issues with the Hue Bridge and the devices attached to Homekit through that bridge?

**Comment by lrucker1** [comment]
So, to follow up: the culprit was an old Tivo that got switched from Ethernet to 2.4 Wifi and was interfering like crazy. And of course it was doing so randomly, which is why I suspected everything from homebridge (the first thing affected) to tvOS 11.

**Comment by salihzett** [comment]
same problem, with ios11.1
i have deleted the persist and accessories folder, restart it, change the username, pin, 
but nothing works.
it is not possible to connect with homebridge (on rpi 3),

any ideas or solutions?
