### ISSUE TITLE
Homebridge suddenly stopped working

### ISSUE THREAD

**Issue by garykinetic** [nfarina/homebridge#1498]
[9/17/2017, 9:18:25 PM] Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-ssh/node_modules/ssh-exec/node_modules/duplexify/index.js:161
  while ((data = this._readable2.read(state.buffer.length ? state.buffer[0].length : state.length)) !== null) {
                                                                           ^

TypeError: Cannot read property 'length' of undefined
    at Duplexify._forward (/usr/local/lib/node_modules/homebridge-ssh/node_modules/ssh-exec/node_modules/duplexify/index.js:161:76)
    at Channel.onreadable (/usr/local/lib/node_modules/homebridge-ssh/node_modules/ssh-exec/node_modules/duplexify/index.js:126:10)
    at emitNone (events.js:86:13)
    at Channel.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (/usr/local/lib/node_modules/homebridge-ssh/node_modules/ssh-exec/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:96:13)

Any ideas how to fix?

**Comment by maragelis** [comment]
homebridge-ssh plugin caused the fault try adding the issue there https://github.com/zb0th/homebridge-ssh
