### ISSUE TITLE
Homebridge doesn't works...

### ISSUE THREAD

**Issue by MarcAlonso** [nfarina/homebridge#1513]
Can you help me with this error, please?
I happens when start homebridge in my Raspberry Pi...

Thanks!

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1315:14)
    at listenInCluster (net.js:1363:12)
    at Server.listen (net.js:1463:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by EdwinJS** [comment]
This is telling you that the port :51826 is already in use - simply, you have more than one instance of home bridge trying to run... check for any other instances and stop them before starting another.

**Comment by AndreiFAD** [comment]
if homebridge run in the background, then try this : 
$ sudo killall homebridge

**Comment by MarcAlonso** [comment]
Thanks!!

**Comment by noworrieseh** [comment]
May be a problem with using the port of 51826.  With no config.json used where a random port is used, no problem.  Verified that port 51826 was not being used prior to each test.  When I changed the port to something else like 51824, verified it wasn't being used either, and it starts up without the error.
