### ISSUE TITLE
Getting kicked out of Homebridge but not sure why

### ISSUE THREAD

**Issue by RAGR1** [nfarina/homebridge#1540]
I've been getting kicked out of homebridge every day or so and I can't see why? I'm only running an Elk M1 alarm and 2 Nest thermostats. Each time I'm kicked out, I just restart homebridge in Terminal and it runs for another day or two. Here are my last 2 errors received: 

===========1st error (most common)====================
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (ECONNRESET)
    at Elk.emit (events.js:163:17)
    at Socket.connection.on (/usr/local/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:45:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

===========2nd error===============================
<html>redirect to <a href="https://czfe86-front01-iad01.transport.home.nest.com/v2/subscribe">https://czfe86-front01-iad01.transport.home.nest.com/v2/subscribe</html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:167:40)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by NorthernMan54** [comment]
Looking at the error dump, this is an issue with the homebridge-elkm1 plugin..  Please raise the issue against the plugin and not homebridge.

Tks
