### ISSUE TITLE
EADDRINUSE Error

### ISSUE THREAD

**Issue by TimTijssens** [nfarina/homebridge#1542]
Hi All, im getting the following error when restarting homebridge: 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)

Does anyone know what is wrong?  I already reinstalled homebridge but that doesnt seem to do the trick.

**Comment by AndreiFAD** [comment]
https://github.com/nfarina/homebridge/issues/1513

**Comment by AppleTechy** [comment]
Please check the wiki next time as well. https://github.com/nfarina/homebridge/wiki/Basic-Trouble-Shooting

**Comment by megavoltt** [comment]
> #1513
> 
> сообщение: порт: 51826 уже используется
> 
> перед перезапуском homebridge попробуйте следующее :
> $ sudo killall homebridge

I did as you instructed. the same error

**Comment by megavoltt** [comment]
found more bugs. By the way checked the status on Homebridge Vera with the old firmware ,there are the same errors,but everything works.
![2019-08-20_01-33-44](https://user-images.githubusercontent.com/44338399/63304196-e7497e80-c2ea-11e9-891e-bdeb49e6a5e9.png)
