### ISSUE TITLE
Launch Agent

### ISSUE THREAD

**Issue by daniel2029** [nfarina/homebridge#1551]
I setup my com.homebridge.server.plist file corresponding to the sample provides and changed the log file location. Except now the server won't start and i am getting the error at the bottom  in my log file, it just repeats every few seconds.

Could someone please help me understand what is going on and how i can fix it. I have searched online and nothing. Please someone help me.

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1218:7)
    at Function.User.storagePath (/usr/local/lib/node_modules/homebridge/lib/user.js:30:15)
    at Function.User.persistPath (/usr/local/lib/node_modules/homebridge/lib/user.js:38:25)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:24:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

Thanks :)

**Comment by plasticrake** [comment]
The line that has the error is looking up your home folder.

```js
var home = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
```

Do you have the plist in your home folder `~/Library/` or system `/Library/`?

**Comment by daniel2029** [comment]
ahhhhh. Yes that fixed it. Moving the plist file into my user home folder library

Thanks!
