### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kskenyon** [nfarina/homebridge#1558]
I have removed and reinstalled homebridge several times and I still get this error.  Code error?

Oct 16 09:37:53 pi3 homebridge[3306]: fs.js:733
Oct 16 09:37:53 pi3 homebridge[3306]:   var r = binding.read(fd, buffer, offset, length, position);
Oct 16 09:37:53 pi3 homebridge[3306]:                   ^
Oct 16 09:37:53 pi3 homebridge[3306]: Error: EISDIR: illegal operation on a directory, read
Oct 16 09:37:53 pi3 homebridge[3306]:     at Error (native)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.fs.readSync (fs.js:733:19)
Oct 16 09:37:53 pi3 homebridge[3306]:     at tryReadSync (fs.js:488:20)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.fs.readFileSync (fs.js:536:19)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.parseDirSync (/home/pi/.npm-packages/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.parseDataDirSync (/home/pi/.npm-packages/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.initSync (/home/pi/.npm-packages/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.nodePersist.initSync (/home/pi/.npm-packages/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
Oct 16 09:37:53 pi3 homebridge[3306]:     at Object.init (/home/pi/.npm-packages/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:29:13)
Oct 16 09:37:53 pi3 homebridge[3306]:     at module.exports (/home/pi/.npm-packages/lib/node_modules/homebridge/lib/cli.js:24:7)

**Comment by kskenyon** [comment]
Tried everything then deleted .homebridge persist folder and restarted homebridge and that seems to have done the trick.
