### ISSUE TITLE
Bindings file not found suddenly on Windows

### ISSUE THREAD

**Issue by gee4vee** [nfarina/homebridge#1593]
Things were working perfectly for weeks, then suddenly the Homebridge device wasn't responding in the Home app. I then tried to start Homebridge via Git-CMD to see what the problem is, and I get this error. Like I said, nothing has changed. I had follows the steps for setting up on Windows and it was working flawlessly.

C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\Debug\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\Release\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\out\Debug\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\Debug\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\out\Release\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\Release\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\default\ed25519.node
 → C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\compiled\6.11.3\win32\ia32\ed25519.node
    at bindings (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\index.js:1:99)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:8:15)

**Comment by gee4vee** [comment]
So I reinstalled homebridge and homebridge-http, deleted persist and accessories, and I can start Homebridge. I had to remove and add in Home app to get it to work again. However, I see this when Homebridge starts up via Git-CMD. What do these errors mean and how do I fix them?

```
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[11/1/2017, 1:43:07 PM] [Nest] TypeError: (buffer.readUInt32BE(...) + (buffer.readUInt32BE(...) * Math.pow(...))).toString(...).toUpperCase(...).padStart is not a function
    at Bridge.Accessory.setupURI (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:384:121)
    at Server._printSetupInfo (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:600:32)
    at Server._publish (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:128:8)
    at Server.<anonymous> (C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:381:14)
    at C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:16:19
    at C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge-nest\index.js:155:6
[11/1/2017, 1:43:07 PM] Homebridge is running on port 51826.
(node:20096) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: This callback function has already been called by someone else; it can only be called one time.
```

**Comment by gee4vee** [comment]
After updating everything this has gone away.
