### ISSUE TITLE
Problems with getting homebridge to work.

### ISSUE THREAD

**Issue by fjh40** [nfarina/homebridge#1598]
Hello Github user, 
I've tried to install homebridge on Ubuntu to remote control my Milight lights with Apple homekit, but can't seem to get it to work. Can anyone enlighten me on what the issue is? Btw i'm completely new to coding etc so i might need the noob explanation.

Error i get when booting up homegbridge in terminal (Ubuntu)

felix@Felix-Ubuntu-PC:~$ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/4/2017, 5:15:56 PM] Loaded plugin: homebridge-milight
[11/4/2017, 5:15:56 PM] Registering platform 'homebridge-milight.MiLight'
[11/4/2017, 5:15:56 PM] ---
[11/4/2017, 5:15:56 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/4/2017, 5:15:56 PM] ---
[11/4/2017, 5:15:56 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:293:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

My config.json file:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51827,
		"pin": "031-45-154"
	},

	"description": "file config",

	"platforms": [{
		"name": "MiLight",
		"bridges": [{
			"ip_address": "192.168.1.5",
			"port": "8899",
			"version": "v6",
			"lights": {
				"fullColor": ["Bedroom", null, null, null]
			},
			"repeat": 1,
			"delay": 50
		}]
	}]
}

**Comment by iCarl** [comment]
Close this
