### ISSUE TITLE
openSUSE Tumbleweed and Homebridge install...

### ISSUE THREAD

**Issue by issic** [nfarina/homebridge#1602]
Trying to install Homebridge on openSUSE and still getting stuck on this error of mdns, even Avahi is up and running...

### Versions
- **Node**:       v8.8.1
- **OS**:         openSUSE Tumbleweed VERSION="20171102"
- mDNS :       avahi-compat-mDNSResponder-devel-0.6.32-4.1.x86_64 or libdns_sd-0.6.32-4.1.x86_64

### Homebridge Log / Command Output

```
sudo npm install -g --unsafe-perm homebridge

/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

sh: /usr/lib64/node_modules/npm8/bin/node-gyp-bin/node-gyp: Permission denied

861 silly install mdns@2.3.3
862 info lifecycle mdns@2.3.3~install: mdns@2.3.3
863 verbose lifecycle mdns@2.3.3~install: unsafe-perm in lifecycle true
864 verbose lifecycle mdns@2.3.3~install: PATH: /usr/lib64/node_modules/npm8/bin/node-gyp-bin:/usr/local/lib/node_modules/homebridge/node_modules/mdns/node_modules/.bin:/usr/local/lib/node_modules/homebridge/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/sbin:/usr/bin:/sbin:/bin
865 verbose lifecycle mdns@2.3.3~install: CWD: /usr/local/lib/node_modules/homebridge/node_modules/mdns
866 silly lifecycle mdns@2.3.3~install: Args: [ '-c', 'node-gyp rebuild' ]
867 silly lifecycle mdns@2.3.3~install: Returned: code: 126  signal: null
868 info lifecycle mdns@2.3.3~install: Failed to exec install script
869 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
870 verbose stack Error: mdns@2.3.3 install: `node-gyp rebuild`
870 verbose stack Exit status 126
870 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/index.js:280:16)
870 verbose stack     at emitTwo (events.js:125:13)
870 verbose stack     at EventEmitter.emit (events.js:213:7)
870 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/lib/spawn.js:55:14)
870 verbose stack     at emitTwo (events.js:125:13)
870 verbose stack     at ChildProcess.emit (events.js:213:7)
870 verbose stack     at maybeClose (internal/child_process.js:927:16)
870 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
871 verbose pkgid mdns@2.3.3
872 verbose cwd /usr/local/lib
873 verbose Linux 4.13.10-1-default
874 verbose argv "/usr/bin/node8" "/usr/bin/npm-default" "install" "-g" "--unsafe-perm" "homebridge"
875 verbose node v8.8.1
876 verbose npm  v5.4.2
877 error code ELIFECYCLE
878 error errno 126
879 error mdns@2.3.3 install: `node-gyp rebuild`
879 error Exit status 126
880 error Failed at the mdns@2.3.3 install script.
```

**Comment by NorthernMan54** [comment]
Looking at this, the line 

sh: /usr/lib64/node_modules/npm8/bin/node-gyp-bin/node-gyp: Permission denied
Points out the issue with the install
Try this before installing
sudo su -

**Comment by issic** [comment]
Hey thanks for trying help. The install command IS 

> sudo npm install -g --unsafe-perm homebridge

**Comment by NorthernMan54** [comment]
Yes that is correct
