### ISSUE TITLE
Issue with startup

### ISSUE THREAD

**Issue by funbags** [nfarina/homebridge#161]
I'm int the process of setting up homebridge for the first time and am getting the following error message which I'm hoping someone can help me with.

Loading 1 platforms...
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.
Loading 3 accessories...
module.js:338
    throw err;
          ^
Error: Cannot find module './lib/helpers'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/richardw/homebridge/node_modules/wemo/node_modules/request/index.js:19:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by nzhome** [comment]
check that this file exists

/home/richardw/homebridge/node_modules/wemo/node_modules/request/lib/helpers.js

because it is referenced in wemo here
inside: wemo\node_modules\request\index.js
var extend                = require('extend')
  , cookies               = require('./lib/cookies')
  , helpers               = require('./lib/helpers')

**Comment by funbags** [comment]
I'm only seeing:
auth.js  cookies.js  getProxyFromURI.js

**Comment by funbags** [comment]
Does anyone know how I can force it to install the helpers module?

**Comment by snowdd1** [comment]
try a
`rm -R /home/richardw/homebridge/node_modules/`
to wipe the dependencies and then
`cd /home/richardw/homebridge`
`npm update`
to reinstall and build all dependencies again.
You're on linux I guess?

**Comment by funbags** [comment]
@snowdd1 & @nzhome Thanks for the help, that worked a treat
