### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by samsonrosen** [nfarina/homebridge#1611]
Hi,

Whenever I check status of the lock or open the home app. Homebridge crashes.

Last login: Tue Nov  7 22:28:04 on ttys000
Church-Server:~ churchserver$ sudo homebridge
Password:
[07/11/2017, 22:44:42] Loaded plugin: homebridge-amazondash
[07/11/2017, 22:44:42] Registering platform 'homebridge-amazondash.AmazonDash'
[07/11/2017, 22:44:42] ---
[07/11/2017, 22:44:42] Loaded plugin: homebridge-broadlink-rm
[07/11/2017, 22:44:42] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[07/11/2017, 22:44:42] ---
[07/11/2017, 22:44:42] Loaded plugin: homebridge-cmdswitch2
[07/11/2017, 22:44:42] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[07/11/2017, 22:44:42] ---
[07/11/2017, 22:44:42] Loaded plugin: homebridge-dash
[07/11/2017, 22:44:42] Registering accessory 'homebridge-dash.Dash'
[07/11/2017, 22:44:42] ---
[07/11/2017, 22:44:42] Loaded plugin: homebridge-milight
[07/11/2017, 22:44:42] Registering platform 'homebridge-milight.MiLight'
[07/11/2017, 22:44:42] ---
[07/11/2017, 22:44:43] Loaded plugin: homebridge-people
[07/11/2017, 22:44:43] Registering platform 'homebridge-people.People'
[07/11/2017, 22:44:43] Registering accessory 'homebridge-people.PeopleAccessory'
[07/11/2017, 22:44:43] Registering accessory 'homebridge-people.PeopleAllAccessory'
[07/11/2017, 22:44:43] ---
[07/11/2017, 22:44:43] Loaded plugin: homebridge-platform-wemo
[07/11/2017, 22:44:43] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[07/11/2017, 22:44:43] ---
[07/11/2017, 22:44:43] Loaded plugin: homebridge-qsesame
[07/11/2017, 22:44:43] Registering accessory 'homebridge-qsesame.QSesame'
[07/11/2017, 22:44:43] ---
[07/11/2017, 22:44:43] Loaded plugin: homebridge-statefuldummy
[07/11/2017, 22:44:43] Registering accessory 'homebridge-statefuldummy.StatefulDummySwitch'
[07/11/2017, 22:44:43] ---
[07/11/2017, 22:44:43] Loaded config.json with 1 accessories and 3 platforms.
[07/11/2017, 22:44:43] ---
[07/11/2017, 22:44:43] Loading 3 platforms...
[07/11/2017, 22:44:43] Initializing People platform...
[07/11/2017, 22:44:43] Initializing platform accessory 'Sam'...
[07/11/2017, 22:44:43] Initializing platform accessory 'Stuart'...
[07/11/2017, 22:44:43] Initializing platform accessory 'Rachael'...
[07/11/2017, 22:44:43] Initializing platform accessory 'Anyone'...
[07/11/2017, 22:44:43] Initializing platform accessory 'No One'...
[07/11/2017, 22:44:43] WebHook: Started server on port '51828'.
[07/11/2017, 22:44:43] Initializing cmdSwitch2 platform...
[07/11/2017, 22:44:43] [WeMo Platform] Initializing BelkinWeMo platform...
[07/11/2017, 22:44:43] Loading 1 accessories...
[07/11/2017, 22:44:43] [201FGW] Initializing QSesame accessory...
[07/11/2017, 22:44:43] [201FGW] Attempting to login to CANDY HOUSE...
Load homebridge-amazondash.AmazonDash
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[07/11/2017, 22:44:43] Initializing platform accessory 'Kettle'...
[07/11/2017, 22:44:43] Homebridge is running on port 51826.
[07/11/2017, 22:44:43] [WeMo Platform] Online: WeMo Switch [08863BC94214]
[07/11/2017, 22:44:44] [201FGW] Logged in as sam.b.rosen@gmail.com...
[07/11/2017, 22:44:44] [201FGW] Getting the list of Sesames from API...
[07/11/2017, 22:44:45] [201FGW] Got a Sesames JSON from CANDY HOUSE!
[07/11/2017, 22:44:45] [201FGW] Found '201FGW' with device_id F8EC3892C307...
[07/11/2017, 22:44:45] [201FGW] That's the one! Set the lockID...
[07/11/2017, 22:44:45] [201FGW] QSesame is ready to LOCK your world...
[07/11/2017, 22:44:56] Kettle is off.
/usr/local/lib/node_modules/homebridge-qsesame/index.js:138
  	self.log("Getting current state..."); 
  	     ^

TypeError: self.log is not a function
    at QSesame.getState (/usr/local/lib/node_modules/homebridge-qsesame/index.js:138:9)
    at emitThree (events.js:116:13)
    at Characteristic.LockCurrentState.emit (events.js:197:7)
    at Characteristic.LockCurrentState.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:706:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:670:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:204:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:1002:14)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:220:47)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Church-Server:~ churchserver$

**Comment by NorthernMan54** [comment]
This is a issue with the homebridge-qsesame plugin.  Please raise an issue against the plugin.
