### ISSUE TITLE
Help launching Homebridge

### ISSUE THREAD

**Issue by spartanrob** [nfarina/homebridge#1637]
I have completely rebuilt my Pi and reinstalled homebridge.  Getting the following error, any help is greatly appreciated:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/27/2017, 9:32:58 PM] No plugins found. See the README for information on installing plugins.
[11/27/2017, 9:32:58 PM] There was a problem reading your config.json file.
[11/27/2017, 9:32:58 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[11/27/2017, 9:32:58 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token }
    at Object.parse (native)
    at Server.str.replace.Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

I have confirmed that my config.json file is correct:
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "pin": "031-45-154"
        },

        "platforms": [{
                "platform": "Wink",
                "name": "Wink",
                "client_id": "H1g--Ct8MlPEtZtrCmxPlIDdGnS1PTdf",
                "client_secret": "seFIpe7A_ECFHA6SSGMa4V9ZQ91X3VWH",
                "username": "spartanrob@gmail.com",
                "password"
        }]
}

**Comment by aswathraja** [comment]
Have you installed mdns and does it work with blank config.json?

**Comment by spartanrob** [comment]
Thanks.  I have.  It does work with a blank config.json.
I got updated credentials from wink, but now I have a new error

/usr/local/lib/node_modules/homebridge/lib/api.js:138
    throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");
          ^
Error: Attempting to register a platform 'homebridge-wink.Wink' which has already been registered!
    at API.registerPlatform (/usr/local/lib/node_modules/homebridge/lib/api.js:138:11)
    at Plugin.module.exports [as initializer] (/usr/lib/node_modules/homebridge-wink/index.js:18:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:160:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:138:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
