### ISSUE TITLE
Homebridge throws error at first run

### ISSUE THREAD

**Issue by grosch** [nfarina/homebridge#1638]
# Expected Behavior

### Steps to Reproduce (for bugs)
`% sudo npm install -g --unsafe-perm homebridge
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
 + homebridge@0.4.33

updated 1 package in 35.463s
% homebridge
module.js:538
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
`
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version` v8.9.1
- **OS**:         macOS High Sierra

**Comment by grosch** [comment]
Installing mdns fixed this.
