### ISSUE TITLE
Still can't run homebridge running on FreeBSD 11.1

### ISSUE THREAD

**Issue by megapearl** [nfarina/homebridge#1640]
I'm running in some problems compiling on FreeBSD.
```
root@fileserver:/usr/local/share/homebridge # npm install

> mdns@2.3.4 install /usr/local/share/homebridge/node_modules/mdns
> node-gyp rebuild

gmake: Entering directory '/usr/local/share/homebridge/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: 'dns_sd.h' file not found
#include <dns_sd.h>
         ^~~~~~~~~~
1 error generated.
gmake: *** [dns_sd_bindings.target.mk:156: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gmake: Leaving directory '/usr/local/share/homebridge/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System FreeBSD 11.1-RELEASE-p4
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/share/homebridge/node_modules/mdns
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-28T11_42_42_023Z-debug.log
```
```
root@fileserver:/usr/local/share/homebridge # node --version
v8.9.1
```
```
root@fileserver:/usr/local/share/homebridge # npm --version
5.4.2
```
```
root@fileserver:/usr/local/share/homebridge # pkg info|grep libdns
avahi-libdns-0.6.31_2          mDNSResponder compatibility from Avahi
```
```
root@fileserver:/usr/local/share/homebridge # locate dns_sd.h
/usr/local/include/avahi-compat-libdns_sd/dns_sd.h
/usr/ports/net/avahi-libdns/work/avahi-0.6.31/avahi-compat-libdns_sd/dns_sd.h
/usr/ports/net/avahi-libdns/work/stage/usr/local/include/avahi-compat-libdns_sd/dns_sd.h
root@fileserver:/usr/local/share/homebridge #
```
How to debug?

Best Regards,
Donald.

**Comment by Valdhor** [comment]
The instructions tell you to install node which is currently at version 9 and Homebridge does not appear to work with this version.

instead of the step 5 pkg install try this:

`pkg install -y node4 www/npm-node4 dbus avahi-libdns gcc`

**Comment by megapearl** [comment]
I had to create a symlink from /usr/include to /usr/local/include/avahi-compat-libdns_sd to get it to build:

root@fileserver:/usr/include # ls -l dns_sd.h
lrwxr-xr-x  1 root  wheel  50 Nov 28 20:20 dns_sd.h -> /usr/local/include/avahi-compat-libdns_sd/dns_sd.h
root@fileserver:/usr/include #

Issue solved.
