### ISSUE TITLE
Wrong node version

### ISSUE THREAD

**Issue by grosch** [nfarina/homebridge#1678]
I get this error as soon as I try to run homebridge.  I tried to reinstall both dns and homebridge using "npm install -g" but that didn't make a difference:

/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

**Comment by ebaauw** [comment]
In my experience, you need to `npm -g uninstall homebridge` explicitly before re-installing it, to force re-compilation of the mdns module.  This is needed every time you change NodeJS to a different major version.

**Comment by gwyner** [comment]
node -v
v8.4.0
npm -v
5.3.0

I'm getting the same error message:

> `Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using`
`NODE_MODULE_VERSION 48. This version of Node.js requires`
`NODE_MODULE_VERSION 57. Please try re-compiling or re-installing`
`the module (for instance, using `npm rebuild` or `npm install`).`
 `   at Object.Module._extensions..node (module.js:602:18)`
`    at Module.load (module.js:507:32)`
`    at tryModuleLoad (module.js:470:12)`
`    at Function.Module._load (module.js:462:3)`
`    at Module.require (module.js:517:17)`
`    at require (internal/module.js:11:18)`
`    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)`
`    at Module._compile (module.js:573:30)`
`    at Object.Module._extensions..js (module.js:584:10)`
`    at Module.load (module.js:507:32)`
`

I've tried `npm -g uninstall homebridge ` and tried deleting homebridge from node_modules and I've done
`sudo npm install --unsafe-perm mdns`
`sudo npm rebuild --unsafe-perm`

I've also tried downgrading to node v7.9.0, but that just changes the error message slightly to "This version of Node.js requires NODE_MODULE_VERSION 51."

Any ideas what else I can try?

**Comment by grosch** [comment]
`rm -rf /usr/local/lib/node_modules/homebridge/node_modules/mdns`
`rm -rf /usr/local/lib/node_modules/homebridge/node_modules/homebridge`

That's what I had to do, and then reinstall homebridge.

**Comment by gwyner** [comment]
@grosch - Same error - `Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48.`

**Comment by JustAnotherPU** [comment]
same issue here any help ?

**Comment by mreassassin** [comment]
I'm getting 'cannot remove ... permission denied' when trying to execute:
rm -rf /usr/local/lib/node_modules/homebridge/node_modules/mdns

any ideas?

how do I scrap the whole thing and start over??

**Comment by grosch** [comment]
@mreassassin Prefix your command with sudo:  `sudo rm -rf /usr/local/......`

**Comment by mreassassin** [comment]
@grosch thanks!  now I'm getting this after launching homebridge.  it auto-disconnects homebridge

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at Server.listen (net.js:1378:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_mod        ules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap        -nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_mod        ules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126        :16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)



any ideas here?

**Comment by grosch** [comment]
EADDRINUSE means that homebridge is trying to run on a port that something else is already running on.  I can't help you with that configuration.  Suggest you open a new issue specifically on this so the owners see it.  They can help you with configuration to run on a non-standard port.
