### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by htyx75** [nfarina/homebridge#1695]
Heya,
since today i get the following error when i try to start homebridge, and i have no idea what went wrong.
Could you please help me out, how to fix that?

[2018-1-8 20:30:59] Homebridge is running on port 51826.
[2018-1-8 20:31:00] [Hs100] New Device Online: [Wohnzimmer ] plug [8006230351B3569C197B27A91EC52663170FEB60] 192.168.1.215 9999
[2018-1-8 20:31:00] [Hs100] Adding: [Wohnzimmer ] plug [8006230351B3569C197B27A91EC52663170FEB60]
[2018-1-8 20:31:00] [Hs100] New Device Online: [PC] plug [8006BE4344D89941D949A1ACF8F9EEA6171E2F1F] 192.168.1.214 9999
[2018-1-8 20:31:00] [Hs100] Adding: [PC] plug [8006BE4344D89941D949A1ACF8F9EEA6171E2F1F]
/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:258
throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 96734f20-3ef1-427a-9657-be6d55764561
at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:258:13)
at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:284:10)
at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:451:16)
at Server. (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
at emitOne (events.js:116:13)
at API.emit (events.js:211:7)
at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
at Hs100Platform.registerPlatformAccessory (/usr/lib/node_modules/homebridge-hs100/lib/platform.js:79:14)
at new PlugAccessory (/usr/lib/node_modules/homebridge-hs100/lib/plug.js:57:16)
at Hs100Platform.addAccessory (/usr/lib/node_modules/homebridge-hs100/lib/platform.js:113:27)
pi@raspberrypi:~/.homebridge $

**Comment by vtcajones** [comment]
try deleting this file 
~/.homebridge/accessories/cachedAccessories.

**Comment by htyx75** [comment]
You´re my hero. That totally didi it. I really appreciate your help with this.

**Comment by devth** [comment]
This didn't fix it for me. :/

**Comment by lucadistefano** [comment]
deleting the file not fixes the problem
