### ISSUE TITLE
JSON Config Issue With Multiple Accessories 

### ISSUE THREAD

**Issue by njdavis90** [nfarina/homebridge#1701]
Installed the plugin for home bridge - relay, tried to add more than one accessories and keep coming up with json errors. Get similar errors when attempting a similar thing on home bridge-http. I have tried copying and pasting the syntax into JSONLint can get the syntax to work but still can get home bridge to run. Any suggestions on the below would be greatly appreciated, suspect the problem is due to the lack of understanding I have for JSON but can't see where I am going wrong. I'm editing all this in nano.

### Versions

- **Homebridge**: `0.4.33` 

- **OS**:       `Rasp Pi Stretch`

### Configuration

```json
{
        "bridge": {
                "name": "Homebridge",
                "username": "CD:xx::3D:E3:Xx:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "accessories": [
                {
                        "accessory": "relay",
                        "name": "K1",
                        "pin": 37
                },
                {
                        "accessory": "relay",
                        "name": "K2",
                        "pin" : 29
        ]
```

### Homebridge Log / Command Output

```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[13/01/2018, 04:24:14] Loaded plugin: homebridge-gpio-relay
[13/01/2018, 04:24:14] Registering accessory 'homebridge-gpio-relay.relay'
[13/01/2018, 04:24:14] ---
[13/01/2018, 04:24:15] Loaded plugin: homebridge-http
[13/01/2018, 04:24:15] Registering accessory 'homebridge-http.Http'
[13/01/2018, 04:24:15] ---
[13/01/2018, 04:24:15] There was a problem reading your config.json file.
[13/01/2018, 04:24:15] Please try pasting your config.json file here to validate it: http://jsonlint.com
[13/01/2018, 04:24:15] 
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token ]
    at Object.parse (native)
    at Server.str.replace.Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by njdavis90** [comment]
Ended up sorting this out myself. There was a missing bracket in the above config but the main issue I think I was having on previous attempts was that I had loaded two plugins http and relay but was not allowing for both plugins when trying to use more than one accessory. In short my guess is if you have loaded a plugin homebridge expects a listing for it in the config file otherwise it throughs a json error (which would make sense).
