### ISSUE TITLE
Issue at launch : TypeError: plugin.initializer is not a function

### ISSUE THREAD

**Issue by xMadelain** [nfarina/homebridge#1752]
Hi,
My config :
 Raspberry Pi 3 Linux X_Pi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
 Node v7.10.1 - I also try with node V8, V4...
I follow your Rasp Pi installation guide
nmp install && npm upgrade done

All is ok (home bridge can launch) when non plugin installed
It's ok with homebridge-info plug-in with a valid .json 

It's ko (see below) when with homebridge-garage-gate-opener
config.json : valid - use this on https://github.com/MForge/homebridge-garage-gate-opener/blob/master/exemple/config.json

Thanks for your support
-----
pi@raspberrypi:/etc/init.d $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of v7.10.1
.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2018-2-21 23:12:27] Loaded plugin: homebridge-rasppi-garagegateopener
/usr/lib/node_modules/homebridge/lib/server.js:160
      _plugin.initializer(this._api);
             ^

TypeError: plugin.initializer is not a function_
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:160:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:138:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
Xavier

**Comment by xMadelain** [comment]
Hi,
homebridge-rasppi-garagegateopener not available any more....
Regards,
Xavier
