### ISSUE TITLE
Can't rebuild

### ISSUE THREAD

**Issue by xMadelain** [nfarina/homebridge#1764]
Made a update in Hap Accesory.js and want to rebuild
Can't rebuild hb
Please help

Linux X_Pi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

sudo npm build homebridge

cat /root/.npm/_logs/2018-03-10T07_34_41_908Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'build', 'homebridge' ]
2 info using npm@5.7.1
3 info using node@v8.10.0
4 info build /usr/lib/node_modules/homebridge
5 info lifecycle homebridge@0.4.38~preinstall: homebridge@0.4.38
6 info linkStuff homebridge@0.4.38
7 silly linkStuff homebridge@0.4.38 has /usr/lib/node_modules as its parent node_modules
8 verbose linkBins homebridge@0.4.38
9 verbose linkBins [ { homebridge: 'bin/homebridge' },
9 verbose linkBins   '/usr/lib/node_modules/.bin',
9 verbose linkBins   false ]
10 verbose linkMans homebridge@0.4.38
11 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/homebridge/bin/homebridge
12 verbose rebuildBundles [ '.bin',
12 verbose rebuildBundles   'ansi-regex',
12 verbose rebuildBundles   'ansi-styles',
12 verbose rebuildBundles   'bindings',
12 verbose rebuildBundles   'buffer-shims',
12 verbose rebuildBundles   'chalk',
12 verbose rebuildBundles   'commander',
12 verbose rebuildBundles   'curve25519-n2',
12 verbose rebuildBundles   'debug',
12 verbose rebuildBundles   'decimal.js',
12 verbose rebuildBundles   'ed25519',
12 verbose rebuildBundles   'escape-string-regexp',
12 verbose rebuildBundles   'fast-srp-hap',
12 verbose rebuildBundles   'graceful-readlink',
12 verbose rebuildBundles   'hap-nodejs',
12 verbose rebuildBundles   'has-ansi',
12 verbose rebuildBundles   'ip',
12 verbose rebuildBundles   'mdns',
12 verbose rebuildBundles   'minimist',
12 verbose rebuildBundles   'mkdirp',
12 verbose rebuildBundles   'ms',
12 verbose rebuildBundles   'nan',
12 verbose rebuildBundles   'node-persist',
12 verbose rebuildBundles   'q',
12 verbose rebuildBundles   'qrcode-terminal',
12 verbose rebuildBundles   'semver',
12 verbose rebuildBundles   'strip-ansi',
12 verbose rebuildBundles   'supports-color' ]
13 verbose rebuild bundle /usr/lib/node_modules/homebridge/node_modules/ansi-regex
14 info build /usr/lib/node_modules/homebridge/node_modules/ansi-regex
15 info lifecycle ansi-regex@2.1.1~preinstall: ansi-regex@2.1.1
16 info linkStuff ansi-regex@2.1.1
17 silly linkStuff ansi-regex@2.1.1 has /usr/lib/node_modules/homebridge/node_modules as its parent node_modules
18 verbose linkBins ansi-regex@2.1.1
19 verbose linkMans ansi-regex@2.1.1
20 info lifecycle ansi-regex@2.1.1~install: ansi-regex@2.1.1
21 info lifecycle ansi-regex@2.1.1~postinstall: ansi-regex@2.1.1
22 verbose rebuild bundle /usr/lib/node_modules/homebridge/node_modules/ansi-styles
23 info build /usr/lib/node_modules/homebridge/node_modules/ansi-styles
24 info lifecycle ansi-styles@2.2.1~preinstall: ansi-styles@2.2.1
25 info linkStuff ansi-styles@2.2.1
26 silly linkStuff ansi-styles@2.2.1 has /usr/lib/node_modules/homebridge/node_modules as its parent node_modules
27 verbose linkBins ansi-styles@2.2.1
28 verbose linkMans ansi-styles@2.2.1
29 info lifecycle ansi-styles@2.2.1~install: ansi-styles@2.2.1
30 info lifecycle ansi-styles@2.2.1~postinstall: ansi-styles@2.2.1
31 verbose rebuild bundle /usr/lib/node_modules/homebridge/node_modules/bindings
32 info build /usr/lib/node_modules/homebridge/node_modules/bindings
33 info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
34 info linkStuff bindings@1.2.1
35 silly linkStuff bindings@1.2.1 has /usr/lib/node_modules/homebridge/node_modules as its parent node_modules
36 verbose linkBins bindings@1.2.1
37 verbose linkMans bindings@1.2.1
38 info lifecycle bindings@1.2.1~install: bindings@1.2.1
39 info lifecycle bindings@1.2.1~postinstall: bindings@1.2.1
40 verbose rebuild bundle /usr/lib/node_modules/homebridge/node_modules/buffer-shims
41 info build /usr/lib/node_modules/homebridge/node_modules/buffer-shims
42 info lifecycle buffer-shims@1.0.0~preinstall: buffer-shims@1.0.0
43 info linkStuff buffer-shims@1.0.0
44 silly linkStuff buffer-shims@1.0.0 has /usr/lib/node_modules/homebridge/node_modules as its parent node_modules
45 verbose linkBins buffer-shims@1.0.0
46 verbose linkMans buffer-shims@1.0.0
47 info lifecycle buffer-shims@1.0.0~install: buffer-shims@1.0.0
48 info lifecycle buffer-shims@1.0.0~postinstall: buffer-shims@1.0.0
49 verbose rebuild bundle /usr/lib/node_modules/homebridge/node_modules/curve25519-n2
50 info build /usr/lib/node_modules/homebridge/node_modules/curve25519-n2
51 info lifecycle curve25519-n2@1.1.3~preinstall: curve25519-n2@1.1.3
52 info linkStuff curve25519-n2@1.1.3
53 silly linkStuff curve25519-n2@1.1.3 has /usr/lib/node_modules/homebridge/node_modules as its parent node_modules
54 verbose linkBins curve25519-n2@1.1.3
55 verbose linkMans curve25519-n2@1.1.3
56 info lifecycle curve25519-n2@1.1.3~install: curve25519-n2@1.1.3
57 verbose lifecycle curve25519-n2@1.1.3~install: unsafe-perm in lifecycle false
58 verbose lifecycle curve25519-n2@1.1.3~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:$
59 verbose lifecycle curve25519-n2@1.1.3~install: CWD: /usr/lib/node_modules/homebridge/node_modules/curve25519-n2
60 silly lifecycle curve25519-n2@1.1.3~install: Args: [ '-c', 'node-gyp rebuild' ]
61 silly lifecycle curve25519-n2@1.1.3~install: Returned: code: 1  signal: null
62 info lifecycle curve25519-n2@1.1.3~install: Failed to exec install script
63 verbose stack Error: curve25519-n2@1.1.3 install: `node-gyp rebuild`
63 verbose stack Exit status 1
63 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
63 verbose stack     at emitTwo (events.js:126:13)
63 verbose stack     at EventEmitter.emit (events.js:214:7)
63 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
63 verbose stack     at emitTwo (events.js:126:13)
63 verbose stack     at ChildProcess.emit (events.js:214:7)
63 verbose stack     at maybeClose (internal/child_process.js:925:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
64 verbose pkgid curve25519-n2@1.1.3
65 verbose cwd /usr/lib/node_modules
66 verbose Linux 4.9.59-v7+
67 verbose argv "/usr/bin/node" "/usr/bin/npm" "build" "homebridge"
68 verbose node v8.10.0
69 verbose npm  v5.7.1
70 error code ELIFECYCLE
71 error errno 1
72 error curve25519-n2@1.1.3 install: `node-gyp rebuild`
72 error Exit status 1
73 error Failed at the curve25519-n2@1.1.3 install script.
73 error This is probably not a problem with npm. There is likely additional logging output above.
74 verbose exit [ 1, true ]

**Comment by xMadelain** [comment]
Find it
sudo npm build -g --unsafe-perm homebridge
