### ISSUE TITLE
New Issues Seen Today

### ISSUE THREAD

**Issue by Wildcat1** [nfarina/homebridge#1766]
All

I saw some errors pop up last night and didn't think much about it. Installed the latest macOS High Sierra beta today and now get further errors. Anyone else seeing this ? Only just started happening, was working fine before. The home bridge-nest & homebridge-smarthings piece I will also post over there but even though my config.json is still set correctly, home bridge now won't even load the devices pulled over from SmartThings directly that way:

3/12/2018, 12:23:51 PM] Loaded plugin: homebridge-legacy-plugins
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.AD2USB'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.Carwings'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.ELKM1'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.FileSensor'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.HomeMatic'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.Tesla'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.X10'
[3/12/2018, 12:23:51 PM] Registering accessory 'homebridge-legacy-plugins.mpdclient'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.Domoticz'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.HomeSeer'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.ISY'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.LIFx'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.SmartThings'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.TelldusLive'
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-legacy-plugins.ZWayServer'
[3/12/2018, 12:23:51 PM] ---
[3/12/2018, 12:23:51 PM] ====================
[3/12/2018, 12:23:51 PM] ERROR LOADING PLUGIN homebridge-nest:
[3/12/2018, 12:23:51 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
at Server. (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
at Array.forEach (native)
[3/12/2018, 12:23:51 PM] ====================
[3/12/2018, 12:23:51 PM] Loaded plugin: homebridge-smartthings
[3/12/2018, 12:23:51 PM] Registering platform 'homebridge-smartthings.SmartThings'
[3/12/2018, 12:23:51 PM] ---
[3/12/2018, 12:23:51 PM] Loaded config.json with 0 accessories and 2 platforms.
[3/12/2018, 12:23:51 PM] ---
[3/12/2018, 12:23:51 PM] Loading 2 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
^

Error: The requested platform 'Nest' was not registered by any plugin.
at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)

**Comment by Wildcat1** [comment]
For continued reference I did try updating to different node versions (thanks for the tip Chris @homebridge-nest) but unfortunately this did not resolve and I'm seeing different errors still when I move past 4.6 node. Included the outputs below in case anyone has any ideas:

From the looks of things it looks like 4.6 got the furthest albeit the new issues seen today. I have separated the sections by nodes.  Any additional thoughts ? Thanks

**With 4.6 running Homebridge command  I got:**

[3/12/2018, 2:42:45 PM] Loaded plugin: homebridge-legacy-plugins
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.AD2USB'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.Carwings'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.ELKM1'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.FileSensor'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.HomeMatic'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.Tesla'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.X10'
[3/12/2018, 2:42:45 PM] Registering accessory 'homebridge-legacy-plugins.mpdclient'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.Domoticz'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.HomeSeer'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.ISY'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.LIFx'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.SmartThings'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.TelldusLive'
[3/12/2018, 2:42:45 PM] Registering platform 'homebridge-legacy-plugins.ZWayServer'
[3/12/2018, 2:42:45 PM] ---
[3/12/2018, 2:42:45 PM] ====================
[3/12/2018, 2:42:45 PM] ERROR LOADING PLUGIN homebridge-nest:
[3/12/2018, 2:42:45 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
[3/12/2018, 2:42:45 PM] ====================
[3/12/2018, 2:42:46 PM] Loaded plugin: homebridge-smartthings
[3/12/2018, 2:42:46 PM] Registering platform 'homebridge-smartthings.SmartThings'
[3/12/2018, 2:42:46 PM] ---
[3/12/2018, 2:42:46 PM] Loaded config.json with 0 accessories and 2 platforms.
[3/12/2018, 2:42:46 PM] ---
[3/12/2018, 2:42:46 PM] Loading 2 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Nest' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)


**With 5.7 running Homebridge commandI got:**

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32



**With 8.1.0 I got rollbackfailoptional when installing packages and then:**

**When trying to install Homebridge Legacy Plugins:**

sudo npm install -g homebridge-legacy-plugins
npm ERR! code 1
npm ERR! Command failed: /usr/local/git/bin/git clone -q git://github.com/kevinohara80/elkington.git /Users//.npm/_cacache/tmp/git-clone-77126ea4
npm ERR! /Users/.npm/_cacache/tmp/git-clone-77126ea4/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2018-03-12T20_44_24_565Z-debug.log

**When trying to install Homebridge-nest:**

sudo npm install -g homebridge-nest
+ homebridge-nest@2.1.3
removed 18 packages, updated 1 package and moved 185 packages in 6.457s

**When trying to install Homebridge-smartthings:**

+ homebridge-smartthings@0.5.1
added 7 packages, removed 19 packages, updated 1 package and moved 82 packages in 3.885s

**Next when running Homebridge in 8.1.0 I get:**

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
