### ISSUE TITLE
New Install

### ISSUE THREAD

**Issue by Magiccowinuse** [nfarina/homebridge#1772]
I have just freshly installed Homebridge on Ubuntu. All most current, up-to-date installs. 

The problem I am having:
Without the config.json file in the .homebridge folder, homebridge starts and shows up in homekit just fine. Obviously without any plugins working. I have the one lockitron plugin installed per the walk-through and trying a chamberlain plugin for my garage. 

[3/15/2018, 8:17:52 PM] Loaded plugin: homebridge-chamberlain
[3/15/2018, 8:17:52 PM] Registering accessory 'homebridge-chamberlain.Chamberlain'
[3/15/2018, 8:17:52 PM] ---
[3/15/2018, 8:17:53 PM] Loaded plugin: homebridge-lockitron
[3/15/2018, 8:17:53 PM] Registering accessory 'homebridge-lockitron.Lockitron'
[3/15/2018, 8:17:53 PM] ---
[3/15/2018, 8:17:53 PM] Loaded config.json with 1 accessories and 0 platforms.
[3/15/2018, 8:17:53 PM] ---
[3/15/2018, 8:17:53 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'lockitron' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

This is the output I get when the config file is in the correct place. If I remove the config file and restart homebridge, homekit will start but is obviously missing the config file. Where am I going wrong here? I have the same troubles when using a modified or unmodified (sample) config.json file.

**Comment by fratinize** [comment]
I had a similar issue where I accidentally installed my plug in locally once I reinstalled globally it worked like a charm

**Comment by ebaauw** [comment]
> [3/15/2018, 8:17:53 PM] Registering accessory 'homebridge-lockitron.Lockitron'
> Error: The requested accessory 'lockitron' was not registered by any plugin.

Did you specify `"accessory": "Lockitron"` in config.json with capital `L`?  The name the plugin uses to register itself needs to match the value in config.json.
