### ISSUE TITLE
Cannot read property 'indexOf' of undefined need help

### ISSUE THREAD

**Issue by Skull09rus** [nfarina/homebridge#1776]
Hi! Please help, what I doing wrong?

iMac:~ ilyabondin$ homebridge
[2018-3-17 11:35:27] Loaded plugin: homebridge-camera-ffmpeg
[2018-3-17 11:35:27] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2018-3-17 11:35:27] ---
[2018-3-17 11:35:27] Loaded plugin: homebridge-mi-aqara-master
[2018-3-17 11:35:27] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2018-3-17 11:35:27] ---
[2018-3-17 11:35:27] Loaded plugin: homebridge-mi-gateway-security
[2018-3-17 11:35:27] Registering accessory 'homebridge-mi-gateway-security.MiGatewaySecurity'
[2018-3-17 11:35:27] ---
[2018-3-17 11:35:27] Loaded plugin: homebridge-mi-philips-light
[2018-3-17 11:35:27] ---
[2018-3-17 11:35:27] Loaded plugin: homebridge-webos3
[2018-3-17 11:35:27] Registering accessory 'homebridge-webos3.webos3'
[2018-3-17 11:35:27] ---
[2018-3-17 11:35:27] Loaded config.json with 2 accessories and 3 platforms.
[2018-3-17 11:35:27] ---
[2018-3-17 11:35:27] Loading 3 platforms...
[2018-3-17 11:35:27] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]**************************************************************
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.6.8 By YinHang
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara  
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710  
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]**************************************************************
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]start success...
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]config gateways: 7811dcb28244
[2018-3-17 11:35:27] [MiAqaraPlatform] [INFO]binding to the default interface
[2018-3-17 11:35:27] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

Config.json
{
	"bridge":
	 {"name": "Homebridge1",
		"username": "CC:22:3D:E3:CE:41",
		"port": 51826,
		"pin": "123-45-321"	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [
	 	{"accessory": "MiGatewaySecurity",
			"ip": "192.168.1.100",
			"token": "df6e212bd2edbd52d1a31137e4803803",
			"name": "Security",
			"disable": false,
			"switchName": "Security Switch",
			"switchDisable": true},
	 	{"accessory": "webos3",
			"name": "TV",
			"ip": "192.168.1.103",
			"mac": "7C:1C:4E:10:24:70",
			"keyFile": "/Пользователи/ilyabondin/.homebridge/lgtvKeyFile",
			"pollingEnabled": true,
			"externalSourceSwitch": "HDMI_2",
			"appSwitch": "com.webos.app.tvguide"}
	],

	"platforms": [
		{"platform": "MiAqaraPlatform",
			"gateways": {"7811dcb28244": "242F53D3EC364519"}},

		{"platform": "Camera-ffmpeg",
			"cameras": [{
				"name": "FFCAM2",
				"videoConfig": {
					"source": "-rtsp_transport tcp -re -i rtsp://admin:admin@192.168.1.99:554/Streaming/Channels/102",
					"stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 25}}]},

		{"type": "MiPhilipsTableLamp2",
			"ip": "192.168.1.100",
			"token": "33b4b871ae455efbf0f5239dbd6c8e71",
			"mainLightName": "living room table lamp",
			"secondLightName": "living room table lamp amb",
			"secondLightDisable": false,
			"eyecareSwitchName": "living room table lamp eyecare model",
			"eyecareSwitchDisable": false}
	]
}

**Comment by Skull09rus** [comment]
Please close this issue, I find my mistake in config.

**Comment by MDSERVER** [comment]
Can I get your assistance.  I get the same error when attempting to start Homebridge.


{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:22",
		"port": 51826,
		"pin": "031-45-154 "
	},
	
	"description": "Homebridge config.",
	
	"platforms": [{
		"platform": "SmartThings",
		"name": "SmartThings",
		"app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
		"app_id": "a900796c-b623-XXXX-XXXX-XXXXXX",
		"access_token": "ca1489d5-475c-4e9d-XXXX-X",
		"update_method": "direct",
		"direct_ip": "10.0.0.196 "
		}, {
	"platforms": [{
		"platform": "Nest",
		"token": "c.tmFjMmcuWQ87ZaPccur3NnT8sDJOOZCh9Ij3E0GIwXXXXXXXXXXXXX",
		"clientId": "72f70e58-9dc7-4125-XXXX-XXXXXXX",
		"clientSecret": "XXXXXXXXX",
		"code": "XXXXXXXX"
			}]
		}]
}

**Comment by MDSERVER** [comment]
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-3-30 13:13:37] Loaded plugin: homebridge-nest
[2018-3-30 13:13:37] Registering platform 'homebridge-nest.Nest'
[2018-3-30 13:13:37] ---
[2018-3-30 13:13:39] Loaded plugin: homebridge-smartthings
[2018-3-30 13:13:39] Registering platform 'homebridge-smartthings.SmartThings'
[2018-3-30 13:13:39] ---
[2018-3-30 13:13:39] Loaded config.json with 0 accessories and 2 platforms.
[2018-3-30 13:13:39] ---
[2018-3-30 13:13:39] Loading 2 platforms...
[2018-3-30 13:13:39] [SmartThings] Initializing SmartThings platform...
[2018-3-30 13:13:39] [SmartThings] Fetching Smart Things devices.
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by Skull09rus** [comment]
Try this config, 
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:22",
		"port": 51826,
		"pin": "031-45-154 "
	},

	"description": "Homebridge config.",

	"platforms": [{
			"platform": "SmartThings",
			"name": "SmartThings",
			"app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
			"app_id": "a900796c-b623-XXXX-XXXX-XXXXXX",
			"access_token": "ca1489d5-475c-4e9d-XXXX-X",
			"update_method": "direct",
			"direct_ip": "10.0.0.196 "
		},
		{
			"platform": "Nest",
			"token": "c.tmFjMmcuWQ87ZaPccur3NnT8sDJOOZCh9Ij3E0GIwXXXXXXXXXXXXX",
			"clientId": "72f70e58-9dc7-4125-XXXX-XXXXXXX",
			"clientSecret": "XXXXXXXXX",
			"code": "XXXXXXXX"
		}
	]
}

**Comment by MDSERVER** [comment]
Thank you for checking my config.  I tried the config you submitted & I'm now getting the following error.

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-3-30 16:16:37] Loaded plugin: homebridge-nest
[2018-3-30 16:16:37] Registering platform 'homebridge-nest.Nest'
[2018-3-30 16:16:37] ---
[2018-3-30 16:16:38] Loaded plugin: homebridge-smartthings
[2018-3-30 16:16:38] Registering platform 'homebridge-smartthings.SmartThings'
[2018-3-30 16:16:38] ---
[2018-3-30 16:16:38] Loaded config.json with 0 accessories and 2 platforms.
[2018-3-30 16:16:38] ---
[2018-3-30 16:16:38] Loading 2 platforms...
[2018-3-30 16:16:38] [SmartThings] Initializing SmartThings platform...
[2018-3-30 16:16:38] [SmartThings] Fetching Smart Things devices.
[2018-3-30 16:16:39] [Nest] Initializing Nest platform...
[2018-3-30 16:16:39] [Nest] Fetching Nest devices.
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Apple TV [Harmony Activity], ID 10136c7c-4c05-40e1-bbb6-7d432da5856d
[2018-3-30 16:16:39] [SmartThings] Device Added - Group fans, Name Ceiling Fan, ID b8f2bd7d-6852-4f41-82ca-6bfcfb1de44c
[2018-3-30 16:16:39] [SmartThings] Device Added - Group lights, Name Ceiling Fan Light, ID 558fb0af-712b-4048-838a-18c90cd0c729
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Chrome Cast [Harmony Activity], ID a5144977-809a-4c6a-a8e0-55e89916e357
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Dining Room, ID 6d86abd6-82db-4da5-9c37-6261da4f9e57
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Driveway, ID 05ff86dd-17c4-4261-b07f-01427e9835bc
[2018-3-30 16:16:39] [SmartThings] Device Added - Group garage_doors, Name Garage, ID 510710c1-8457-4564-93c7-0874611b5d8f
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Kitchen, ID 3b21b2f0-907b-4fa4-ba4f-8094fc77960a
[2018-3-30 16:16:39] [SmartThings] Device Added - Group lights, Name Living Room Left Lamp, ID 3b36888c-9100-4650-ab01-8f3667276f06
[2018-3-30 16:16:39] [SmartThings] Device Added - Group lights, Name Living Room Right Lamp, ID adc93be4-3ad9-444f-9e71-a60a6ca5cc6e
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Playstation [Harmony Activity], ID bc725b6d-9963-4cfa-bb6a-ca2eaafab47a
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Patio, ID a00c14fb-7055-494d-bb6a-26025e746ae2
[2018-3-30 16:16:39] [SmartThings] Device Added - Group switch, Name Porch, ID 37c71bd9-753b-41c8-9153-725ac8e1e597
[2018-3-30 16:16:39] [SmartThings] Unknown Capabilities: ["Health Check","Light","Relay Switch"]
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Apple TV [Harmony Activity]'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Ceiling Fan'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Ceiling Fan Light'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Chrome Cast [Harmony Activity]'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Dining Room'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Driveway'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Garage'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Kitchen'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Living Room Left Lamp'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Living Room Right Lamp'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Playstation [Harmony Activity]'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Patio'...
[2018-3-30 16:16:39] [SmartThings] Initializing platform accessory 'Porch'...
_http_client.js:125
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:125:13)
    at Object.request (http.js:39:10)
    at Object.request (https.js:239:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/agent-base/patch-core.js:23:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/pac-proxy-agent/node_modules/agent-base/patch-core.js:52:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:52:20)
    at Object.request (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/https-proxy-agent/node_modules/agent-base/patch-core.js:52:20)
    at _http (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:27:20)
    at GET (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:75:5)
    at Object.startDirect (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:117:9)
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:139:17
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:98:5
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:94:29
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:45:29)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Skull09rus** [comment]
Post whole config, maybe the reason anover syntax error again.

**Comment by MDSERVER** [comment]
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:22",
"port": 51826,
"pin": "031-45-154 "
},

"description": "Homebridge config.",

"platforms": [{
		"platform": "SmartThings",
		"name": "SmartThings",
		"app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
		"app_id": "a900796c-b623",
		"access_token": "ca1489d5-475c",
		"update_method": "direct",
		"direct_ip": "10.0.0.39 "
	},
	{
		"platform": "Nest",
		"token": "c.tmFjMmcuWQ87ZaPccur3NnT8sDJOOZCh9Ij3E0GIwX88Ex",
		"clientId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"clientSecret": "XXXXXXXXXXXXXXXXXXXXXX",
		"code": "XXXXXXXX"
	}
]
}
