### ISSUE TITLE
Crash on adding to apple home

### ISSUE THREAD

**Issue by OstapW** [nfarina/homebridge#1793]
Hi!

When I add accessories to my apple home homebridge crashes every time.  And if I try to launch it again while apple home is running it crashes with the same error.
Data below.
 
### Versions
- **Homebridge**: 0.4.38
- **Node**:       v8.11.0
- **OS**:         debian_version 9.4
latest homebridge-c4-plugin

### Configuration
```
{ 
 "bridge": {
        "name": "Castle",
        "username": "0C:22:3D:E3:CE:30"
    },
 "accessories": [
  {
    "accessory": "c4",
    "name": "Kabinet points",
    "device_type": "light",
    "proxy_id": "42",
    "variable_ids": {
      "level": "1001",
      "state": "1000"
    },
    "base_url": "http://10.0.1.49:9000",
    "refresh_interval": 2000
  }
] }
```

### Homebridge Log / Command Output
```
EventedHTTPServer Server listening on port 44783 +195ms
[2018-3-29 19:18:53] Homebridge is running on port 44783.
  EventedHTTPServer [::ffff:10.0.1.69] New connection from client +6s
  EventedHTTPServer [::ffff:10.0.1.69] HTTP server listening on port 35207 +2ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /pair-setup +30ms
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: POST /pair-setup +2ms
  HAPServer [0C:22:3D:E3:CE:30] Pair step 1/5 +12ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP Response is finished +2s
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /pair-setup +110ms
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [0C:22:3D:E3:CE:30] Pair step 2/5 +2ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP Response is finished +2s
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /pair-setup +68ms
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [0C:22:3D:E3:CE:30] Pair step 3/5 +1ms
  HAPServer [0C:22:3D:E3:CE:30] Pair step 4/5 +19ms
  HAPServer [0C:22:3D:E3:CE:30] Pair step 5/5 +3ms
  Accessory [Castle] Paired with client 87705314-2490-412B-83D7-CCFAB614ECEE +10ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:10.0.1.69] Client connection closed +28ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP connection was closed +3ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP server was closed +2ms
  EventedHTTPServer [::ffff:10.0.1.69] New connection from client +1s
  EventedHTTPServer [::ffff:10.0.1.69] HTTP server listening on port 45765 +2ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /pair-verify +6ms
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [0C:22:3D:E3:CE:30] Pair verify step 1/2 +4ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP Response is finished +36ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /pair-verify +22ms
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [0C:22:3D:E3:CE:30] Pair verify step 2/2 +4ms
  HAPServer [0C:22:3D:E3:CE:30] Client 87705314-2490-412B-83D7-CCFAB614ECEE verification complete +16ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /accessories +26ms
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:10.0.1.69] HTTP request: /characteristics +3s
  HAPServer [0C:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Castle] Processing characteristic set: [{"aid":2,"iid":10,"ev":true},{"aid":2,"iid":11,"ev":true}] +6ms
  Accessory [Castle] Registering Characteristic "On" for events +5ms
  Accessory [Castle] Registering Characteristic "Brightness" for events +2ms
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:852
        characteristic.subscribe();
                       ^

TypeError: characteristic.subscribe is not a function
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:852:24)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:807:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
```

**Comment by OstapW** [comment]
Well, I removed 
```
