### ISSUE TITLE
Problem reading confing.json

### ISSUE THREAD

**Issue by alvinaute** [nfarina/homebridge#1809]
Hello, i have an issue when i launch "homebridge" : 
i don't know why because it wasn't here before.
[2018-04-08 12:27:31] Loaded plugin: homebridge-thermostat-netatmo
[2018-04-08 12:27:31] Registering accessory 'homebridge-thermostat-netatmo.Netatmo Thermostat'
[2018-04-08 12:27:31] ---
[2018-04-08 12:27:31] There was a problem reading your config.json file.
[2018-04-08 12:27:31] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-04-08 12:27:31] 
/usr/local/lib/node_modules/homebridge/lib/server.js:194
    throw err;
    ^

SyntaxError: Unexpected token s
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:188:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:49:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by aswathraja** [comment]
Could you post your config .json file. Please post it without any secret key which u provide for any of ur plugins
