### ISSUE TITLE
This version of Node.js requires NODE_MODULE_VERSION 57

### ISSUE THREAD

**Issue by iuliusmaximilian** [nfarina/homebridge#1812]
My Homebridge isn't starting anymore after (accidentally) I executed the commands in this thread: https://forum.iobroker.net/viewtopic.php?f=8&t=1702 I downgraded node and nodejs again but Homebridge is not starting throwing the exception below. Any ideas?

### Expected Behavior
Homebridge starts properly.

### Current Behavior
When starting Homebridge I get an an exception:

```
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

### Versions
homebridge@0.4.38
npm 5.8.0
nodejs v8.11.1
node v8.9.0

**Comment by gt2416** [comment]
Delete node js completely then try this
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
