### ISSUE TITLE
 I can’t run home bridge on CentOS 7.

### ISSUE THREAD

**Issue by 911061873** [nfarina/homebridge#1816]
Last login: Wed Apr 11 01:32:23 2018 from 127.0.0.1
[root@localhost ~]# homebridge 
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
[root@localhost ~]#

**Comment by 911061873** [comment]
Missed something?

**Comment by k06a** [comment]
Have same problem with `cjs` loader, but for completely different project. Maybe NodeJS on NPM issue?

**Comment by 911061873** [comment]
It has been solved
‘’‘
yum install -y avahi-compat-libdns_sd-devel.$(uname -m)
‘’‘’

**Comment by 911061873** [comment]
https://gitee.com/n233333/homeassistant-and-homebridge-on-Centos-7/blob/master/README.md
