### ISSUE TITLE
Can't get Homebridge up and running

### ISSUE THREAD

**Issue by johnny1diesel** [nfarina/homebridge#1823]
### Expected Behavior
Homebridge should start when typing 'homebrew' in terminal

### Current Behavior
Homebridge does not start and I get an error message

### Steps to Reproduce (for bugs)
Have Xcode installed, then installed node from nodejs.org, ran npm install -g homebridge in terminal, followed by npm install -g homebridge-telldus. 
I did the above as root user. According to the tutorial I was following, after performing the above, I should be able to start Homebridge by typing 'Homebridge' in the terminal.

### Versions

- **Homebridge**: `0.4.38`
- **Node**:       `9.11.1`
- **OS**:         'MacOS 10.13.5 beta'

### Configuration

```json

```

### Homebridge Log / Command Output

```
Pxxxxx-MBP:~ xxxxxxxxxxxx$ homebridge
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Pxxxxxx-MBP:~ xxxxxxxxxxxx$ 
```

**Comment by linjiejim** [comment]
Same issue, did you find the solution? Thanks in advance.

**Comment by rjblake** [comment]
Same issue after upgrading in Raspberry PI:
/usr/lib/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/ed25519-hap/build/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/build/Debug/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/build/Release/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/out/Debug/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/Debug/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/out/Release/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/Release/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/build/default/ed25519.node
 → /usr/lib/node_modules/ed25519-hap/compiled/7.10.1/linux/arm/ed25519.node
    at bindings (/usr/lib/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:8:15)

**Comment by dmitrybercan** [comment]
it doesn't work
