### ISSUE TITLE
Node 4.0.0 / 4.x.x > Running HomeBridge on a Raspberry Pi

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#183]
Upgrading Raspbian will install node 4.0.0.
```
sudo apt-get upgrade
````
It seems Node 4.0.0 is available for Raspbian (Wheezy) but 2 files are missing.
I didn't found a solution yet. Any idea?

**Comment by cflurin** [comment]
... here is how to install node 4.0.0 on a RPi:
http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/

node -v
v4.0.0
 :ok:
but it still doesn't work with homebridge.

**Comment by volschin** [comment]
Remove the harmony crap from package.json and it will work.

**Comment by cflurin** [comment]
@volschin Thanks:
I quickly tried with a new install and following package.json:
```javascript
{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.1.1",
  "scripts": {
    "start": "DEBUG=* node app.js || true"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "license": "ISC",
  "dependencies": {
    "color": "0.10.x",
    "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#0030b35856e04ee2b42f0d05839feaa5c44cbd1f",
    "mdns": "^2.2.4",
    "node-persist": "0.0.x",
    "request": "2.49.x",
    "xml2js": "0.4.x",  
    "xmldoc": "0.1.x"
   }
}
```
there are still some dependencies not working:
```
ed25519.target.mk:132: recipe for target 'Release/obj.target/ed25519/src/ed25519.o' failed
make: *** [Release/obj.target/ed25519/src/ed25519.o] Error 1
make: Leaving directory '/home/pi/homebridge/node_modules/HAP-NodeJS/node_modules/ed25519/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/homebridge/node_modules/HAP-NodeJS/node_modules/ed25519
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Linux 4.1.6+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
pi@raspberrypi ~/homebridge $ 
```

**Comment by volschin** [comment]
Looks like your HAP-NodeJS submodules are not updated correctly. Check this.

**Comment by cflurin** [comment]
Actually I installed homebridge again:
```
$ git clone https://github.com/nfarina/homebridge.git
$ cd homebridge
$ npm install
```
I'm investigating about the submodules.

**Comment by volschin** [comment]
Do you have also deleted the npm cache in the folder ~/.npm?

**Comment by cflurin** [comment]
quick update:
```
npm cache clean
````
done! however no success.

**Comment by volschin** [comment]
Just to be sure, make a separate

git clone https://github.com/KhaosT/ed25519.git
cd ed25519
npm install

If this runs fine, there is a consistency problem with your machine. If it runs into problems, there is a general problem with the build of this module on your machine needing further investigation.

**Comment by cflurin** [comment]
done! it doesn't build.
did you install node 4.0.0 and homebridge on a RPi?
I think this is a general issue with RPi.

Log:
````
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/ed25519
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 

npm ERR! Linux 4.1.6+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! ed25519@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ed25519@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/ed25519/npm-debug.log
```

**Comment by volschin** [comment]
No, RPi2 with Kernel 4.1.6-v7+ and Jessie.

**Comment by cflurin** [comment]
Ok, I tried with RPi B v4.1.6+ #810. - I've got a second RPi2, 4.1.6-v7+ #810. Just now I'm running the branch "characteristic-props" on this one. I'll install it as soon as the PR is done.
Thanks for your help.

**Comment by cflurin** [comment]
@volschin:
I've just installed node 4.0.0 and homebridge on my RPi2. :+1:
Conclusion:
node 4.0.0 and RPI2, 4.1.6-v7 works.
RPi B: either it's a problem with my RPi B or it's a general issue with v4.1.6+?

@nfarina: 
this link might be useful for the wiki:
http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/

**Comment by nfarina** [comment]
@cflurin Updated, thanks!

**Comment by desvdp** [comment]
Did anyone find a solution for using a serial port ( yes I know it's old ... ) in 4.0.0 / 4.1.0 ? The popular node-serialport doesn't seem to be available yet for 4.x ...

**Comment by cflurin** [comment]
... continuing testing: node 4.1.0 on RPi 2 (v4.1.7-v7+ #815) installed -> :+1:
howto:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n latest
````

**Comment by cflurin** [comment]
Node 4.0.0 / 4.1.1 now works on a RPi B B+ (arm6l) too. The crucial point is the gcc 4.8. We need to install gcc v4.8. 
More details [here](https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi)

**Comment by PJCzx** [comment]
Hello,

I'm trying hard to make Nomebrige work on my Pi, but without success... It was really easy on my mac so... I don't understand :
```
uname -a
Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

gcc --version
gcc (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2

node -v
v4.2.1

cat package.json
{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.1.1",
  "scripts": {
    "start": "DEBUG=* node app.js || true"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "license": "ISC",
  "dependencies": {
    "color": "0.10.x",
    "hap-nodejs": "^0.0.2",
    "mdns": "^2.2.4",
    "node-persist": "0.0.x",
    "q": "1.4.x",
    "request": "2.49.x",
    "xml2js": "0.4.x",
    "xmldoc": "0.1.x",
    "debug": "^2.2.0"
  }
}

npm install


> mdns@2.2.10 install /home/pi/original/homebridge/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/pi/original/homebridge/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/4.2.1/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/4.2.1/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’

```

and a looooot of other errors...

Thx you in advance for you help :)

**Comment by nfarina** [comment]
Hm, I'm actually still using Node v0.12.x on my Pi - I haven't tried with 4.x yet. Has anyone else?

**Comment by PJCzx** [comment]
Downgraded to v0.12.6, compilation success :) I will comme back if it's not working but I doubt it :) Nice to know for further updated

**Comment by nfarina** [comment]
Thanks for testing that - I'll add a note to the wiki.

**Comment by raspman** [comment]
Can someone please help me find the package.son?  I'm thinking this is why I can't get my iOS app. Eve to see the devices...I can fully run home bridge without errors, but Eve isn't picking anything up (using Raspberry pi 2 b.)  Had better look using OSx, but that is still 50/50.  Thanks
