### ISSUE TITLE
config.json - help needed

### ISSUE THREAD

**Issue by Nivlac7** [nfarina/homebridge#1834]
Hi there, 

Need some jhelp with my config.json
If I launch hombridge without any config.json, it will launch, but as soon as I add the config.json, I get errors... I tried several very simple config file without success.

Thx for help!!

### Versions
- **Homebridge**:  0.4.38`
- **Node**:       4.3.2

### Configuration
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "B8:27:EB:B4:DD:7E",
        "port": 51826,
        "pin": "031-45-154"
    },


    "platforms": [
        {
            "platform" : "NukiBridge",
        }
        "bridge_url": "http://192.168.1.3:8080",
        "api_token": "IV5LXP",
        "locks": [{
            "id": "183447081",
            "name": "Front Door",
            "usesDoorLatch": true, // (default: false)
            "priority": 1 // (optional, default: 99 [locks with higher priority {lower number} will b$
                }]
    ]
}


```

### Homebridge Log / Command Output
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[5/3/2018, 4:53:37 PM] Loaded plugin: homebridge-nukiio
[5/3/2018, 4:53:37 PM] Registering platform 'homebridge-nukiio.NukiBridge'
[5/3/2018, 4:53:37 PM] Registering accessory 'homebridge-nukiio.NukiLock'
[5/3/2018, 4:53:37 PM] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
[5/3/2018, 4:53:37 PM] ---
[5/3/2018, 4:53:37 PM] There was a problem reading your config.json file.
[5/3/2018, 4:53:37 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[5/3/2018, 4:53:37 PM]
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token }
    at Object.parse (native)
    at Server.str.replace.Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by NiklasBr** [comment]
Your config.json is incorrect. The error message even says so: "Please try pasting your config.json file here to validate it: http://jsonlint.com". If you paste it there you will get automatic help trying to fix it.  JSON cannot contain comments and also it seems there are is a misplaced curly brace. I tried to clean it up, try this:

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "B8:27:EB:B4:DD:7E",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "NukiBridge",
		"bridge_url": "http://192.168.1.3:8080",
		"api_token": "IV5LXP",
		"locks": [{
			"id": "183447081",
			"name": "Front Door",
			"usesDoorLatch": true,
			"priority": 1
		}]
	}]
}
```

**Comment by Nivlac7** [comment]
Thanks a lot! Spent hours on that... The devil is in the details :)

**Comment by rposborne** [comment]
@Nivlac7 Make sure you close the github issue when your issue is solved :)
