### ISSUE TITLE
homebridge v0.4.39 crash

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#1841]
### Expected Behavior
Happy to see the native nodejs Bonjour in v0.4.39!  I'm testing my plugins for compatibility.  I did a `sudo npm -g uninstall homebridge` followed by `npm -g install homebridge --unsafe-perm`.

### Current Behavior
When my homebridge-zp plugin is active, homebridge crashes shortly after starting the server, see log below.  I'm not sure to what the "Service name" refers: is this the service as advertised by Bonjour or the HAP service?  Afaik, homebridge-zp doens't do anything with Bonjour, just like my other plugins.  Unlike my other plugins, it does create a web server (to receive notifications from the Sonos players).  I do have several other homebridge instances running on my network, on different servers, with different usernames /mac addresses (double-checked that) and different Bonjour service names.

I did notice that the Bonjour advertisement is a lot more noisier than for homebridge v0.4.38, see attached screenshot from Bonjour Browser (server is on v0.4.38; mbpr on v0.4.39).  Also note the `-CAD8` suffix to the name.  Obviously this screenshot was taken without homebridge-zp in the config.json.
![untitled](https://user-images.githubusercontent.com/22179355/39671314-0008801c-5116-11e8-93ed-970973f52a4c.jpeg)

### Steps to Reproduce (for bugs)
Run `homebridge -D`.

### Versions

- **Homebridge**: v0.4.39
- **Node**:       v8.11.1
- **OS**:         macOS 10.13.4

### Configuration
```json
{
  "bridge": {
    "name": "Homebridge - mbpr",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "987-65-432"
  },
  "platforms": [
    {
      "platform": "ZP",
      "speakers": true,
      "searchTimeout": 15
    }
  ]
}
```

### Homebridge Log / Command Output
```
[2018-5-6 10:17:16] Loaded plugin: homebridge-hue
[2018-5-6 10:17:16] Registering platform 'homebridge-hue.Hue'
[2018-5-6 10:17:16] ---
[2018-5-6 10:17:16] Loaded plugin: homebridge-music
[2018-5-6 10:17:16] Registering platform 'homebridge-music.Music'
[2018-5-6 10:17:16] ---
[2018-5-6 10:17:16] Loaded plugin: homebridge-p1
[2018-5-6 10:17:16] Registering platform 'homebridge-p1.P1'
[2018-5-6 10:17:16] ---
[2018-5-6 10:17:16] Loaded plugin: homebridge-ws
[2018-5-6 10:17:16] Registering platform 'homebridge-ws.WS'
[2018-5-6 10:17:16] ---
[2018-5-6 10:17:16] Loaded plugin: homebridge-zp
[2018-5-6 10:17:16] Registering platform 'homebridge-zp.ZP'
[2018-5-6 10:17:16] ---
[2018-5-6 10:17:16] Loaded config.json with 0 accessories and 1 platforms.
[2018-5-6 10:17:16] ---
[2018-5-6 10:17:16] Loading 1 platforms...
[2018-5-6 10:17:16] [ZP] Initializing ZP platform...
[2018-5-6 10:17:16] [ZP] homebridge-zp v0.2.18, node v8.11.1, homebridge v0.4.39
[2018-5-6 10:17:16] [ZP] warning: not using recommended homebridge version v0.4.38
[2018-5-6 10:17:16] [ZP] config.json: {"platform":"ZP","speakers":true,"searchTimeout":15}
[2018-5-6 10:17:16] [ZP] listening on http://192.168.76.41:56566/notify
[2018-5-6 10:17:16] [ZP] Home: setup ZP90 v8.5 player RINCON_000E58A8171201400 at 192.168.76.70:1400
[2018-5-6 10:17:17] [ZP] Living Room: ignore slave ZPS1 v8.5 player RINCON_5CAAFD7C941401400 at 192.168.76.72:1400
[2018-5-6 10:17:17] [ZP] Dining Room: ignore slave ZPS3 v8.5 player RINCON_B8E937DFD0A201400 at 192.168.76.76:1400
[2018-5-6 10:17:17] [ZP] Bathroom: setup ZPS12 v8.5 player RINCON_949F3E0E142C01400 at 192.168.76.77:1400
[2018-5-6 10:17:17] [ZP] Dining Room: setup ZPS3 v8.5 player RINCON_B8E937DF892C01400 at 192.168.76.75:1400
[2018-5-6 10:17:17] [ZP] Bedroom: setup ZPS1 v8.5 player RINCON_5CAAFD9EAF0A01400 at 192.168.76.78:1400
[2018-5-6 10:17:17] [ZP] Living Room: setup ZPS9 v8.5 player RINCON_5CAAFD1FA0D701400 at 192.168.76.71:1400
[2018-5-6 10:17:17] [ZP] Living Room: ignore slave ZPS1 v8.5 player RINCON_5CAAFD7C940401400 at 192.168.76.73:1400
[2018-5-6 10:17:17] [ZP] Bedroom: ignore slave ZPS1 v8.5 player RINCON_5CAAFD9EAFD401400 at 192.168.76.79:1400
[2018-5-6 10:17:31] [ZP] Home Sonos: SUBSCRIBE http://192.168.76.70:1400/GroupManagement/Event
[2018-5-6 10:17:31] [ZP] Bathroom Sonos: SUBSCRIBE http://192.168.76.77:1400/GroupManagement/Event
[2018-5-6 10:17:31] [ZP] Dining Room Sonos: SUBSCRIBE http://192.168.76.75:1400/GroupManagement/Event
[2018-5-6 10:17:31] [ZP] Bedroom Sonos: SUBSCRIBE http://192.168.76.78:1400/GroupManagement/Event
[2018-5-6 10:17:31] [ZP] Living Room Sonos: SUBSCRIBE http://192.168.76.71:1400/GroupManagement/Event
[2018-5-6 10:17:31] [ZP] Initializing platform accessory 'Home Sonos'...
[2018-5-6 10:17:31] [ZP] Initializing platform accessory 'Bathroom Sonos'...
[2018-5-6 10:17:31] [ZP] Initializing platform accessory 'Dining Room Sonos'...
[2018-5-6 10:17:31] [ZP] Initializing platform accessory 'Bedroom Sonos'...
[2018-5-6 10:17:31] [ZP] Initializing platform accessory 'Living Room Sonos'...
Setup Payload:
X-HM://00253QFZS4K79
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[Cut]
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 987-65-432 │     
    └────────────┘     
                       
[2018-5-6 10:17:31] Homebridge is running on port 51826.
[2018-5-6 10:17:31] [ZP] Living Room Sonos: new GroupManagement subscription uuid:RINCON_5CAAFD1FA0D701400_sub0000000366 (timeout Second-1800)
[2018-5-6 10:17:31] [ZP] Living Room Sonos: GroupManagement event
[2018-5-6 10:17:31] [ZP] Home Sonos: new GroupManagement subscription uuid:RINCON_000E58A8171201400_sub0000000548 (timeout Second-1800)
[2018-5-6 10:17:31] [ZP] Dining Room Sonos: new GroupManagement subscription uuid:RINCON_B8E937DF892C01400_sub0000000430 (timeout Second-1800)
[2018-5-6 10:17:31] [ZP] Bedroom Sonos: new GroupManagement subscription uuid:RINCON_5CAAFD9EAF0A01400_sub0000000360 (timeout Second-1800)
[2018-5-6 10:17:31] [ZP] Bathroom Sonos: new GroupManagement subscription uuid:RINCON_949F3E0E142C01400_sub0000000465 (timeout Second-1800)
[2018-5-6 10:17:31] [ZP] Dining Room Sonos: GroupManagement event
[2018-5-6 10:17:31] [ZP] Dining Room Sonos: coordinator for group Dining Room
[2018-5-6 10:17:31] [ZP] Bedroom Sonos: GroupManagement event
[2018-5-6 10:17:31] [ZP] Home Sonos: GroupManagement event
[2018-5-6 10:17:31] [ZP] Home Sonos: coordinator for group Home
[2018-5-6 10:17:31] [ZP] Home Sonos: platform coordinator
[2018-5-6 10:17:31] [ZP] Bedroom Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:31] [ZP] Bedroom Sonos: set member sonos group from undefined to Home
[2018-5-6 10:17:31] [ZP] Living Room Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:31] [ZP] Living Room Sonos: set member sonos group from undefined to Home
[2018-5-6 10:17:31] [ZP] Bathroom Sonos: GroupManagement event
[2018-5-6 10:17:31] [ZP] Bathroom Sonos: coordinator for group Bathroom
[2018-5-6 10:17:32] [ZP] Living Room Sonos: SUBSCRIBE http://192.168.76.71:1400/MediaRenderer/AVTransport/Event
[2018-5-6 10:17:32] [ZP] Living Room Sonos: new AVTransport subscription uuid:RINCON_5CAAFD1FA0D701400_sub0000000367 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Living Room Sonos: SUBSCRIBE http://192.168.76.71:1400/MediaRenderer/GroupRenderingControl/Event
[2018-5-6 10:17:32] [ZP] Living Room Sonos: new GroupRenderingControl subscription uuid:RINCON_5CAAFD1FA0D701400_sub0000000368 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Living Room Sonos: SUBSCRIBE http://192.168.76.71:1400/MediaRenderer/RenderingControl/Event
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: member of group Home Sonos
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:32] [ZP] Living Room Sonos: member of group Home Sonos
[2018-5-6 10:17:32] [ZP] Living Room Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:32] [ZP] Home Sonos: SUBSCRIBE http://192.168.76.70:1400/MediaRenderer/AVTransport/Event
[2018-5-6 10:17:32] [ZP] Dining Room Sonos: SUBSCRIBE http://192.168.76.75:1400/MediaRenderer/AVTransport/Event
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: SUBSCRIBE http://192.168.76.78:1400/MediaRenderer/AVTransport/Event
[2018-5-6 10:17:32] [ZP] Bathroom Sonos: SUBSCRIBE http://192.168.76.77:1400/MediaRenderer/AVTransport/Event
[2018-5-6 10:17:32] [ZP] Living Room Sonos: new RenderingControl subscription uuid:RINCON_5CAAFD1FA0D701400_sub0000000369 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Home Sonos: new AVTransport subscription uuid:RINCON_000E58A8171201400_sub0000000549 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Home Sonos: SUBSCRIBE http://192.168.76.70:1400/MediaRenderer/GroupRenderingControl/Event
[2018-5-6 10:17:32] [ZP] Living Room Sonos: AVTransport event
[2018-5-6 10:17:32] [ZP] Living Room Sonos: power (play/pause) changed from undefined to true
[2018-5-6 10:17:32] [ZP] Home Sonos: new GroupRenderingControl subscription uuid:RINCON_000E58A8171201400_sub0000000550 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Home Sonos: SUBSCRIBE http://192.168.76.70:1400/MediaRenderer/RenderingControl/Event
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: new AVTransport subscription uuid:RINCON_5CAAFD9EAF0A01400_sub0000000361 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: SUBSCRIBE http://192.168.76.78:1400/MediaRenderer/GroupRenderingControl/Event
[2018-5-6 10:17:32] [ZP] Dining Room Sonos: new AVTransport subscription uuid:RINCON_B8E937DF892C01400_sub0000000431 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Dining Room Sonos: SUBSCRIBE http://192.168.76.75:1400/MediaRenderer/GroupRenderingControl/Event
[2018-5-6 10:17:32] [ZP] Home Sonos: new RenderingControl subscription uuid:RINCON_000E58A8171201400_sub0000000551 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Home Sonos: AVTransport event
[2018-5-6 10:17:32] [ZP] Home Sonos: power (play/pause) changed from undefined to true
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: set member power (play/pause) from undefined to true
[2018-5-6 10:17:32] [ZP] Living Room Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:32] [ZP] Home Sonos: current track changed from undefined to THE ROLLING STONES - LITTLE RED ROOSTER
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: set member track from undefined to THE ROLLING STONES - LITTLE RED ROOSTER
[2018-5-6 10:17:32] [ZP] Living Room Sonos: copy group characteristics from Home Sonos
[2018-5-6 10:17:32] [ZP] Living Room Sonos: set member track from undefined to THE ROLLING STONES - LITTLE RED ROOSTER
[2018-5-6 10:17:32] [ZP] Bathroom Sonos: new AVTransport subscription uuid:RINCON_949F3E0E142C01400_sub0000000466 (timeout Second-1800)
[2018-5-6 10:17:32] [ZP] Bathroom Sonos: SUBSCRIBE http://192.168.76.77:1400/MediaRenderer/GroupRenderingControl/Event
[2018-5-6 10:17:32] [ZP] Dining Room Sonos: AVTransport event
[2018-5-6 10:17:32] [ZP] Dining Room Sonos: power (play/pause) changed from undefined to false
[2018-5-6 10:17:32] [ZP] Dining Room Sonos: current track changed from undefined to Arrow Classic Rock
[2018-5-6 10:17:32] [ZP] Bedroom Sonos: AVTransport event
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
```

**Comment by ebaauw** [comment]
Did some more testing.  I create the server using `http.createServer()`.  When I comment out the server.listen(), no crash occurs (but homebridge-zp doesn't receive any state from the Sonos players...).  I tried homebridge-config-ui-x, which also creates a server, but that one seems to work just fine.

I would appreciate any pointers as to what's happening here.

**Comment by KhaosT** [comment]
About advertising interfaces part, I think the implementation advertises on all interfaces it can see, which for macOS, IPv6 has a lot of transient addresses. The suffix was added for the exact purpose of preventing `Service name is already in use on the network`.

I'm not exactly sure why it would think the service name is already exist on network in this case...

**Comment by ebaauw** [comment]
Thanks, @KhaosT 

> I'm not exactly sure why it would think the service name is already exist on network in this case...

Because it tries to create the same advertisement twice, for the HAP server and for the homebridge-zp server?  Is there some debug option for hap-bonjour?

Did some more testing.  I create the homebridge-zp server _before_ the HAP server is created, because I need to discover the Sonos players and return them to homebridge (still using the static accessory model).  homebridge-config-ui-x creates its server _after_ the HAP server has been created (and, presumably, after the Bonjour advertisement has been setup?).  When I create the homebridge-zp server _after_ the HAP server has been created, no crash (and no accessories exposed...).

> I think the implementation advertises on all interfaces it can see, which for macOS, IPv6 has a lot of transient addresses.

Probably, the public IPv6 addresses are listed in `ifconfig`.  The local link addresses (fe80::) aren't though.  Anyway, probably not related to the issue.

**Comment by KhaosT** [comment]
@ebaauw Can you try manually comment out `this._advertisement.updateTxt(txtRecord);` in `Advertiser.js` and see if that still breaks homebridge-zp?

**Comment by KhaosT** [comment]
Actually can you try v4.40.0 first?

**Comment by ebaauw** [comment]
No joy in v0.4.40.

I can workaround the issue in homebridge-zp, by closing the server, just before the callback to homebridge from the platform `accessories()` function, and re-opening it a second later.  Not sure if the crash wouldn't appear later, when the Bonjour advertisement is updated or renewed...

**Comment by KhaosT** [comment]
@ebaauw Alright, now can you try put back `updateTxt()` but edit `./node_modules/bonjour-hap/lib/Service.js`, adding `if (!this._activated) { return }` as first line to `updateTxt` function there?

**Comment by ebaauw** [comment]
Like this?  No joy.

```javascript
  updateTxt: function (txt) {
    if (!this._activated) { return }
    this._unpublish()

    if (this.packet) { this.emit('service-packet-change', this.packet, this.onAnnounceComplete.bind(this)) }

    this.packet = null
    this.txt = txt
    this.announce()
  },
```

**Comment by KhaosT** [comment]
How about this?

```js
  updateTxt: function (txt) {
    if (!this.published) { return }
    
    this._unpublish()

    if (this.packet) { this.emit('service-packet-change', this.packet, this.onAnnounceComplete.bind(this)) }

    this.packet = null
    this.txt = txt
    this.announce()
  }
```

**Comment by KhaosT** [comment]
Alright those changes are in v0.4.42 now. It would be nice if npm has a progressional rollout then I can have plugin developers to test it before ship it out...

I'm really sorry for breaking the stuff for you guys. 😞

**Comment by ebaauw** [comment]
> Alright those changes are in v0.4.42 now.

Thanks, this version seems to work.

> It would be nice if npm has a progressional rollout then I can have plugin developers to test it before ship it out...

You can `npm publish --tag` to use a different tag than `latest`, so it's installed only through `sudo npm -g i homebridge@beta`or something.  When it's OK, you can simply update the tag with `npm dist-tag`.

> I'm really sorry for breaking the stuff for you guys.

Not to worry, and, as always, thank you very much for your hard work!

**Comment by cubilon** [comment]
>Alright those changes are in v0.4.42 now. It would be nice if npm has a progressional rollout then I can have plugin developers to test it before ship it out... ...

@KhaosT are you kidding? thanks for your great work!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mgoeller** [comment]
I get the same error using v.0.4.44. Should I try an older version?

**Comment by fantomnotabene** [comment]
@mgoeller change the mac address of your second instance

**Comment by mgoeller** [comment]
The username ("MAC address") in both config files is of course changed.
