### ISSUE TITLE
Config.JSON

### ISSUE THREAD

**Issue by HawkEye9034** [nfarina/homebridge#1844]
Hi. I cannot figure out whats wrong with my config.json file. I get this error: 

SyntaxError: Unexpected token { in JSON at position 93
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Here Is my config.JSON file: 
{
"bridge":{
"name": "HomeBridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},

{
 "platform": "Camera-ffmpeg",
 "cameras": [
 {
 "name": "OfficeCam",
 "videoConfig": {
 "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
 "maxStreams": 2,
 "maxWidth": 1280,
 "maxHeight": 720,
 "maxFPS": 30,
 "vcodec": "h264_omx"
 }
}
]
}
}

It would be a big help if you could help me fix this. Thanks!

**Comment by timodejong95** [comment]
Hey, the issue is that you put `platform` and `cameras` in a new object without key, this is not possible, objects with out keys need to be in an array.

I gues the following json is what you want:
```json
{
   "bridge":{
      "name":"HomeBridge",
      "username":"CC:22:3D:E3:CE:30",
      "pin":"031-45-154"
   },
   "platform":"Camera-ffmpeg",
   "cameras":[
      {
         "name":"OfficeCam",
         "videoConfig":{
            "source":"-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams":2,
            "maxWidth":1280,
            "maxHeight":720,
            "maxFPS":30,
            "vcodec":"h264_omx"
         }
      }
   ]
}
```

**Comment by HawkEye9034** [comment]
Thank you VERY MUCH it works now!

**Comment by HawkEye9034** [comment]
It says that it has loaded with 0 accessories and 0 platforms

**Comment by timodejong95** [comment]
@HawkEye9034 Is it correct yout missing the `port` key in the config?

You might try to use this as platform: 

```json
"platforms": [
    {
        "platform" : "Camera-ffmpeg",
        "name" : "Camera"
    }
]
```

**Comment by HawkEye9034** [comment]
Also, I have loaded it and it initialized the camera but it is not showing the camera in the home app

**Comment by timodejong95** [comment]
@HawkEye9034 Did you install the homebridge plugin for ffmpeg?: https://github.com/KhaosT/homebridge-camera-ffmpeg

**Comment by HawkEye9034** [comment]
@timodejong95 Still doesn't work

**Comment by HawkEye9034** [comment]
@timodejong95 I just cant figure out why

**Comment by timodejong95** [comment]
@HawkEye9034 I haven't tested camera module myself but are you sure your source is good because it needs to open a stream: https://github.com/KhaosT/homebridge-camera-ffmpeg#configjson-example

Can you try using this test stream:
```
"source": "-i https://video3.earthcam.com/fecnetwork/10874.flv/playlist.m3u8",
"stillImageSource": "https://www.earthcam.com/cams/includes/image.php?logo=0&img=64ea74600b4ef6441db62fd3ad3ce754",
```
What is the output if you type `ffmpeg` on the command line?

**Comment by HawkEye9034** [comment]
Still nothing @timodejong95

**Comment by ebaauw** [comment]
Fix your config.json: the `"cameras"` array should be inside the Camara-ffmpeg platform, see https://github.com/KhaosT/homebridge-camera-ffmpeg#configjson-example:
```
{
  "bridge": {
    "name": "HomeBridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Camera-ffmpeg",
      "name": "Camera",
      "cameras": [
        {
          "name": "OfficeCam",
          "videoConfig": {
            "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "h264_omx"
          }
        }
      ]
    }
  ],
  "accessories": [
    {
      "accessory": "Sonos",
      "name": "Living Room Speakers",
      "room": "Lounge",
      "mute": false
    }
  ]
}
```

**Comment by HawkEye9034** [comment]
@ebaauw thank you it is working perfectly now

**Comment by ebaauw** [comment]
I think there’s a comma missing between the } and { just before the SonyBravia platform.  Try https://jsonlint.com.

**Comment by ebaauw** [comment]
Btw if you’re looking at integrating your Sonos speakers, you might have a look at my homebridge-zp plugin.  Sorry for the shameless plug...

**Comment by HawkEye9034** [comment]
@ebaauw @timodejong95 Sorry having issues again. Heres the json:
`{
  "bridge": {
    "name": "HomeBridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Camera-ffmpeg",
      "name": "Camera",
      "cameras": [
        {
          "name": "OfficeCam",
          "videoConfig": {
            "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "h264_omx"
          }
]        
}
 {
 "platform":"SonyBravia", 
 "name":"Living Room TV",
 "ipadress":"xxxxxxxx",
 "psk":"xxxxxxxx",
}
    }
  ]
{
  "accessories": [
    {
      "accessory": "Sonos",
      "name": "Living Room Speakers",
      "room": "Lounge",
      "mute": false
    }
  ]
}

}
`

**Comment by HawkEye9034** [comment]
@ebaauw ^^^^^^^

**Comment by HawkEye9034** [comment]
please can you fix this i dont know why its not working
`{
  "bridge": {
    "name": "HomeBridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Camera-ffmpeg",
      "name": "Camera",
      "cameras": [
        {
          "name": "OfficeCam",
          "videoConfig": {
            "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "h264_omx"
          }
{
"platform": "ZP",
"service": "speaker",
"brightness": true,
"speakers": false
}
]        
}
 {
 "platform":"SonyBravia", 
 "name":"Living Room TV",
 "ipadress":"192.168.1.10",
 "psk":"220304",
}
    }
  ]
}
`

**Comment by HawkEye9034** [comment]
Please can you fix this i don't know why it wont work:
{
  "bridge": {
    "name": "HomeBridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Camera-ffmpeg",
      "name": "Camera",
      "cameras": [
        {
          "name": "OfficeCam",
          "videoConfig": {
            "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "h264_omx"
          }
{
"platform": "ZP",
"service": "speaker",
"brightness": true,
"speakers": false
}
]        
}
 {
 "platform":"SonyBravia", 
 "name":"Living Room TV",
 "ipadress":"192.168.1.10",
 "psk":"220304",
}
    }
  ]
}

**Comment by HawkEye9034** [comment]
I just upgraded node so that your sonos zp would work and now im getting this error: 

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)

**Comment by ebaauw** [comment]
Best uninstall and re-install homebridge after upgrading (the major version of) node.
```
sudo npm -g un homebridge
sudo npm -g i homebridge --unsafe-perm
```

In your JSON, again there's a comma missing between the `}` and `{`.  Or, as jsonlint puts it: _Expecting 'EOF', '}', ',', ']', got '{'_.

**Comment by HawkEye9034** [comment]
Ok fixed the homebridge issue. Added the comma but json lint gives me this now:

Error: Parse error on line 20:
...264_omx"				},				{					"platform": "
---------------------^
Expecting 'STRING', got '{'

**Comment by ebaauw** [comment]
You need to add the "ZP" platform to the `"platforms"` array, not halfway in the camera platform.
You need to balance { and } (for objects) as well as [ and ] (for arrays).  You need commas only between array elements or object key/value pairs.  Best use a decent layout, so you can spot the unbalanced {} and [].  Also enclose the json in ``` (triple backquotes), so the formatting is preserved.

I think this is what you meant:
```json
{
  "bridge": {
    "name": "HomeBridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Camera-ffmpeg",
      "name": "Camera",
      "cameras": [
        {
          "name": "OfficeCam",
          "videoConfig": {
            "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "h264_omx"
          }
        }
      ]
    },
    {
      "platform": "ZP",
      "service": "speaker",
      "brightness": true,
      "speakers": false
    },
    {
      "platform": "SonyBravia",
      "name": "Living Room TV",
      "ipadress": "192.168.1.10",
      "psk": "220304"
    }
  ]
}
```

**Comment by HawkEye9034** [comment]
And is that all i need to do, will zp automatically find my sonos system?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-zp#homebridge-zp
