### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mx801** [nfarina/homebridge#1846]
this is my config.json:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:4D:D5:6D:B8",
        "port": 51826,
        "pin": "031-45-154"
    },

"platforms": [
        {
            "platform" : "HomeAssistant",
            "name" : "HomeAssistant",
	    "host": "http://192.168.10.118",
            "username": "xxxxxxx",
            "password": "xxxxxxx",
	    "grouping": "room",
	    "pollerperiod": "2",
	    "supported_types": ["input_boolean"," light "," lock "," media_player "," scene "," sensor "," switch "],
	    "default_visibility": "visible"
        }
    ]
}

and error: 
TypeError: Cannot read property 'pollerperiod' of null
    at new FibaroHC2 (C:\Users\EDER\AppData\Roaming\npm\node_modules\homebridge-fibaro-hc2\dist\index.js:59:40)
    at Server._loadDynamicPlatforms (C:\Users\EDER\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:325:30)
    at Server.run (C:\Users\EDER\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:87:8)
    at module.exports (C:\Users\EDER\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (C:\Users\EDER\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

Please, Can someone help me

thanks

**Comment by mol7os** [comment]
Same here:

Load homebridge-fibaro-hc2.FibaroHC2
/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:65
        let pollerPeriod = this.config.pollerperiod ? parseInt(this.config.pollerperiod) : defaultPollerPeriod;
                                       ^

TypeError: Cannot read property 'pollerperiod' of null
    at new FibaroHC2 (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:65:40)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:346:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

node.js updated, same to plugin and homebridge. All on latest versions.
