### ISSUE TITLE
Node.js 10.1.0 and Homebridge

### ISSUE THREAD

**Issue by tellice** [nfarina/homebridge#1869]
I updated node.js to v10.1.0 and now homebridge will not run, i was running v 9.11.1 and all worked. But i seen a newer node.js was out so i updated and now its  broken homebridge any advise. Please below error when i run homebridge.

/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/bui                                                                                 ld/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/lib/node_modules/homebridge/node_modules/bindings/bindings                                                                                 .js:81:44)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/ed25519                                                                                 -hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
root@raspberrypi:/home/pi#

**Comment by ebaauw** [comment]
After updating the major version of node, you need to uninstall and re-install homebridge.  Somehow, just re-installing doesn’t cut it.

**Comment by tellice** [comment]
Cheers unistalling and installing done the trick and working again. That is strange that rebuild or reinstalling donst work
