### ISSUE TITLE
Error 'body.forEach is not a function' on startup homebridge

### ISSUE THREAD

**Issue by stehof2** [nfarina/homebridge#1878]
Hi,

I've a problem to get Homebridge fully functional with the ewelink plugin. Everythin is installed correctly to my knowlegde, but when I start the homebridge app I get the following error message:

[2018-5-31 23:10:37] [eWeLink] A total of [0] accessories were loaded from the local cache
[2018-5-31 23:10:37] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-ota.coolkit.cc:8080]
[2018-5-31 23:10:37] Homebridge is running on port 51826.
[2018-5-31 23:10:37] [eWeLink] eWeLink HTTPS API reports that there are a total of [108] devices registered
/usr/lib/node_modules/homebridge-ewelink/index.js:98
                body.forEach((device) => {
                     ^

TypeError: body.forEach is not a function
    at /usr/lib/node_modules/homebridge-ewelink/index.js:98:22
    at Object.parseBody (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1085:12)

Does anyone can help me how to fix this?

**Comment by stehof2** [comment]
Problem was solved by changing line 98 in index.js to -> Array.from(body).forEach(function (device) {

Problem is solved.
