### ISSUE TITLE
Hombridge crashes with Nuki

### ISSUE THREAD

**Issue by gold2605** [nfarina/homebridge#1879]
Hello, I first added Nuki to my hombridge and after entering my config data, Hombridge crashes with the following error message.
Does anyone know help?

`[2018-6-2 15:31:26] [Config] Initializing config platform...
[2018-6-2 15:31:26] [Config] Spawning homebridge-config-ui-x with PID 12169
[2018-6-2 15:31:26] [Nuki] Initializing NukiBridge platform...
[2018-6-2 15:31:26] [Nuki] Initializing Nuki bridge 'http://192.168.0.13:8080'...
Error: EACCES: permission denied, mkdir '/.node-persist'
    at Object.fs.mkdirSync (fs.js:887:18)
    at sync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:77:24)
    at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
    at new NukiBridge (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:70:18)
    at new NukiBridgePlatform (/usr/local/lib/node_modules/homebridge-nukiio/index.js:17:23)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service hold-off time over, scheduling restart.
Stopped Node.js HomeKit Server.
`
Homebridge runs on an RPI with node.js V8.8.1 and homebridge 0.4.42 
on port 51826

config:

{
            "platform": "NukiBridge",
            "name": "Nuki",
            "api_token": "xxxxxx",
            "bridge_url": "192.168.0.13:8080",
            "webhook_port": "51826",
            "lock_state_mode": "1",
            "webhook_server_ip_or_name": "192.168.0.113",
            "locks": [
                {
                    "id": "xxxxxxxxx",
                    "usesDoorLatch": "true",
                    "name": "Vorbautür",
                    "priority": "1"
                }
            ]
        },Many Thanks

**Comment by theo-69** [comment]
Maybe try Issue @ the Yuki Plugin Site [https://github.com/benzman81/homebridge-nukiio](url)
