### ISSUE TITLE
I just update homebridge and now not working.

### ISSUE THREAD

**Issue by toshibochan** [nfarina/homebridge#1885]
please help.
I just update homebridge and now not working.
"
/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at bindings (/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
"

**Comment by toshibochan** [comment]
I update node to 8.x and possible this is the problem!

**Comment by theo-69** [comment]
did you run `npm rebuild` or `npm install` like it said in the Error?

**Comment by toshibochan** [comment]
Uninstall Homebridge going to delete ~/.homebridge?

**Comment by ebaauw** [comment]
No, just /usr/lib/node_modules/homebridge (and /usr/bin/homebridge).

**Comment by toshibochan** [comment]
Thanks! What is the best node version for raspberry pi? 10, 9, 8, 7 or 6?

**Comment by ebaauw** [comment]
The latest LTS (Long Term Stability) version, currently 8.11.2.  Best install by:
```
$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install -y nodejs
```
See https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions.

**Comment by toshibochan** [comment]
@ebaauw thanks! I will install later!

**Comment by alexmagereanu** [comment]
Remove `package-lock.json` , then do
`npm install` 
and 
`npm rebuild`
You should be good to go. Works for node v8.11.3
ps. you have to be in the folder where homebridge was installed. for me this was /usr/local/lib/node_modules/homebridge

**Comment by martin072** [comment]
Hi, 

I ran into a similar problem, having update Node, homebridge fails to start.

node -v
v10.12.0

/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)

Any help??
