### ISSUE TITLE
TypeError: "value" argument must not be a number

### ISSUE THREAD

**Issue by grendel513** [nfarina/homebridge#1890]
When starting Hombridge the following error and stack trace emerges (Homekit is not able to find hombridge):
```
[6/10/2018, 10:43:10 PM] Loaded config.json with 0 accessories and 3 platforms.
[6/10/2018, 10:43:10 PM] ---
[6/10/2018, 10:43:11 PM] Loaded plugin: homebridge-bond
[6/10/2018, 10:43:11 PM] Registering platform 'homebridge-bond.Bond'
[6/10/2018, 10:43:11 PM] ---
[6/10/2018, 10:43:11 PM] Loaded plugin: homebridge-nest
[6/10/2018, 10:43:11 PM] Registering platform 'homebridge-nest.Nest'
[6/10/2018, 10:43:11 PM] ---
[6/10/2018, 10:43:11 PM] Loaded plugin: homebridge-wink3
[6/10/2018, 10:43:11 PM] Registering platform 'homebridge-wink.Wink'
[6/10/2018, 10:43:11 PM] ---
[6/10/2018, 10:43:11 PM] Loading 3 platforms...
[6/10/2018, 10:43:11 PM] [Bond] Initializing Bond platform...
[6/10/2018, 10:43:11 PM] [Nest] Initializing Nest platform...
[6/10/2018, 10:43:11 PM] [Nest] Fetching Nest devices.
[6/10/2018, 10:43:11 PM] [Wink] Initializing Wink platform...
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Daughter's Light (binary_switch/88688)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Son's Light (binary_switch/88697)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Kitchen Light (binary_switch/107559)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Backyard Lights (binary_switch/150391)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Tapt Light (binary_switch/150453)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Hallway Light (binary_switch/239537)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Dining room Light (light_bulb/736928)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Kitchen Table Light (light_bulb/768722)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Garage Light (binary_switch/641309)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Home Kitchen Nest Protect (smoke_detector/163565)
[6/10/2018, 10:43:11 PM] [Wink] Loaded from cache: Home Hallway Nest Protect (smoke_detector/163567)
[6/10/2018, 10:43:11 PM] [Bond] 2 cached accessories were loaded
[6/10/2018, 10:43:11 PM] [Wink] Refreshing devices...
[6/10/2018, 10:43:12 PM] [Bond] Configure Accessory: Living Room Fan
[6/10/2018, 10:43:12 PM] [Bond] Configure Accessory: Master Bedroom Fan
[6/10/2018, 10:43:12 PM] [Wink] Hidden by hide_groups config option: Home Nest Thermostat (thermostat/65615)
[6/10/2018, 10:43:12 PM] [Wink] Not supported by HomeKit: Tapt Smart Switch (gang/25624)
[6/10/2018, 10:43:12 PM] [Wink] Not supported by HomeKit: Top Tapt Button (button/51643)
[6/10/2018, 10:43:12 PM] [Wink] Not supported by HomeKit: Bottom Tapt Button (button/51644)
[6/10/2018, 10:43:12 PM] [Wink] Not supported by HomeKit: Sprinkler (sprinkler/6701)
[6/10/2018, 10:43:12 PM] [Wink] Devices refreshed
[6/10/2018, 10:43:12 PM] [Wink] Checking if hub is reachable (Wink, 192.168.1.237)...
[6/10/2018, 10:43:12 PM] [Wink] Hub is reachable locally (Wink, 192.168.1.237)
[6/10/2018, 10:43:13 PM] [Nest] initing thermostat "Nest Thermostat": deviceId: ZTCahQnCOyG9Mp7vQ8c6QY83CUFZXCqu structureId: RLUpPSkIP-1V3mEUZmb4yJaSbGXYU_v06ri4FZdUjxqmXB5GbPNg6g
[6/10/2018, 10:43:13 PM] [Nest] initing protect "Kitchen Nest Protect": deviceId: tc48qw_XHM1GaEOBPKMY7483CUFZXCqu structureId: RLUpPSkIP-1V3mEUZmb4yJaSbGXYU_v06ri4FZdUjxqmXB5GbPNg6g
[6/10/2018, 10:43:13 PM] [Nest] initing protect "Hallway Nest Protect": deviceId: tc48qw_XHM1eL3hPH40TKI83CUFZXCqu structureId: RLUpPSkIP-1V3mEUZmb4yJaSbGXYU_v06ri4FZdUjxqmXB5GbPNg6g
[6/10/2018, 10:43:13 PM] [Nest] Initializing platform accessory 'Nest Thermostat'...
[6/10/2018, 10:43:13 PM] [Nest] Initializing platform accessory 'Kitchen Nest Protect'...
[6/10/2018, 10:43:13 PM] [Nest] Initializing platform accessory 'Hallway Nest Protect'...
[6/10/2018, 10:43:13 PM] [Nest] TypeError [ERR_INVALID_ARG_TYPE]: The "value" argument must not be of type number. Received type number
    at Function.from (buffer.js:215:11)
    at Object.from (/usr/local/lib/node_modules/homebridge/node_modules/buffer-shims/index.js:53:19)
    at Characteristic.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:459:26)
    at Service.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:239:44)
    at Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:485:30)
    at Bridge.Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:41)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:572:21)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:402:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:268:11
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
Unhandled rejection Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-nest/index.js:274:11
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

[6/10/2018, 10:43:13 PM] [Wink] Authenticated with local hub (Wink, 192.168.1.237)
[6/10/2018, 10:43:26 PM] [Wink] Received update notification: Son's Light (binary_switch/88697)
```

### Versions

├── homebridge@0.4.43
├── homebridge-bond@0.1.0
├── homebridge-nest@2.1.3
├── homebridge-wink3@1.9.1
└── npm@6.1.0
- **Node**:       `node --version` v10.4.0
- **OS**:         macOS High Sierra 10.13.4 (17E199)

### Configuration

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "description": "Homebridge",
  "platforms": [
    {
      "platform": "Bond",
      "email": "xxxxx",
      "password": "xxxxx"
    },
    {
      "platform": "Nest",
      "token": "xxxxx",
      "clientId": "xxxx",
      "clientSecret": "xxxxx",
      "code": "xxxxx"
    },
    {
      "platform": "Wink",
      "name": "Wink",
      "client_id": "xxxxx",
      "client_secret": "xxxxx",
      "username": "xxxxx",
      "password": "xxxxxxx",
      "hide_groups": [
        "garage_door",
        "thermostat"
      ],
      "hide_ids": [],
      "access_token": "xxxxxx",
      "refresh_token": "xxxxxxxx"
    }
  ]
}
```

**Comment by grendel513** [comment]
I tried removing the nest plugin and still received:

```
[6/10/2018, 11:05:20 PM] Loaded config.json with 0 accessories and 2 platforms.
[6/10/2018, 11:05:20 PM] ---
[6/10/2018, 11:05:21 PM] Loaded plugin: homebridge-bond
[6/10/2018, 11:05:21 PM] Registering platform 'homebridge-bond.Bond'
[6/10/2018, 11:05:21 PM] ---
[6/10/2018, 11:05:21 PM] Loaded plugin: homebridge-wink3
[6/10/2018, 11:05:21 PM] Registering platform 'homebridge-wink.Wink'
[6/10/2018, 11:05:21 PM] ---
[6/10/2018, 11:05:21 PM] Loading 2 platforms...
[6/10/2018, 11:05:21 PM] [Bond] Initializing Bond platform...
[6/10/2018, 11:05:21 PM] [Wink] Initializing Wink platform...
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Daughter's Light (binary_switch/88688)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Son's Light (binary_switch/88697)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Kitchen Light (binary_switch/107559)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Backyard Lights (binary_switch/150391)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Tapt Light (binary_switch/150453)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Hallway Light (binary_switch/239537)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Dining room Light (light_bulb/736928)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Kitchen Table Light (light_bulb/768722)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Garage Light (binary_switch/641309)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Home Kitchen Nest Protect (smoke_detector/163565)
[6/10/2018, 11:05:21 PM] [Wink] Loaded from cache: Home Hallway Nest Protect (smoke_detector/163567)
TypeError [ERR_INVALID_ARG_TYPE]: The "value" argument must not be of type number. Received type number
    at Function.from (buffer.js:215:11)
    at Object.from (/usr/local/lib/node_modules/homebridge/node_modules/buffer-shims/index.js:53:19)
    at Characteristic.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:459:26)
    at Service.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:239:44)
    at Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:485:30)
    at Bridge.Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:41)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:572:21)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

**Comment by grendel513** [comment]
fixed by deleting the persist and cachedAccessories directories
