### ISSUE TITLE
Platform Contrast - ERROR - Attempting to register a platform which has already been registered

### ISSUE THREAD

**Issue by imbackniantic** [nfarina/homebridge#1908]
### Current Behavior

When i've installed a different plugin to control the aqara network but is in contrast with the old one because based on the same script and using same platform. I've already tried to uninstall the single plugin, to uninstall homebridge and delete all the folders. I can't find the folders of plugins and i suppose they remain also after the uninstallation of homebridge because runningit after a fresh installation i also have the error about platofrm

### Versions

- **Homebridge**: `v0.4.43`
- **Node**:       `v8.9.1`
- **OS**:     `MacOs`   

### Configuration

```json
if needed i can add
```

### Homebridge Log / Command Output

```
[2018-6-24 21:46:24] Loaded config.json with 0 accessories and 4 platforms.
[2018-6-24 21:46:24] ---
[2018-6-24 21:46:25] Loaded plugin: homebridge-broadlink-rm
[2018-6-24 21:46:25] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2018-6-24 21:46:25] ---
[2018-6-24 21:46:25] Loaded plugin: homebridge-config-ui-x
[2018-6-24 21:46:25] Registering platform 'homebridge-config-ui-x.config'
[2018-6-24 21:46:25] ---
[2018-6-24 21:46:25] Loaded plugin: homebridge-mi-aqara
[2018-6-24 21:46:25] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2018-6-24 21:46:25] ---
[2018-6-24 21:46:25] Loaded plugin: homebridge-mi-aqara-nightly

/usr/local/lib/node_modules/homebridge/lib/api.js:138
    throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");
          ^
Error: Attempting to register a platform 'homebridge-mi-aqara.MiAqaraPlatform' which has already been registered!
    at API.registerPlatform (/usr/local/lib/node_modules/homebridge/lib/api.js:138:11)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-mi-aqara-nightly/index.js:31:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:165:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:139:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3


```

**Comment by ebaauw** [comment]
Each plugin installs separately from homebridge and from other plugins, to `/usr/local/lib/node_modules`.  Apparently both Aqara plugins use the same name to register with homebridge, causing the error.  Uninstall the plugin by `sudo npm -g un homebridge-mi-aqara`, or simply `sudo rm -r /usr/local/lib/node_modules/homebridge-mi-aqara`.  Alternatively, you can disable the plugin from loading in config.json, see #1880 (make sure to scroll down).
