### ISSUE TITLE
Can't run multiple platforms: Config.json

### ISSUE THREAD

**Issue by Tucker28** [nfarina/homebridge#1924]
### Expected Behavior
Works fine when just using the Hue platform.  Cannot add another platform.  I've checked other posts and made sure it is set as per the posts.  I have used https://jsonlint.com and when I remove the second platform from { to }, it works fine.

### Current Behavior
With just the Hue platform, works perfect.  With both, will not start.

### Versions

- **Homebridge**:  `0.4.44`
- **Node**:       `v10.6.0`
- **OS**:        ` macOS 10.13.5`

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
          "accessory": "TuyaOutlet",
          "name": "Tuya Outlet",
          "devId": "012005935ccf7fdf8e19",
          "localKey": "966e64437e7670b7"
        }
    ],

    "platforms": [
      {
        "platform": "Hue",
        "users": {
          "001788FFFE7D2003": "8SC039ooD3uvucBYelCzyZ99D8hEuffkEUhJU-bD",
          "001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
        },
        "sensors": true,
        "nativeHomeKitSensors": false,
        "excludeSensorTypes": ["CLIPPresence", "Geofence"],
        "lights": true
      }
      {
          "platform": "config",
          "name": "Config",
          "port": 8080,
          "log": "/var/log/homebridge.log",
          "restart": "sudo systemctl restart homebridge.service"
      }
      ]
}
```

### Homebridge Log / Command Output

```
[7/5/2018, 6:00:29 PM] There was a problem reading your config.json file.
[7/5/2018, 6:00:29 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[7/5/2018, 6:00:29 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:213
    throw err;
    ^

SyntaxError: Unexpected token { in JSON at position 960
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:207:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by Apollon77** [comment]
Your JSON is not valid. You need an comma between the two platform definitions. There are online json validators available.

**Comment by Tucker28** [comment]
Thank you.  Everything I saw made no mention of the comma between them, but that worked perfectly.
