### ISSUE TITLE
Homebridge Installation issue

### ISSUE THREAD

**Issue by gwhizkids** [nfarina/homebridge#1932]
I am attempting to install Homebridge on my Mac.  

Upon install and running "Homebridge" v 8.11.3, I am getting the following:

Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
Any help that could be provided would be much appreciated!  Let me know if additional information is needed.

Thanks!
```

**Comment by Apollon77** [comment]
Please post your configuration.
