### ISSUE TITLE
Homebridge Error Permission Denied

### ISSUE THREAD

**Issue by socratatom** [nfarina/homebridge#1933]
### Expected Behavior
Homebridge should allow for devices to connect to the Home app when 'home bridge' is initiated from the command prompt.

### Current Behavior
Homebridge does not connect to the Home app.  It displays the error "Couldn't add accessory" or something to that effect.

### Versions

- **Homebridge**: 0.4.44
- **Node**:       10.6.0
- **NPM**:   6.1.0
- **OS**:         10.13.5

### Configuration

```{
        "bridge": {
            "name": "Homebridge",
            "username": "**:DB:**:EE:CE:**",
            "pin": "***-**-***"
        },


        "platforms": [
            {
            "platform": "Nest",
            "token": "************************",
            "clientId": "***********************************",
            "clientSecret": "*****************************",
            "code": "******************",
            "username": "******************",
            "password": "******************"
            }
        ]



}
```

### Homebridge Log / Command Output
```
┌─────────────────────────────────────────────────────────────┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) /Users/username/.config │
└─────────────────────────────────────────────────────────────┘
/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/Users/username'
    at Object.mkdirSync (fs.js:738:3)
    at sync (/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:71:13)
    at sync (/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:77:24)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:642:20)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:7)
```

**Comment by Apollon77** [comment]
The User you start homebridge with do not have rights to access the directory in the error message. Fix that.

**Comment by socratatom** [comment]
The directory in the error does not exist. '/Users/username' is not a user.  I am starting it with the same account that I installed it with.  Thats what has me perplexed.  I don't know how to grant rights to a location that isn't there.
