### ISSUE TITLE
Windows 10 Homebridge - Loaded config.json with 0 Accessories

### ISSUE THREAD

**Issue by parsamanesh** [nfarina/homebridge#1934]
I have this Homebridge running on a Mac perfectly fine, but I wish to switch it to a windows pc.
I have setup everything, without the config.json running Homebridge results in a QR code as expected.
When putting in the config.json (same one I'm using with Mac) I get the error without a QR code:

**### CMD Homebridge output**
`[2018-7-12 17:36:37] Loaded config.json with 0 accessories and 1 platforms.
[2018-7-12 17:36:37] ---
[2018-7-12 17:36:37] No plugins found. See the README for information on installing plugins.
[2018-7-12 17:36:37] Loading 1 platforms...
C:\Users\ENTERTAINMENT PC\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'SmartThings' was not registered by any plugin.
    at API.platform (C:\Users\ENTERTAINMENT PC\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:122:13)
    at Server._loadPlatforms (C:\Users\ENTERTAINMENT PC\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:315:45)
    at Server.run (C:\Users\ENTERTAINMENT PC\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:85:36)
    at module.exports (C:\Users\ENTERTAINMENT PC\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:43:10)
    at Object.<anonymous> (C:\Users\ENTERTAINMENT PC\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)`

**### Config.json:**
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"platforms": [{
		"platform": "SmartThings",
		"name": "SmartThings",
		"app_url": "XXXXXX",
		"app_id": "XXXXXX",
		"access_token": "XXXXXXX"
	}]
}

Why is this happening?
Thanks

**Comment by Apollon77** [comment]
Do you installed the smartthings homebridge plugin correctly?! Homebridge can not find it.
