### ISSUE TITLE
 TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by crunchy59** [nfarina/homebridge#1946]
Hello,
In my case I wish to operate my FGR-222.
In my configuration my ID is 1 and my logicaID 1.38.0
Here is my configuration file:
"accessory": "HttpJeedom",
"jeedom_url": "http://127.0.0.1",
"jeedom_api": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
"service": "UpService",
"name": "Salon Volet Roulant",
"1.38.0CommandID": "1"

But when I launch homebridge I get this error:
`[2018-7-26 21:03:59] Loaded config.json with 2 accessories and 0 platforms.
[2018-7-26 21:03:59] ---
[2018-7-26 21:03:59] Loaded plugin: homebridge-http-jeedom
[2018-7-26 21:03:59] Registering accessory 'homebridge-http-jeedom.HttpJeedom'
[2018-7-26 21:03:59] ---
[2018-7-26 21:03:59] Loading 0 platforms...
[2018-7-26 21:03:59] Loading 2 accessories...
[2018-7-26 21:03:59] [Salon Volet Roulant] Initializing HttpJeedom accessory...
/usr/lib/node_modules/homebridge/lib/server.js:411
  if (!(services[0] instanceof Service)) {
                ^

TypeError: Cannot read property '0' of undefined
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:411:17)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

Can you help me?
Thanks in advance,
C.

**Comment by ololobus** [comment]
I guess that there is something wrong with `homebridge-http-jeedom` plugin. Homebridge is trying to locate `UpService`, which you specified in your `config.json` as `"service": "UpService"`, but cannot find it for some reason. Try to read `homebridge-http-jeedom` docs
