### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by avidmills** [nfarina/homebridge#1950]
I am attempting to develop a homebridge platform plugin, but I keep getting stuck on the error in the title of this ticket. As I understand it, when I run homebridge with my plugin the first time, it caches any accessories that get added. When I then run it again the second time, it first loads those accessories, then I go through setup and detect the same accessories are still present, try to add them, and it crashes. How do I prevent this? I assume I need to look in my accessories array and if an accessory is already present, to skip adding it. I didn't see an example of this happening in the example plugin platform. What is the best way to handle this situation? How can I easily compare one accessory to another? 

### Versions
- **Node**:       8.11.3
- **Homebridge**: 0.4.44
- **OS**:         Linux raspberry 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux

### Homebridge Log / Command Output
```
[2018-7-26 22:31:05] [SleepNumber] Found BedSide:  bed0leftSide
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: cabb93da-d16a-41ea-b47d-40c03bec5ed9
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:290:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:472:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at emitOne (events.js:116:13)
    at API.emit (events.js:211:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at SleepNumberPlatform.<anonymous> (/home/pi/Documents/homebridge-sleepiq/index.js:69:16)
    at Array.forEach (<anonymous>)
    at SleepNumberPlatform.<anonymous> (/home/pi/Documents/homebridge-sleepiq/index.js:56:22)
    at Array.forEach (<anonymous>)
    at SleepNumberPlatform.<anonymous> (/home/pi/Documents/homebridge-sleepiq/index.js:50:26)
    at emitNone (events.js:106:13)
    at EventEmitter.emit (events.js:208:7)
    at SleepNumberPlatform.<anonymous> (/home/pi/Documents/homebridge-sleepiq/index.js:208:13)
    at emitNone (events.js:106:13)
    at EventEmitter.emit (events.js:208:7)
    at Request._callback (/home/pi/Documents/homebridge-sleepiq/index.js:194:8)
    at Request.self.callback (/home/pi/Documents/homebridge-sleepiq/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pi/Documents/homebridge-sleepiq/node_modules/request/request.js:1157:10)
```

Thanks for the awesome platform!

**Comment by avidmills** [comment]
Thanks, I figured it would be along that lines. I will give it a try when I get home.

**Comment by pdlove** [comment]
One thing to note is that the UUID that is used by Homebridge is comprised of accessoryType:accessoryName. I believe accessoryType ends up being the platform type name.
This means that if you have a static ID that you are using to build your UUID then a change of the device name will reset the room and triggers based on that device.

I still haven't fixed Smartthings and it currently does it like this:
    var id = uuid.generate(DeviceKeyFromSmartThings);
    Accessory.call(this, this.name, id);

So in my house I have a light called "Bedroom" and, for simplicity, I call my motion detector/temp sensor the same name, "Bedroom". This crashes with a duplicate UUID even though I use the Device Key from the platform.

When homebridge adds it to the HAS bridge, it creates a new accessory based on your original using a new UUID and ignores the one you gave it. The new uuid is based on the accessoryType and the displayname.
This happens here: https://github.com/nfarina/homebridge/blob/0d77bb93d33a7b6e158efe4b4d546636d976d5c7/lib/server.js#L426

The only way around this is to set uuid_base. So the new code from my example above is:
    var id = uuid.generate(DeviceKeyFromSmartThings);
    Accessory.call(this, this.name, id);
    this.uuid_base = id;

There may be an easier way to do this, but this is the only way I've found. Changes can't be made to this mechanism without resetting everyone's devices, so I think education is the only way to handle it.

**Comment by avidmills** [comment]
> When homebridge adds it to the HAS bridge, it creates a new accessory based on your original using a new UUID and ignores the one you gave it. 

Why do we supply a UUID at all then, if the platform disregards it? Also, shouldn't you not get a crash because of accessoryType? A lightbulb is certainly a different accessory from a motion detector/temp sensor?

**Comment by pdlove** [comment]
I may have missed my explanation... AccessoryType is a holdover from before platforms were introduced to homebridge. It gets populated with the Platform name. So in my case it is trying SmartThings:Bedroom for both devices. I agree it's silly that it disregards it. I'm sure there's a reason but it's an issue at the core and those are the hardest things to change. Anyone else who have been with this project longer than I know why it was done this way and if there is any other solution?
Until then... make sure to set uuid_base on the accessory to your UUID so you can influence the final UUID directly.
