### ISSUE TITLE
Updated NPM now Homebridge won't run!

### ISSUE THREAD

**Issue by samsonrosen** [nfarina/homebridge#1953]
Hi! I ran the command:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

The version is now:

```
node -v
v10.6.0
```

And now when I run homebridge I am seeing these errors:

```
UNKNOWN:~ churchserver$ sudo homebridge -I
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'mdns'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
UNKNOWN:~ churchserver$ 
```

When I run the following commands I get:

```
UNKNOWN:~ churchserver$ sudo npm rebuild

> caporal@0.10.0 postinstall /Users/churchserver/node_modules/caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0


> spawn-sync@1.0.15 postinstall /Users/churchserver/node_modules/spawn-sync
> node postinstall


> curve25519-n2@1.1.3 install /Users/churchserver/node_modules/curve25519-n2
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/curve/node_curve.o
In file included from ../node_curve.cc:13:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../node_curve.cc:13:
../../nan/nan.h:820:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../node_curve.cc:13:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../node_curve.cc:13:
../../nan/nan.h:848:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../node_curve.cc:13:
../../nan/nan.h:1451:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/churchserver/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/curve/node_curve.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/churchserver/node_modules/curve25519-n2
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n2@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/churchserver/.npm/_logs/2018-08-01T11_06_06_865Z-debug.log
UNKNOWN:~ churchserver$ 
```

```
UNKNOWN:~ churchserver$ sudo npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/churchserver/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/churchserver/package.json'
npm WARN churchserver No description
npm WARN churchserver No repository field.
npm WARN churchserver No README data
npm WARN churchserver No license field.

audited 2131 packages in 4.66s
found 63 vulnerabilities (13 low, 40 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
UNKNOWN:~ churchserver$ sudo npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/churchserver/.npm/_logs/2018-08-01T11_07_06_248Z-debug.log
```

**Comment by poudenes** [comment]
Yesterday had the same and did follow:

sudo npm uninstall npm -g
rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/npm*

Reinstalled nodejs and npm and after that reinstalled homebridge worked for me

**Comment by bittles** [comment]
> Yesterday had the same and did follow:

sudo npm uninstall npm -g
rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/npm*

Reinstalled nodejs and npm and after that reinstalled homebridge worked for me
> 

I had this same problem, and ended on this same solution.  Worked great.
