### ISSUE TITLE
can't get homebridge to launch with my config.json

### ISSUE THREAD

**Issue by ldhall1856** [nfarina/homebridge#1964]
here is the error i have

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ tel:031-45-154 │     
    └────────────┘     
                       
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:127:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:403:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:274:11
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)

config.json

{

	"bridge": {

		"name": "Homebridge",

		"username": "CC:22:3D:E3:CE:30",

		"port": 51826,

		"pin": "tel:031-45-154"

	},

	"accessories": [{
		"accessory": "TuyaOutlet",
		"name": "Lukes Outlet",
		"ip": "192.168.3.127",
		"devId": "042004836001947ec787",
		"localKey": "e3d4737e14483141"
	}, {
		"accessory": "TuyaOutlet",
		"name": "Kourtney Outlet",
		"ip": "192.168.3.126",
		"devId": "0420005168c63a99f181",
		"localKey": "e417a3cd35e31f68"
	}, {
		"accessory": "TuyaOutlet",
		"name": "Den Outlet",
		"ip": "192.168.3.125",
		"devId": "0420005168c63a99f187",
		"localKey": "63a2e6d7ee9822c8"
	}, {
		"accessory": "TuyaOutlet",
		"name": "Kitchen",
		"ip": "192.168.3.111",
		"devId": "03200329b4e62d0cbf38",
		"localKey": "d518e3ebbcaaf8c0"
	}, {
		"accessory": "TuyaOutlet",
		"name": "Extra 1",
		"ip": "192.168.3.103",
		"devId": "03200329b4e62d0c9cae",
		"localKey": "65773d608be987f7"
	}, {
		"accessory": "TuyaOutlet",
		"name": "Extra 2",
		"ip": "192.168.3.118",
		"devId": "03200329b4e62d0c9b39",
		"localKey": "ff01264a04e4f26c"
	}, {
		"accessory": "TuyaOutlet",
		"name": "Extra 3",
		"ip": "192.168.3.119",
		"devId": "03200329b4e62d0c94eb",
		"localKey": "a8955b344fd509e7"
	}
],
	"platforms": [{

		"platform": "Nest",

		"clientId": "16a31a3b-c6d3-4c96-9e1a-5950075e58be",

		"clientSecret": "nZ3VyI2drGp8LycM2PL90cswg",

		"code": "77UV3BWM"

	}, {

		"platform": "AssureLink2",

		"username": "e-mail",

		"password": "password"

	}]

}

**Comment by goedh452** [comment]
This means the port is already in use, probably by another homebridge process. Check if homebridge is already running with "ps -ef | grep homebridge". Kill the homebridge proces(ses) with "sudo kill -9 <procesid>".

**Comment by ldhall1856** [comment]
That fixed the port issue. but now when i try to add the accessory it says its "Accessory not ready"

I'm up to date on all updates... Homebridge, nodes, plugin etc....

**Comment by ldhall1856** [comment]
when i try to add it manually it says "the setup code is incorrect"

**Comment by goedh452** [comment]
Is this error about the Nest module? Because I do not own a nest and can’t help you with that other than that de installation of the nest module requires some specific steps. Maybe someone owning a nest can help.

**Comment by Partizan7676** [comment]
Accessory not ready? Just give another name for bridge. For example Homebridge2018

**Comment by ream88** [comment]
One issue I see is that your pin is `"tel:031-45-154"` which is a URI for a phone number. Looks like copy & paste from a browser did mess with this. Changing it to `"031-45-154"` (sans the `tel:` protocol) should fix it!
