### ISSUE TITLE
Adding multiple of the the same accessories: "Cannot add a bridged Accessory with the same UUID as another bridged Accessory"

### ISSUE THREAD

**Issue by ayanez17** [nfarina/homebridge#1972]
### Expected Behavior

 I expect to have 4 [mqttlightbulb](https://github.com/ameeuw/homebridge-mqttlightbulb) accessories. When I put just one in the config fie it works. The problem arises when I put more than 1. I get the error described below. I have deleted the cache multiple times ( both accessories and persist folders). Is the problem with how Homebridge deals with accessories of the same type or how the plugin itself creates names/ids etc ?

Any help would be appreciated :)

### Versions

- **Homebridge**: `0.4.44`
- **Node**:       `v8.11.4`
- **OS**:        ` Raspberry P 3 model B`

### Configuration

```
{

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
    "platforms": [],
    "accessories": [{
        "accessory": "mqttlightbulb",
        "name": "Shelf Light 1",
        "url": "http://localhost",
        "username": "",
        "password": "",
        "caption": "<label>",
        "topics": {
            "getOn": "light1/report/status",
            "setOn": "light1/status",
            "getBrightness": "light1/report/brightness",
            "setBrightness": "light1/brightness",
            "getHue": "light1/report/hue",
            "setHue": "light1/hue",
            "getSaturation": "light1/report/saturation",
            "setSaturation": "light1/saturation"
        }
    },
    {
        "accessory": "mqttlightbulb",
        "name": "Shelf Light 2",
        "url": "http://localhost",
        "username": "",
        "password": "",
        "caption": "<label>",
        "topics": {
            "getOn": "light2/report/status",
            "setOn": "light2/status",
            "getBrightness": "light2/report/brightness",
            "setBrightness": "light2/brightness",
            "getHue": "light2/report/hue",
            "setHue": "light2/hue",
            "getSaturation": "light2/report/saturation",
            "setSaturation": "light2/saturation"
        }
    },
                    {
        "accessory": "mqttlightbulb",
        "name": "Shelf Light 3",
        "url": "http://localhost",
        "username": "",
        "password": "",
        "caption": "<label>",
        "topics": {
            "getOn": "light3/report/status",
            "setOn": "light3/status",
            "getBrightness": "light3/report/brightness",
            "setBrightness": "light3/brightness",
            "getHue": "light3/report/hue",
            "setHue": "light3/hue",
            "getSaturation": "light3/report/saturation",
            "setSaturation": "light3/saturation"
        }
    },
                    {
        "accessory": "mqttlightbulb",
        "name": "Shelf Light 3",
        "url": "http://localhost",
        "username": "",
        "password": "",
        "caption": "<label>",
        "topics": {
            "getOn": "light4/report/status",
            "setOn": "light4/status",
            "getBrightness": "light4/report/brightness",
            "setBrightness": "light4/brightness",
            "getHue": "light4/report/hue",
            "setHue": "light4/hue",
            "getSaturation": "light4/report/saturation",
            "setSaturation": "light4/saturation"
        }
    }]
}
```

### Homebridge Log / Command Output

```
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 53ee2e66-082a-404b-869b-a6b85f7a321f
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:300:18)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by ayanez17** [comment]
ugh.  I had two accessories names `Shelf Light 3` Sorry
