### ISSUE TITLE
Error: 'Unexpected String in JSON' When Running Homebridge for the first time (Solved), Update: Firebase Error

### ISSUE THREAD

**Issue by lamb00** [nfarina/homebridge#1976]
Hi,

I'm using a Rasperry Pi to run Homebridge, both of which I have very little experience using. I have gotten far enough along to install Homebridge on the Pi and create (what I thought was) a usable config.json. So far I've only tried to set up Homebridge with Nest.

When I run Homebridge though, this is what I get in Terminal:

`[2018-8-22 03:46:48] There was a problem reading your config.json file.
[2018-8-22 03:46:48] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-8-22 03:46:48] 
/opt/nodejs/lib/node_modules/homebridge/lib/server.js:213
    throw err;
    ^

SyntaxError: Unexpected string in JSON at position 414
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:207:19)
    at new Server (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/opt/nodejs/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)`

I have validated the code at the site it suggests, and I even manually counted the characters to position 414 to try to find the error in my config.json (maybe that was not what it meant, I'm not sure) which is below:

`{
  "bridge": {
    "name": "Homebridge",
    "username": "(*****************)",
    "port": 45525,
    "pin": "(**********)"
  },
  "description": "SmartHome with Homebridge",
  "accessories": [],
  "platforms": [{
                "platform": "Nest",
                "clientId": "(************************************)",
                "clientSecret": "(*************************)",
                "code": "(********)"
                "token":"c.ZNhmFLfYUqQG71OVyOpy3f0EZoZjYxlFl57zNN7PksA67gVqzy6gi6RLVdfttj1MmnJz8u118RsEDdEQAQFk0FxcbLqIRVrcEJSiAPQi6q8QV6wLVGNlP23lmOWUteXNI64Vp3uQBfb94fKy"
        }]
}`

(I'm not sure if it's necessary, but I removed the User, Pin, ID, Secret, and Code for privacy reasons, but the number of asterisks corresponds to the actual number of characters. I left the Token because "Position 414" is somewhere in there. If these changes prevent someone from helping me, please let me know)

I've spent many hours on this, but I'm stumped. Please help, and please know that I am new to coding so I may need a more in-depth description than a seasoned user. Thanks.

Ps. Sorry for the poor code formatting in this post. I couldn't figure out how to properly insert it. I'm a total newb...

**Comment by lamb00** [comment]
@Apollon77 Thanks, that worked.

Another issue now: Homebridge runs, but after fetching the nest devices and loading accessories, I get this error:

`[Nest] [NestFirebase] Disconnect Detected`

Tried looking up a solution, but I haven't found one yet. Any ideas?

**Comment by lamb00** [comment]
Nevermind, I figured out the Firebase error. I had to make sure I was using the primary nest account as the developer account, not a secondary account.
