### ISSUE TITLE
Can connect, but not control Harmony remote

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#198]
When I run homebridge, it connects to my harmony remote and gets a list of activities. However, I can't control any of the activities from the Insteon+ app and therefore from Siri. If I tell it to turn on the AppleTV activity, for example, I get this:

```
[Living Room] Set activity AppleTV power state to true
  harmonyhubjs:client:harmonyclient start activity 6950501 +2ms
  harmonyhubjs:client:harmonyclient request with command "startactivity" with body activityId=6950501:timestamp=1443038697596 +0ms
  harmonyhubjs:client:harmonyclient buildCommandIqStanza for command "startactivity" with body activityId=6950501:timestamp=1443038697596 +0ms
```
And it shows as On in the app, but nothing actually turns on.

**Comment by fitzage** [comment]
Well, that was the way things used to be, and now homebridge has started throwing this error shortly after launch (maybe related to switching to the Elgato Eve app?)

```
/Users/fitzage/Source/homebridge/platforms/LogitechHarmony.js:165
    if (this.isActivity) {
            ^

TypeError: Cannot read property 'isActivity' of undefined
    at LogitechHarmonyAccessory.getPowerState (/Users/fitzage/Source/homebridge/platforms/LogitechHarmony.js:165:13)
    at Characteristic.<anonymous> (/Users/fitzage/Source/homebridge/node_modules/HAP-NodeJS/lib/AccessoryLoader.js:163:7)
    at emitTwo (events.js:87:13)
    at Characteristic.emit (events.js:172:7)
    at Characteristic.getValue (/Users/fitzage/Source/homebridge/node_modules/HAP-NodeJS/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/Users/fitzage/Source/homebridge/node_modules/HAP-NodeJS/lib/Accessory.js:438:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/Users/fitzage/Source/homebridge/node_modules/HAP-NodeJS/lib/Accessory.js:410:8)
    at emitThree (events.js:97:13)
    at HAPServer.emit (events.js:175:7)
```

**Comment by KraigM** [comment]
I know you are on the other item ( #299 ) but if that fixes this issue then we should close this out

**Comment by fitzage** [comment]
Yes, #299 fixes the crashing problem and also actually works to control my harmony.
