### ISSUE TITLE
Developing plugin, the requested platform was not registered by any plugin.

### ISSUE THREAD

**Issue by petaren** [nfarina/homebridge#1980]
I'm developing a custom plugin. 

I've created an `index.js` file and a `package.json` that I've put in a folder. 

In the `index.js` file, in the `module.exports`, I've defined the plugin as such:
`homebridge.registerAccessory("homebridge-gate", "Gate", Gate);`.

My `config.json` looks like such:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file",

    "platforms": [
        {
            "platform": "homebridge-gate"
        }
    ]
}
```

When I try to run `homebridge -D -U .` from within the same folder as I have my plugin I get the following response:

```
$homebridge -D -P .
[2018-8-25 16:17:19] Loaded config.json with 0 accessories and 1 platforms.
[2018-8-25 16:17:19] ---
[2018-8-25 16:17:19] Loaded plugin: Homebridge-gate
[2018-8-25 16:17:19] Registering accessory 'homebridge-gate.Gate'
[2018-8-25 16:17:19] ---
[2018-8-25 16:17:19] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:128
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'homebridge-gate.Gate' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:128:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I cannot understand why it doesn't want to load my plugin. It seems as if it finds it considering it prints the lines:
```
Loaded plugin: Homebridge-gate
Registering accessory 'homebridge-gate.Gate'
``` 

I've also tried installing my plugin by executing `npm install -g` from within the folder where my plugin is installed. Same results. 

I'm going to run this from a RPi ultimately but am debugging on my mac now. Same results on both machines. Any ideas?

**Comment by petaren** [comment]
I figured it out. I was supposed to load an accessory in the `config.json` and not a platform. My bad.
