### ISSUE TITLE
Homebridge won't start, I get no errors and can't uninstall/re-install Homebridge

### ISSUE THREAD

**Issue by leebutler** [nfarina/homebridge#2000]
I seem to be stuck. Suddenly Homekit could not connect to Homebridge (yesterday it worked, today it doesn't and nothing changed...) This install has been in place for a couple of years, but updated as needed...
I unload/load HomeBridge after renaming homebrige.log and homebridge-errors.log and get both files created but empty. I do a "ps -A | grep homebridge" and nothing but the grep process comes back. HomeKit can't connect to HomeBridge. Strangely, launchctl load says it is already loaded...

I updated npm and same results. I even went through the install instructions again and still same results.

I decided to uninstall everything and start over, but now I can't remove npm...
I get:
sudo npm -g uninstall npm
module.js:471
    throw err;
    ^

Error: Cannot find module 'strip-ansi'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/wide-align/node_modules/string-width/index.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any tips?

**Comment by leebutler** [comment]
I found a native plug-in for Indigo (HomeKit Bridge) that uses homebridge under the covers an that is working without my managing homebridge myself so I have switched...
