### ISSUE TITLE
Compile Issue [ The module was compiled against a different Node.js version using NODE_MODULE_VERSION 48. This version of Node.js requires NODE_MODULE_VERSION 57.]

### ISSUE THREAD

**Issue by cbgroves** [nfarina/homebridge#2001]
Hi All,

I was able to get homebridge installed and the wemo plugin added on a fresh raspbian install on a raspberrypi. My issue came up when I tried to add the Nest plugin. Evidently, I hadn't fully updated node.js when I started the process, and the nest plugin required a higher version. So, I updated node and now I can't get homebridge to launch. 

When trying to start homebridge, I instead get the following error:

/opt/node/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/opt/node/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/opt/node/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

I've tried the rebuild and reinstall as it suggests, with no luck. I've tried uninstalling all plugins, with no luck. And I've tried uninstalling homebridge and reinstalling using:

sudo npm uninstall -g homebridge
sudo npm install -g --unsafe-perm homebridge

With no luck. Any help would be appreciated!

### Versions
- **Homebridge**: will not start to run command
- **Node**:       8.11.1
- **OS**:         PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

**Comment by Apollon77** [comment]
Did you Upgrade your nodejs? Then you need to do a „npm rebuild“ to recompile the native part.

**Comment by cbgroves** [comment]
Yes, I upgraded nodejs and also run the "npm rebuild" as I indicated above. Other ideas?

**Comment by Mkohm** [comment]
I had the exact same issue. After uninstalling node completely and then reinstalling everything - it worked out nice.
