### ISSUE TITLE
HomeBridge Crashing on Start Up - TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by playcaststeffen** [nfarina/homebridge#2003]
We setting up HomeBridge for the first time and installing the MyQ Chamberlain Garage Door plugin HomeBridge crashes on start up with this error:

`[2018-9-17 22:22:18] Loaded config.json with 1 accessories and 1 platforms.
[2018-9-17 22:22:18] ---
[2018-9-17 22:22:18] No plugins found. See the README for information on installing plugins.
[2018-9-17 22:22:18] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)`

This is my config.json file (I started out username and password):

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": " ",

    "accessories": [{
        
        "accessory": "Chamberlain",
        "name": "Garage Door",
        "username": "********@gmail.com",
        "password": "*********"

    }],

    "platforms": [{

    }]
}`

**Comment by Apollon77** [comment]
Try 

...
platforms:  []

Instead of an empty platform

**Comment by playcaststeffen** [comment]
I am getting this error now:


[2018-9-18 06:39:44] No plugins found. See the README for information on installing plugins.
[2018-9-18 06:39:44] Loading 0 platforms...
[2018-9-18 06:39:44] Loading 1 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Chamberlain' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by cps5155** [comment]
Have you installed the [homebridge-chamberlain plugin](https://www.npmjs.com/package/homebridge-chamberlain) via npm ? That error looks like it sees the accessory you're requesting in the config but doesn't know what to do with it since it doesn't have the plugin. 
```npm i homebridge-chamberlain```

**Comment by playcaststeffen** [comment]
Yes I did. I already tried running it again and another time with sudo.
