### ISSUE TITLE
Updating homebridge 0.4.44 to 0.4.45 glitch MacOS

### ISSUE THREAD

**Issue by bdii** [nfarina/homebridge#2008]
### Expected Behavior

Update from homebridge 0.4.44 to 0.4.45

### Current Behavior

Used npm to update, says successfully updated
—version returns 0.4.45
But loading homebridge-hue plugin returns error says version is 0.4.44
Package.json file in homebridge directory also says 0.4.44 

### Versions

- **Homebridge**: `0.4.45`
- **Node**:       `8.12`
- **OS**:         MacOS 10.13.6
-**npm**:        ‘6.4.1’
### Configuration

```json

```

### Homebridge Log / Command Output

```
[2018-9-23 14:06:34] ERROR LOADING PLUGIN homebridge-hue:
[2018-9-23 14:06:34] Error: Plugin /usr/local/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.45 which does not satisfy the current HomeBridge version of 0.4.44. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/Users/brianpauldalrymple/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/Users/brianpauldalrymple/node_modules/homebridge/lib/server.js:148:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/Users/brianpauldalrymple/node_modules/homebridge/lib/server.js:140:22)
    at new Server (/Users/brianpauldalrymple/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/Users/brianpauldalrymple/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/Users/brianpauldalrymple/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
``.

**Comment by ebaauw** [comment]
In my experience `npm update` doesn’t always do what you expect.  Not sure, but I think it might be related to a major version of `0`.  Instead, do an `npm install` to update an installed package.

**Comment by bdii** [comment]
Thanks tried just installing homebridge with npm. Same result —version shown as 0.4.45, but homebridge-hue plugin loading returns the same error for the wrong version of homebridge. Homebridge package.json not updated to 0.4.45.

Sent from my iPad

On 23 Sep 2018, at 17:07, Erik Baauw <notifications@github.com<mailto:notifications@github.com>> wrote:


In my experience npm update doesn’t always do what you expect. Not sure, but I think it might be related to a major version of 0. Instead, do an npm install to update an installed package.

**Comment by ebaauw** [comment]
Sounds like you have installed homebridge multiple times, maybe locally and globally?  Did you start homebridge manually after the update?

**Comment by ebaauw** [comment]
Best install homebridge and all plugins globally by `sudo npm -g i homebridge --unsafe-perm`.  On macOS, this installs the (link to the) homebridge executable to `/usr/local/bin`, and the plugins to `/usr/local/lib/node_modules`.
