### ISSUE TITLE
Don,t start in service 

### ISSUE THREAD

**Issue by maimbe** [nfarina/homebridge#2014]
Hi,

I have homebridge in PI with ubuntu 18.04, and worked for few days, but now i have this messenger in log:

Sep 27 22:54:54 raspberry systemd[1]: Started Node.js HomeKit Server.
Sep 27 22:54:59 raspberry homebridge[5691]: [9/27/2018, 10:54:59 PM] Loaded config.json with 3 accessories and 0 platforms.
Sep 27 22:54:59 raspberry homebridge[5691]: [9/27/2018, 10:54:59 PM] ---
Sep 27 22:54:59 raspberry homebridge[5691]: [9/27/2018, 10:54:59 PM] Loaded plugin: homebridge-homesung
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] Registering platform 'homebridge-homesung.SamsungTV'
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] ---
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] Loaded plugin: homebridge-http
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] Registering accessory 'homebridge-http.Http'
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] ---
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] Loaded plugin: homebridge-http-motion-sensor
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] Registering accessory 'homebridge-http-motion-sensor.http-motion-sensor'
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] ---
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] Loading 3 accessories...
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] [luzQuarto] Initializing Http accessory...
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] [Sensor] Initializing Http accessory...
Sep 27 22:55:00 raspberry homebridge[5691]: [9/27/2018, 10:55:00 PM] [SensorQuarto] Initializing http-motion-sensor accessory...
Sep 27 22:55:00 raspberry homebridge[5691]: Fri, 28 Sep 2018 01:55:00 GMT Accessory [Home Bruneras] Creating new AccessoryInfo for our HAP server
Sep 27 22:55:00 raspberry homebridge[5691]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:480
Sep 27 22:55:00 raspberry homebridge[5691]:             throw e;
Sep 27 22:55:00 raspberry homebridge[5691]:             ^
Sep 27 22:55:00 raspberry homebridge[5691]: Error: ENOSPC: no space left on device, write
Sep 27 22:55:00 raspberry homebridge[5691]:     at Object.fs.writeSync (fs.js:735:20)
Sep 27 22:55:00 raspberry homebridge[5691]:     at Object.fs.writeFileSync (fs.js:1309:24)
Sep 27 22:55:00 raspberry homebridge[5691]:     at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:476:16)
Sep 27 22:55:00 raspberry homebridge[5691]:     at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:277:14)
Sep 27 22:55:00 raspberry homebridge[5691]:     at Object.nodePersist.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:99:29)
Sep 27 22:55:00 raspberry homebridge[5691]:     at AccessoryInfo.save (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:165:11)
Sep 27 22:55:00 raspberry homebridge[5691]:     at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:543:23)
Sep 27 22:55:00 raspberry homebridge[5691]:     at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:128:16)
Sep 27 22:55:00 raspberry homebridge[5691]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:97:10)
Sep 27 22:55:00 raspberry homebridge[5691]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
Sep 27 22:55:00 raspberry systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 22:55:00 raspberry systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by maimbe** [comment]
Resolved!!

No space in device! I use other HD and now just ok!!

Thx!!
