### ISSUE TITLE
Update Node.js v11.0.0 and doesn't work

### ISSUE THREAD

**Issue by fradser-cambodia** [nfarina/homebridge#2044]
### Expected Behavior

Start `homebridge`.

### Current Behavior

Doesn't work.

### Versions

- **Homebridge**: `0.4.45`
- **Node**:       `v11.0.0`
- **OS**:         macOS 10.14 (18A391)

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "",

    "accessories": [
      {
        "accessory": "AirVisual",
        "name": "Air Quality",
        "api_key": "",
        "sensor": "air_quality",
        "aqi_standard": "us",
        "latitude": 11.549042,
        "longitude": 104.921762,
        "city": "",
        "state": "",
        "country": "",
        "ppb_units": ["no2", "o3", "so2"],
        "polling": false,
        "https": true
      },
      {
        "accessory": "AirVisual",
        "name": "Humidity",
        "api_key": "",
        "sensor": "humidity",
        "aqi_standard": "us",
        "latitude": 11.549042,
        "longitude": 104.921762,
        "city": "",
        "state": "",
        "country": "",
        "ppb_units": ["no2", "o3", "so2"],
        "polling": false,
        "https": true
      },
      {
        "accessory": "AirVisual",
        "name": "Temperature",
        "api_key": "",
        "sensor": "temperature",
        "aqi_standard": "us",
        "latitude": 11.549042,
        "longitude": 104.921762,
        "city": "",
        "state": "",
        "country": "",
        "ppb_units": ["no2", "o3", "so2"],
        "polling": false,
        "https": true
      }
    ],

    "platforms": [
    ]
}
```

### Homebridge Log / Command Output

```
○ → homebridge
/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n/build/Release/curve.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n/index.js:1:96)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
```

**Comment by fradser-cambodia** [comment]
@Apollon77 Cool.

```
○ → cd  /usr/local/lib/node_modules/homebridge
○ → npm rebuild
```
Works.

**Comment by fradser-cambodia** [comment]
But `npm rebuild` gets some warnings:

```
○ → npm rebuild

> ed25519-hap@0.0.5 install /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap
> node-gyp rebuild

  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
In file included from ../src/ed25519.cc:4:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2537:3: note: 'ToString' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:19:89: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        if ((info.Length() < 1) || (!Buffer::HasInstance(info[0])) || (Buffer::Length(info[0]->ToObject()...
                                                                                               ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:22:68: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        const unsigned char* seed = (unsigned char*)Buffer::Data(info[0]->ToObject());
                                                                          ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:53:60: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        if ((info.Length() < 2) || (!Buffer::HasInstance(info[0]->ToObject()))) {
                                                                  ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:56:65: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        if ((Buffer::HasInstance(info[1])) && (Buffer::Length(info[1]->ToObject()) == 32)) {
                                                                       ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:57:63: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
                unsigned char* seed = (unsigned char*)Buffer::Data(info[1]->ToObject());
                                                                            ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:65:72: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        } else if ((Buffer::HasInstance(info[1])) && (Buffer::Length(info[1]->ToObject()) == 64)) {
                                                                              ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:66:54: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
                privateKey = (unsigned char*)Buffer::Data(info[1]->ToObject());
                                                                   ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:68:44: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
                Local<Value> privateKeyBuffer = info[1]->ToObject()->Get(Nan::New<String>("privateKey").T...
                                                         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:68:110: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ...privateKeyBuffer = info[1]->ToObject()->Get(Nan::New<String>("privateKey").ToLocalChecked())->ToObject();
                                                                                                   ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:76:36: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Handle<Object> message = info[0]->ToObject();
                                          ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:101:60: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        if ((info.Length() < 3) || (!Buffer::HasInstance(info[0]->ToObject())) ||
                                                                  ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:102:34: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
                (!Buffer::HasInstance(info[1]->ToObject())) || (!Buffer::HasInstance(info[2]->ToObject()))) {
                                               ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:102:81: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
                (!Buffer::HasInstance(info[1]->ToObject())) || (!Buffer::HasInstance(info[2]->ToObject()))) {
                                                                                              ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:105:36: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Handle<Object> message = info[0]->ToObject();
                                          ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:106:38: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Handle<Object> signature = info[1]->ToObject();
                                            ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/ed25519.cc:107:38: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Handle<Object> publicKey = info[2]->ToObject();
                                            ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
17 warnings generated.
  SOLINK_MODULE(target) Release/ed25519.node

> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

  CXX(target) Release/obj.target/curve/node_curve.o
In file included from ../node_curve.cc:10:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2537:3: note: 'ToString' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../node_curve.cc:18:70: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned char* arg0 = (unsigned char*) node::Buffer::Data(info[0]->ToObject());
                                                                     ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../node_curve.cc:19:70: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned char* arg1 = (unsigned char*) node::Buffer::Data(info[1]->ToObject());
                                                                     ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../node_curve.cc:20:70: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned char* arg2 = (unsigned char*) node::Buffer::Data(info[2]->ToObject());
                                                                     ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/FradSer-KH/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
4 warnings generated.
  SOLINK_MODULE(target) Release/curve.node
chalk@1.1.3 /usr/local/lib/node_modules/homebridge/node_modules/chalk
ansi-styles@2.2.1 /usr/local/lib/node_modules/homebridge/node_modules/ansi-styles
escape-string-regexp@1.0.5 /usr/local/lib/node_modules/homebridge/node_modules/escape-string-regexp
has-ansi@2.0.0 /usr/local/lib/node_modules/homebridge/node_modules/has-ansi
ansi-regex@2.1.1 /usr/local/lib/node_modules/homebridge/node_modules/ansi-regex
strip-ansi@3.0.1 /usr/local/lib/node_modules/homebridge/node_modules/strip-ansi
supports-color@2.0.0 /usr/local/lib/node_modules/homebridge/node_modules/supports-color
commander@2.8.1 /usr/local/lib/node_modules/homebridge/node_modules/commander
graceful-readlink@1.0.1 /usr/local/lib/node_modules/homebridge/node_modules/graceful-readlink
ed25519-hap@0.0.5 /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap
bindings@1.3.0 /usr/local/lib/node_modules/homebridge/node_modules/bindings
nan@2.11.1 /usr/local/lib/node_modules/homebridge/node_modules/nan
hap-nodejs@0.4.47 /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs
bonjour-hap@3.5.1 /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap
array-flatten@2.1.1 /usr/local/lib/node_modules/homebridge/node_modules/array-flatten
deep-equal@1.0.1 /usr/local/lib/node_modules/homebridge/node_modules/deep-equal
dns-equal@1.0.0 /usr/local/lib/node_modules/homebridge/node_modules/dns-equal
dns-txt@2.0.2 /usr/local/lib/node_modules/homebridge/node_modules/dns-txt
buffer-indexof@1.1.1 /usr/local/lib/node_modules/homebridge/node_modules/buffer-indexof
multicast-dns@6.2.3 /usr/local/lib/node_modules/homebridge/node_modules/multicast-dns
dns-packet@1.3.1 /usr/local/lib/node_modules/homebridge/node_modules/dns-packet
ip@1.1.5 /usr/local/lib/node_modules/homebridge/node_modules/ip
safe-buffer@5.1.2 /usr/local/lib/node_modules/homebridge/node_modules/safe-buffer
thunky@1.0.3 /usr/local/lib/node_modules/homebridge/node_modules/thunky
multicast-dns-service-types@1.1.0 /usr/local/lib/node_modules/homebridge/node_modules/multicast-dns-service-types
buffer-shims@1.0.0 /usr/local/lib/node_modules/homebridge/node_modules/buffer-shims
curve25519-n@1.4.0 /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
debug@2.6.9 /usr/local/lib/node_modules/homebridge/node_modules/debug
ms@2.0.0 /usr/local/lib/node_modules/homebridge/node_modules/ms
decimal.js@7.5.1 /usr/local/lib/node_modules/homebridge/node_modules/decimal.js
fast-srp-hap@1.0.1 /usr/local/lib/node_modules/homebridge/node_modules/fast-srp-hap
node-persist@0.0.11 /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist
mkdirp@0.5.1 /usr/local/lib/node_modules/homebridge/node_modules/mkdirp
minimist@0.0.8 /usr/local/lib/node_modules/homebridge/node_modules/minimist
q@1.1.2 /usr/local/lib/node_modules/homebridge/node_modules/q
node-persist@0.0.8 /usr/local/lib/node_modules/homebridge/node_modules/node-persist
mkdirp@0.3.5 /usr/local/lib/node_modules/homebridge/node_modules/node-persist/node_modules/mkdirp
qrcode-terminal@0.11.0 /usr/local/lib/node_modules/homebridge/node_modules/qrcode-terminal
semver@5.0.3 /usr/local/lib/node_modules/homebridge/node_modules/semver
```

**Comment by NebzHB** [comment]
i have exactly the same problem, how did you solved the V8_DEPRECATED ? because in my case that leads to error in make :(
