### ISSUE TITLE
Homebridge Install on Centos 7

### ISSUE THREAD

**Issue by chrisolson91** [nfarina/homebridge#2048]
Hey all, 

I'm hoping you can help me out. I have a Centos 7 NAS that i'm trying to install homebridge on. I went through the steps that were discussed and have successfully installed node and npm as well as the linux pre-requisite that was listed. I went to install homebridge though and I get the following errors. It seems like that g++ might be the culprit. Everything i've found though says that g++ is for older version of Centos. GCC seems to be the replacement. I tried installing that but still got the same problems. I'm new to linux so I apologize if these are dumb questions. Here a list of all the errors that were thrown

[olson@localhost ~]$ sudo npm install -g -unsafe-perm homebridge
[sudo] password for olson:
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.4.0 install /usr/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge/node_modules/curve25519-n/build'
  CXX(target) Release/obj.target/curve/node_curve.o
make: g++: Command not found
make: *** [Release/obj.target/curve/node_curve.o] Error 127
make: Leaving directory `/usr/lib/node_modules/homebridge/node_modules/curve25519-n/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-862.14.4.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/curve25519-n
gyp ERR! node -v v6.14.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/lib
└── (empty)

npm ERR! Linux 3.10.0-862.14.4.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "-unsafe-perm" "homebridge"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/olson/npm-debug.log
npm ERR! code 1

**Comment by chrisolson91** [comment]
I figured it out actually...found this post on Gitee. 

https://gitee.com/n233333/homeassistant-and-homebridge-on-Centos-7/blob/master/README.md

I realized I needed to run this command and that seemed to do it. Homebridge is now successfully installed! 

yum install -y gcc-c++ make
