### ISSUE TITLE
Multiple Controllable Devices

### ISSUE THREAD

**Issue by PfliegionOfDoom** [nfarina/homebridge#2062]
I've successfully installed homebridge and the homebridge-chamberlain plugin.  When running homebridge I'm receiving the following error:

[2018-11-12 10:48:26] Homebridge is running on port 51826.
[2018-11-12 10:48:26] [Garage] Error: Multiple controllable devices found: 3952823, 3952824
    at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:78:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

This is my config.json file (which validates successfully in jsonlint.com)
{
"bridge": {
"name": "MyHomebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"accessories": [
"accessory": "Chamberlain",
"name": "Garage Door",
"username": "email_address",
"password": "password"
}
]
}

Has anyone seen this message?  Any help would be greatly appreciated!

**Comment by samutang** [comment]
I had the same issue and found a solution from the post below. My garage door works fine now.

https://github.com/caseywebdev/homebridge-chamberlain/issues/33
