### ISSUE TITLE
Cannot read property 'indexOf' of undefined please help

### ISSUE THREAD

**Issue by TangoTaker** [nfarina/homebridge#2080]
Hello, after I changed the config to include the Mi Aqara platform, I always get the same Error:

/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {

When I remove the Aqara platform everything works as expected again. Please help, I am rather new to homebridge. 

```
Config:

{
    "bridge": {
        "name": "Homebridge",
        "username": "C0:A8:B2:3A:CE:33",
        "port": 51826,
        "pin": "111-11-111"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "platforms": [
        {
            "platform": "Hue",
            "host": "192.168.178.58",
            "name": "homebridge-hue(MP)",
            "users": {
                "*****************censored**********************"
            },
            "lights": true
        },
        {
            "platform": "DoorBird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird_ip": "192.168.178.223",
                    "doorbird_username": "censored",
                    "doorbird_password": "censored",
                    "cmd_doorbell": "",
                    "cmd_motionsensor": "",
                    "videoConfig": {
                        "source": "-re -i rtsp://censored",
                        "stillImageSource": "-i http://censored",
                        "maxStreams": 10,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "port": 5005
                    }
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Kamera Hintereingang",
                    "videoConfig": {
                        "source": "-re -i rtsp://censored",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 180,
                        "maxFPS": 30
                    }
                }
            ]
        },
        {
            "platform": "config",
            "name": "Config",
            "restart": "sudo -n systemctl restart homebridge",
            "port": 8080,
            "sudo": true
        },
{
    "platforms": [{
        "platform": "MiAqaraPlatform",
        "gateways": {
            "6409802da3b3": "02i44k56zrgg578b"
        }
    }]
}
    ]
}

```
```
Output:

[2018-12-7 12:52:54] Loaded config.json with 0 accessories and 5 platforms.
[2018-12-7 12:52:54] ---
[2018-12-7 12:52:55] Loaded plugin: homebridge-camera-ffmpeg
[2018-12-7 12:52:55] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2018-12-7 12:52:55] ---
[2018-12-7 12:52:56] Loaded plugin: homebridge-config-ui-x
[2018-12-7 12:52:56] Registering platform 'homebridge-config-ui-x.config'
[2018-12-7 12:52:56] ---
[2018-12-7 12:52:58] Loaded plugin: homebridge-doorbird
[2018-12-7 12:52:58] Registering platform 'homebridge-doorbird.DoorBird'
[2018-12-7 12:52:58] ---
[2018-12-7 12:53:00] Loaded plugin: homebridge-hue
[2018-12-7 12:53:00] Registering platform 'homebridge-hue.Hue'
[2018-12-7 12:53:00] ---
[2018-12-7 12:53:01] Loaded plugin: homebridge-ifttt
[2018-12-7 12:53:01] Registering platform 'homebridge-ifttt.IFTTT'
[2018-12-7 12:53:01] ---
[2018-12-7 12:53:02] Loaded plugin: homebridge-mi-aqara
[2018-12-7 12:53:02] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2018-12-7 12:53:02] ---
[2018-12-7 12:53:02] Loading 5 platforms...
[2018-12-7 12:53:02] [homebridge-hue(MP)] Initializing Hue platform...
[2018-12-7 12:53:02] [homebridge-hue(MP)] homebridge-hue v0.11.1, node v10.13.0, homebridge v0.4.45
[2018-12-7 12:53:02] [DoorBird] Initializing DoorBird platform...
[2018-12-7 12:53:02] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[2018-12-7 12:53:02] [Config] Initializing config platform...
[2018-12-7 12:53:02] [Config] Spawning homebridge-config-ui-x with PID 11428

/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^
TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

```

**Comment by wittyfans** [comment]
I get the same errors:

`/usr/lib/node_modules/homebridge-mi-aqara/index.js:170
    if(Object.getOwnPropertyNames(hosts).length < Object.getOwnPropertyNames(gateways).length) {
                                                         ^

TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at MiAqaraPlatform.sendWhoisCommand (/usr/lib/node_modules/homebridge-mi-aqara/index.js:170:58)
    at API.<anonymous> (/usr/lib/node_modules/homebridge-mi-aqara/index.js:101:18)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)`

If I delete the config.json file, everything works fine.

**Comment by marianrick** [comment]
@TangoTaker you got two times the „platforms: []“ arrays, nested into each other. 

If you count your lines from the bottom to the top (starting with the first } sign), you should delete the following lines:

4 - containing }]
9 - containing „platforms“: [{

**Comment by TangoTaker** [comment]
@marianrick
Thanks, didnt get that. I will try without the second array soon.

**Comment by TheHomekitWayFinder** [comment]
im getting the same errors.

please not i am running homebridge on macos mojave planning on moving the process to a raspberry pi

here is my config file:

{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "xxx-xx-xxx"
        },

        "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating$

"accessories": [
{
                "accessory": "Xbox",
                "name": "Xbox",
                "ipAddress": "192.168.x.xx",
                "liveId": "xxxxxxxxxxxxxx"
        }
        ],

        "platforms": [
        {


                }

                ]

}

here are the errors homebridge is giving me in the console:
[1/26/2019, 7:53:18 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/26/2019, 7:53:18 PM] ---
[1/26/2019, 7:53:18 PM] Loaded plugin: homebridge-xbox-one
[1/26/2019, 7:53:18 PM] Registering accessory 'homebridge-xbox-one.Xbox'
[1/26/2019, 7:53:18 PM] ---
[1/26/2019, 7:53:18 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

please advise what to do

**Comment by hazemgabdalla** [comment]
I have the same issue after adding the Camera-ffmpeg plugin.
I get this error:
I'm new to Homebridge and I can't get my Hikvision IP cameras to stream on HomeKit. I tried two plugins and several third party software (Security.Spy and Blue Iris) but non work. 
Can someone urgently help me please? Thanks in advance

[7/23/2019, 2:35:50 PM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by ebaauw** [comment]
Fix your config.json.  Make sure each object in the `"accessories"` array has an `"accessory"` key and each object in the `"platforms"` array has a `"platform"` key.

**Comment by hazemgabdalla** [comment]
Thanks ebaauw ....
Would you please help me out more?
I don't know what's a platform key and where to put it in the config file.
Here is my config.json

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"accessories": [],
	"platforms": [
		{
			"platform": "eWeLink",
			"name": "eWeLink",
			"apiHost": "eu-api.coolkit.cc:8080",
			"webSocketApi": "eu-pconnect3.coolkit.cc",
			"email": "xxxxxxxx",
			"password": "xxxxxx",
			"imei": "73C27099-F3D0-4C36-B0DB-78F5806A8E4C"
		},
		{
			"platform": "Camera-IP",
			"cameras": [
				{
					"name": "Entrance",
					"videoConfig": {
						"source": "-re -i http://Hazem:xxxxxx@http://197.51.179.156:81/h264/Entrance/temp.ts",
						"stillImageSource": "-i http://Hazem:xxxxxx@http://197.51.179.156:81/image/Entrance?q=75",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 1024,
						"maxFPS": 15
					}
				}
			]
		},
		{
			"platform": "Camera-ffmpeg",
			"cameras": [
				{
					"name": "Kids",
					"videoConfig": {
						"source": "-i http://admin:xxxxxx@197.51.179.150:8000/++hls?cameraNum=9&codec=h264&width=1280&height=720",
						"stillImageSource": "-i http://admin:xxxxxx@197.51.179.150:8000/++image?cameraNum=9&width=480&height=270",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 30
					}
				}
			]
		},
		{
			"name": "Reception",
			"videoConfig": {
				"source": "-i http://admin:xxxxxx2@197.51.179.150:8000/++hls?cameraNum=0&codec=h264&width=1280&height=720",
				"stillImageSource": "-i http://admin:xxxxxx@197.51.179.150:8000/++image?cameraNum=0&width=480&height=270",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 30
			}
		}
	]
}

**Comment by ebaauw** [comment]
Better start by pasting the contents through a JSON linter, like https://jsonlint.com/ to get a decent layout.

**Comment by hazemgabdalla** [comment]
I already validated the json file.
