### ISSUE TITLE
Raspberry Pi Zero W - Permissions, and wont start

### ISSUE THREAD

**Issue by NagyAttilaORG** [nfarina/homebridge#2088]
Hello!

My fresh install cause some problems again. This is a Raspberry Pi zero W, with latest everything and three plugins with a little config file. My homebridge won't start automatically, but if I write to terminal the DEBUG=* homebridge -D it is working, when I quit the log it shut again.

This is my /etc/default6homebridge file: 

HOMEBRIDGE_OPTS=-U /var/lib/homebridge -D -I

Nothing happened.

When it is runs, it has some permission problem what you could see above.

### Versions

- **Homebridge**: `homebridge --version` : 0.4.45
- **Node**:       `node --version` : v11.4.0
- **OS**:         Latest Rasbian

### Configuration

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "156-45-303"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "MagicHome",
		"name": "TV Led",
		"ip": "10.0.1.4",
		"setup": "RGBW",
		"purewhite": false
	},
	{
		"accessory": "MagicHome",
		"name": "Ágy Led",
		"ip": "10.0.1.40",
		"setup": "RGB",
		"purewhite": false
	}],

	"platforms": [{
			"platform": "SamsungTizen",
			"devices": [{
				"name": "Hálószoba TV",
				"ip": "10.0.1.22",
				"mac": "5c:49:7d:6b:c3:82",
				"switches": [{
						"name": "Hangerő Fel",
						"command": "KEY_VOLUP"
					},
					{
						"name": "Hangerő Le",
						"command": "KEY_VOLDOWN"
					}
				]
			}]
		},
		{
			"platform": "config",
			"name": "Config",
			"port": 8080,
			"sudo": true,
			"restart": "sudo -n systemctl restart homebridge",
			"log": {
				"method": "systemd",
				"service": "homebridge"
			}
		}
	]
}
```

### Homebridge Log / Command Output
-->
```
Error: EACCES: permission denied, mkdir '/var/lib/homebridge'
    at Object.mkdirSync (fs.js:775:3)
    at sync (/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:77:24)
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service hold-off time over, scheduling restart.
Stopped Node.js HomeKit Server.
Started Node.js HomeKit Server.
/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:90
                    throw err0;
```

I'm so bored to install again from the start. This is my second week to tries to work this.

Has someone got any advice?

Thank you guys!

**Comment by NagyAttilaORG** [comment]
I made a mistake in the etc/default/homebridge file:

HOMEBRIDGE_OPTS=-U /var/lib/homebridge -D -I was a bad configuration.

This was the solution:

HOMEBRIDGE_OPTS=-U -D /var/lib/homebridge -I
