### ISSUE TITLE
Problem reading config file

### ISSUE THREAD

**Issue by zlockhart** [nfarina/homebridge#2105]
I checked the config file on jsonlint and its valid. I'm not sure what to do after that. This is the output when running homebridge.

pi@RaspberryPi3:~ $ sudo homebridge
[1/8/2019, 10:22:05 AM] There was a problem reading your config.json file.
[1/8/2019, 10:22:05 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[1/8/2019, 10:22:05 AM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:213
    throw err;
    ^

SyntaxError: Unexpected token 
 in JSON at position 1779
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:207:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
pi@RaspberryPi3:~ $

**Comment by iRayanKhan** [comment]
You mind pasting your config and list of plugins?

**Comment by F4stFr3ddy** [comment]
Not sure why jsonlint said its valid cause obviously it isn't valid given the error `SyntaxError: Unexpected token`. Indeed if you could share the config that would help, but I suggest you re-check the file and copy it again into the the Pi3 making sure its untouched in the mean time.

**Comment by ebaauw** [comment]
Make sure to edit config.json using a plain text editor, see **REALLY IMPORTANT** in 
https://github.com/nfarina/homebridge#installation-details.
