### ISSUE TITLE
homebridge using wrong npm version

### ISSUE THREAD

**Issue by bobisaperson1** [nfarina/homebridge#2108]
### Current Behavior
when installing some plugins it come up with an error saying "npm WARN engine rxjs@5.5.12: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.1","npm":"1.4.21"})" wich then causes a heap of other errors because homebrige says i have npm version 1.4.21 but when i do npm -v it says i have version 6.5.0.

### Versions

- **Homebridge**: `0.4.45 (I think I dont know how to check)`
- **Node**:       `8.11.1`
- **OS**:         armv7

### Homebridge Log / Command Output

```
pi@raspi_nas:~ $ sudo npm install -g node-appletv
(node:16290) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN engine rxjs@5.5.12: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.1","npm":"1.4.21"})
 
> curve25519-n2@1.1.3 install /usr/local/lib/node_modules/node-appletv/node_modules/curve25519-n2
> node-gyp rebuild

|
module.js:549
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-appletv/node_modules/curve25519-n2
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/node-appletv/node_modules/mdns/src'
npm ERR! error rolling back  node-appletv@1.0.10 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/node-appletv/node_modules/mdns/src'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/node-appletv/node_modules/mdns/src' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-appletv"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.11/package.tgz
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> ed25519@0.0.4 install /usr/local/lib/node_modules/node-appletv/node_modules/ed25519
> node-gyp rebuild

path.js:1167
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1167:25)
    at Function.Module._resolveLookupPaths (module.js:424:17)
    at Function.Module._resolveFilename (module.js:541:20)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/bin/node-gyp.js:13:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! tar.unpack untar error /root/.npm/rxjs/5.5.12/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/3.10.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/rx/4.1.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/extend/3.0.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/spawn-sync/1.0.15/package.tgz
npm ERR! tar.unpack untar error /root/.npm/tmp/0.0.29/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/node-appletv/node_modules/caporal/node_modules/tabtab/node_modules/inquirer/node_modules/cli-cursor/node_modules/restore-cursor/node_modules/onetime'
npm ERR! error rolling back  inquirer@1.2.3 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/node-appletv/node_modules/caporal/node_modules/tabtab/node_modules/inquirer/node_modules/cli-cursor/node_modules/restore-cursor/node_modules/onetime'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/node-appletv/node_modules/caporal/node_modules/tabtab/node_modules/inquirer/node_modules/cli-cursor/node_modules/restore-cursor/node_modules/onetime' }
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.11/package.tgz
npm ERR! tar.unpack untar error /root/.npm/onetime/1.1.0/package.tgz
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

```

**Comment by NorthernMan54** [comment]
Looking at your log, this is not a homebridge issue.  Please raise an issue against the package you are attempting to install instead and close this issue.

**Comment by bobisaperson1** [comment]
I put it up here because I have received this error on multiple occasions with multiple plugins.
