### ISSUE TITLE
There was a problem reading my config.json file

### ISSUE THREAD

**Issue by Cy83r5p4c3** [nfarina/homebridge#2109]
I am a novice with programming and i am trying to connect my nest thermostat to homekit via homebridge. I have checked that it is a valid config.json through JSONLint, which it says it is. However, when i run homebridge through terminal, i get this message:

[1/11/2019, 1:01:28 PM] There was a problem reading your config.json file.
[1/11/2019, 1:01:28 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[1/11/2019, 1:01:28 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:214
    throw err;
    ^

SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:208:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Can someone please help me overcome this as i am lost as to how to get it to work. Here is the config.json i am using;

{
--
  | "namespace": "tonesto7",
  | "repoOwner": "tonesto7",
  | "repoName": "nest-manager",
  | "repoBranch": "master",
  | "name": "NST Manager",
  | "author": "Anthony S.",
  | "description": "The Best Solution to integrate your Nest Products into the SmartThings Enviroment.",
  | "category": "My Apps",
  | "bannerUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/nst_manager_5_banner.png",
  | "forumUrl": "https://community.smartthings.com/t/release-nst-manager-v5-0/",
  | "docUrl": "http://thingsthataresmart.wiki/index.php?title=NST_Manager",
  | "releaseType": "production",
  | "keywords": [
  | "nest",
  | "thermostat",
  | "nst",
  | "camera",
  | "protect",
  | "smoke",
  | "carbon",
  | "monoxide"
  | ],
  | "notes": "Nothing to show here (yet)",
  | "smartApps": {
  | "parent": {
  | "name": "Nest Manager",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/nst_manager_5.png",
  | "published": true,
  | "oAuth": true,
  | "version": "5.5.8",
  | "appSettings": {
  | "clientId": "________@me.com",
  | "clientSecret": "__________",
  | "devOpt": "false"
  | },
  | "appUrl": "smartapps/tonesto7/nest-manager.src/nest-manager.groovy"
  | },
  | "children": [{
  | "name": "NST Automations",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/nst_automations_5.png",
  | "published": true,
  | "oAuth": false,
  | "version": "5.4.9",
  | "appSettings": {},
  | "appUrl": "smartapps/tonesto7/nst-automations.src/nst-automations.groovy",
  | "optional": false
  | }]
  | },
  | "deviceHandlers": [{
  | "name": "Nest Thermostat",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/thermostat_icon.png",
  | "published": true,
  | "version": "5.4.4",
  | "appUrl": "deviceTypes/tonesto7/nest-thermostat.src/nest-thermostat.groovy",
  | "optional": false
  | },
  | {
  | "name": "Nest Protect",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/protect_icon.png",
  | "published": true,
  | "version": "5.4.2",
  | "appUrl": "deviceTypes/tonesto7/nest-protect.src/nest-protect.groovy",
  | "optional": false
  | },
  | {
  | "name": "Nest Camera",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/camera_icon.png",
  | "published": true,
  | "version": "5.4.3",
  | "appUrl": "deviceTypes/tonesto7/nest-camera.src/nest-camera.groovy",
  | "optional": false
  | },
  | {
  | "name": "Nest Presence",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/presence_icon.png",
  | "published": true,
  | "version": "5.4.2",
  | "appUrl": "deviceTypes/tonesto7/nest-presence.src/nest-presence.groovy",
  | "optional": true
  | },
  | {
  | "name": "Nest Weather",
  | "iconUrl": "https://raw.githubusercontent.com/tonesto7/nest-manager/master/Images/App/weather_icon.png",
  | "published": true,
  | "version": "5.5.0",
  | "appUrl": "deviceTypes/tonesto7/nest-weather.src/nest-weather.groovy",
  | "optional": true
  | }
  | ]
  | }

Like I said, please help!!!

Thanks

**Comment by W0GER** [comment]
That doesn't look like a config.json file. Please see the sample in the repo
https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by Cy83r5p4c3** [comment]
> That doesn't look like a config.json file. Please see the sample in the repo
> https://github.com/nfarina/homebridge/blob/master/config-sample.json

Ok, so I have changed the config.json. Now it is saying there is a problem with the accessory (not registered by and plugin.

here is what i have it as currently;

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "Nest Thermostat",
    "accessories": [
        {
            "accessory": "Thermostat.Nest",
            "plugin": "Homebridge-nest"
        }
    ],
    "platforms": [
        {
            "platform" : "Nest",
            "name" : "Nest"
        }
    ]
}


This is the message that comes up;

[1/15/2019, 7:08:35 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/15/2019, 7:08:35 PM] ---
[1/15/2019, 7:08:36 PM] Loaded plugin: homebridge-nest
[1/15/2019, 7:08:36 PM] Registering platform 'homebridge-nest.Nest'
[1/15/2019, 7:08:36 PM] ---
[1/15/2019, 7:08:36 PM] Loading 1 platforms...
[1/15/2019, 7:08:36 PM] [Nest] Initializing Nest platform...
[1/15/2019, 7:08:36 PM] [Nest] Fetching Nest devices.
[1/15/2019, 7:08:36 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:70
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Thermostat.Nest' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:70:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Please Help!!!

**Comment by AppleTechy** [comment]
You were pointed in a helpful direction but you must look at the readme docs for the plugins to understand how to set them up. If you look at [Homebridge-Nest's readme file](https://github.com/KraigM/homebridge-nest/blob/master/README.md), it explains to you exactly how you need to have your config file setup. I have included what it should look like below but make sure to read the Homebridge-Nest Readme file as it explains to you how to fill in those values.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [
        {
        }
    ],

    "platforms": [
       {
   		"platform": "Nest",
   		
   		"token" : "token will be generated upon first run of homebridge without a token",
   		
   		"clientId": "developer Product ID",
   		"clientSecret": "developer Product Secret.",
   		"code": "your Pincode from Nest",
   		
   		"username" : "username",
   		"password" : "password"
   	}
    ]
}
```

**Comment by EnriqueSubias** [comment]
Try deleting everything and starting all over again. That worked for me after trying several times.
