### ISSUE TITLE
Homebridge will not start anymore

### ISSUE THREAD

**Issue by Crox77** [nfarina/homebridge#2111]
Hi I am completely new to Homebridge but managed to install everything ok on my Mac using terminal, managed to run it and Pair with my Home app on my iPhone. I then tried writing my config.json files (took me a min to work out how to do) I think I have everything correct now but get this error when trying to run homebridge

[12/01/2019, 17:35:27] There was a problem reading your config.json file.
[12/01/2019, 17:35:27] Please try pasting your config.json file here to validate it: http://jsonlint.com
[12/01/2019, 17:35:27] 
/usr/local/lib/node_modules/homebridge/lib/server.js:214
    throw err;
    ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:208:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

went to the json help page and this is what I got

Error: Parse error on line 11:
...tat",		"username": “user @help.com” "pa
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

Here is my Config file
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
"accessories": [
        {
            "accessory": "HiveThermostat",
            "name": "Hive Thermostat",
            "username": “user@help.com”
            "password": “password”
        }
    ],
any help gratefully received please

Thanks

**Comment by ebaauw** [comment]
There’s a comma missing after the username line, but I think the error is caused by a non-ascii double quote character.  Make sure to use a plain text editor to edit config.json, see 
https://github.com/nfarina/homebridge#installation-details.

**Comment by Crox77** [comment]
Thanks for your help I have sorted it now
