### ISSUE TITLE
Homebridge stops after couple of hours

### ISSUE THREAD

**Issue by Kakoutis** [nfarina/homebridge#2116]
Hi all.

I have installed homebridge on my Raspberry pi Zero W and everything is working as expected for the first couple of hours. 

Then out of a sudden all the devices are unresponsive and I get the following on the logs:

```
[16/01/2019, 09:37:50] [homebridge-tplink-smarthome.TplinkSmarthome] didFinishLaunching
[16/01/2019, 09:37:50] [homebridge-tplink-smarthome.TplinkSmarthome.API] client.startDiscovery({"discoveryInterval":10000,"deviceTypes":[],"deviceOptions":{"timeout":15000},"macAddresses":[],"excludeMacAddresses":[]})
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::52826
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:97:10)
```

Any idea what this might be? I am using Tplinksmarthome and yeelight plugins

Thank you!

**Comment by iRayanKhan** [comment]
Install PM2 and then after doing that make sure:
Homebridge is killed ``` sudo killall HomeBridge```
then do:
pm2 start HomeBridge 
and then do pm2 save
Homebridge will now auto start when crashing.

**Comment by F4stFr3ddy** [comment]
`listen EADDRINUSE :::52826` is this port configured in your config? If so, try a different port as another process is also trying to use it.
