### ISSUE TITLE
Homebridge not starting after power cut

### ISSUE THREAD

**Issue by samsonrosen** [nfarina/homebridge#2136]
I run Homebridge on a Raspberry Pi which has been working splendidly. Running at startup via systemd. We had a power cut this week and now the homebridge service won't startup.

When I run the command:

`systemctl status homebridge`
```
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-01-30 18:51:37 GMT; 3s ago
  Process: 1725 ExecStart=/usr/bin/homebridge (code=exited, status=1/FAILURE)
 Main PID: 1725 (code=exited, status=1/FAILURE)

Jan 30 18:51:37 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 18:51:37 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Jan 30 18:51:37 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

Strangely, if I run NPM commands I now get these errors:

```
pi@raspberrypi:~ $ npm -v
/usr/lib/node_modules/npm/lib/npm.js:3
 "/* globals WScbipt0*/
 ^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:29:13
pi@raspberrypi:~ $ 

```

**Comment by NorthernMan54** [comment]
This log just shows it failing, to figure out why it is failing you need to look at the homebridge log.  The location of the log depends on your os and how you are starting it.
