### ISSUE TITLE
Can’t run homebridge at start on Raspberry if running with -P option

### ISSUE THREAD

**Issue by rnglad** [nfarina/homebridge#2137]
I cant run homebridge without
homebridge -P /home/pi/node_modules
Everything I’ve tried, but only this line works
Whatever I do to run on startup - doesnt work.
PM2 - doesnt let app with options, systemd - the same, just do not know what to do.
My ACs depend on this, but I have to be around everytime the power goes off 😖

**Comment by iRayanKhan** [comment]
@rnglad Send the output and your config please. Make sure to redact sensitive info. Also don't plugins by default go for the Node_Modules/ folder?

**Comment by rnglad** [comment]
if I run homebridge without any options (-P) it gives me this error:
homebridge
[2019-2-4 21:20:04] Loaded config.json with 3 accessories and 0 platforms.
[2019-2-4 21:20:04] ---
[2019-2-4 21:20:04] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-gree-ac' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-gree-ac'.
[2019-2-4 21:20:04] ====================
[2019-2-4 21:20:04] ERROR LOADING PLUGIN homebridge-gree-ac:
[2019-2-4 21:20:04] Error: Cannot find module 'mqtt'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-gree-ac/index.js:3:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[2019-2-4 21:20:04] ====================
[2019-2-4 21:20:04] No plugins found. See the README for information on installing plugins.
[2019-2-4 21:20:04] Loading 3 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'GreeAC' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:285:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)



If I run it like 
homebridge -P /home/pi/node_modules it works perfectly

If I run the service it gives me this:

systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor prese
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-02-04 21
  Process: 8753 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, sta
 Main PID: 8753 (code=exited, status=1/FAILURE)

Feb 04 21:25:04 raspberry systemd[1]: homebridge.service: Main process exited, c
Feb 04 21:25:04 raspberry systemd[1]: homebridge.service: Unit entered failed st
Feb 04 21:25:04 raspberry systemd[1]: homebridge.service: Failed with result 'ex
lines 1-9/9 (END)

**Comment by NorthernMan54** [comment]
If you review the log file carefully, you can see a couple of issues, and if you can resolve them you should be good to go.

1) This message

> Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-gree-ac' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-gree-ac'.
> 

2) And this message

> [2019-2-4 21:20:04] ERROR LOADING PLUGIN homebridge-gree-ac:
> [2019-2-4 21:20:04] Error: Cannot find module 'mqtt'
> 


It appears you have free-ac plugin installed twice and one of the is not installed correctly

**Comment by F4stFr3ddy** [comment]
Also `"The requested accessory '" + name + "' was not registered by any plugin."` usually means an accessory has been added as a platform.
