### ISSUE TITLE
Second Instance on OS X

### ISSUE THREAD

**Issue by marcodesantis71** [nfarina/homebridge#2163]
HI All

I need to setup a second instance on my OS X Mojave.

I have created a second plist script on launchdaemon, a second folder and a second config.json.

I changed port and username.

I have duplicated the binary folder and created a second init file and second link on /usr/local/bin.
And changed all path.

I receive address in use.

Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1256:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1392:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge2/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge2/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge2/node_modules/hap-nodejs/lib/Accessory.js:609:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge2/lib/server.js:128:16)
    at Server.run (/usr/local/lib/node_modules/homebridge2/lib/server.js:97:10)
    at module.exports (/usr/local/lib/node_modules/homebridge2/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge2/bin/homebridge:17:22)
Emitted 'error' event at:
    at emitErrorNT (net.js:1283:8)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:800:11)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

This is my plist:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge2.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/homebridge2</string>
             <string>-D -I -U /Users/thegod/.homebridge2</string>
        </array>
    <key>StandardOutPath</key>
        <string>/var/log/homebridge2/logfile_info.log</string>
    <key>StandardErrorPath</key>
        <string>/var/log/homebridge2/logfile_error.log</string>
    <key>EnvironmentVariables</key>
        <dict>
        <key>PATH</key>
            <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
            <string>/Users/thegod</string>
        </dict>
</dict>
</plist>

and this Is my config.json of second instance:

cat config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51827,
        "pin": "031-45-154"
    }

}

Where I wrong?

**Comment by ebaauw** [comment]
Make sure to change the `username` and `port` in the second `config.json`.

You don't need to create a second binary folder, just a second `config.json` in `~/.homebridge2` and a second launchdaemon file.

**Comment by marcodesantis71** [comment]
> Make sure to change the `username` and `port` in the second `config.json`.
> 
> You don't need to create a second binary folder, just a second `config.json` in `~/.homebridge2` and a second launchdaemon file.

Hi @ebaauw 

Thank for reply.

I checked my plist file. I wrong the array syntax.

Now it works.

Thx again.
