### ISSUE TITLE
Homebridge don't install on Raspbian

### ISSUE THREAD

**Issue by Kaveckiy** [nfarina/homebridge#2172]
### Steps to Reproduce (for bugs)
I write installation command 

sudo npm install -g --unsafe-perm homebridge

and receive error (see below)

### Versions
node --version
v11.9.0

Raspbian Stretch Lite 4.14

### Homebridge Log / Command Output
/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)

**Comment by aveach** [comment]
I believe you need to update your version on npm: `sudo npm install -g npm` should do it.

**Comment by Kaveckiy** [comment]
> I believe you need to update your version on npm: `sudo npm install -g npm` should do it.

Not work :(

`pi@raspberrypi:~ $ sudo npm install -g npm
/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
pi@raspberrypi:~ $ 
`

**Comment by aveach** [comment]
Have you already installed avahi? `sudo apt-get install libavahi-compat-libdnssd-dev`

**Comment by Kaveckiy** [comment]
Yes, I have

`pi@raspberrypi:~ $ sudo apt-get install libavahi-compat-libdnssd-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavahi-compat-libdnssd-dev is already the newest version (0.6.32-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
