### ISSUE TITLE
 Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by aramaki87** [nfarina/homebridge#2176]
Hi guys,

I just installed homebridge on a raspi 2 and get this error msg. I tried several nodejs/npm versions without any luck. I reinstalled again but cannot get passed this message.

### Current Behavior
```
pi@Computer:~$ homebridge

/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Debug/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/out/Debug/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/Debug/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/out/Release/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/Release/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/default/ed25519.node
 â†’ /usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/compiled/11.11.0/linux/arm/ed25519.node
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:96:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:8:15)
```

### Versions
npm -v
6.7.0

nodejs -v
v10.15.3

git --version
git version 2.11.0

uname -a
Linux Kyoto 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
(The current Raspbian Stretch Lite)

Thank you for your help. Maybe someone can provide a working installation guide for the raspi?
Best regards

**Comment by andybno1** [comment]
I'm getting the same I have just updated homebridge & webos-tv

`C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\Debug\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\Release\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\out\Debug\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\Debug\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\out\Release\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\Release\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\default\curve.node
 → C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\compiled\10.15.1\win32\x64\curve.node
    at bindings (C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:96:9)
    at Object.<anonymous> (C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\index.js:1:96)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\andyb\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\encryption.js:5:18)`
