### ISSUE TITLE
ed25519.MakeKeypair(seed) is failing even with no plugins

### ISSUE THREAD

**Issue by rex555** [nfarina/homebridge#2182]
### Pre Steps
Raspberry Pi
Updated all OS/Node/Homebridge code
Trying to run with no plugins, just loading (have tried with plugins too, just removed them trail and error till there were none)

Keep getting the same error

Directory has been updated with the update:
drwxr-xr-x  5 root root 4096 Mar 20 19:12 hap-nodejs

File in question has not:
-rw-r--r-- 1 pi pi 5270 May  5  2018 /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js

EDIT: I removed the hap-nodejs directory and did the install again, same problem

### Expected Behavior
homebridge should run

### Current Behavior
Does not run, has errors

### Steps to Reproduce (for bugs)
Try running homebridge

### Versions
pi@raspberrypi ~ $ homebridge --version
0.4.46
pi@raspberrypi ~ $ node --version
v10.6.0
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:32",
        "port": 51826,
        "pin": "053-73-875"
    },

    "accessories": [
    ]
}

```

### Homebridge Log / Command Output

```
pi@raspberrypi ~ $ homebridge 
[3/20/2019, 8:50:25 PM] Loaded config.json with 0 accessories and 0 platforms.
[3/20/2019, 8:50:25 PM] ---
[3/20/2019, 8:50:25 PM] Loaded plugin: homebridge-legacy-plugins
[3/20/2019, 8:50:25 PM] Registering accessory 'homebridge-legacy-plugins.GarageDoorOpener_accessory'
[3/20/2019, 8:50:25 PM] Registering accessory 'homebridge-legacy-plugins.types'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.Domoticz'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.HomeSeer'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.ISY'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.LIFx'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.SmartThings'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.TelldusLive'
[3/20/2019, 8:50:25 PM] Registering platform 'homebridge-legacy-plugins.ZWayServer'
[3/20/2019, 8:50:25 PM] ---
[3/20/2019, 8:50:27 PM] Loaded plugin: homebridge-nest
[3/20/2019, 8:50:27 PM] Registering platform 'homebridge-nest.Nest'
[3/20/2019, 8:50:27 PM] ---
[3/20/2019, 8:50:27 PM] Loaded plugin: homebridge-rasppi-gpio-garagedoor
[3/20/2019, 8:50:27 PM] Registering accessory 'homebridge-rasppi-gpio-garagedoor.RaspPiGPIOGarageDoor'
[3/20/2019, 8:50:27 PM] ---
[3/20/2019, 8:50:27 PM] Loading 0 accessories...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:94
  var keyPair = ed25519.MakeKeypair(seed);
                        ^

TypeError: ed25519.MakeKeypair is not a function
    at Function.AccessoryInfo.create (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:94:25)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:528:41)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:97:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

```

**Comment by rex555** [comment]
Also, are there instructions on how to wipe and start over? The uninstalls do not seem to remove all files.

**Comment by mafyata** [comment]
Copy config.json to https://jsonlint.com/ and click validate json. See for error

**Comment by rex555** [comment]
My config is fine, I have tried with multiple validated configs
