### ISSUE TITLE
Homebridge dead after Synology reboot

### ISSUE THREAD

**Issue by mikesalz** [nfarina/homebridge#2187]
My Synology rebooted last night, and since then my Homebridge (docker) will not run.  

The UI works, but the service is apparently not running:

![image](https://user-images.githubusercontent.com/46855061/55275703-40733000-52c0-11e9-9b92-d628f979f0a2.png)

This is the error in the logs:

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:494:3)
    at tryReadSync (fs.js:333:20)
    at Object.readFileSync (fs.js:370:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:610:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:545:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:145:14)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:36:20)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
fs.js:115
    throw err;
    ^

**Comment by henkhb** [comment]
For it also stopped working. :/ Starts normal but all devices show no response.

**Comment by greztaylor** [comment]
I have EXACTLY the same issue

**Comment by mikesalz** [comment]
Any thoughts or suggestions from the developers on this?

**Comment by mikesalz** [comment]
Hello?

**Comment by KhaosT** [comment]
The issue is related to your docker configuration. Please make sure you gave homebridge RW access to correct folders.

**Comment by mikesalz** [comment]
@KhaosT Thank you for the reply.  I'm pretty sure it has the right access.  It works flawlessly 99% of the time.  Even if I start and stop the docker container.  It's just *sometimes* when the Synology reboots this happens.
