### ISSUE TITLE
Failed at the curve25519-n@1.4.0 install script

### ISSUE THREAD

**Issue by EG-Julien** [nfarina/homebridge#2189]
```
> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/curve25519-n
> node-gyp rebuild

Aborted
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/curve25519-n
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-01T18_34_01_976Z-debug.log
Aborted
```

Build essentials installed ...

Thanks in advance for any help !

**Comment by madpierce** [comment]
I got the same error.

**Comment by madpierce** [comment]
Sorry, I’m a serious novice. What what that look like in terminal step-by-step?

**Comment by EG-Julien** [comment]
Don't worry we all started with the same way !

1. Connect to your raspberry
2. `$ sudo vim /boot/config.txt`
*If `vim` isn't recognize type  `sudo nano /boot/config.txt`*
3. Find this line : `dtoverlay=pi3-disable-bt`
4. Add an `#` at the start of this line to now have : `#dtoverlay=pi3-disable-bt`
5. Save and exit the editor
6. Reboot your rpi and try again

That worked for me, if it's not for u just try on a fresh install of your pi

Good luck :)

**Comment by madpierce** [comment]
Thank you! I’m all set now. :)
