### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by PDiddyDaddyDog** [nfarina/homebridge#2201]
Howdy,

I apologize in advance if this has been solved in a previous issue post, I did look but I'm afraid I am but a noob and couldn't figure it out.
This is a Windows 10 setup of Homebridge with the Homeseer Plug-in.
Everything was going well after the install, the QR code came up and HomeKit could pair with it.
When creating the config.json file I copied the content of the samples provided without much success and eventually came up the file attached. (.txt extension )
[config.json.txt](https://github.com/nfarina/homebridge/files/3084518/config.json.txt)

Anyhoo, please help and I apologize again if this is a duplicate of a previously solved issue.

Log output
C:\WINDOWS\system32>homebridge
[2019-4-16 18:37:54] Loaded config.json with 4 accessories and 1 platforms.
[2019-4-16 18:37:54] ---
[2019-4-16 18:37:56] Loaded plugin: homebridge-homeseer-plugin-2018
homebridge API version: 2.4
[2019-4-16 18:37:56] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[2019-4-16 18:37:56] ---
[2019-4-16 18:37:56] Loading 1 platforms...
[2019-4-16 18:37:56] [HomeSeer] Initializing HomeSeer platform...
[2019-4-16 18:37:56] [HomeSeer] System default periodic polling rate set to: 10 seconds
[2019-4-16 18:37:56] Loading 4 accessories...
[2019-4-16 18:37:56] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:50:12)
    at Server._loadAccessories (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:297:42)
    at Server.run (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:91:38)
    at module.exports (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:59:10)
    at Object.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

C:\WINDOWS\system32>

**Comment by mafyata** [comment]
Did you install homeseer plugin ? After every “,” (comma) type on a new row

**Comment by PDiddyDaddyDog** [comment]
Sure did and reinstalled again to make sure. Same issue.

**Comment by PDiddyDaddyDog** [comment]
Hi Again,
Just released I had installed the 32 bit version of OpenSSL so have installed Win64OpenSSL-1_0_2r.exe as Win64OpenSSL-1_0_2q.exe was not available.
Also I have update homeseer to the lastest version as suggesed
Now when I try to run Homebridge I get the following.


openssl config failed: error:02001003:system library:fopen:No such process
C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:91
        throw e
        ^

Error: \\?\C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519-hap\build\Release\ed25519.node is not a valid Win32 application.
\\?\C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519-hap\build\Release\ed25519.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519-hap\index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
