### ISSUE TITLE
Unable to connect to accessory

### ISSUE THREAD

**Issue by evy0311** [nfarina/homebridge#2219]
### Expected Behavior
Home app should be able to add HomeBridge as an accessory to the app.

### Current Behavior
When trying to add Homebridge as an accessory to the Home app, it crashes HomeBridge and says "Couldn't add Homebridge-479D" inside the Home app.

### Steps to Reproduce (for bugs)
Install homebridge on a raspberry pi connected via ethernet. Attempt to add accessory to Home using iOS 12.2

### Versions

- **Homebridge**: `0.4.49`
- **Node**:       `v6.9.5`
- **OS**: `Raspbian 4.14.98 2019-04-08`

### Configuration
```
{
  "mdns": {
    "interface": "192.168.1.85"
  },

  "bridge": {
    "name": "Homebridge",
    "username": "XX-XX-XX-XX-XX-XX",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "This is my config",

  "platforms": [
    {
    "platform": "SmartThings",
    "name": "SmartThings",
    "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
    "app_id": "XXXXXXXX",
    "access_token": "XXXXXXXX",
    "update_method": "direct",
    "direct_port": 8000
    }
  ]
}
```

### Homebridge Log / Command Output

```
[5/13/2019, 1:23:30 AM] Loaded config.json with 0 accessories and 1 platforms.
[5/13/2019, 1:23:30 AM] ---
[5/13/2019, 1:23:39 AM] Loaded plugin: homebridge-smartthings-tonesto7
Homebridge Version: 2.4
[5/13/2019, 1:23:39 AM] Registering platform 'homebridge-smartthings.SmartThings'
[5/13/2019, 1:23:39 AM] ---
[5/13/2019, 1:23:40 AM] Loading 1 platforms...
[5/13/2019, 1:23:40 AM] [SmartThings] Initializing SmartThings platform...
[5/13/2019, 1:23:40 AM] [SmartThings] Fetching SmartThings devices.
[5/13/2019, 1:23:41 AM] [SmartThings] Mode: (Mode - Home)
[5/13/2019, 1:23:41 AM] [SmartThings] Unknown Capabilities: ["Health Check"]
[5/13/2019, 1:23:41 AM] [SmartThings] Initializing platform accessory 'Evan's Ceiling Lights'...
[5/13/2019, 1:23:41 AM] [SmartThings] Initializing platform accessory 'Mode - Home'...
[5/13/2019, 1:23:41 AM] [SmartThings] Initializing platform accessory 'Security Alarm'...
Setup Payload:
X-HM://0023ISYWYCC90
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
QR CODE HERE
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
CODE HERE
[5/13/2019, 1:23:42 AM] [SmartThings] update_method: direct
[5/13/2019, 1:23:43 AM] Homebridge is running on port 51826.
[5/13/2019, 1:23:43 AM] [SmartThings] Direct Connect Is Listening On 192.168.1.85:8000
[5/13/2019, 1:23:43 AM] [SmartThings] SmartThings Hub Communication Established
[5/13/2019, 1:25:16 AM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HA
```

As stated above i am unable to connect my homebridge into the home app. The iphone is connected via wifi and the raspberry pi is connected via ethernet but these are the same wifi network. I am using the smarthings plugin from here [https://github.com/tonesto7/homebridge-smartthings-tonesto7](url) but I dont think that is what is causing the issue. I believe this is an issue with the HAP server authentication but not sure what. The same error occurs with a sample config as well.

**Comment by KhaosT** [comment]
@evy0311 if possible, can you try update node to some recent version? Like 10.x or 12.x?

**Comment by evy0311** [comment]
Updating my Node version worked. Thanks so much! Im not sure why it was so outdated, and didnt even realize it. Thanks again!

**Comment by matthieudu06** [comment]
Hi,

I'm having the same issue now. For some reason it suddenly appeared without any update or changes on my side.

NPM version : v6.13.0
Nodejs : v0.10.29 (latest)

Here's the error I get while starting homebridge :

`TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)`

**Comment by NorthernMan54** [comment]
Sorry, that log fragment is to short to provide any feedback

**Comment by matthieudu06** [comment]
Sorry, here’s the full error:

[2019-11-15 12:46:20] Homebridge is running on port 34509.
[2019-11-15 12:46:21] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 12:46:21] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 12:46:21] Got SIGTERM, shutting down Homebridge...
[2019-11-15 12:46:22] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 12:46:22] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 12:46:22] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by NorthernMan54** [comment]
What version of nodejs are you using?

This is not the latest

Nodejs : v0.10.29 (latest)

 node -v
v10.16.3

**Comment by matthieudu06** [comment]
Thank you for your help. I'm not sure I'm using the right commands but from what I can see it shows the latest version already installed, no?

`matthieu@BB-8:~ $ node -v
v6.11.2
matthieu@BB-8:~ $ nodejs -v
v0.10.29
matthieu@BB-8:~ $ sudo apt install nodejs@latest
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nodejs@latest
matthieu@BB-8:~ $ sudo apt install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.`

**Comment by NorthernMan54** [comment]
Nope, those are historic

Google how to install node js on your RPI 

It has multiple old versions that need removal, then install the latest

**Comment by mafyata** [comment]
Which model of raspberry are you using?

**Comment by matthieudu06** [comment]
Raspberry Pi 3 model b+

Matthieu Nasri

**Comment by mafyata** [comment]
First delete old nodejs.
After that install new:
curl -sL https://deb.nodesource.com/setup_10.x | bash -
sudo apt-get install -y nodejs

**Comment by matthieudu06** [comment]
Thank you for your help.

I’ve deleted all NodeJS. The command `curl -sL https://deb.nodesource.com/setup_10.x <https://deb.nodesource.com/setup_10.x> | bash -` return the following error, I’ve tried using sudo but I get the same…

`sudo curl -sL https://deb.nodesource.com/setup_10.x | bash -
## Installing the NodeSource Node.js 10.x repo...
## Populating apt-get cache...
+ apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
Error executing command, exiting`

**Comment by mafyata** [comment]
Try with su:
1. sudo su
2. curl -sL https://deb.nodesource.com/setup_10.x | bash -
3. sudo apt-get install -y nodejs

**Comment by matthieudu06** [comment]
Worked with su. I'm stealing having errors...

nodeJS : v10.17.0

`[2019-11-15 21:35:28] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 21:35:29] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 21:35:29] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 21:35:29] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-11-15 21:35:29] Got SIGTERM, shutting down Homebridge...
[2019-11-15 21:35:29] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)`

**Comment by mafyata** [comment]
Uninstall homebridge and plugins and install them again
