### ISSUE TITLE
Can't have more than one instance.

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2244]
Hello,
I have over 5 home bridge instances running on one of my pi's so I wanted to bring one of them over to my 2nd pi. I copied the exact config and installed the plugins and etc. I get the following.
Might be good to mention that this config works on the other Pi. 
# Error
```
pi@raspberrypi:~/GarageBridge $ homebridge -U ~/GarageBridge
[6/22/2019, 6:43:49 AM] Loaded config.json with 2 accessories and 1 platforms.
[6/22/2019, 6:43:49 AM] ---
[6/22/2019, 6:43:51 AM] Loaded plugin: homebridge-camera-ffmpeg
[6/22/2019, 6:43:51 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[6/22/2019, 6:43:51 AM] ---
[6/22/2019, 6:43:51 AM] Loaded plugin: homebridge-chamberlain
[6/22/2019, 6:43:51 AM] Registering accessory 'homebridge-chamberlain.Chamberlain'
[6/22/2019, 6:43:51 AM] ---
[6/22/2019, 6:43:51 AM] Loading 1 platforms...
[6/22/2019, 6:43:51 AM] TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:120:12)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[6/22/2019, 6:43:51 AM] Got SIGTERM, shutting down Homebridge...
```
# My Config
```
{
	"bridge": {
		"name": "GarageBridge",
		"username": "CB:22:3D:E3:CE:30",
		"port": 51806,
		"pin": "031-45-154"
	},
	"accessories": [{
			"accessory": "Chamberlain",
			"name": "Double Garage",
			"username": "redacted",
			"password": "redacted",
			"deviceId": "redacted"
		},
		{
			"accessory": "Chamberlain",
			"name": "Single Garage",
			"username": "redacted,
			"password": "redacted",
			"deviceId": "redacted"

		}
	],
	"platforms": [{}]
}
```

**Comment by ebaauw** [comment]
> Might be good to mention that this config works on the other Pi.
> 	"platforms": [{}]

No it doesn’t.

**Comment by iRayanKhan** [comment]
Oops I'm. a fool, didn't check that the copy paste formatted platforms like that. It does work on the other Pi just if It didn't format while pasting.

**Comment by iRayanKhan** [comment]
Nope, still broke. Json lint formats in that order too with the [{}]

**Comment by ebaauw** [comment]
Homebridge expects a `”platform”` key inside the `{}`.  Leave the `”platforms”` array out, or specify and empty array.  Not an array with an empty object.

**Comment by iRayanKhan** [comment]
Updated my config, still having the same error. 
```
{
	"bridge": {
		"name": "GarageBridge",
		"username": "CB:22:3D:E3:CE:30",
		"port": 51806,
		"pin": "031-45-154"
	},
	"accessories": [{
			"accessory": "Chamberlain",
			"name": "Double Garage",
			"username": "redacted",
			"password": "redacted",
			"deviceId": "redacted"
		},
		{
			"accessory": "Chamberlain",
			"name": "Single Garage",
			"username": "redacted,
			"password": "redacted",
			"deviceId": "redacted"

		}
	],
	"platforms": [{

	}]
}

**Comment by ebaauw** [comment]
> Updated my config

No, you didn’t.
