### ISSUE TITLE
TypeError Issue with pairing Homebridge

### ISSUE THREAD

**Issue by SahajS9** [nfarina/homebridge#2249]
**Homebridge**: 0.4.50
**Node**:       v6.9.5
**Model*:         Raspberry Pi Zero W

My Homebridge was working fine for a while but after some issues, I had to reinstall some parts and change the username and port to readd it to my HomeKit.
However, when pairing the device, HAP has an error in the process. I ran Homebridge in debug mode to see if anything else showed up, but this is all I get.

```Pair step 5/5 +3s
[6/26/2019, 3:38:53 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)```

**Comment by mafyata** [comment]
Your nodejs is old. Install v10.

**Comment by SahajS9** [comment]
Oh, no wonder. Thanks, I'll try that.
