### ISSUE TITLE
Hive Forever Plugin - Hive Lights - Mac OS

### ISSUE THREAD

**Issue by jpsmith16** [nfarina/homebridge#2254]
Hi

Relatively new to Homebridge and have been able to set up the Hive Forever Plugin to operate Hive Smart Plugs and some of my Hive Dimmable Lights via Homebridge, but having issues adding the remainder of my Hive Dimmable Lights for some reason. Im running Homebridge 0.4.5 and latest Node.js on Mac OS Mojave

I have 13 individual Hive Dimmable bulbs. They’re grouped in the Hive app, but adding them separately in the config.json file, so I can group them then in the iOS Home app. 

Ive no issue adding them into the config.json file and then I startup Homebridge with no issue. However, when I then open up the iOS Home app, Homebridge gives the error below and then shuts down.

The config.json file is valid and that the accessory names match the Hive dashboard. I've tried adding them one by one in to the config.json file, restarting Homebridge and the iOS Home app each time to check, and I can add a certain quantity (5-6 individual bulbs) but then on the next bulb I add --> Homebridge restart --> open iOS Home app, I get this error (which only seems to occur after opening the iOS app)

Im not really sure what’s causing this and not experienced enough to be able to fix myself, so am wondering if anyone else is experiencing this issue?

Thanks in advance

TypeError: Cannot read property 'forEach' of undefined
    at HiveForever.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/index.js:274:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
[5/7/2019, 00:17:31] Got SIGTERM, shutting down Homebridge...
[5/7/2019, 00:17:31] TypeError: Cannot read property 'forEach' of undefined
    at HiveForever.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/index.js:274:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
[5/7/2019, 00:17:31] TypeError: Cannot read property 'forEach' of undefined
    at HiveForever.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/index.js:274:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
[5/7/2019, 00:17:31] TypeError: Cannot read property 'forEach' of undefined
    at HiveForever.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/index.js:274:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hive-forever/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)

**Comment by jpsmith16** [comment]
Any inputs on this issue would be much appreciated

**Comment by ebaauw** [comment]
You might have better luck asking this at the Hives Forever plugin.

**Comment by jpsmith16** [comment]
Thanks. I couldn't;t find one on GitHub. Plugin creator has been in touch through via email so will work it directly via that
