### ISSUE TITLE
Error: TypeError: buf.copy is not a function

### ISSUE THREAD

**Issue by SwissChoko** [nfarina/homebridge#2284]
Fresh install of Homebridge on my Raspberry PI
Raspberry Pi 3 - raspbian v9.9 (Stretch)

node v4.2.1
npm v2.14.7
homebridge v2.14.7

homebridge installed in global mode (-g) & starting correctly 

When trying to add homebridge to my iPhone by scanning the code & entering the passcode, Homebridge crashes with the following error

Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 230-32-016 │
    └────────────┘

[Sat Aug 10 2019 11:56:45 GMT+0200 (CEST)] Homebridge is running on port 23316.
[Sat Aug 10 2019 11:57:16 GMT+0200 (CEST)] TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:238:9)
    at Object.encode (/usr/lib/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/lib/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/usr/lib/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:67:13)
[Sat Aug 10 2019 11:57:16 GMT+0200 (CEST)] Got SIGTERM, shutting down Homebridge...
![JTB0n2DemY](https://user-images.githubusercontent.com/53967022/62820577-6cec6200-bb66-11e9-8cba-14e1b8b9a5e3.png)

any ideas ?

**Comment by Apollon77** [comment]
Nodejs 4 is eol since 2018. nodejs 6 is eol since April 2019. 

You should update your nodejs. And do not forget to reinstall homebridge or do a npm rebuild and ideally use most current version.
