### ISSUE TITLE
Fragile config.json

### ISSUE THREAD

**Issue by Hochiss** [nfarina/homebridge#2287]
as reported at [onze/ homebrige](https://github.com/oznu/docker-homebridge/issues/221#issue-481097926), the central file of config.json is quite sensitive to any settings' change or grammar mistake thus fragile, e.g. if one device mis-configured, all devices will be out and homebridge down.

So I wonder if each device could have its own "config.json" (kind of) , and links to the central config.json, thus single out the mis-configured device(s) and the other plugins can still run.

In general, is to make homebridge more stable and robust, esp. as HB platform goes wider and controls dozens of devices and more, config.json would be huge and very vulnerable. 
thanks!

**Comment by ebaauw** [comment]
If you're concerned about stability, you really want to run different plugins in different homebridge instances.  That way, each plugin has its own config.json and misbehaving plugins cannot interfere with other plugins.  You can run these multiple instances on the same server, by starting homebride with `-U `_user directory_ and by explicitly whitelisting the plugins to be loaded in respectvie config.json using the `plugins` keys.

**Comment by grzegorz914** [comment]
Hi, @Hochiss 

I think the problem is if we uninstall some homebridge-plugins and the settings stil in config.json, in this state Homebridge automatically shut down:

here the log after uninstall aomebridge-alexa and not removed its settings from config.json

```
[8/16/2019, 11:35:56 AM] [openHAB2-Complete] Getting services for Łazienka piętro roleta (2 service(s) registered for this accessory
[8/16/2019, 11:35:56 AM] [openHAB2-Complete] Initializing platform accessory 'Taras tył markiza'...
[8/16/2019, 11:35:56 AM] [openHAB2-Complete] Getting services for Taras tył markiza (2 service(s) registered for this accessory
[8/16/2019, 11:35:56 AM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[8/16/2019, 11:35:56 AM] Error: The requested platform 'Alexa' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[8/16/2019, 11:35:56 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by mafyata** [comment]
It is normal. You must change config.json when you install/uninstall plugins. You can check config.json for errors at https://jsonlint.com/

**Comment by grzegorz914** [comment]
My config.json is OK

Why homebridge shutdowns if some plugins are not installed and corespondent settings exist in config.json, why not skipped this settings during hombridge starts if plugin was removed?

**Comment by mafyata** [comment]
Config file is the brain and when something is wrong it can’t work normal. I can’t understand where is the problem, just delete plugin’s settings in config file. It is not “plug and play software”. It takes 30secs to edit config file.

**Comment by grzegorz914** [comment]
Don't worry for me it's not a problem just remove the settings and all working again OK, but why not integrated some mechanism in code to make life easy?

**Comment by Hochiss** [comment]
Thanks for your comments.

@ebaauw e.g. I installed your plugin for hue in NAS docker, I set NAS routinely power-off at night and start next morning due to noise, energy, security... But every morning after reboot, HB cannot start, because plugin-hue need a re-authorization, I have to walk to hue box and press the top button. 

This is just one case, even not a json grammar or format or mis-configuration, that HB is totally down.

HB is a open platform for any developers and any plugins, so you may imagine the vulnerability for HB.

**Comment by ebaauw** [comment]
> But every morning after reboot, HB cannot start, because plugin-hue need a re-authorization

You need to edit config.json, adding the bridgeid and username as described here: https://github.com/ebaauw/homebridge-hue#installation.
