### ISSUE TITLE
Homebridge keeps shutting down due to Error

### ISSUE THREAD

**Issue by naorth** [nfarina/homebridge#2294]
Homebridge was working great until today when I restarted my pi. Everytime I start it up it shows the same error message:

[2019-8-27 14:29:10] Error: listen EADDRINUSE :::44593
    at Server.setupListenHandle [as _listen2] (net.js:1345:14)
    at listenInCluster (net.js:1386:12)
    at Server.listen (net.js:1474:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:101:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
[2019-8-27 14:29:10] Got SIGTERM, shutting down Homebridge...

I've tried reinstalling homebridge and nodeJS but nothing has changed.

I'm using node v9.9.0

**Comment by Frank-Friemel** [comment]
The port you have chosen in your config is already in use. Trying a different port might help
