### ISSUE TITLE
How can I prevent 'same UUID'-error when restart?

### ISSUE THREAD

**Issue by JHurk** [nfarina/homebridge#2384]
**What is the problem?**
I would like to know a way to prevent the 'same UUID' error (see below) when I restart Homebridge. Why does this error occur every time I restart Homebridge and is there a way to solve this?

**How does this occur?**
When I restart Homebridge (because I installed or edited a plugin) I alway get the error and Homebridge doesn't start.
The only solution I have found is to delete the accessories cache (on synology Docker: /volume1/docker/homebridge/accessories/cachedAccessories). After deleting this file Homebridge will run again.
The BIG problem with this is that all settings of Homebridge devices are lost in the Home-app (makes sense as you delete the cache :)). So all lights, sockets, etc. are all set to default (as favorite, default icons and deleted from automations). It takes me an hour or so to get everything sorted again.

**Steps to reproduce and log**
Shut down Homebridge in Docker (by flipping the switch in the container screen)
Start Homebridge in Docker (by flipping the switch again)
I can reach the webpage of Homebridge <ip>:8581 but it states that Homebridge is not running.

The logging is as followed:
`[37m[1/9/2020, 9:21:17 PM][39m Loaded config.json with 1 accessories and 1 platforms.
[37m[1/9/2020, 9:21:17 PM][39m ---
[37m[1/9/2020, 9:21:18 PM][39m Loaded plugin: homebridge-edomoticz-ui-x
[37m[1/9/2020, 9:21:18 PM][39m Registering platform 'homebridge-edomoticz-ui-x.eDomoticz-ui-x'
[37m[1/9/2020, 9:21:18 PM][39m ---
[37m[1/9/2020, 9:21:18 PM][39m Loaded plugin: homebridge-nefit-easy
[37m[1/9/2020, 9:21:18 PM][39m Registering accessory 'homebridge-nefit-easy.NefitEasy'
[37m[1/9/2020, 9:21:18 PM][39m ---
[37m[1/9/2020, 9:21:18 PM][39m Loaded plugin: homebridge-config-ui-x
[37m[1/9/2020, 9:21:18 PM][39m Registering platform 'homebridge-config-ui-x.config'
[37m[1/9/2020, 9:21:18 PM][39m ---
[37m[1/9/2020, 9:21:18 PM][39m Loading 1 platforms...
[37m[1/9/2020, 9:21:18 PM][39m [36m[Domoticz][39m Initializing eDomoticz-ui-x platform...
[37m[1/9/2020, 9:21:18 PM][39m Loading 1 accessories...
[37m[1/9/2020, 9:21:18 PM][39m [36m[thermostaat][39m Initializing NefitEasy accessory...
Failed to find plugin to handle accessory Achterdeur
Failed to find plugin to handle accessory Garagedeur opener
Failed to find plugin to handle accessory Garagedeur status
Failed to find plugin to handle accessory Hondenhok
Failed to find plugin to handle accessory Kerstverlichting Achtertuin
Failed to find plugin to handle accessory Kerstverlichting Storm
Failed to find plugin to handle accessory Kerstverlichting Voortuin
Failed to find plugin to handle accessory Kerstverlichting Woonkamer
Failed to find plugin to handle accessory Lamp Honden
Failed to find plugin to handle accessory Lamp Zolder
Failed to find plugin to handle accessory Terras
Failed to find plugin to handle accessory Verlengkabel
Failed to find plugin to handle accessory Verlengkabel
Failed to find plugin to handle accessory Verwarming Honden
Failed to find plugin to handle accessory Voordeur
Failed to find plugin to handle accessory Achterdeur
[37m[1/9/2020, 9:21:18 PM][39m [1m[31mError: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 0b5e2abe-ee84-4702-a46e-bd5deeab9eb1
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:396:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11[39m[22m
[37m[1/9/2020, 9:21:18 PM][39m Got SIGTERM, shutting down Homebridge...`

**Versions**
- **Homebridge**: `0.4.50`
- **Node**:       `12.14.0`
- **OS**:         Synology DSM 6.2.2-24922 Update 4 (DS415+) in a Docker Container
-**Docker**:  18.09.0-0506
-**Plugins**: homebridge-edomoticz-ui-x v1.1.3
                       homebridge-config-ui-x v4.6.7
                       homebridge-nefit-easy v2.2.0

This error has something to do with the naming of the accessories, or bridge accessory. I found this much on the internet, but deleting the accessories cache is the only solution given. Unfortunately this doesn't prevent the error from happening again at a future restart.
I can not find a solid solution, could someone please help me?

**Comment by JHurk** [comment]
Problem was caused by the plugin homebridge-edomoticz-ui-x v1.1.3, I deleted that one and installed eDomoticz instead to connect Homebridge with Domoticz.
Now it seems that restarting Homebridge doesn't cause any troubles.
