### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by ctschach** [nfarina/homebridge#241]
Homebrighe is crashing before I had the chance to work with any devices...

[Kitchen Lamp] Initializing Http accessory...
[Phillips Hue] Initializing platform accessory 'WZ Couchtisch'...
[Phillips Hue] Initializing platform accessory 'WZ Sideboard'...
[Phillips Hue] Initializing platform accessory 'WZ Schrank'...
[Phillips Hue] Initializing platform accessory 'Studio Licht 1'...
Scan this code with your HomeKit App on your iOS device:

```
┌────────────┐
│ 031-45-154 │
└────────────┘
```

  EventedHTTPServer Server listening on port 51826 +0ms
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Connection.openTGroup (/home/oscar/src/HomeKit-NodeJS/homebridge/node_modules/eibd/lib/connection.js:142:15)
    at Object.<anonymous> (/home/oscar/src/HomeKit-NodeJS/homebridge/accessories/knxdevice.js:134:20)
    at Socket.emit (events.js:129:20)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at fireErrorCallbacks (net.js:456:13)
    at Socket._destroy (net.js:467:5)

events.js:0
(null)

RangeError: Maximum call stack size exceeded

**Comment by snowdd1** [comment]
Hi Carsten,
that is the not-so-good-formatted way of eibd to say the connection to knxd has not worked.
Please check: is your knxd deamon running, and if it is, does it accept ip requests?
Please also check the ip address and port configured in config.json to match your setup.

**Comment by neonightmare** [comment]
Hi, I also had this problem after changes in the config.json. I had to stop and restart the eibd before running home bridge

greets neo

**Comment by AppleTechy** [comment]
Please update to the latest version of Homebridge to confirm if the issue is still occuring. If it is go ahead and reopen this issue or hop onto Slack and ask around
