### ISSUE TITLE
Homebridge stop working

### ISSUE THREAD

**Issue by SzilagyiR** [nfarina/homebridge#2418]
Hi!

Homebridge stopped working, here is the error:
Can you help me?

Thanks!

hapNodeJSClient Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +0ms
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at Server.listen (net.js:1392:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:163:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:129:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

root@raspberrypi:/home/pi#

**Comment by SzilagyiR** [comment]
Homebridge is running....

Sorry!

**Comment by SzilagyiR** [comment]
Homebridge is running fine, but my phone and tablet says Not responding.

Can you help me?

**Comment by SzilagyiR** [comment]
After running an update, it work again!
