### ISSUE TITLE
improper shutdown requires deleting home in app

### ISSUE THREAD

**Issue by ceciltech** [nfarina/homebridge#249]
If you shutdown the server improperly (I used ctrl-z instead of ctrl-c) you need to reboot to get server to start again and afterwards the ios app no longer sees the server.  All the accessories are grayed out in the app.  Only way to get working again is to delete the home from homekit and re-add it in the app again.

**Comment by justme-1968** [comment]
noticed the same after a power outage. more on the exact behavior here: https://github.com/nfarina/homebridge/issues/237#issuecomment-146465669

**Comment by snizzleorg** [comment]
what then is the proper way to shut-down?

**Comment by jdwhite** [comment]
Ctrl-Z suspends the current process, it doesn't kill it.  When that happens, you can typically use the 'fg' command to bring the process to the **f**ore**g**round and then kill it with Ctrl-C.  A process in a suspended state is still allocating resources, including port bindings, but isn't running.  Starting another process won't work because the suspended process is still bound to port 51826.

**Comment by JangoBritt** [comment]
I have a similar issue, but I'm using CTRL+C to shut down the app.

If I shutdown homebridge using Ctrl+C, and then re-run it with `sudo homebridge` my accessories all grey-out, and won't re-discover.

I've tried changing the username, deleting the persist folder, the only thing that works is removing the Home from the HomeKit setting, and starting from scratch.

**Comment by andig** [comment]
> If I shutdown homebridge using Ctrl+C, and then re-run it with sudo homebridge my accessories all grey-out, and won't re-discover.

Same problem here using iOS 10 public beta 2, see https://github.com/nfarina/homebridge/issues/713

**Comment by emeshuris** [comment]
I am unable to reproduce, im on IOS 10 public beta 2
Here is what I did:

1. Opened home app cycled an accessory
1. ctrl+z
1. Started homebridge
1. Got an error, its a port issue, found the process, killed
1. Checked that all of my devices were greyed out in the home app
1. Started homebridge
1. Waited a few seconds for the devices to come back to life
1. Power cycled the same accessory

```
edward@theemm-homebridge:~ $ homebridge
...
                       
[7/30/2016, 5:31:21 AM] Homebridge is running on port 51826.
[7/30/2016, 5:31:37 AM] [Office Lamp] Setting power state to on
[7/30/2016, 5:31:37 AM] [Office Lamp] HTTP set power function succeeded!
[7/30/2016, 5:31:42 AM] [Office Lamp] Setting power state to off
[7/30/2016, 5:31:43 AM] [Office Lamp] HTTP set power function succeeded!
[7/30/2016, 5:31:44 AM] [Office Lamp] Setting power state to on
[7/30/2016, 5:31:44 AM] [Office Lamp] HTTP set power function succeeded!

edward@theemm-homebridge:~ $ homebridge
...
                       
[7/30/2016, 5:32:32 AM] Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:351:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:155:6
edward@theemm-homebridge:~ $ pgrep homebridge
678
edward@theemm-homebridge:~ $ kill -9 678
edward@theemm-homebridge:~ $ homebridge
...
[7/30/2016, 5:33:19 AM] Homebridge is running on port 51826.
[7/30/2016, 5:33:27 AM] [Office Lamp] Setting power state to on
[7/30/2016, 5:33:27 AM] [Office Lamp] HTTP set power function succeeded!
[7/30/2016, 5:33:29 AM] [Office Lamp] Setting power state to off
[7/30/2016, 5:33:30 AM] [Office Lamp] HTTP set power function succeeded!
[7/30/2016, 5:33:30 AM] [Office Lamp] Setting power state to on
[7/30/2016, 5:33:31 AM] [Office Lamp] HTTP set power function succeeded!
```

**Comment by emeshuris** [comment]
I have the homebridge running as a daemon, this is definitely the preferred method.
I only start via the command to debugging and even then the log could always be seen by running the following command, it updates live:
`tail -f /var/log/homebridge.log`

To start and stop the service I use:

- sudo /etc/init.d/homebridge start
- sudo /etc/init.d/homebridge stop
