### ISSUE TITLE
Tellus requires additional packages

### ISSUE THREAD

**Issue by lucacri** [nfarina/homebridge#262]
Hello,
after the addition of tellus (node-tellus package), i've been getting a lot of errors.
Apparently to solve the missing .h file, it's now required to follow these steps ( https://github.com/Hexagon/node-telldus/issues/60 )

After that, i still can't run `npm install` :

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-62-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/homebridge/node_modules/telldus
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Linux 3.13.0-62-generic
npm ERR! argv "node" "/usr/bin/npm" "rebuild"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! telldus@0.0.9 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telldus@0.0.9 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the telldus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls telldus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/homebridge/npm-debug.log

```

Could we make it that the tellus package is at least optional for now? It looks like it's bringing a lot of headaches (at least for me)

**Comment by SphtKr** [comment]
Same here, I had to remove the telldus lines from package.json to get the latest master to build tonight. The answer here is probably the new module system, which @nfarina is working on, but it's a project.
