### ISSUE TITLE
LIFX-API - Unexpected Shutdown

### ISSUE THREAD

**Issue by macreloaded** [nfarina/homebridge#266]
Anybody knows what's happen here? I´m still confusing...

HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=6.9 +3ms
  Accessory [Homekit] Getting value for Characteristic "On" +8ms
/home/pi/homebridge/node_modules/lifx-api/lifx.js:15
			throw (err);
			^

Error: connect ECONNREFUSED 104.20.0.60:443
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

**Comment by macreloaded** [comment]
Hello again,

can please somebody help me with this issue.
It seems like only a problem with the lifx-api module. Hue only works without problems.

Any help appreciated...please

**Comment by AppleTechy** [comment]
@macreloaded Has your issue been fixed? (There has also now been a LAN API as well as cloud released for the LIFX)

**Comment by AppleTechy** [comment]
I assume as there has been no activity that your issue was resolved. If not feel free to create a new issue on the Github page for the LiFX plugin.
