### ISSUE TITLE
Error: Cannot find module 'HAP-NodeJS/accessories/types.js'

### ISSUE THREAD

**Issue by solidstudio** [nfarina/homebridge#290]
getting the following

Loading 1 platforms...
module.js:338
    throw err;
          ^
Error: Cannot find module 'HAP-NodeJS/accessories/types.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/z/git/homebridge/platforms/YamahaAVR.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by Lologam** [comment]
Hello,

Same problem for me on Raspi:
Loading 1 platforms...
module.js:339
    throw err;
    ^

Error: Cannot find module 'HAP-NodeJS/accessories/types.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/homebridge/platforms/PhilipsHue.js:36:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by luc-ass** [comment]
I solved the problem by doing the install from the homebridge folder again, i.e.

<code>npm install</code>

**Comment by solidstudio** [comment]
had to match the case from 'HAP-NodeJS/accessories/types.js' to 'hap-nodejs/accessories/types.js'
