### ISSUE TITLE
Crash when called by someone else

### ISSUE THREAD

**Issue by billburgess** [nfarina/homebridge#296]
I had multiple users in the house using Homebridge. This morning when we tried to turn the lamp on, it didn't work. I tried with multiple devices. When I checked the server (thinking the computer had went to sleep) I found the server had stopped running. Here are the console outputs leading up to the crash, including the error. 

 Accessory [iMac Home] Processing characteristic set: {"characteristics":[{"aid":7,"iid":9,"value":true}]} +0ms
  Accessory [iMac Home] Setting Characteristic "On" to value true +0ms
[Lamp] Setting power state on the 'Lamp' to 1
[Lamp] Error setting power state to 1 on the 'Lamp'
  Accessory [iMac Home] Error setting Characteristic "On" to value true:  +2s undefined
  HAPServer [CC:22:3D:E3:CE:30] Error setting characteristics: undefined +0ms
  EventedHTTPServer [::ffff:10.0.1.59] HTTP Repsonse is finished +0ms
[Lamp] Error setting power state to 1 on the 'Lamp'
/Users/Bill/Git/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /Users/Bill/Git/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at WeMoAccessory.<anonymous> (/Users/Bill/Git/homebridge/accessories/WeMo.js:99:7)
    at /Users/Bill/Git/homebridge/node_modules/wemo/wemo.js:127:5
    at ClientRequest.<anonymous> (/Users/Bill/Git/homebridge/node_modules/wemo/wemo.js:99:4)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:235:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

**Comment by nfarina** [comment]
Yeah unfortunately I've seen this myself at least once ... I can't figure out how it could possibly be calling the callback twice - but I will add a var to discard any excess calls in WeMo.js.

**Comment by nfarina** [comment]
Also if you find that this is reproducible, it would be awesome to have some steps so we can track down what's really going on.

**Comment by nfarina** [comment]
The logic in WeMo seems susceptible to multiple callbacks, especially if the NodeJS contract has changed for `http.request` in terms of when it calls _its_ callback functions. This should patch it up well enough.

**Comment by KennyVB** [comment]
still an issue


Homebridge is running on port 51826.
[Dovecot] State of Dovecot is: 1      13      86 -
[Dovecot] State of Dovecot is: 1      13      86 total
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at null.<anonymous> (/usr/lib/node_modules/homebridge-ssh/index.js:74:5)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (/usr/lib/node_modules/homebridge-ssh/node_modules/readable-stream/lib/_stream_readable.js:201:16)
    at Readable.push (/usr/lib/node_modules/homebridge-ssh/node_modules/readable-stream/lib/_stream_readable.js:165:10)
    at Duplexify._forward (/usr/lib/node_modules/homebridge-ssh/node_modules/duplexify/index.js:162:26)
    at Channel.onreadable (/usr/lib/node_modules/homebridge-ssh/node_modules/duplexify/index.js:126:10)
    at emitNone (events.js:67:13)
    at Channel.emit (events.js:166:7)

**Comment by rafaelsantander** [comment]
seeing this with the wemo accessory. 

[master bedroom lights] Setting power state on the 'Master' to 1
[master bedroom lights] Error setting power state to 1 on the 'Master'
[master bedroom lights] WARNING: setBinaryState called its callback more than once! Discarding the second one.
[master bedroom lights] Error setting power state to 1 on the 'Master'
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at WeMoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/index.js:108:7)
    at /usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:127:5
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:99:4)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:235:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

**Comment by erfinb** [comment]
Having this issue too:

[Entry Way] Getting power state on the 'Entry Way'...
[Entry Way] Error getting power state on the 'Entry Way': undefined
[Entry Way] Error getting power state on the 'Entry Way': socket hang up
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at WeMoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/index.js:77:7)
    at /usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:110:5
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:99:4)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:235:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

Any way I can help?

**Comment by rudders** [comment]
Homebridge-wemo is getting little love and one of its dependencies is getting even less. Strongly suggest moving to homebridge-platform-wemo which is getting quite a bit of love from a few contributors.

**Comment by erfinb** [comment]
Thank you!
