### ISSUE TITLE
Homematic Accessoire: ReferenceError: modvalue is not defined

### ISSUE THREAD

**Issue by MaxMan23** [nfarina/homebridge#315]
Hi, 

i got an Error with the last Callback Function of the Homematic Accessoire:
ReferenceError: modvalue is not defined
    at Request._callback (/home/pi/Desktop/homebridge2/accessories/HomeMatic.js:50:27)
    at Request.self.callback (/home/pi/Desktop/homebridge2/node_modules/request/request.js:373:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/pi/Desktop/homebridge2/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/pi/Desktop/homebridge2/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Can someone help me, please

**Comment by iRaven** [comment]
Hi, seems there is not an expected value (true/false) returned, try uncommentig lines 43, 45 to see the (modified) response. I suggest 0 or 1 could be returned by other devices then the types i tested.
