### ISSUE TITLE
Nest error unofficial-nest-api/index.js:167:40

### ISSUE THREAD

**Issue by Dageezah** [nfarina/homebridge#332]
Oh dear - just hit this when starting homebridge... is there any way of limiting requests?

Too many requests
^
SyntaxError: Unexpected token T
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/unofficial-nest-api/index.js:167:40)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by AppleTechy** [comment]
If you are still having any issues please refile an issue at https://github.com/kraigm/homebridge-nest
