### ISSUE TITLE
issue with Wink.js

### ISSUE THREAD

**Issue by pir2** [nfarina/homebridge#338]
TypeError: Cannot read property 'on' of undefined
    at new WinkLightAccessory (/var/www/homebridge/platforms/Wink.js:220:7)
    at /var/www/homebridge/platforms/Wink.js:91:27
    at /var/www/homebridge/node_modules/wink-js/index.js:198:7
    at IncomingMessage.<anonymous> (/var/www/homebridge/node_modules/wink-js/index.js:69:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by fitzage** [comment]
Same here. Running `npm install` after my latest pull fixed it, so it must need a new or updated npm module.

**Comment by KraigM** [comment]
It does.
