### ISSUE TITLE
Nest (2nd Gen) fails because of empty displayName

### ISSUE THREAD

**Issue by jumpkick** [nfarina/homebridge#343]
Here's the stacktrace:

````
/home/user/homebridge/node_modules/hap-nodejs/lib/Accessory.js:45
  if (!displayName) throw new Error("Accessories must be created with a non-em
                          ^
Error: Accessories must be created with a non-empty displayName.
    at NestThermostatAccessory.Accessory (/home/user/homebridge/node_modules/hap-nodejs/lib/Accessory.js:45:27)
    at new NestThermostatAccessory (/home/user/homebridge/platforms/Nest.js:73:15)
    at /home/user/homebridge/platforms/Nest.js:38:49
    at /home/user/homebridge/node_modules/unofficial-nest-api/index.js:232:17
    at IncomingMessage.<anonymous> (/home/user/homebridge/node_modules/unofficial-nest-api/index.js:214:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by jumpkick** [comment]
This is the content of intialData:

```
initialData: {"$version":-8546,"$timestamp":1446130023690,"touched_by":{},
"auto_away":0,"auto_away_learning":"ready","hvac_heat_x3_state":false,
"compressor_lockout_enabled":false,"hvac_alt_heat_state":false,
"target_temperature_type":"heat","hvac_heater_state":false,"hvac_emer_heat_state":false,
"can_heat":true,"compressor_lockout_timeout":0,"hvac_cool_x2_state":false,
"target_temperature_high":26.5,"hvac_aux_heater_state":false,"hvac_heat_x2_state":false,"target_temperature_low":19,"hvac_ac_state":false,
"target_temperature":20.5,"hvac_fan_state":false,"target_change_pending":false,
"name":"","current_temperature":20.97,"hvac_alt_heat_x2_state":false,"can_cool":true}
```

Name is empty, so I changed line 36 of platforms/Nest.js from this: 
```
                                var name = initialData.name;
```
to this:
```
                                var name = (initialData.name != "" ? initialData.name : "Nest");
```

**Comment by jumpkick** [comment]
Okay, it turns out the real problem is a missing "this." reference on line 72:
```
    Accessory.call(this, name, id);
```
should be: 
```
    Accessory.call(this, this.name, id);
```

**Comment by KraigM** [comment]
Looks like the fix was merged in.  If it doesn't fix it, let me know.  If it does, go ahead and close this out.
