### ISSUE TITLE
Settings multiple values once, makes the PhilipsHue platform crash

### ISSUE THREAD

**Issue by patricks** [nfarina/homebridge#345]
I am using an app, where i can change a whole set of hue lamps and there settings.

If I start such a scene. I get the following crash:

```
[Phillips Hue] Set Bedroom Lamp, characteristic: brightness, value: 70.
  EventedHTTPServer [::ffff:10.0.1.4] Muting event '18.9' notification for this connection since it originated here. +29ms
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event '18.9' with data: {"characteristics":[{"aid":18,"iid":9,"value":true}]} +1ms
[Phillips Hue] Set Living Room Lamp, characteristic: power, value: true.
/Users/patrick/Developer/homebridge/platforms/PhilipsHue.js:241
            this.executeChange(characteristic, value, callback);
                 ^

TypeError: this.executeChange is not a function
    at null._onTimeout (/Users/patrick/Developer/homebridge/platforms/PhilipsHue.js:241:18)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by yhellowt** [comment]
I am having the same issue. Everything works fine until >7 actions need to be processed.

**Comment by andersboe** [comment]
I am experiencing the same issue as well. As @yhellowt said, it seems to happen once too many actions are called.

**Comment by andersboe** [comment]
Fixed the issue, made a pull request, check it out :)

**Comment by dvinc** [comment]
Commit 70f2dc62 seems to be related to solving the issue.
