### ISSUE TITLE
Homebridge crash with too many 'Philips Hue' actions

### ISSUE THREAD

**Issue by andersboe** [nfarina/homebridge#349]
First off: Love this project! 

I have got stuck into an error with the Philips Hue shim, that seems to fail if too many actions are called at a time. 

The homebridge server crashes when I try to set 'Power', 'Color' and 'Brightness' of three lights. 
Most of the scene get set correctly before the server crashes. 

(Setting 'Power', 'Color' and 'Brightness' for two lights works fine, same goes for setting two of the properties for all three lights. The limit seems to be somewhere around 8-9 "actions")

Below is the log from the call until the crash:
```
EventedHTTPServer [::ffff:10.0.1.4] HTTP request: /characteristics +5s
  HAPServer [XX:XX:XX:XX:XX:XX] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: {"characteristics":[{"aid":5,"iid":11,"value":0},{"aid":4,"iid":11,"value":0},{"aid":4,"iid":9,"value":1},{"aid":3,"iid":11,"value":0},{"aid":5,"iid":9,"value":1},{"aid":3,"iid":9,"value":1},{"aid":3,"iid":10,"value":56},{"aid":4,"iid":10,"value":56},{"aid":5,"iid":10,"value":56}]} +0ms
  Accessory [Homebridge] Setting Characteristic "Hue" to value 0 +1ms
  Accessory [Homebridge] Setting Characteristic "Hue" to value 0 +2ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +1ms
  Accessory [Homebridge] Setting Characteristic "Hue" to value 0 +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +0ms
  Accessory [Homebridge] Setting Characteristic "Brightness" to value 56 +0ms
  Accessory [Homebridge] Setting Characteristic "Brightness" to value 56 +1ms
  Accessory [Homebridge] Setting Characteristic "Brightness" to value 56 +0ms
[Phillips Hue] Set Hue Spot 2, characteristic: power, value: 1.
[Phillips Hue] Set Hue Spot 2, characteristic: hue, value: 0.
[Phillips Hue] Set Hue Spot 3, characteristic: hue, value: 0.
[Phillips Hue] Set Hue Spot 3, characteristic: power, value: 1.
[Phillips Hue] Set Hue Spot 1, characteristic: power, value: 1.
  EventedHTTPServer [::ffff:10.0.1.4] Muting event '3.10' notification for this connection since it originated here. +152ms
[Phillips Hue] Set Hue Spot 1, characteristic: brightness, value: 56.
  EventedHTTPServer [::ffff:10.0.1.4] Muting event '4.10' notification for this connection since it originated here. +11ms
[Phillips Hue] Set Hue Spot 2, characteristic: brightness, value: 56.
/Users/me/git/homebridge/platforms/PhilipsHue.js:241
            this.executeChange(characteristic, value, callback);
                 ^

TypeError: this.executeChange is not a function
    at null._onTimeout (/Users/me/git/homebridge/platforms/PhilipsHue.js:241:18)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by andersboe** [comment]
I have no idea how I did not see this issue, sorry.
https://github.com/nfarina/homebridge/issues/345
