### ISSUE TITLE
iControl/Xfinity Communication Error

### ISSUE THREAD

**Issue by tropicalisurf** [nfarina/homebridge#354]
Hello! Very new to GitHub and code so please excuse the lack of technical knowledge...

I have Xfinity Home and I was able to get HomeBridge running and recognized in MyTouchHome.app. However, Current System State is wrong and I cannot change it. Siri also does not recognize any commands. Any help would be greatly appreciated! 

Here's what I get in terminal:

  iControl Hidden input lang = en +0ms
[Xfinity Home] There was an error while communicating with iControl. Status code was 200 and error was: Error: Bad status code 200
Stack:Error
    at iControl._notifyError (/Users/john/homebridge/node_modules/node-icontrol/index.js:476:181)
    at iControl.<anonymous> (/Users/john/homebridge/node_modules/node-icontrol/index.js:239:12)
    at Request.self.callback (/Users/john/homebridge/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/john/homebridge/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/john/homebridge/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
Response:

Then it shows the Comcast website in html...

**Comment by nfarina** [comment]
In the HTML response, the text says "The username and password entered do not match. Please try again."

Are you positive your email/password combination is correct? Can you login at their website here: https://login.comcast.net/login

**Comment by tropicalisurf** [comment]
I can't believe I missed that. Thanks @nfarina! I'm up and running now.
