### ISSUE TITLE
Netatmo failing on startup

### ISSUE THREAD

**Issue by deejc-uk** [nfarina/homebridge#356]
just pulled the latest and am getting the following error on start up, i thought i should add that my Netatmo was working before this pull request, thanks

[Netatmo Weather] Initializing Netatmo platform...

==> /var/log/homebridge.err <==
/opt/homebridge/platforms/Netatmo.js:124
    that.api.getStationsData(function(err, devices) {
             ^
TypeError: undefined is not a function
    at Object.NetAtmoRepository.refresh (/opt/homebridge/platforms/Netatmo.js:124:14)
    at /opt/homebridge/platforms/Netatmo.js:151:16
    at NodeCache.module.exports.NodeCache.get (/opt/homebridge/node_modules/node-cache/lib/node_cache.js:64:11)
    at NodeCache.get (/opt/homebridge/node_modules/node-cache/lib/node_cache.js:3:59)
    at Object.NetAtmoRepository.load (/opt/homebridge/platforms/Netatmo.js:148:16)
    at Object.NetatmoPlatform.accessories (/opt/homebridge/platforms/Netatmo.js:179:21)
    at loadPlatformAccessories (/opt/homebridge/app.js:122:20)
    at loadPlatforms (/opt/homebridge/app.js:116:9)
    at startup (/opt/homebridge/app.js:59:27)
    at Object.<anonymous> (/opt/homebridge/app.js:223:1)

**Comment by planetk** [comment]
Hi,
the new netatmo is working with an updated version of the netatmo api provided by patricks.
(Please check: https://github.com/nfarina/homebridge/issues/326)
This version does nolonger use an outdated and deprecated API call

For me a "npm install" fixed this, since the netatmo lib was updated.

Kind regards
planetK

**Comment by deejc-uk** [comment]
perfect, working now, thanks so much, maybe i should remember to do this after every update?
