### ISSUE TITLE
Crashes in Nest.js

### ISSUE THREAD

**Issue by billburgess** [nfarina/homebridge#367]
This was working in previous builds. The latest version of Nest.js crashes when I start the server. Here are the crash logs.

/Users/Bill/Git/homebridge/platforms/Nest.js:123
        .on('get', function(callback) {
        ^

TypeError: Cannot read property 'on' of undefined
    at new NestThermostatAccessory (/Users/Bill/Git/homebridge/platforms/Nest.js:123:9)
    at /Users/Bill/Git/homebridge/platforms/Nest.js:37:49
    at /Users/Bill/Git/homebridge/node_modules/unofficial-nest-api/index.js:232:17
    at IncomingMessage.<anonymous> (/Users/Bill/Git/homebridge/node_modules/unofficial-nest-api/index.js:214:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
brasky-imac:homebridge Bill$

**Comment by nfarina** [comment]
Can you check that you're using the updated (v0.0.3) version of the `hap-nodejs` dependency?

**Comment by billburgess** [comment]
How would I check that? I'm basically just doing a git pull on the repo then restarting the server. The latest changes break things even worse. I'm getting npm error, missing script start. Not sure what I did, or didn't update, but it is unusable now.

**Comment by billburgess** [comment]
I'm clearly behind in a few things. This is likely not even an issue anymore given the recent changes. I'll read up and close this out.
