### ISSUE TITLE
Crashing apparently in wink.js.

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#372]
```
  harmonyhubjs:client:harmonyclient received response stanza for queued response handler +0ms
response in http: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/fitzage/Source/homebridge/node_modules/wink-js/index.js:62:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
raw message <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
/Users/fitzage/Source/homebridge/platforms/Wink.js:54
      for (var i=0; i<devices.data.length; i++){
                             ^

TypeError: Cannot read property 'data' of undefined
    at /Users/fitzage/Source/homebridge/platforms/Wink.js:54:30
    at /Users/fitzage/Source/homebridge/node_modules/wink-js/index.js:198:7
    at IncomingMessage.<anonymous> (/Users/fitzage/Source/homebridge/node_modules/wink-js/index.js:69:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

**Comment by fitzage** [comment]
This hasn't gone away. This is what I'm getting with the latest version.

```
response in http: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/wink-js/index.js:62:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
raw message <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Wink.js:54
      for (var i=0; i<devices.data.length; i++){
                             ^

TypeError: Cannot read property 'data' of undefined
    at /usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Wink.js:54:30
    at /usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/wink-js/index.js:198:7
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/wink-js/index.js:69:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

**Comment by fitzage** [comment]
I'm not sure if this is an occasional error from the Wink API, and then it doesn't fail gracefully and continue, but crashes?
