### ISSUE TITLE
Won't launch because of Wink error (latest version)

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#374]
When using the new global installation method, I get the following error when attempting to run homebridge:

```
[Wink] WARN: Unable to find id of Wink so using name instead
/usr/local/lib/node_modules/homebridge/lib/server.js:201
  platformInstance.accessories(once(function(foundAccessories){
                   ^

TypeError: platformInstance.accessories is not a function
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:201:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:195:14)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:34:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:22:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

I used the same config.json as I had before, because it seemed to be correct according to the new method.

**Comment by nfarina** [comment]
This should be fixed by [9f351a6caf](https://github.com/nfarina/homebridge-legacy-plugins/commit/9f351a6caf425e0225a746de3b3b7a8bb4e43342). Could you try updating your `homebridge-legacy-plugins` module?

**Comment by fitzage** [comment]
That seems to have moved the error down the line a bit:
```
/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Wink.js:220
      .on('get', function(callback) {
      ^

TypeError: Cannot read property 'on' of undefined
    at new WinkLightAccessory (/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Wink.js:220:7)
    at /usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Wink.js:91:27
    at /usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/wink-js/index.js:198:7
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/wink-js/index.js:69:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

**Comment by nfarina** [comment]
Ah, seems I forgot to update the version of HAP-NodeJS in the new branch - could you try reinstalling homebridge v0.2.3? It should be installing hap-nodejs v0.0.3.

**Comment by fitzage** [comment]
Ah, yes. That fixed it.

Now hopefully this new version also won't have the wink crashing issue I was having before. We'll see…
