### ISSUE TITLE
Error on accessoryLoader

### ISSUE THREAD

**Issue by cali0028** [nfarina/homebridge#375]
Getting the following accessory loading error on the new install...

Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[SmartThings] Initializing SmartThings platform...
Loading legacy platform SmartThings
[SmartThings] Fetching SmartThings devices...
[SmartThings] Initializing platform accessory 'Bedroom Switch'...
[SmartThings] Loaded services for Bedroom Switch
/usr/local/lib/node_modules/homebridge/lib/server.js:232
    return accessoryLoader.parseAccessoryJSON({
           ^

ReferenceError: accessoryLoader is not defined
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:232:12)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:211:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Request._callback (/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/SmartThings.js:37:9)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

**Comment by nfarina** [comment]
Published a fix - give that a shot!
