### ISSUE TITLE
homebridge -D returns error

### ISSUE THREAD

**Issue by rudders** [nfarina/homebridge#376]
Trying to debug why I can't see home bridge on my network so I tried homebridge -D and got the following error.

`/usr/lib/node_modules/homebridge/lib/cli.js:16
    .option('-D, --debug', 'turn on debug level logging', function() { logger.setDebugEnabled(true) })
                                                                       ^

ReferenceError: logger is not defined
    at /usr/lib/node_modules/homebridge/lib/cli.js:16:72
    at Command.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/commander/index.js:395:35)
    at emitNone (events.js:67:13)
    at Command.emit (events.js:166:7)
    at Command.parseOptions (/usr/lib/node_modules/homebridge/node_modules/commander/index.js:697:14)
    at Command.parse (/usr/lib/node_modules/homebridge/node_modules/commander/index.js:455:21)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:17:6)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)`

**Comment by nfarina** [comment]
Thanks for catching this!
