### ISSUE TITLE
Homebridge Starting Problem

### ISSUE THREAD

**Issue by namirister** [nfarina/homebridge#390]
hi everyone
i have just install hombridge solution
I start it well by:
     pi@raspberrypi ~ $ homebridge    
when i close my session  the homebridge thread end too
so i try the solution PM2 to use the homebridge in the background
i do the configuration as it describted in other issues
but whene i reboot no homebridge found in PM2 list
can any one give me a hint about this problem
thanks

**Comment by snowdd1** [comment]
For testing purposes you might try to start homebridge with 
`nohup homebridge` 
That will prevent the program from being killed when the session ends.
Homebridge will run until 
- an error occurs,
- the OS is restarted

**Comment by namirister** [comment]
thanks @snowdd1 
i test your command it not do what you have describe 
```pi@raspberrypi ~ $ nohup homebridge```
```nohup: ignoring input and appending output to `nohup.out' ```
ctrl+c kill the program

**Comment by cali0028** [comment]
@snowdd1  
root@raspberrypi:~# nohup homebridge &
[1] 822
root@raspberrypi:~# nohup: ignoring input and appending output to ‘nohup.out’

it worked for me.. Guess you forgot the "&"

@namirister add the "G" in the end it should work. Worked for me!

**Comment by snowdd1** [comment]
Sorry, @cali0028 was right, I frequently forget the `&`.
Work around **after** the mishap: instead of ctrl-c (Cancel process), press ctrl-z (Pause process) and then send it to background with `bg 1`... :roller_coaster:

**Comment by rlust** [comment]
I am getting the following error when the program completes scanning my platform devices.

Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/opt/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/opt/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:132:20)
    at Bridge.Accessory.publish (/opt/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:347:16)
    at Server._publish (/opt/local/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.<anonymous> (/opt/local/lib/node_modules/homebridge/lib/server.js:220:14)

**Comment by EIBHomeControl** [comment]
@rlust try (sudo) killall homebridge

**Comment by adamstephenson** [comment]
@namirister I'm not sure if you're still having problems. I've been experiencing Homebridge closing/quiting on my RPi2 after various amounts of time. I didn't track it down to my own SSH sessions or other reasons. 

I read up on PM2, Supervisor, and others. I tried Supervisor first, but didn't figure out a way for it to work the way I needed for me. 

I then looked into Forever and have had success. 

You can read a bit about, and install from NPMJS.com: https://www.npmjs.com/package/forever
You may want to make sure you've updated homebridge, and be sure to read about how to create an init.d script for launching homebridge at startup from the Wiki: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup

I had followed those instructions initially, and it launches at startup great. I then changed the command line in the script to include Forever so it would monitor and restart homebridge if necessary.

Here's my updated cmd line in my homebridge init.d config file: 
         cmd="forever start /usr/local/bin/homebridge"

If anyone else reading see's a problem or risks with this approach please let me know! I'm just a 3-day noob trying to share learnings/guessings with others. 

Thanks!

**Comment by adamstephenson** [comment]
Oh and on my RPi, it's be rock solid for 7 hours now, FWIW. Might not be forever or something else (I removed some packages and plugins I didnt need) since the pid has remained the same since (indicating no crash and restart, right?)

**Comment by AppleTechy** [comment]
Since your issue is fix do you mind if I go ahead and close the issues?

**Comment by namirister** [comment]
yes thanks a lots

**Comment by jonbid** [comment]
this wasn't working for me... dir="/usr/local/bin/" cmd="homebridge" user="root"

the script would start but homebridge didn't work. this change made it work:

dir="/usr/local/bin/" cmd="forever start /usr/local/bin/homebridge" user="pi"

**Comment by Joeip12** [comment]
hi Snowdd1, 

i test the command ...  $ nohup home bridge &   ... but doesn't work.
then i test ....  sudo killall home bridge.....   and restart home bridge...  there are some error occurred as below.  
my home bridge ip is 192.168.244.19
my hs100  ip is 192.168.244.16  (my video cam is connected to HS100 and the ip is not .18  

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[6/13/2017, 11:44:32 PM] Homebridge is running on port 51826.
[6/13/2017, 11:44:32 PM] New Plug Online: Cam at Living Room [8006A112FE9E4259240F591932CABFE51877CC87]
[6/13/2017, 11:44:32 PM] Configuring: Cam at Living Room
HS100 Plug TCP error
Trace: { [Error: connect EHOSTUNREACH 192.168.244.18:9999]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.244.18',
  port: 9999 }
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/plug.js:61:17)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
[6/13/2017, 11:44:36 PM] { [Error: connect EHOSTUNREACH 192.168.244.18:9999]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.244.18',
  port: 9999 }
[6/13/2017, 11:45:02 PM] Online: Cam at Living Room [8006A112FE9E4259240F591932CABFE51877CC87]

**Comment by snowdd1** [comment]
Any idea where the .18 address might come from? I am not familiar with the plugin.

**Comment by Joeip12** [comment]
IP  .18 address is for my canon printer and i've removed it from the network just now.  Then try again the above command but the error still there.  can any one give me a hint about this problem ?  Thanks. 

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/14/2017, 11:13:53 PM] Loaded plugin: homebridge-hs100
[6/14/2017, 11:13:53 PM] Registering platform 'homebridge-hs100.Hs100'
[6/14/2017, 11:13:53 PM] ---
[6/14/2017, 11:13:53 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/14/2017, 11:13:53 PM] ---
[6/14/2017, 11:13:53 PM] Loading 1 platforms...
[6/14/2017, 11:13:53 PM] Initializing Hs100 platform...
[6/14/2017, 11:13:53 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)
pi@raspberrypi:~ $

**Comment by snowdd1** [comment]
`EADDRINUSE` means expanded *Error, Address in Use* which should tell us that the address that homebridge is trying to bind itself to is already taken by another process. For homebridge that usually means that another instance is still running in the background, though it might be dysfunct at that time. 
Try finding that other instance (using `ps` *processes* command e.g., google for help) and kill it - or just reboot the machine, after having ensured that homebridge is not configured to autostart.

**Comment by sprokkie** [comment]
Hi Guys,

i am trying to install the homebrigde on a Pi Zero W  got lots of troubles finaly i managed to start.
added the fakebulb script and start the homebridge, got this error:
Error: listen EADDRINUSE :::51826
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:601:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)
 any idea's ?

**Comment by sprokkie** [comment]
ok got it working, just a big misstake in te json file.
i did not add the server adres etc.

now siri is turning the fake bulb on and off  when i ask

**Comment by GoogleIT2** [comment]
Hi, I know this is a really old post, but I have found another solution for Mac.
My problem was that homebridge was actually running in the background (not properly though) and was hogging the port. What I has to do was use `sudo lsof -i :518261` in the terminal app to help identify the process that was hogging the port, and then `Activity Monitor` to stop the process.
