### ISSUE TITLE
Weird EADRINUSE error on MAC and Synology Nas

### ISSUE THREAD

**Issue by techyowl** [nfarina/homebridge#410]
the mac first I suppose:
I have been trying all day today to get home bridge setup and have ran from issue to issue. I first attempted to install it on my Sinology NAS which only lead to the same issue with the mac

I installed node via the pkg from node.js's website. then I installed home bridge via sudo npm install -g homebridge and then proceeded to installing a few other plugins. I have gotten all plugins to function properly some by using github raw updates but most just by using the npm installer. and now all the platforms and accessories seem to initialize just find and search for devices  but the mac shoots this error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

and there is no other errors or warning shown only my mac and I have scanned and killed anything on my mac for apps using port 5224, 51826, or any app running under the phrase node. nothing works its the same error over and over again with no clear trace or possible fix. 

The NAS has several AVAHI warnings as shown below:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
```

 but the plugins finally load fine and it has a slightly different error code. I followed 
[this guide](http://jensbouma.nl/hello-siri-turn-the-lights-on-the-siri-for-iot-bridge-running-on-a-synology-nas/) for the most part. it required setting up debian chroot and manually configuring NodeJS 0.12 from source code using a make install and such. 

NAS Error code:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

MacBook Pro Retina Early 2015 13" model fully specced out OS X 10.11.1 Xcode is installed and active

Synology NAS Model DS215j with 2X4Tb Drives running Disk Station 5.2

if you have any suggestions for me that might fix at least one of these that would be awesome!

**Comment by techyowl** [comment]
ok so I found out after doing a lot of research on home bridge that harmony hub was likely causing the same issue on 4.1.2 as it was on node v0.12.6 so I removed it from both the config.son and from nam and it now starts up just fine. too bad Harmony Hub doesn't work but glad I got it running.
