### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by simhadris** [nfarina/homebridge#413]
im using Nest accessory, homebridge on mac desktop.
It runs fine, but after some time i get following error:
1. 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:209:15)
    at TLSSocket.socketOnEnd (_http_client.js:294:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)

or this:

2.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1089:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)

**Comment by nfarina** [comment]
Please reopen in https://github.com/kraigm/homebridge-nest
