### ISSUE TITLE
config.json and server.js issue

### ISSUE THREAD

**Issue by jhembach** [nfarina/homebridge#439]
I'm hoping someone can point me in the right direction to resolve these errors I'm getting.

Here's what happens when I run homebridge:

    Loaded plugin: homebridge-lockitron
    Registering accessory 'homebridge-lockitron.Lockitron'
    ---
    Loaded plugin: homebridge-nest
    Registering platform 'homebridge-nest.Nest'
    ---
    There was a problem reading your config.json file.
    Please try pasting your config.json file here to validate it: http://jsonlint.com

    /usr/local/lib/node_modules/homebridge/lib/server.js:124
        throw err;
        ^

    SyntaxError: Unexpected token “
        at Object.parse (native)
        at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
        at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
        at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
        at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
        at Module._compile (module.js:435:26)
        at Object.Module._extensions..js (module.js:442:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Function.Module.runMain (module.js:467:10)

My .json file is pretty straightforward:

	{
		"bridge": {
			"name": "Homebridge",
			"pin": "987-65-432"
		},

		"platforms": [{
			"platform": "Nest",
			"username": “xxx@xxx.com”,
	        "password": “xxxt”
		}]
	}

**Comment by snowdd1** [comment]
Strange quote symbols around username and password.  Did you use a "smart" editor?

**Comment by jhembach** [comment]
Wow. I'm a bit embarrassed I didn't catch that myself. Thanks so much! Works perfectly now.
