### ISSUE TITLE
Valid config.json won't parse in homebridge

### ISSUE THREAD

**Issue by fahrvergnuugen** [nfarina/homebridge#441]
I am trying to pass RS232 control characters into my homebridge plugin from the config.json file, but homebridge fails to load:

```
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/usr/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected token x
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
```

To reproduce this issue, use this example config.json. The "test" property which contains the \x02 \x03 control characters causes the error:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "test": "\x02PON\x03"
    },

    "description": "This is an example configuration file that will cause homebridge to throw an error even though the json validates.",

    "accessories": [
    ],

    "platforms": [
   ]

}
```

**Comment by snowdd1** [comment]
Do you want to pass the literal string with backslashes? Then use "escaped" backslashes like "\\x02"
You cannot escape the letter "x".
Regards
Raoul

**Comment by snowdd1** [comment]
Just noticed that github doesn't like escaped strings either. Imagine the backslashes are doubled above. 
I'll try again: "\\\\x02"

**Comment by fahrvergnuugen** [comment]
@snowdd1 I need to set STX and ETX control characters as part of the rs232 commands that control my television. 

STX is \x02
ETX is \x03

See here http://www.ascii-code.com

**Comment by snowdd1** [comment]
I just googled the json specs and it looks like \\x is no valid json expression. I think you need to find either a Unicode expression \\u0000 replacement for the ascii expressions or write your own parser that replaces your stx / etx tokens by the real thing within the plugin.

**Comment by fahrvergnuugen** [comment]
@snowdd1 that JSON parses completely fine in nodejs, safari, chrome & http://jsonlint.com
It only causes a problem with homebridge for some reason.

**Comment by mdod** [comment]
Mine works fine on Mac without the "test" line.

**Comment by AppleTechy** [comment]
@fahrvergnuugen what text editor are you using?

**Comment by fahrvergnuugen** [comment]
@AppleTechy Textmate

**Comment by rudders** [comment]
Shouldn't the port have quotes around it?

**Comment by fahrvergnuugen** [comment]
@rudders it doesn't technically need them because it's an integer. It actually should work both ways, but the example provided by homebridge is without quotes. See [config-sample.json] (https://github.com/nfarina/homebridge/blob/master/config-sample.json)

**Comment by rudders** [comment]
Good point.

**Comment by lewisward1** [comment]
can some one help with mine i have the same problem


{
	

	"platforms": [{
		"platform": "Nest",

		"token": "c.N9.....Aga",

		"clientId": "c4......7",
		"clientSecret": "XYZ",
		"code": "XYZ",

		"username": "me@home.com",
		"password": "thesisapassword"
	}]

}






Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/usr/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected token :
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by AppleTechy** [comment]
@lewisward1 Is that your entire config.json?

**Comment by lewisward1** [comment]
yes mate , should i have more ?

**Comment by AppleTechy** [comment]
@lewisward1 Yes!!!!!

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
           
        }
    ],

    "platforms": [
        {
           "platform": "Nest",

    "token": "c.N9.....Aga",

    "clientId": "c4......7",
    "clientSecret": "XYZ",
    "code": "XYZ",

    "username": "me@home.com",
    "password": "thesisapassword"
        }
    ]
}

**Comment by lewisward1** [comment]
i just copied and pasted this and got same result, i am guessing  i need the username , port etc different from yours ? if it doesn't mention this on nest developer

loobymac:~ itunes$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/usr/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected token :
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by lewisward1** [comment]
sorry bud , complete newbie

**Comment by AppleTechy** [comment]
@lewisward1 So now copy what you have in your config

**Comment by lewisward1** [comment]
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},




	"description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",


	"platforms": [{
		"platform": "Nest",

		"token": "c.N9YZ4RqBUr2Aga",

		"clientId": "c4ee6abe1b85827",
		"clientSecret": "oQJsmsfys",
		"code": "66X",

		"username": "my@email.net",
		"password": "my password"
	}]
}

**Comment by AppleTechy** [comment]
@lewisward1 Try putting the bracket in the line before "bridge"
{
"bridge": {

**Comment by lewisward1** [comment]
i spotted that too, but same result sadly

**Comment by AppleTechy** [comment]
@lewisward1 Then I am not sure what the issue is

**Comment by lewisward1** [comment]
ok i just took out client id, secret and code and now its working , obi cos i had registered the token. Thank you so much for your help your a Star

**Comment by AppleTechy** [comment]
@lewisward1 No problem

**Comment by lewisward1** [comment]
It says on the site that one the token is registered you can delete those lines, it says if you leave them in they will be ignored. clearly not in this case.

Thank you so much for all your help, i was tearing my hair out. Is there somewhere i can rate you on github ?

**Comment by AppleTechy** [comment]
@lewisward1 As far as I know there is no way to rate people on GitHub. Out of curiosity what text editor were you using when editing the config.json?

**Comment by lewisward1** [comment]
Morning mate , it is called atom , got the nest going good , now trying the Lightwave rf stuff :-)

**Comment by mightythias** [comment]
Hello I am also having this issue.

I had homebrigde working perfectly but when i tried to add smarthings it doesn't want to load anymore. I installed the smartthings plugin modified my config.json file but when i start it up i get the bellow error.

Loaded plugin: homebridge-harmonyhub
[3/11/2016, 3:03:42 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[3/11/2016, 3:03:42 PM] ---
[3/11/2016, 3:03:42 PM] Loaded plugin: homebridge-smartthings
[3/11/2016, 3:03:42 PM] Registering platform 'homebridge-smartthings.SmartThings'
[3/11/2016, 3:03:42 PM] ---
[3/11/2016, 3:03:42 PM] There was a problem reading your config.json file.
[3/11/2016, 3:03:42 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[3/11/2016, 3:03:42 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:176
    throw err;
    ^

SyntaxError: Unexpected token  
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:170:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

config.json:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "987-65-432"
	},

	"platforms": [{
			"platform": "HarmonyHub",
			"name": "MyHub"
		},
{
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "37b335e5-5d16-4ba7-b9d4-0c481c63f206",
            "access_token": "9dff3176-4047-4927-94a4-26b4d73036c2"
        }
	]
}

Any help would be appreciated.

**Comment by fahrvergnuugen** [comment]
@mightythias its a different issue. My json example is valid but homebridge fails to load. Your json isnt valid (you have an unmatched ])

Check it with http://jsonlint.com/
