### ISSUE TITLE
"unhanded error event" after running for 2 hrs

### ISSUE THREAD

**Issue by AppleTechy** [nfarina/homebridge#457]
I ran my homebridge for approx. 2 hr then I get this message.  Does anyone have any idea what is causing it? Is it a plugin I have installed? If so can you tell me which so I can move the issue to that page. Thanks for the help!
events.js:141
     throw er; // Unhandled 'error' event
     ^

Error: connect TIME-OUT {has Ip address}
   at Object.exports._errnoException (util.js:874:11)
   at exports._exceptionWithHostPort (util.js:897:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by AppleTechy** [comment]
I have recently run home bridge in debug mode and am almost positive it is an issue with the demo-platform. I am going to keep this issue open incase it is actually an issue with homebridge. After we get it resolved whether it is Homebridge or the plugins faults I will close the issue

**Comment by rudders** [comment]
By that do you mean the wemo-platform (auto-correct) - can you send me the debug logs in an issue in https://github.com/rudders/homebridge-platform-wemo please.

**Comment by vincentanthony** [comment]
Having the exact same issue. Running on a Rasp Pi. Any thoughts on what this is?

**Comment by rudders** [comment]
@vincentanthony - are you using homebridge-platform-wemo?

**Comment by vincentanthony** [comment]
No, just nest and harmony hub at the moment.

**Comment by rudders** [comment]
try running `env DEBUG=* homebridge` and post some of the error log that leads up to the error - that should help identify the module that isn't handling this http.request error.

**Comment by benmazin** [comment]
I'm having this error too. Sometimes it happens after a couple of days, others after a couple of hours:
Using homebridge-platform-wemo.

Here are some of the logs:

```
Tue, 29 Dec 2015 02:48:41 GMT EventedHTTPServer [::ffff:10.0.1.30] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Tue, 29 Dec 2015 02:48:41 GMT EventedHTTPServer [::ffff:10.0.1.13] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Tue, 29 Dec 2015 02:48:41 GMT EventedHTTPServer [fe80::1489:e5d7:c839:86a9] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Tue, 29 Dec 2015 02:49:45 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:49:45 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:49:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:49:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:49:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:49:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:49:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:45 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:45 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:51:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Tue, 29 Dec 2015 02:53:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 10.0.1.11:49153
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
```


````
Sun, 03 Jan 2016 08:18:36 GMT EventedHTTPServer [::ffff:10.0.1.30] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sun, 03 Jan 2016 08:18:36 GMT EventedHTTPServer [::ffff:10.0.1.25] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sun, 03 Jan 2016 08:18:36 GMT EventedHTTPServer [::ffff:10.0.1.13] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sun, 03 Jan 2016 08:18:36 GMT EventedHTTPServer [2601:646:8b00:fb19:a2:ab9f:2031:4cde] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:18:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:18:44 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:18:45 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:18:45 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:18:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:20:44 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:45 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:20:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:20:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:22:44 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:45 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:22:46 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:22:46 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120017B, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221448K1300E1C, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221445K1300262, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:insight:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221504K12000B8, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:24:43 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K1200172, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:24:44 GMT wemo-client Renewing subscription - Device: uuid:Insight-1_0-221506K120013A, Service: urn:Belkin:service:basicevent:1
Sun, 03 Jan 2016 08:24:47 GMT wemo-client Renewing subscription - Device: uuid:Lightswitch-1_0-221439K13003D3, Service: urn:Belkin:service:basicevent:1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.0.1.11:49153
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
````

**Comment by AppleTechy** [comment]
@devbobo found where the issue was. It was an issue of the Wemo-client dependency for the plugin. it has now been fixed. I have been running homebridge for the past 5 hrs and haven't had the error yet. You need to replace the contents the client.js with https://raw.githubusercontent.com/timonreinhard/wemo-client/master/client.js 
You will find the client.js at homebridge-platfprm-wemo/node_modules/wemoclient/master/client.js
Tell me if that worked for you. The fix should be pushed to the nam site soon just the Wemo-Client npm has to be updated for the homebridge-platform-wemo npm to be updated for the fix. If that makes any since. So essentially the fix should be mainstream as soon as the Wemo-client NPM page gets updated then enabling @rudders to update the homebridge-platform-wemo plugin.
@benmazin

**Comment by rudders** [comment]
Please update to homebridge-platform-wemo@0.6.1 which will pull the latests wemo-client form a private fork. This will get us out of trouble till wemo-client is updated,

**Comment by AppleTechy** [comment]
@benmazin ^^

**Comment by benmazin** [comment]
Thanks for the update, I've upgraded to 0.6.1, I'll see how it behave over the next few days.

**Comment by benmazin** [comment]
Even running homebridge-platform-wemo@0.6.1 I received the error after. It took 1h50m to appear.
I've attached the full debug logs from starting Homebridge to the error.

[homebridge.err.txt](https://github.com/nfarina/homebridge/files/79881/homebridge.err.txt)

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.0.1.12:49153
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

I'm running:
Raspbian 4.9.2-10
└── homebridge@0.2.13 
└── homebridge-platform-wemo@0.6.1

**Comment by AppleTechy** [comment]
@bemazin Try downloading @devbobo fork of the platform-wemo and delete @rudders plugin. Let us know how that works. The way I described how I got it working worked for me. I haven't updated to @rudders newest version of the platform-wemo plugin. I just have been using a manually edited client.js

**Comment by rudders** [comment]
@benmazin - please make sure you do an pm install -g home bridge-platform-wemo so you pull through the wemo-client from my repo ( dependency that should come through with platform-wemo@0.6.1 )

**Comment by rudders** [comment]
Could you could also run `env DEBUG=* homebridge` and share with us the log just before it crashes so we can be sure it's in this plugin.

**Comment by benmazin** [comment]
@rudders I've upgraded to the latest version as you described:
```
└─┬ homebridge-platform-wemo@0.6.2 
  ├─┬ request@2.67.0
  │ ├─┬ http-signature@1.1.0
  │ │ └─┬ sshpk@1.7.2
  │ │   └── tweetnacl@0.13.3 
  │ └─┬ mime-types@2.1.9 
  │   └── mime-db@1.21.0 
  └── wemo-client@0.6.2 
```

I also upgraded Homebridge to the latest:
```
└─┬ homebridge@0.2.14 
  └─┬ hap-nodejs@0.0.7 
    ├── curve25519@1.1.0  (git://github.com/KhaosT/node-curve25519.git#922eae612bb379fa84e8deb29f80c53d57c8be7b)
    ├── ed25519@0.0.3  (git://github.com/KhaosT/ed25519.git#6356bc9e6e4643d56020293c14920ac12bcaa1ac)
    ├── node-persist@0.0.6 
    └── srp@0.2.0  (git://github.com/KhaosT/node-srp.git#7feff53254897a0b1b9f0667ad17a8beb78acbb9)
```

But I'm still receive the error "events.js:141". Homebrige is crashing and throwing this error extremely frequently.
I've attached some of the DEBUG logs
[Debug Log.txt](https://github.com/nfarina/homebridge/files/80740/Debug.Log.txt)

Any help is appreciate.
Thanks
Ben

**Comment by rudders** [comment]
Thats a different error mate - that looks like a second instance of home bridge trying to be started and they're clashing in listening on that port.

```
Homebridge is running on port 51827.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51827
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
```

**Comment by benmazin** [comment]
thanks for the help, I'm in the process of looking the for instance and cleaning it up.

**Comment by AppleTechy** [comment]
@benmazin I am going to close the issue because the original problem was fixed and this was improperly placed. Feel free to create a separate issue if you need to but make sure you share your debug log or at least the last couple of lines including the error.

**Comment by benmazin** [comment]
Thanks @AppleTechy and @rudders for your help.
I was playing with using forever to keep homebridge running due to the crashes constant, looks like I had it setup running on a different port and hadn't stopped it from auto starting at boot.
I'm back up hopefully no more crashes.

**Comment by AppleTechy** [comment]
@benmazin No problem thats the beauty of open source is everyone helps each other. Good Luck!

**Comment by rudders** [comment]
No worries

**Comment by rudders** [comment]
Anyone experiencing `ETIMEDOUT` errors and that use the `homebridge-platform-wemo` plugin might like to test my forked version of the plugin discussed here https://github.com/rudders/homebridge-platform-wemo/issues/21#issuecomment-171392046 - please update that issue with your findings.
