### ISSUE TITLE
Homebridge won't start

### ISSUE THREAD

**Issue by lbstephane** [nfarina/homebridge#47]
Hi, 

I'm trying to use homebride on my Mac on Yosemite.

Here the message when I try to run server.

homebridge stephane$ node -v
v0.10.13
homebridge stephane$ npm -v
1.3.2
homebridge stephane$ sudo npm run start

> homebridge@0.0.0 start /Developer/homebridge
> node app.js

Starting HomeBridge server...

/Developer/homebridge/lib/HAP-NodeJS/node_modules/ed25519/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Symbol ed25519_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Developer/homebridge/lib/HAP-NodeJS/node_modules/ed25519/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Developer/homebridge/lib/HAP-NodeJS/node_modules/ed25519/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! not ok code 0

any idea ?

**Comment by nfarina** [comment]
Hello, please see https://github.com/KhaosT/HAP-NodeJS/issues/57 and reopen if that doesn't solve your issue, thanks!
