### ISSUE TITLE
Need help with error message. Please.

### ISSUE THREAD

**Issue by thomasbruce** [nfarina/homebridge#473]
Is this message something I need to fix? I'm new to this. Bought a Raspberry Pi 2 to use homebrige and some plugins :)

After hombridge starts at the end of all the "text/code" it says this:

Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:138:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:347:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:229:14)

Hope someone can help me. Thanks!

And thanks for making Homebridge!!

**Comment by KhaosT** [comment]
This means homebridge failed to listen to the port. Please make sure there isn't another instance of homebridge running on your device. If this still happens, please try to edit the config.json and change the port 51826 to a different port.

**Comment by thomasbruce** [comment]
Ok
Thanks for the fast reply! I booted the RP with script to run homebridge at startup. Homebridge was already running when i typed "homebridge" in the command line to see the homekit code to add it as an accessory and to see if my plugins worked. Could that be the cause for the error? running home bridge again when it is running already?

**Comment by KhaosT** [comment]
Yep

**Comment by thomasbruce** [comment]
Cool. Thanks for helping me :)
