### ISSUE TITLE
Cant seem to "sudo npm install -g  homebridge"

### ISSUE THREAD

**Issue by scooter133** [nfarina/homebridge#484]
I'm installing on OS X El Capitan. I installed the npm and node.js from
https://nodejs.org/dist/v4.2.6/node-v4.2.6.pkg

I've done the suggested chown commands (except the /usr/local) and even ran everything under su. 

Below is the output form the install and the debug file. 

$sudo npm install -g  homebridge

```
|
> curve25519@1.1.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found

> ed25519@0.0.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found

> bignum@0.11.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found

> mdns@2.2.11 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! curve25519@1.1.0 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scooter133/npm-debug.log
```

the nam-debug.log has almost 2500 lines in it though I think the relative part is this:

```
2389 info install bignum@0.11.0
2390 verbose unsafe-perm in lifecycle false
2391 info bignum@0.11.0 Failed to exec install script
2392 verbose unlock done using /Users/scooter133/.npm/_locks/bignum-4cb6bb7ac0b4952a.lock for /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
2393 verbose about to build /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp
2394 verbose unlock done using /Users/scooter133/.npm/_locks/srp-5a99e14b524c4f4f.lock for /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp
2395 verbose about to build /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs
2396 verbose unlock done using /Users/scooter133/.npm/_locks/hap-nodejs-ad226527e82daf47.lock     for /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs
2397 verbose about to build /usr/local/lib/node_modules/homebridge
2398 verbose unlock done using /Users/scooter133/.npm/_locks/homebridge-a5618ac2152da688.lock for /usr/local/lib/node_modules/homebridge
2399 verbose stack Error: curve25519@1.1.0 install: `node-gyp rebuild`
2399 verbose stack spawn ENOENT
2399 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
2399 verbose stack     at emitTwo (events.js:87:13)
2399 verbose stack     at ChildProcess.emit (events.js:172:7)
2399 verbose stack     at maybeClose (internal/child_process.js:821:16)
2399 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2400 verbose pkgid curve25519@1.1.0
2401 verbose cwd /Users/scooter133
2402 error Darwin 15.0.0
2403 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
2404 error node v4.2.6
2405 error npm  v2.14.12
2406 error file sh
2407 error code ELIFECYCLE
2408 error errno ENOENT
2409 error syscall spawn
2410 error curve25519@1.1.0 install: `node-gyp rebuild`
2410 error spawn ENOENT
2411 error Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
2411 error This is most likely a problem with the curve25519 package,
2411 error not with npm itself.
2411 error Tell the author that this fails on your system:
2411 error     node-gyp rebuild
2411 error You can get their info via:
2411 error     npm owner ls curve25519
2411 error There is likely additional logging output above.
2412 verbose exit [ 1, true ]
2413 verbose unbuild lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519
2414 info preuninstall curve25519@1.1.0
2415 info uninstall curve25519@1.1.0
2416 verbose unbuild rmStuff curve25519@1.1.0 from /usr/local/lib/node_modules
2417 verbose unbuild rmStuff in /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules
2418 info postuninstall curve25519@1.1.0
2419 silly gentlyRm /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519 is being purged from base /usr/local
2420 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519
2421 silly vacuum-fs purging /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519
2422 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules
```

**Comment by rudders** [comment]
Have you tried - `npm install homebridge -g --unsafe-perm` - a clue from googling and finding  
https://github.com/nodejs/node-gyp/issues/115#issuecomment-28490552

**Comment by AppleTechy** [comment]
Were you able to get this issue resolved?

**Comment by 128keaton** [comment]
I'm having the same issue

**Comment by Connor-Knabe** [comment]
I had the same issue on my RPi. This seemed to fix it for me sudo apt-get install libavahi-compat-libdnssd-dev

**Comment by BuckarooToo** [comment]
Similar issue. Using Macintosh OS 11.4 (El Capitan). XCode installed.
Here's what happens:

gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/_username_/npm-debug.log
npm ERR! code 1

Any help you can offer is appreciated!

**Comment by Edylc** [comment]
BuckarooToo, I'm having the same error.  Did you ever find a solution?

**Comment by BuckarooToo** [comment]
Yes - I had the wrong version of Python. Latest Python 2 version is supported.

**Comment by davispw** [comment]
--unsafe-perm fixed it for me

**Comment by aarocka** [comment]
I had a similiar issue because I wanted to run my instance in a docker container. I got the same error but it was fixed when I installed python.
