### ISSUE TITLE
Homebridge Nest error 

### ISSUE THREAD

**Issue by lewisward1** [nfarina/homebridge#494]
Hello, I installed home bridge and nest and all worked well, i then added lightwaverf and songs but i got a nest error, tried to uninstall the other two and still got the error. uninstalled everything including npm and started from scratch but still same error and driving me crazy - any help would be greatly appreciated as i don't know where to start on troubleshooting this issue. ( i even tried a new beta of Xcode but now back to the stable version) running on mac i get this error

homebridge
Loaded plugin: homebridge-lightwaverf
Registering platform 'homebridge-lightwaverf.LightWaveRF'
---
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded plugin: homebridge-sonos
Registering accessory 'homebridge-sonos.Sonos'
---
Loaded config.json with 0 accessories and 2 platforms.
---
Loading 2 platforms...
Initializing Nest platform...
Fetching Nest devices.
/Users/itunes/.node/lib/node_modules/homebridge/lib/api.js:74
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/Users/itunes/.node/lib/node_modules/homebridge/lib/api.js:74:11)
    at Server._loadPlatforms (/Users/itunes/.node/lib/node_modules/homebridge/lib/server.js:194:45)
    at Server.run (/Users/itunes/.node/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/Users/itunes/.node/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/Users/itunes/.node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
my config file looks like this

{

	"bridge": {
		"name": "Homebridge",
		"username": "XXX",
		"port": 51826,
		"pin": "XXX-45-154"
	},

	"platforms": [

		{

			"platform": "Nest",
			"token": "c.xxx",
			"username": "xxx",
			"password": "xxx"
		},

		{
			"accessories": [{
				"accessory": "Sonos",
				"name": "Bedroom Speakers",
				"room": "Bedroom"
			}]
		}

	]
}

**Comment by dkruyt** [comment]
Your config is wrong, this part

>     {
>        "accessories": [{
>          "accessory": "Sonos",
>           "name": "Bedroom Speakers",
>            "room": "Bedroom"
>        }

ahould be under accessories and not under platforms in the _config.json_

**Comment by lewisward1** [comment]
Thankyou !! Your a star

**Comment by lewisward1** [comment]
Thank you to the person that emailed me and mentioned i have not terminated the platform section and my accessories was part of platforms.
