### ISSUE TITLE
Issues installing on CentOS 5 - fails at ed25519

### ISSUE THREAD

**Issue by dkaimal** [nfarina/homebridge#525]
I have been struggling with homebridge installation on CentOS 5 for a while. I am trying to install by 
`npm install -g homebridge --python=python2.6 --unsafe-perm`
 I have the avahi, avahi-compat-libdns_sd and avahi-compat-libdns_sd-devel ver 0.6.16 packages installed. The error I see is
````
make: Leaving directory `/usr/lib/node_modules/homebridge/node_modules/mdns/build'

> ed25519@0.0.3 install /usr/lib/node_modules/homebridge/node_modules/ed25519
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.18-371.3.1.el5
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/ed25519
gyp ERR! node -v v0.10.42
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
install:nan               â
install:nan               â â¢ââââââââââââââââââââââââââââââââââââââââââââââââââ
/usr/lib
âââ (empty)

npm ERR! Linux 2.6.18-371.3.1.el5
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "homebridge" "--python=python2.6" "--unsafe-perm"
npm ERR! node v0.10.42
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519@0.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ed25519
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
````

**Comment by dkaimal** [comment]
I was able to solve with the following two steps
1. Update npm `` npm install -g npm@latest --python=python2.6 --unsafe-perm``
2. Install Python 2.7.3 using the instructions at https://gist.github.com/stantonk/4082043 
I was able to install on CentOS 5 with ``npm install -g homebridge --python=python2.7 --unsafe-perm``

**Comment by AppleTechy** [comment]
Since you got it to work would you do a write up on the homebridge wiki of
the steps you had to take to get it to install for CentOS 5? Not sure if
anyone else has plans to use CentOS 5 but might as well document it so your
efforts don't get lost in the many issues of the project on Github
