### ISSUE TITLE
Service don't start after raspbian jessie upgrade

### ISSUE THREAD

**Issue by movitch** [nfarina/homebridge#526]
Hi,

After upgrading raspbian Jessie today, homebridge don't start. 

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at Server.listen (net.js:1359:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:138:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:437:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:42:10)

**Comment by AppleTechy** [comment]
Try changing your port number. That error is caused when there is already
something on the port that you have set in your config

**Comment by rudders** [comment]
I'd say homebridge has started which is your issue. Do you have something set up to auto start it on boot? if you do I'd say it's working.

**Comment by movitch** [comment]
Thanks for your answers. I found the problem this morning. It's not after raspbian jessie update but after a Jeedom plugin update. This plugin (btsniffer) install a new version of node.js and after installation homebridge don't start.
After uninstall btsniffer and all dependencies, homebridge is OK.
Thanks for your help

**Comment by rudders** [comment]
So longs as it's all sorted  might be good to close this issue then if you wouldn't mind.
