### ISSUE TITLE
homebridge crashes after about 8 hours here is error message

### ISSUE THREAD

**Issue by Slepperpon** [nfarina/homebridge#528]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::54827
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at new EventedHTTPServerConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:125:20)
    at EventedHTTPServer._onConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:79:20)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
    at TCP.onconnection (net.js:1427:8)

**Comment by AppleTechy** [comment]
Not sure why you would be getting that error after running homebridge for 5
hrs. That error is caused when there is something else using the port that
you have set in your config. You might want to try changing the port you
have set in your config

**Comment by Slepperpon** [comment]
thank you i will try that

Date: Mon, 15 Feb 2016 09:12:48 -0800

**Comment by Slepperpon** [comment]
Changed port now after a few hours get this?

/usr/local/lib/node_modules/homebridge-smartthings/index.js:70
            } else if (myList.error) {
                             ^

TypeError: Cannot read property 'error' of undefined
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:70:30
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:27)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by KhaosT** [comment]
this is a problem caused by SmartThings’s plugin. Please contact plugin developer for this.

Best Wishes,
Tian

**Comment by Slepperpon** [comment]
Ok thank you for fast reply. 

Adam Hoffman
District Team Lead
District 9445
NTB 892
