### ISSUE TITLE
Error installing Homebridge on Windows 10

### ISSUE THREAD

**Issue by yrb0107** [nfarina/homebridge#531]
Hello All,

I followed the instructions in the site below and getting an error installing home bridge via git cmd 
https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows:-New-version-(with-Plugin)

Here is the error:
```
C:\Users\Rakesh>npm install -g homebridge
|
> curve25519@1.1.0 install C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\curve25519
> node-gyp rebuild


C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\curve25519>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_mo
dules\hap-nodejs\node_modules\curve25519\build\curve.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\n
ode_modules\hap-nodejs\node_modules\curve25519\build\curve.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\curve25519
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bignum@0.11.0 install C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum
> node-gyp configure build


C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node  configure build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_mo
dules\hap-nodejs\node_modules\srp\node_modules\bignum\build\bignum.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\n
ode_modules\hap-nodejs\node_modules\srp\node_modules\bignum\build\bignum.vcxpro
j]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> ed25519@0.0.3 install C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\ed25519
> node-gyp rebuild


C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\ed25519>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_mo
dules\hap-nodejs\node_modules\ed25519\build\ed25519.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\n
ode_modules\hap-nodejs\node_modules\ed25519\build\ed25519.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\ed25519
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> mdns@2.2.11 install C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\mdns
> node-gyp rebuild


C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_mo
dules\hap-nodejs\node_modules\mdns\build\dns_sd_bindings.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\n
ode_modules\hap-nodejs\node_modules\mdns\build\dns_sd_bindings.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rakesh\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\node_modules\mdns
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! curve25519@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rakesh\npm-debug.log


```

[npm-debug.txt](https://github.com/nfarina/homebridge/files/135143/npm-debug.txt)

Kindly Help!!!

**Comment by PatcherMustermann** [comment]
Hello,
you have a problem with the vs2015.

You read this:
https://github.com/nodejs/node-gyp/issues/694
https://github.com/nodejs/node-gyp/issues/422

**Comment by PatcherMustermann** [comment]
It's running?

**Comment by PatcherMustermann** [comment]
I think, the Admin close this issues...

**Comment by AppleTechy** [comment]
@patchermustermann I will close it it the issues was resolved..?

**Comment by PatcherMustermann** [comment]
I guess so. It's got no answer...
