### ISSUE TITLE
Repeated Econ Resets

### ISSUE THREAD

**Issue by realdannys** [nfarina/homebridge#542]
```
Error: read ECONNRESET
at exports._errnoException (util.js:856:11)
at TCP.onread (net.js:544:26)
events.js:141
  throw er; // Unhandled 'error' event
  ^
```

Keep getting the same error repeated over and over throughout the error log.

**Comment by rudders** [comment]
A bit more of the log file might help determine the device throwing the error and hence the plugin that is not handling this TCP/IP error. Can you provide more before and after or ideally the entire log from starting homebridge.

**Comment by realdannys** [comment]
Will do rudders - i'm having an utter nightmare with Homebridge recently - it used to work fine, now it works for about 30 minutes and totally breaks. I'm getting devices duplicating in homekit, i'm getting stuff stopping working quickly and in the case of your Wemo platform plugin it just wont find the one socket i've got and then crashses. It's becoming unusable unfortunately and yet the old versions worked fine for months!

**Comment by realdannys** [comment]
I'm going to add the duplicating devices to this though - there's no easy way to delete them either...or if I delete them it deletes everything and then I have to start from scratch and delete the persist file in OS X as well :(

**Comment by rudders** [comment]
Can you see that WEMO device okay in the WEMO app?
Try this utility and see if it can be seen at all from your Homebridge server. 
https://github.com/rudders/wemo-discover

**Comment by realdannys** [comment]
Sure works perfectly in the Wemo app and with SmartThings (and it used to work perfectly with the old Wemo accessories plugin too...in fact Wemo was the fastest acting thing on my network)

I'll test the wemo-discover

**Comment by realdannys** [comment]
@rudders 

I just got this unfortunately

    [mac-mini:wemo-discover Mac-mini$ node index.js
    events.js:154
      throw er; // Unhandled 'error' event
      ^

    TypeError: Cannot read property '0' of undefined
    at /Users/Mac-mini/node_modules/wemo-discover/index.js:21:42
    at Parser.<anonymous> (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.onclosetag (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/Users/Mac-mini/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Users/Mac-mini/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/Users/Mac-mini/node_modules/sax/lib/sax.js:903:7)
    at Object.write (/Users/Mac-mini/node_modules/sax/lib/sax.js:1444:13)
    at Parser.exports.Parser.Parser.parseString (/Users/Mac- mini/node_modules/xml2js/lib/xml2js.js:503:31)`

**Comment by rudders** [comment]
That's odd - it's a pretty rudimental tool - what wemo devices do you have?

**Comment by rudders** [comment]
I've made a small change - update the module https://github.com/rudders/wemo-discover and try again please. Will just tell us what the device is before it explodes I expect..

**Comment by realdannys** [comment]
No change i'm afraid Rudders. I've just got one single Wemo socket (not the insight). I'm in the UK too if that makes any difference. Have run Homebridge overnight with Wemo module turned off and there are no error messages or crashes in the morning. I've still got the doubled entries (there appears no easy to clear those out without deleting everything and adding again?)

    mac-mini:wemo-discover Mac-mini$ node index.js
    events.js:154
      throw er; // Unhandled 'error' event
      ^

    TypeError: Cannot read property '0' of undefined
    at /Users/Mac-mini/node_modules/wemo-discover/index.js:21:42
    at Parser.<anonymous> (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.onclosetag (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/Users/Mac-mini/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Users/Mac-mini/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/Users/Mac-mini/node_modules/sax/lib/sax.js:903:7)
    at Object.write (/Users/Mac-mini/node_modules/sax/lib/sax.js:1444:13)
    at Parser.exports.Parser.Parser.parseString (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:503:31)

**Comment by realdannys** [comment]
Looks like my install didn't overwrite the last one so I tried it again (i'm always confused with npm if to do standard, global, sudo standard or sudo global - they all seem to install in different places!)

Anyway - for some reason it seem so to think my Hue hub is a Wemo device!

    mac-mini:wemo-discover Mac-mini$ node index.js
Wemo Philips hue bridge 2015 found: Philips hue (192.168.0.48) (http://192.168.0.48:80/description.xml)
    events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '0' of undefined
    at /Users/Mac-mini/node_modules/wemo-discover/index.js:22:42
    at Parser.<anonymous> (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.onclosetag (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/Users/Mac-mini/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Users/Mac-mini/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/Users/Mac-mini/node_modules/sax/lib/sax.js:903:7)
    at Object.write (/Users/Mac-mini/node_modules/sax/lib/sax.js:1444:13)
    at Parser.exports.Parser.Parser.parseString (/Users/Mac-mini/node_modules/xml2js/lib/xml2js.js:503:31)

**Comment by realdannys** [comment]
Any idea with this @rudders - Homebridge has been running stable for me now since I turned off the Wemo platform. But id quite like to have my Wemo switch up on and running.

**Comment by rudders** [comment]
That probably explains the plugin issue! It's trying to manage a hue as a WEMO which is very odd. Node-ssdp is finding a hue that thinks it's a WEMO. Have you tried restarting your router? Maybe an ip conflict is causing the error. I'm overseas on business so apologies for the slow response.

Can you try an ios network scanner to scan your network and see what devices can see and compare that to the results is WEMO-discover?

**Comment by realdannys** [comment]
@rudders - yeah routers have been reset. The Wemo-discover doesn't find anything, just the Hue hub and then the crash message. So its hard to compare it to anything.
