### ISSUE TITLE
Custom accessory Plugin

### ISSUE THREAD

**Issue by anthonycastelli** [nfarina/homebridge#544]
I'm not sure if I should be posting this here, but I'm not sure where to look for help on this. I've building or rather built a plugin that will control my janky thermostat. When I try and run home bridge pointing to a directory with the custom plugin, I get this error

```
====================
ERROR LOADING PLUGIN homebridge-mpowered-thermostat-accessory:
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:77:14)
    at Array.forEach (native)
====================
```
`Error: The requested accessory 'Thermostat' was not registered by any plugin.`

I have checked my plugins source a few times I can find any any thing that would cause it to break. I've never worked with node or js in general so I'm learning as I go. Is there something I am overlooking or missing?

**Comment by tekuonline** [comment]
You can chat with most of plugin authors, and other good peoples in our [Slack instance.](homebridgeteam.slack.com) 
It will be a great place for you to get any help!

**Comment by anthonycastelli** [comment]
@tekuonline Alright thanks!! I'll drop by and see if anyone can help me out with my issue. Thanks.
