### ISSUE TITLE
Homebridge keeps crashing. Any idea what is causing this?

### ISSUE THREAD

**Issue by TheHavocHero** [nfarina/homebridge#551]
I have the server running in a Docker Container on my Synology NAS and the server will run for a while and then crash. After a reboot of the NAS, it will not immediately start and crashes with the same error. It does function for a while. Any idea what this crash might be from?

```
Homebridge is running on port 51826.
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,


Error: dns service error: unknown
  at Error (native)
  at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
  at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
  at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
  at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-  nodejs/lib/Accessory.js:498:20)
  at emitNone (events.js:80:13)
  at HAPServer.emit (events.js:179:7)
  at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-  nodejs/lib/HAPServer.js:169:8)
  at emitNone (events.js:80:13)
  at EventedHTTPServer.emit (events.js:179:7)
```

**Comment by TheHavocHero** [comment]
FYI. After loading the latest RC candidate for the Synology DSM 6, all my weird problems went away. No more crashes.
