### ISSUE TITLE
crash at startup with Fibaro HC2

### ISSUE THREAD

**Issue by dg1yds** [nfarina/homebridge#556]
Hello,

the homebridge does not start with Fibaro HC2 connected.
Do you have any ideas to fix the issue?

Thanks.

[FibaroHC2] Found: com.fibaro.temperatureSensor
[FibaroHC2] Found: HC_user
[FibaroHC2] Found: HC_user
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: HC_user
[FibaroHC2] Found: weather
[FibaroHC2] Found: com.fibaro.zwavePrimaryController
[FibaroHC2] Initializing platform accessory 'Temperatur'...
[FibaroHC2] Initializing platform accessory 'Temperatur'...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:216
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 647efa6a-2ed2-4cac-a7b1-cb2e3bfbc36e
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:216:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:346:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Request._callback (/usr/lib/node_modules/homebridge-fibaro-hc2/index.js:208:9)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fibaro-hc2/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fibaro-hc2/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-fibaro-hc2/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)

**Comment by dg1yds** [comment]
@all: renaming of the duplicate names fix the problem - its no homebridge / fibaro plugin issue.
