### ISSUE TITLE
Homebridge is suddenly coming with errors, used to work fine

### ISSUE THREAD

**Issue by corvankruchten** [nfarina/homebridge#571]
Running Homebridge on my Raspberry Pi worked fine, but suddenly comes with an error after a reboot:
What could be wrong? Homebridge seems to be running when asked status, but accessories are not reachable.

Thanx for the help.

Cor

Snipping from log-file:

Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:132:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:347:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:229:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:225:6
    at /usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:232:17
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:214:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by AppleTechy** [comment]
That means there is something else using the port homebridge wants to use.
Most of the time this is due to accidentally having 2 different homebridge
process running.
>
>

**Comment by corvankruchten** [comment]
AppleTechy: thank you for your reply. 
I did a reboot several times, with no result. What can I do?

**Comment by corvankruchten** [comment]
I solved it: it was an issue of IOS 9.3: I had to reinstall homekit to my iPhone.

**Comment by AppleTechy** [comment]
Sorry for not responding, I didn't get email notifications till u had figured everything out already. Glad you got it working.
