### ISSUE TITLE
Please help! Driving me mad!

### ISSUE THREAD

**Issue by miguelmolez** [nfarina/homebridge#581]
I've set up the bridge and without the config.son file it works and will pair with my iPhone.
I've tried to set up the config.json but i keep getting 'There was a problem reading your config.json file.
[3/23/2016, 8:55:47 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com'

I've checked it on http://jsonlint.com' but I'm non the wiser.

Here is my config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
       {
         "platform": "PhilipsHue",
         "name": "Philips Hue",
         "ip_address": 192.168.1.199
         }
   ]

**Comment by KraigM** [comment]
Prob the missing `}` at the end.  

PS https://github.com/KraigM/HomeBridgeController its still a work in progress but it should help :smile:

**Comment by pdlove** [comment]
@miguelmolez The IP Address needs to be in quotes... And what @KraigM said.

**Comment by miguelmolez** [comment]
Thanks guys. At the end of what sorry?

**Comment by miguelmolez** [comment]
does this look right?
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
       {
         "platform": "PhilipsHue",
         "name": "Philips Hue",
         "ip_address": "192.168.1.199"
         }

**Comment by miguelmolez** [comment]
this is the whole error! 
Last login: Wed Mar 23 21:44:13 on ttys000
Michaels-MBP-2:~ michaelhatton$ homebridge
[3/23/2016, 9:46:55 PM] Loaded plugin: homebridge-philipshue
[3/23/2016, 9:46:55 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[3/23/2016, 9:46:55 PM] ---
[3/23/2016, 9:46:55 PM] There was a problem reading your config.json file.
[3/23/2016, 9:46:55 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[3/23/2016, 9:46:55 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:176
    throw err;
    ^

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:170:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
Michaels-MBP-2:~ michaelhatton$

**Comment by KhaosT** [comment]
I highly encourage you use [JSONLint](http://jsonlint.com/)

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "PhilipsHue",
		"name": "Philips Hue",
		"ip_address": "192.168.1.199"
	}]
}
```

**Comment by miguelmolez** [comment]
Thanks very much, i'm now further than I was. I'm a complete novice! I tried to add the username following adding the Hue Bridge but the structure is wrong, i've tried to restructure in JSONlint but it comes back with an error again. I'm really stuck!

**Comment by miguelmolez** [comment]
example
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "PhilipsHue",

		"name": "Philips Hue",
		"ip_address": "192.168.1.199"
                "username": ""7MbJQ0nTMg2W7sxAp-Zfdorl-G1T-MXzPRkultCB"
        }]
}

**Comment by KhaosT** [comment]
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "PhilipsHue",
		"name": "Philips Hue",
		"ip_address": "192.168.1.199",
		"username": "7MbJQ0nTMg2W7sxAp-Zfdorl-G1T-MXzPRkultCB"
	}]
}
```

**Comment by miguelmolez** [comment]
Thanks a lot guys! Still learning! :)

**Comment by miguelmolez** [comment]
Guys everything is working as it should, but now its not pairing with my iphone! I've tried different apps but to no avail??

**Comment by miguelmolez** [comment]
root@raspberrypi:~# homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/24/2016, 8:57:02 PM] Loaded plugin: homebridge-philipshue
[3/24/2016, 8:57:02 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[3/24/2016, 8:57:02 PM] ---
[3/24/2016, 8:57:02 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/24/2016, 8:57:02 PM] ---
[3/24/2016, 8:57:02 PM] Loading 1 platforms...
[3/24/2016, 8:57:02 PM] [Philips Hue] Initializing PhilipsHue platform...
[3/24/2016, 8:57:02 PM] [Philips Hue] PhilipsHue Platform Plugin Version 0.0.2
[3/24/2016, 8:57:02 PM] [Philips Hue] Fetching Philips Hue lights...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'Table lamp'...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'Left wall light'...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'Right wall light'...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'LightStrips 1'...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'LightStrips 2'...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'LightStrips 3'...
[3/24/2016, 8:57:03 PM] [Philips Hue] Initializing platform accessory 'LightStrips 4'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[3/24/2016, 8:57:03 PM] Homebridge is running on port 51826.

**Comment by miguelmolez** [comment]
Got it working! Woohoo

**Comment by lad1337** [comment]
Please close the issue ^^
