### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by benw525** [nfarina/homebridge#603]
What does this mean and how can I fix it?

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:68:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
raw message <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

**Comment by snowdd1** [comment]
As it says `/usr/local/lib/node_modules/homebridge-wink` I would recommend to post it at the homebridge-wink's issues.

**Comment by benw525** [comment]
Thanks for the help! I was wondering which would be the appropriate place to ask. I'll move over there!
