### ISSUE TITLE
EADDRINUSE Error

### ISSUE THREAD

**Issue by MBj1703** [nfarina/homebridge#605]
I used the old version with success, now did an upgrade and homebridge isn't starting anymore:

```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2016-04-10 23:36:35] Loaded plugin: homebridge-fhem
homebridge API version: 2
[2016-04-10 23:36:35] Registering platform 'homebridge-fhem.FHEM'
[2016-04-10 23:36:35] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2016-04-10 23:36:35] Homebridge is running on port 51826.
Server error: Error: listen EADDRINUSE :::8082
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1230:14)
    at listen (net.js:1266:10)
    at Server.__dirname.Server.Server.listen (net.js:1362:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:479:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:82:10)
```

What could be the problem?

**Comment by AppleTechy** [comment]
Kill all homebridge processes and restart. Check wiki for more info

**Comment by MBj1703** [comment]
There is no homebridge process running

**Comment by AppleTechy** [comment]
Check the wiki troubleshooting page for more info on the error code

**Comment by DaronLord** [comment]
I am experiencing the same problem.

**Comment by AppleTechy** [comment]
@daronlord Check the wiki for troubleshooting and if you still have a the problem let me know.

**Comment by DaronLord** [comment]
[4/14/2016, 11:54:05 PM] Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:479:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:351:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:141:6
    at process._tickCallback (node.js:356:9)

**Comment by DaronLord** [comment]
I think I figured out my issue.  I am running home bridge on a raspberry pi and was using PM2 to make it run at startup.  I am guessing that the newest version doesn't require PM2.  A process appears to start automatically.  I stopped it from running under PM2 and now I can see the device to configure in my HomeKit app.  However, now I am getting and error stating the setup code is incorrect.  When I input the default "987-65-432" it does not work.  This is what I still configured in my config.json but it will not accept it.

**Comment by AppleTechy** [comment]
@DaronLord Have you tried deleting the persist folder on the RPI? And are you sure you're editing the config under ```./homebridge```?

**Comment by macguy67** [comment]
I am have a problem I am a new to this.  Perhaps you could help?

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at Server.listen (net.js:1378:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22iMac-36-i5:~

**Comment by macguy67** [comment]
I have deleted the persist and the accessories directory.  I also removed the config.json file
