### ISSUE TITLE
Homebridge not warning about missing config.json

### ISSUE THREAD

**Issue by WiildchiilD** [nfarina/homebridge#616]
Hey guys,
having homebridge installed on my PI successfuly without any error, juste after the setup, i run homebridge, it told that no plugins founds, but not about missing config.json. And for sure config.json is not in homebridge directory.
I'am asking for this, because on my first homebridge setup, i was editing the config file and nothing seems to be changing, so i deleted the config file, and homebridge still not warning me about, so i uninstall all , and reinstall only homebridge, still same issue, any help please.

**Comment by luc-ass** [comment]
did you install some plugin and tried again? Perhaps Homebridge only looks for the config.json if there is any plugin.

**Comment by WiildchiilD** [comment]
Yes, i just did ! i installed homebridge-http. 
The main problem i faced, and i'm facing it again, is that home bridge doesn't find any accessory.
Startup logs like this : Loaded plugin homebridge-http
registering accessory 'homebridge-http.http'
---
scan this code with you homekit ..
and my config file :
`{
"bridge": {

"name": "Homebridge",

"username": "CC:22:3D:E3:CE:30",

"port": 51826,

"pin": "031-45-154"

},

"platforms": [

],

"accessories": [

{

"accessory": "Http",

"name": "Living Room Lamp",

"on_url": "http://192.168.1.201:80/?on",

"off_url": "http://192.168.1.201:80/?off",

"http_method": "GET"

}

]

}`

**Comment by luc-ass** [comment]
I assume everything is insatlled globally?

**Comment by WiildchiilD** [comment]
Globally ? how ? i think ..

**Comment by luc-ass** [comment]
did you add the "-g" to your npm install?

**Comment by WiildchiilD** [comment]
yes sure !! everything i installed, globally '-g' :)

**Comment by luc-ass** [comment]
Just to understand this correct: Homebridge says that there are no plugins installed?

**Comment by WiildchiilD** [comment]
No, here s a screen 
![homeb](https://cloud.githubusercontent.com/assets/9802667/14884031/1a6ea4f8-0d3a-11e6-84b7-ac2472f42d7a.png)

**Comment by luc-ass** [comment]
Looks fine to me. What's the problem?

**Comment by WiildchiilD** [comment]
ain't missing those line ? : 
(---)
Loaded config.json with 1 accessories and 0 platforms.
---
Loading 0 platforms...
Loading 1 accessories...
[Back Door ie ] Initializing Lockitron accessory ie...

**Comment by luc-ass** [comment]
can you navigate to the Folder homebridge and the plugins are stored in and post what `ls -l` gives you?

**Comment by WiildchiilD** [comment]
here you go.
plugins are installed in same parent directory of homebridge
![cddhome](https://cloud.githubusercontent.com/assets/9802667/14884214/23c63178-0d3b-11e6-9e47-4c98997b2578.png)

**Comment by luc-ass** [comment]
one folder up ;) I'd like to see the content of node_modules

**Comment by WiildchiilD** [comment]
here
![homeb](https://cloud.githubusercontent.com/assets/9802667/14884305/ba8a5436-0d3b-11e6-817e-ba98f07fc118.png)

**Comment by luc-ass** [comment]
Ah! See? There is no lockitron in there. You probably installed it using different that what you did with homebridge and homebridge-http. Did you use sudo in one case but not in the other?

**Comment by WiildchiilD** [comment]
i just checked my last commands, homebridge and homebridge-http were both installed with sudo npm install -g ... !

**Comment by luc-ass** [comment]
so target of all this is to run http and lockitron, right?

**Comment by WiildchiilD** [comment]
i think you missunderstand me later when i post this :
ain't missing those lines ? : 
(---)
Loaded config.json with 1 accessories and 0 platforms.
(---)
Loading 0 platforms...
Loading 1 accessories...
[Back Door ie ] Initializing " Lockitron " accessory ie...

And i think i have missunderstand Homebridge system
* My case : i just want to be able to request arduino with http command.
so i installed homebridge-http, i configured it like Json posted before. i can pair with it with iOS app but unable to control it with siri , saying that there's no living room lamp

**Comment by luc-ass** [comment]
can you add `"service" : "light"` to your http config?

**Comment by luc-ass** [comment]
This is what exposes it as a lamp ;)

**Comment by WiildchiilD** [comment]
Okay, this is the json file : 
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"platforms": [
],
"accessories": [
{
"accessory": "Http",
"name": "Living Room Lamp",
"on_url": "http://192.168.1.201:80/?on",
"off_url": "http://192.168.1.201:80/?off",
"http_method": "GET",
"service": "light"
}
]
}

I'am using insteon+ app : can you help me out configuring the app please.
The app get the device name : homebridge, and then there is siri control : i put light.
when i ask siri to turn the light, her response, sorry D, there no light .

**Comment by luc-ass** [comment]
hm. where is your config.json located?

you could also try the eve-app. it is much clearer about the types.

**Comment by WiildchiilD** [comment]
I tried with insteon+ , eve, avea , and siri still not find " the device name " 
I followed this tuto : http://www.instructables.com/id/Arduino-and-Apple-HomeKit-Integration-Control-Your/?ALLSTEPS
after some debugging : App are sending request asking for data ie ( screen ) and it's seems like this data aren't in the config file so maybe they are causing the probleme.
![scree](https://cloud.githubusercontent.com/assets/9802667/14885161/d6fcf1cc-0d41-11e6-9a6c-c94dd002eb55.png)

**Comment by WiildchiilD** [comment]
And here is homebridge not warning me about missing config.json file
![withou](https://cloud.githubusercontent.com/assets/9802667/14885466/644a901a-0d43-11e6-95fd-06d3906ada85.png)

**Comment by luc-ass** [comment]
but why do you expect it to be missing? it should be usr/local/.homebridge/

**Comment by WiildchiilD** [comment]
is this normal ?
![sans titre](https://cloud.githubusercontent.com/assets/9802667/14885704/c7b37184-0d44-11e6-8f19-8189a12b6b69.png)

**Comment by luc-ass** [comment]
hm i would think you could use `find / -Name 'config.json'` to find the location of your files

**Comment by luc-ass** [comment]
(name small)

**Comment by WiildchiilD** [comment]
Nothing suspicious ! i put config.json back in homebridge directory ..
![sans titre](https://cloud.githubusercontent.com/assets/9802667/14886130/22300922-0d47-11e6-8a2a-f3bec39d1fe8.png)

**Comment by luc-ass** [comment]
okay. strange. the config file hould in your case be placed in home/pi/.homebridge/
try creating a folder there and paste your config in this folder.

**Comment by WiildchiilD** [comment]
Thank you so much , for all your dedicated time i realy appreciate man :+1: i made it :dancers: ! now it loads platforms and accessories and for sure my Device name. this is it : "  home/pi/.homebridge/ " :D
Thank you so much :D

**Comment by luc-ass** [comment]
no problem. allways happy to help out.

**Comment by bentheone** [comment]
I have the same problem WiildchiilD had, but I used the following guide for autostarting homebridge:
https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a

So my config.json is under /var/homebridge and not in the user folder.
I only get the following lines:

```
[9/21/2016, 7:55:43 PM] Loaded plugin: homebridge-philipshue
[9/21/2016, 7:55:43 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[9/21/2016, 7:55:43 PM] ---
[9/21/2016, 7:55:44 PM] Loaded plugin: homebridge-sonos
[9/21/2016, 7:55:44 PM] Registering accessory 'homebridge-sonos.Sonos'
[9/21/2016, 7:55:44 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

┌────────────┐     
│ 031-45-154 │     
└────────────┘     
[9/21/2016, 7:55:44 PM] Homebridge is running on port 51826.
```

**Comment by richierockskool** [comment]
I have a similar problem that I can get past.

[8/6/2022, 5:53:16 PM] ====================
[8/6/2022, 5:53:16 PM] ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway:
[8/6/2022, 5:53:16 PM] /Users/richjagger/Documents/GitHub/Hombridge-Inkbird-Wifi-Gateway/dist/index.js:2
import { PLATFORM_NAME } from "./settings";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:141:22)
[8/6/2022, 5:53:16 PM] ====================

**Comment by richierockskool** [comment]
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/which/which.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by richierockskool** [comment]
and 

No plugin was found for the platform "homebridge-inkbird-wifi-gateway" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by richierockskool** [comment]
ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway:
[4/20/2023, 5:50:40 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/src/index.js' imported from /usr/local/lib/node_modules/homebridge/lib/plugin.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1186:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21)
