### ISSUE TITLE
username "like a MAC address" error, solution on readme doesn't work.

### ISSUE THREAD

**Issue by DancinDirk** [nfarina/homebridge#634]
Hey All, 

Trying to set this up for the first time and am running into a problem. I've tried the solution listed in the readme but still nothing.

> iOS device has gotten your Homebridge username (looks like a MAC address) "stuck" somehow, where it's in the database but inactive. Fix: change your username in the "bridge" section of config.json to be some new value.

I've tried changing the username in the config.json file but still nothing.

`Mac-mini:~ dirk$ homebridge
[5/19/2016, 8:56:39 PM] Loaded plugin: homebridge-lifx
[5/19/2016, 8:56:39 PM] Registering accessory 'homebridge-lifx-bulb.LIFxBulb'
[5/19/2016, 8:56:39 PM] Registering platform 'homebridge-lifx.LIFx'
[5/19/2016, 8:56:39 PM] ---
[5/19/2016, 8:56:39 PM] Loaded plugin: homebridge-nest
[5/19/2016, 8:56:39 PM] Registering platform 'homebridge-nest.Nest'
[5/19/2016, 8:56:39 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:184
      throw new Error('Not a valid username: ' + username + '. Must be 6 pairs of colon-' +
      ^

Error: Not a valid username: undefined. Must be 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address.
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:184:13)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
Mac-mini:~ dirk$ 
`

I also tried searching previous topics but nothing so far. Anyone have any advice?

**Comment by toshibochan** [comment]
6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address.
A-F 0-9
Only A to F no more than F

**Comment by DancinDirk** [comment]
> 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address.
A-F 0-9 Only A to F no more than F

But where does this go?

**Comment by toshibochan** [comment]
Config.json! What you usin? Mac, Windows, Linux or raspberry pi?

**Comment by DancinDirk** [comment]
Well there we go... I was using an outdated config.json from a tutorial on a different site. It was missing username entirely.

**Comment by toshibochan** [comment]
Now working?

**Comment by DancinDirk** [comment]
Appears to be, yes!

Now to figure out why my Nest is showing Celsius when I have it set to F

**Comment by toshibochan** [comment]
Siri give you temperature in Celsius?

**Comment by toshibochan** [comment]
I have set my nest to Celsius but Siri only give me temperature in F!

**Comment by guillaume1410** [comment]
Did you add             "temperature_unit": "C"
 in your config.json ?

**Comment by DancinDirk** [comment]
Haven't tried Siri yet, but this is what's showing in terminal, and in the HMCatalog app, it is NOT 22 Degrees in here!! ha!

`[5/19/2016, 9:18:53 PM] Away for Nest02AA01AC181508K6 is: false
[5/19/2016, 9:18:53 PM] Current humidity for Nest02AA01AC181508K6 is: 47
[5/19/2016, 9:20:00 PM] Current heating for Nest02AA01AC181508K6 is: 0
[5/19/2016, 9:20:00 PM] Target heating for Nest02AA01AC181508K6 is: 2
[5/19/2016, 9:20:00 PM] Current temperature for Nest02AA01AC181508K6 is: 21.92
[5/19/2016, 9:20:00 PM] Target temperature for Nest02AA01AC181508K6 is: 22.22222222222222
[5/19/2016, 9:20:00 PM] Temperature unit for Nest02AA01AC181508K6 is: Fahrenheit`

**Comment by DancinDirk** [comment]
This is my config.json

`{
	"bridge": {
		"name": "homebridge",
		"username": "CC:22:3D:E3:CE:20",
		"port": 51826,
		"pin": "987-65-432"
	},

	"platforms": [{
		"platform": "Nest",
		"username": "dancindirk@gmail.com",
        "password": "#####"
	}]
}
`

**Comment by toshibochan** [comment]
I don't know we can add "temperature_unit":"C"!
I will try when I get back home

**Comment by guillaume1410** [comment]
try this
"platforms": [{
    "platform": "Nest",
    "username": "dancindirk@gmail.com",
    "password": "#####"
     "temperature_unit": "C"
}]
 
it works for a wink hub

**Comment by toshibochan** [comment]
Thanks @guillaume1410

**Comment by DancinDirk** [comment]
I tried that but with "F" and I'm still getting readings in the 20s.

However if I ask siri to set the temp in F it does work. now to work on that name readout...

![2016-05-19 21 29 26](https://cloud.githubusercontent.com/assets/414755/15414598/220da336-1e0a-11e6-8693-1ef05b1fec7f.png)

**Comment by GreenyDev** [comment]
@DancinDirk Can't you set the name of the Nest in the HMCatalog App?

**Comment by DancinDirk** [comment]
I have updated it in the Catalog but it still reads out the old name.

**Comment by domeniquemalone** [comment]
@DancinDirk my Devices app says "Couldn't add Homebridge" what am I missing? Which MAC address do I add?

**Comment by greenywd** [comment]
@domeniquemalone you can just use the address included in the [config-sample.json](https://github.com/nfarina/homebridge/blob/master/config-sample.json) file. I usually just grab the sample config when setting up homebridge and add whatever I need from there.
