### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by ezfe** [nfarina/homebridge#664]
```
$ npm -v
3.9.3
```

```
$ node -v
v6.2.1
```

```
$ homebridge
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at new require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by b3nk3** [comment]
try this:

`sudo apt-get purge nodejs npm`
`sudo apt-get install -y nodejs`

[credit]( http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts)
