### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by FireBall1725** [nfarina/homebridge#667]
Hello,
When trying to install, i get the following error:
```
npm WARN lifecycle bignum@0.12.2~preinstall: cannot run in wd %s %s (wd=%s) bignum@0.12.2 npm install node-pre-gyp /usr/lib/node_modules/.staging/bignum-39af7bf9
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /usr/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp"
make: Entering directory `/usr/lib/node_modules/homebridge/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory `/usr/lib/node_modules/homebridge/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-59-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/usr/lib
└── (empty)

npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
```

I saw the directions about adding the --unsafe-perm, but then I get:
```
> bignum@0.12.2 preinstall /usr/lib/node_modules/.staging/bignum-39af7bf9
> npm install node-pre-gyp

/usr/bin/node-pre-gyp -> /usr/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
/usr/lib
└── node-pre-gyp@0.6.28

/usr/lib
└── (empty)

npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge" "--unsafe-perm"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! path /usr/lib/node_modules/.staging/abbrev-3f3fcfa2
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-3f3fcfa2' -> '/usr/lib/node_modules/homebridge/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-3f3fcfa2' -> '/usr/lib/node_modules/homebridge/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

```
Any help would be great in installing this.

I am using Ubuntu 14.04 Server.

Thanks

**Comment by mattrayner** [comment]
Hi @FireBal1725, you're missing a step that's required on Debian based systems:

**Comment by FireBall1725** [comment]
@mattrayner what step is that?

**Comment by FireBall1725** [comment]
@mattrayner that worked! Thank you for your help!
