### ISSUE TITLE
SONOS Plugin

### ISSUE THREAD

**Issue by Sjekke** [nfarina/homebridge#678]
Hi there, I'm a newbie on this forum. I installed Homebridge on a Mac Mini incl. the homebridge-legacy-plugins. I made a simple config.json file to connect my SONOS speakers. But after firing up Homebridge I get:

[2016-06-20 14:05:13] Loaded plugin: homebridge-sonos
[2016-06-20 14:05:13] Registering accessory 'homebridge-sonos.Sonos'
[2016-06-20 14:05:13] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:181
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:181:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

My **config.json** file looks like ..

{
  "accessories": [
    {
      "accessory": "Sonos",
      "name": "Living Speaker",
      "room": "Living"
    }
  ]
}

Thanks for your help.

**Comment by lukeg01** [comment]
seems to be similar to #675

**Comment by mdod** [comment]
**I have almost the same problem. My error looks a little different though.**

Error: listen EADDRINUSE :::51828
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/bluebird/js/release/promise.js:178:30)
    at Server.startAsync (/usr/local/lib/node_modules/homebridge-controllerlink/lib/server.js:113:11)
    at Object.HomeBridgeControllerLink.accessories (/usr/local/lib/node_modules/homebridge-controllerlink/index.js:34:15)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:333:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:277:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by AppleTechy** [comment]
You are missing the "Bridge Section of your config file.
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
"accessories": [
{
"accessory": "Sonos",
"name": "Living Speaker",
"room": "Living"
}
]
}`
