### ISSUE TITLE
issues running homebridge

### ISSUE THREAD

**Issue by jvidales** [nfarina/homebridge#684]
Hello,

Homebridge was running perfectly until today in the morning it had stopped and now it it giving me the following error when I launch:

$ homebridge 
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

I've tried tried rebuilding node-gyn but no luck.

Any ideas?

Thanks in advance!

**Comment by mactr0n** [comment]
Looks like you updated node.js?
