### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by olekenneth** [nfarina/homebridge#7]
After running for 10-12 hours I get this error:

```fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/tmp/spawn-sync_input_208028a732bfc46b34947fb70'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at spawnSyncFallback (/root/chains-devices/homebridge/node_modules/sync-request/node_modules/spawn-sync/lib/spawn-sync.js:83:6)
    at doRequest (/root/chains-devices/homebridge/node_modules/sync-request/index.js:19:13)
    at Object.RequestAccessory.toggle (/root/chains-devices/homebridge/accessories/Request.js:31:20)
    at Object.characteristics.onUpdate (/root/chains-devices/homebridge/accessories/Request.js:109:50)
    at Object.updateCharacteristicValue (/root/chains-devices/homebridge/lib/HAP-NodeJS/Characteristic.js:34:9)
    at Object.processCharacteristicsValueWrite (/root/chains-devices/homebridge/lib/HAP-NodeJS/AccessoryController.js:59:16)
    at Object.responseCharacteristic (/root/chains-devices/homebridge/lib/HAP-NodeJS/Server.js:112:29)
    at IncomingMessage.<anonymous> (/root/chains-devices/homebridge/lib/HAP-NodeJS/Server.js:52:17)
```

**Comment by nfarina** [comment]
What accessory is `accessori
es/Request.js`? Is that a custom one?

**Comment by olekenneth** [comment]
A custom one I created, but it doesn't open any files. I just does a HTTP GET/PUT.
