### ISSUE TITLE
Homebridge TypeError on macOS 10.12 (16A254g)

### ISSUE THREAD

**Issue by Kfeavel** [nfarina/homebridge#727]
```
homebridge restart
[7/30/2016, 9:29:38 PM] Loaded plugin: homebridge-suncalc
[7/30/2016, 9:29:38 PM] Registering accessory 'homebridge-suncalc.Suncalc'
[7/30/2016, 9:29:38 PM] ---
[7/30/2016, 9:29:38 PM] Loaded plugin: homebridge-wunderground
[7/30/2016, 9:29:38 PM] Registering accessory 'homebridge-wunderground.WUNDERGROUND'
[7/30/2016, 9:29:38 PM] ---
[7/30/2016, 9:29:38 PM] Loaded config.json with 2 accessories and 1 platforms.
[7/30/2016, 9:29:38 PM] ---
[7/30/2016, 9:29:38 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:92
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:92:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

I just installed Homebridge onto my iMac and have had this problem since the start. I can add Homebridge in the iOS 10 Home app but none of my accessories will show up. I've already validated my config.json file but I'll post it below for the sake of being thorough.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "expected_accessories": "2"
    },

    "description": "Keeton's homebridge",

    "accessories": [
        {
          "accessory": "WUWeatherStation",
          "name": "Weather",
          "key": "3420b96e2217c3b5",
          "location": "47591"
        },
        {
          "accessory": "Suncalc",
          "location": {
              "lat": 38.677269,
              "lng": 87.528633
            },
            "offset": {
              "sunriseEnd" : 30,
              "sunsetStart" : -30
            },
            "name": "Suncalc"
          }
    ],

    "platforms": [
        {

        }
    ]
}

```

Any ideas? Am I doing something stupid or missing a step? (Let's hope not.)

**Comment by KhaosT** [comment]
```json
"platforms": [
        {

        }
    ]
```
This part, since you're not using any platform, please remove this section.

**Comment by Kfeavel** [comment]
Getting different errors not but I'm working on those. Shouldn't a check be implemented for empty fields like in my case since I simply followed the guideline in the example json provided in the repo?

**Comment by johnypony3** [comment]
Yeah, I feel like a settings check would solve most issues here.
But you know, there is also a wiki that has some info.

**Comment by Kfeavel** [comment]
Having a settings check should be a given for any application in my opinion. I understand the reason for simply having the wiki but I didn't find my specific issue in the wiki until after I filed this issue. At the very least a human understandable error system should be implemented instead of giving the node.js errors (unless Homebridge is run in verbose mode or something similar).

**Comment by johnypony3** [comment]
I am not a contributor yet, but...
This is an open source application hosted on github, all are welcome to submit pr's.
