### ISSUE TITLE
Bignum module load error while starting homebridge

### ISSUE THREAD

**Issue by coolhandtluke** [nfarina/homebridge#729]
Hello,

I am receiving the errors below while running homebridge on Windows 10. 

Can anyone help, please?

C:\Users\tomlu_000>homebridge
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\?\C:\Users\tomlu_000\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\tomlu_000\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\index.js:4:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by nrobinson2000** [comment]
This should fix the problem:
```
cd \C:\Users\tomlu_000\AppData\Roaming\npm\node_modules\homebridge\node_modules
npm install bignum
```

**Comment by mikeknoop** [comment]
@nrobinson2000 unfortunately that didn't work for me either (having same error as OP). I manually verified the file exists at the path mentioned in the error, too.

**Comment by nrobinson2000** [comment]
@mikeknoop
Well I had a problem like this on my Raspberry Pi.  Going into homebridge and reinstalling bignum fixed the problem.  My previous comment may be incorrect.
