### ISSUE TITLE
Error: The requested platform 'globalcache-gc100' was not registered by any plugin.

### ISSUE THREAD

**Issue by mahe7998** [nfarina/homebridge#745]
Hi,
I am trying to enable the home bridge with the globalcache-gc100 plugin.

I installed it this way: 

sudo npm install -g homebridge-globalcache-gc100

and modified ~/.homebridge/config.json this way

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is Jacques's beautiful config.json file",

    "platforms": [
	{
            "platform": "globalcache-gc100",
            "name": "homebridge-globalcache-gc100",
            "host": "172.16.1.33",
            "ir_port": "4999",
	    
            "rs232_devices": [
		{"name": "Xantech",
		 "port": "4999",
		 "base64_encoded": true,
                 "commands": {
                     "on" : "AlBPTgM=",
                     "off" : "AlBPRgM="
                 },
                 "success_messages" : {
                     "on" : "AlBPTgM=",
                     "off" : "AlBPRgM="
                 }
		}
            ]
	}
    ]
}

Launching homebridge outputs:

[Wed Aug 17 2016 19:49:23 GMT-0700 (PDT)] Loaded plugin: homebridge-globalcache-gc100
[Wed Aug 17 2016 19:49:23 GMT-0700 (PDT)] Registering platform 'homebridge-globalcache-gc100.GC100Platform'
[Wed Aug 17 2016 19:49:23 GMT-0700 (PDT)] ---
[Wed Aug 17 2016 19:49:23 GMT-0700 (PDT)] Loaded config.json with 0 accessories and 1 platforms.
[Wed Aug 17 2016 19:49:23 GMT-0700 (PDT)] ---
[Wed Aug 17 2016 19:49:23 GMT-0700 (PDT)] Loading 1 platforms...

/usr/local/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registere
            ^
Error: The requested platform 'globalcache-gc100' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

I searched online and cannot find why the requested platform 'globalcache-gc100' was not registered. Any help?

**Comment by mahe7998** [comment]
I did not change anything and today seems OK on that issue:

[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] Loaded plugin: homebridge-globalcache-gc100
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] Registering platform 'homebridge-globalcache-gc100.GC100Platform'
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] ---
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] Loaded config.json with 0 accessories and 1 platforms.
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] ---
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] Loading 1 platforms...
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] [homebridge-globalcache-gc100] Initializing globalcache-gc100 platform...
[Thu Aug 18 2016 10:05:36 GMT-0700 (PDT)] [homebridge-globalcache-gc100] Initializing platform accessory 'Xantech'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

Not sure why... Could be a cache issue?
