### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by heartlikedecember** [nfarina/homebridge#756]
Running Homebridge server on a MacBook Pro. When running homebridge with the wemo platform installed I get this message.

[8/30/2016, 7:30:56 PM] Loaded plugin: homebridge-platform-wemo
[8/30/2016, 7:30:56 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[8/30/2016, 7:30:56 PM] ---
[8/30/2016, 7:30:56 PM] Loaded config.json with 1 accessories and 1 platforms.
[8/30/2016, 7:30:56 PM] ---
[8/30/2016, 7:30:56 PM] Loading 1 platforms...
[8/30/2016, 7:30:56 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[8/30/2016, 7:30:56 PM] [WeMo Platform] Wemo Platform Plugin Loaded 
[8/30/2016, 7:30:56 PM] [WeMo Platform] Fetching the Wemo Accessories, expecting 1 and will wait 60 seconds to find them.
[8/30/2016, 7:30:56 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:46
if (name.indexOf('.') == -1) {
^

TypeError: Cannot read property 'indexOf' of undefined
at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:233:42)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

My config.json file

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [
    {

    }
],

"platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories" : "1",
          "timeout" : "60",
          "no_motion_timer": "60",
          "homekit_safe" : "1"
        }   
    ]
}

Any ideas?

**Comment by simonrb2000** [comment]
Take out the accessories from your config file.

Sent from my iPhone

On 31 Aug 2016, at 00:35, heartlikedecember <notifications@github.com<mailto:notifications@github.com>> wrote:


Running Homebridge server on a MacBook Pro. When running homebridge with the wemo platform installed I get this message.

[8/30/2016, 7:30:56 PM] Loaded plugin: homebridge-platform-wemo
[8/30/2016, 7:30:56 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[8/30/2016, 7:30:56 PM] ---
[8/30/2016, 7:30:56 PM] Loaded config.json with 1 accessories and 1 platforms.
[8/30/2016, 7:30:56 PM] ---
[8/30/2016, 7:30:56 PM] Loading 1 platforms...
[8/30/2016, 7:30:56 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[8/30/2016, 7:30:56 PM] [WeMo Platform] Wemo Platform Plugin Loaded
[8/30/2016, 7:30:56 PM] [WeMo Platform] Fetching the Wemo Accessories, expecting 1 and will wait 60 seconds to find them.
[8/30/2016, 7:30:56 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:46
if (name.indexOf('.') == -1) {
^

TypeError: Cannot read property 'indexOf' of undefined
at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:233:42)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

My config.json file

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [
{

}


],

"platforms": [
{
"platform": "BelkinWeMo",
"name": "WeMo Platform",
"expected_accessories" : "1",
"timeout" : "60",
"no_motion_timer": "60",
"homekit_safe" : "1"
}

]
}

Any ideas?

-

**Comment by rafacampoamor** [comment]
I'm having the same problem here, can anyone give an eye on my config file?
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },


        "accessories": [
                {
			"accesory": "TADO",
			"name": "Aire Acondicionado",
			"homeID": "96071",
			"username": "rafa@campoamor.me",
			"password": "Rosebud=194",
			"maxValue": 31,
  			"minValue": 16,
 			"zone": 1,
			"useFanSpeed": "AUTO",
			"useSwing": false,
			"tadoMode": "TADO_MODE",
			"useFahrenheit": false
                },


		{

                        "accessory": "PiTemperature",
                        "name": "Temperatura Raspberry PI"
                },


               {
            "accessory": "SamsungTV",
            "name": "Tele",
            "ip_address": "192.168.0.155",
            "send_delay": 400
        }
        ]
}

`

**Comment by snowdd1** [comment]
Spelling in `"accesory": "TADO"` ? Missing an `s`?

**Comment by rafacampoamor** [comment]
That was it! Thank you!!


De: Raoul <notifications@github.com> <notifications@github.com>
Responder: nfarina/homebridge
<reply@reply.github.com>
<reply@reply.github.com>
Fecha: 12 de junio de 2017 at 22:47:55
Para: nfarina/homebridge <homebridge@noreply.github.com>
<homebridge@noreply.github.com>
CC: rafacampoamor <rafacampoamor@gmail.com> <rafacampoamor@gmail.com>,
Comment <comment@noreply.github.com> <comment@noreply.github.com>
Asunto:  Re: [nfarina/homebridge] Cannot read property 'indexOf' of
undefined (#756)

Spelling in "accesory": "TADO" ? Missing an s?

**Comment by dcl66** [comment]
I know I am missing something that is there but I am at a complete loss. I ran the config through json validator and it was "clean but I continue to get this error message every time I attempt to load Homebrige 

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (c:\Users\MCPCBackup\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:50:12)
    at Server._loadAccessories (c:\Users\MCPCBackup\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:264:42)
    at Server.run (c:\Users\MCPCBackup\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:86:38)
    at module.exports (c:\Users\MCPCBackup\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (c:\Users\MCPCBackup\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)


Below Is my config if anyone can lead me down the right path I would greatly appreciate it !!!!!

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "830-26-426"
	},

	"accessories": [{
						"accessory": "WUNDERGROUND",
						 "name": "Weather Underground",
						 "device": "Fort Worth",
						 "key": "a1b30269183f640b",
						 "city": "Fort_Worth",
						 "polling": "10"
		},
		{
			"platforms": []

		}
	]
}

**Comment by ivovdgrift** [comment]
Platforms shouldn't be in the list of accessories. Take it out and put it underneath.
