### ISSUE TITLE
Home bridge unexpected token / problem authenticating with WINK

### ISSUE THREAD

**Issue by QuarterHorseRider** [nfarina/homebridge#757]
I have been using WINK with Homebridge for a month now on Mac Mini. No problems. Only have WINK installed as a platform. This morning 9/1/2016 system stopped and displayed unexpected token error. Stopped home bridge and restarted. Received following:

Last login: Thu Sep  1 06:58:32 on ttys000
Mac-Mini:~ paul$ homebridge
[9/1/2016, 7:03:33 AM] Loaded plugin: homebridge-wink
[9/1/2016, 7:03:33 AM] Registering platform 'homebridge-wink.Wink'
[9/1/2016, 7:03:33 AM] ---
[9/1/2016, 7:03:33 AM] Loaded config.json with 0 accessories and 1 platforms.
[9/1/2016, 7:03:33 AM] ---
[9/1/2016, 7:03:33 AM] Loading 1 platforms...
[9/1/2016, 7:03:33 AM] [Wink] Initializing Wink platform...
[9/1/2016, 7:03:33 AM] [Wink] Fetching Wink devices.
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:68:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
raw message <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
[9/1/2016, 7:03:33 AM] [Wink] There was a problem authenticating with Wink.

Here is my Config.json
{

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
	{
        	"platform": "Wink",
        	"name": "Wink",
        	"client_id": "quirky_wink_android_app",
        	"client_secret": "e749124ad386a5a35c0ab554a4f2c045",
        	"username": "web.shopping@att.net",
        	"password": "Azqqza16",
        	"hide_groups": ["thermostats", "smoke_detectors"],
        	"hide_ids": []
	}
    ]

}

Has been working fine. Nothing has changed except we are now in September. Does anyone have any information or suggestions? Thanks

**Comment by QuarterHorseRider** [comment]
It's working now. I rebooted the Wink Hub. Don't know if that fixed it or if it was something else. Thanks.

**Comment by apwelsh** [comment]
I hopr yhat isnt your real username/password.  Ig it is, I suggest you change it ASAP

**Comment by apwelsh** [comment]
Sorry for the typos.  Typing on my phone

**Comment by QuarterHorseRider** [comment]
Ahhhhh. So STUPID of me. just did. Thanks.
