### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by cpives2008** [nfarina/homebridge#780]
Hi,

Ive just updated my Raspberry Pi, and Homebridge is no longer working. This is what I get if itty to run it:

pi@raspberrypi:~ $ homebridge
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

Any ideas?

**Comment by danielballance** [comment]
`+1`  Same issue here on macOS 10.11.6 running NodeJS 6.6.0. Updated earlier today and Homebridge no longer runs. Terminal error below:

```
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

**Comment by marcelkordek** [comment]
Try the following solution:
```
sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
cd /usr/local/lib/node_modules/homebridge/
sudo npm install --unsafe-perm bignum
cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild
```

**Comment by cpives2008** [comment]
Done all that. Still get the same result

**Comment by loggoi** [comment]
Same problem here after updating my raspberry (apt-get dist-upgrade). homebridge refuse to start with error : 
/usr/lib/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: /usr/lib/arm-linux-gnueabihf/libavahi-client.so.3: symbol __stackchk_guard, version GLIBC_2.4 not defined in file ld-linux-armhf.so.3 with link time reference
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

I tried to uninstall/reinstall homebridge, but same result. I tried with another version of nodejs (5.19 instead of 6.6.0) and same error.

I also tried to reinstall with 
sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
cd /usr/local/lib/node_modules/homebridge/
sudo npm install --unsafe-perm bignum
cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild

but also same error.

What else can I try ?

**Comment by drewcovi** [comment]
+1, watching. Thanks for any advice.

**Comment by cpives2008** [comment]
I had this problem but managed to fix it with the following steps:

1) uninstalled Homebridge and all installed plugins
2) reinstalled, renamed the bridge in config.json to something different

Et voila, that was it. All working perfectly.

**Comment by rehafer** [comment]
Updated nodejs installed in /local/use/bin and homebridge in /opt/local/lib/node_modules/homebridge/ 
Is that part of my problem? Nodejs is not my area of expertise.

**Comment by kolyanok** [comment]
Same problem on macOS Sierra.

**Comment by edgr-sanchez** [comment]
Same problem here on a Raspberry Pi Zero.

![screenshot](http://i.imgur.com/yz9qu2b.png)

**Comment by drewcovi** [comment]
I'm back in order after uninstalling and reinstalling homebridge

**Comment by b3nk3** [comment]
None of this worked for me. 

Reverting back to the latest lts nodejs did.

`sudo apt-get purge nodejs npm`
`sudo apt-get install -y nodejs`

[credit]( http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts)

**Comment by edgr-sanchez** [comment]
Yeah I figured that's what I had to do as well

Thanks

On Oct 17, 2016, at 2:58 PM, b3nk3 <notifications@github.com<mailto:notifications@github.com>> wrote:


None of this worked for me.

Reverting back to the latest lts nodejs did.

sudo apt-get purge nodejs npm
sudo apt-get install -y nodejs

credit<http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts>

-

**Comment by bhaap** [comment]
Hi im getting this error now. All solutions posted here did not work:

`/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)`

**Comment by b3nk3** [comment]
@bhaap this is not related to this issue, as it was a version mismatch, hence the solution did not work for you.

**Comment by bhaap** [comment]
Oh sorry. Will create a new issue

**Comment by cocobear** [comment]
@b3nk3 this worked for me too!
