### ISSUE TITLE
Problems with homebridge-chamberlain

### ISSUE THREAD

**Issue by mikerpalmer-12** [nfarina/homebridge#786]
Hello,

I just installed the homebridge-chamberlain module today and setup the config in the config.json file. When I run homebridge, I get the following errors:

[9/21/2016, 8:06:51 PM] [Garage Door] Error: No controllable devices found
    at getDeviceList.then.devices (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:70:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)

I did some searching but came up empty. Anyone experience or have any thoughts on how to solve?

Thanks!

**Comment by mikerpalmer-12** [comment]
I decided to abandon and used the LiftMaster2 module instead https://www.npmjs.com/package/homebridge-liftmaster2

Works just fine.
