### ISSUE TITLE
homebridge cannot find config.json but it is in the homebridge folder

### ISSUE THREAD

**Issue by wooconstructions** [nfarina/homebridge#793]
Hi all, I am new to home bridge and Raspberry Pi, but a big fan of home automation in Australia. I have finally successfully install home bridge on pi3 via nfarina, I used nano to type the config.json up and save it in the homebridge folder and I have validated it was a valid json.

Could someone point me to the right direction please.

[homebridge cannot file config.json but it is there.pdf](https://github.com/nfarina/homebridge/files/489578/homebridge.cannot.file.config.json.but.it.is.there.pdf)

Below is my config.json contents.
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

```
"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [
    {
        "accessory": "WeMo",
        "name": "Coffee Maker"
    }
],

"platforms": [
    {
        "platform" : "PhilipsHue",
        "name" : "Hue"
    }
]
```

}

**Comment by toshibochan** [comment]
Have to be in
/home/pi/.homebridge/
Just run
Sudo nano /home/pi/.homebridge/config.json

**Comment by wooconstructions** [comment]
Hi toshibochan

thank you for your reply, after continue to create config.json to location where it complain that could not find. I end up with the following error.
proot@RasPi:/home/pi# homebridge
[9/24/2016, 6:51:22 AM] Loaded plugin: homebridge-lockitron
[9/24/2016, 6:51:22 AM] Registering accessory 'homebridge-lockitron.Lockitron'
[9/24/2016, 6:51:22 AM] ---
[9/24/2016, 6:51:22 AM] Loaded config.json with 1 accessories and 0 platforms.
[9/24/2016, 6:51:22 AM] ---
[9/24/2016, 6:51:22 AM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'WeMo' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:243:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
__________________

my config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ]
}

**Comment by toshibochan** [comment]
Look this
For install homebridge use "sudo"
https://github.com/rudders/homebridge-wemo/blob/master/README.md

**Comment by wooconstructions** [comment]
thanks again toshibochan

New error this time:

[9/24/2016, 7:24:48 AM] Loaded plugin: homebridge-lockitron
[9/24/2016, 7:24:49 AM] Registering accessory 'homebridge-lockitron.Lockitron'
[9/24/2016, 7:24:49 AM] ---
[9/24/2016, 7:24:51 AM] Loaded plugin: homebridge-wemo
[9/24/2016, 7:24:51 AM] Registering accessory 'homebridge-wemo.WeMo'
[9/24/2016, 7:24:51 AM] ---
[9/24/2016, 7:24:51 AM] Loaded config.json with 1 accessories and 0 platforms.
[9/24/2016, 7:24:51 AM] ---
[9/24/2016, 7:24:51 AM] Loading 1 accessories...
[9/24/2016, 7:24:51 AM] [Coffee Maker] Initializing WeMo accessory...
[9/24/2016, 7:24:51 AM] [Coffee Maker] Searching for WeMo device with exact name 'Coffee Maker'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/24/2016, 7:24:51 AM] Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:100:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:10)
root@RasPi:/home/pi#

**Comment by toshibochan** [comment]
You using root?

**Comment by wooconstructions** [comment]
Yes and that is the only way I can run it successfully.

**Comment by wooconstructions** [comment]
I am also using Wifi on pi3 to connection to my router if that makes any difference

**Comment by wooconstructions** [comment]
Ok, i got it running now after killing other homebridge processes. I now got this error?

I have tried delete all Coffee Maker on my config.json but still getting this:

[9/24/2016, 7:56:02 AM] [Coffee Maker] Error finding device 'Coffee Maker': WeMoSearchTimeoutError
[9/24/2016, 7:56:02 AM] [Coffee Maker] Continuing search for WeMo device with exact name 'Coffee Maker'...
[9/24/2016, 7:56:07 AM] [Coffee Maker] Error finding device 'Coffee Maker': WeMoSearchTimeoutError
[9/24/2016, 7:56:07 AM] [Coffee Maker] Continuing search for WeMo device with exact name 'Coffee Maker'...

**Comment by wooconstructions** [comment]
better go now, have to prepare a slab for a house. continue tonight.

**Comment by toshibochan** [comment]
What device you have?

**Comment by toshibochan** [comment]
You have memo devices?

**Comment by toshibochan** [comment]
Look like not finding you wemo called wemo "coffee maker"

**Comment by wooconstructions** [comment]
I dont have any Wemo devices at all, I have veralite and it is connected to all my houses lights and garage door. I wanted to be able to use siri to activate them and I had it working last week accidentally (haha). but I was playing around with it and my pi3 was frozen, so I have to reinstall and took me over a week to get to this stay.  Now I have to look for coffee maker

**Comment by wooconstructions** [comment]
I my case, how would you configure my config.json? can I have no accessories and no platforms?

**Comment by toshibochan** [comment]
No I don't understand you! You show your config.json having wemo! And now you saying you don't have wemo products!!!!! I don't know what you want

**Comment by wooconstructions** [comment]
I think I know what I went wrong now.  I need VeraHomekitBridge not homebridge.  I am working on it now but getting error in installing HAP-NodeJS . Thank you for your help. I might have to start a new conversation. Thanks again.

**Comment by toshibochan** [comment]
You need homebridge, but you have to install homebridge-vera inside homebridge.

**Comment by toshibochan** [comment]
https://www.npmjs.com/package/homebridge-vera

**Comment by toshibochan** [comment]
Good luck

**Comment by wooconstructions** [comment]
Hi toshibochan, I was trying to do what you suggested and couldn't get  it working because of my limited knowledge.  After trying many many times, I am now able to install VeraHomeKitBridge onto my Pi3.  Instructions Hackworth gave was 1 year ago and a few things had changed and I was not able to run some installation at first.  After search web and keep trying different ways, i added --unsafe -perm to two commands and it worked.  I am so happy, I am now able to use siri to control all my veralite device inside the house AND remotely through apple TV4 with my icould account.  I will try your suggestion with another sd card when i have time.  Many Thanks for your help.
https://github.com/Hackworth/VeraHomeKitBridge

**Comment by lagunacomputer** [comment]
mine only works if config.json is in /var/homebridge
