### ISSUE TITLE
Block-scoped declarations when trying to start homebridge

### ISSUE THREAD

**Issue by danielsen2009** [nfarina/homebridge#806]
Just removed and reinstalled homebridge  for the new ip cam support and whenever I try to restart homebridge I get the following..

`root@bridge1:/home/pi# homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:61
    let port = this._tcpServer.address().port
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:11:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
root@bridge1:/home/pi# `

**Comment by KhaosT** [comment]
Can you try update your nodejs to 6.0?

**Comment by danielsen2009** [comment]
That did it! I assumed it was the latest with an apt-upgrade but I was wrong after a node -v. Installed n to manage node and everything is working again.
