### ISSUE TITLE
Error: ENOTDIR: not a directory, scandir

### ISSUE THREAD

**Issue by pannous** [nfarina/homebridge#814]
strange error:
```
$ homebridge
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir '/usr/local/bin/node'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Function.Plugin.installed (/usr/local/lib/node_modules/homebridge/lib/plugin.js:156:20)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:124:10)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:48:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

**Comment by pannous** [comment]
patch:

/usr/local/lib/node_modules/homebridge/lib/plugin.js:156
```
    // we only care about directories
    if (!fs.statSync(requirePath).isDirectory()) continue;
```

**Comment by KhaosT** [comment]
but how did ``/usr/local/bin/node`` got into the path... Did you set strange environment variables?

**Comment by pannous** [comment]
oops
NODE_PATH=/usr/local/bin/node
;)

DOCs: add the /usr/lib/node_modules folder to the $NODE_PATH  ;)

**Comment by trungtrangtreo** [comment]
[
]
[
