### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by RGKS** [nfarina/homebridge#817]
I installed HomeBridge and was able to add it to HomeKit, but getting the following error when launching the application on my Raspberry Pi.
 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/a...bdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/a...erviceRegister>
[9/29/2016, 2:12:48 AM] Loaded plugin: homebridge-isy-js
[9/29/2016, 2:12:48 AM] Registering platform 'homebridge-isy-js.isy-js'
[9/29/2016, 2:12:48 AM] ---
[9/29/2016, 2:12:48 AM] Loaded config.json with 0 accessories and 1 platforms.
[9/29/2016, 2:12:48 AM] ---
[9/29/2016, 2:12:48 AM] Loading 1 platforms...
[9/29/2016, 2:12:48 AM] [isy-js] Initializing isy-js platform...
/usr/local/lib/node_modules/homebridge-isy-js/index.js:71
for (var index = 0; index < this.config.ignoreDevices.length; index++) {
                                                    ^
 
TypeError: Cannot read property 'length' of undefined
    at ISYPlatform.shouldIgnore (/usr/local/lib/node_modules/homebridge-isy-js/index.js:71:56)
    at /usr/local/lib/node_modules/homebridge-isy-js/index.js:120:13
    at ISY.finishInitialize (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:368:5)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:535:30
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:420:17)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:229:10)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:161:20
    at IncomingMessage.parsers.auto (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:402:7)

config.json
 
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
 
    "description": "My config file",
 
    "platforms": [
        {
            "platform": "isy-js",
            "name": "isy-js",
            "host": "192.168.2.XXX",
   "port": "80",
            "username": "admin",
            "password": "my password",
            "elkEnabled": false,
            "useHttps": false,
            "debugLoggingEnabled": false,
            "includeAllScenes": true,
            "garageDoors": [
                { "address": "22 D4 89 2", "name": "Garage Door", "timeToOpen": 12000 }
            ]
        }    
            ]
        
}

**Comment by RGKS** [comment]
Had to ignore at least one device
