### ISSUE TITLE
Cannot pair on Windows 10 - ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by hageson** [nfarina/homebridge#819]
Homebridge seems to run but the IOS app doesn't detect any accessories so I'm not sure its running after all.  There is no mention of Homebridge on the Bonjour Browser.  

I added a rule into BitDefender Firewall that allows all protocols with C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

I get the following "ReferenceError: callback is not defined" console error messages displayed after it reports that Homebridge is running:

`C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge\bin>node homebridge
[9/29/2016, 10:34:21 AM] Loaded plugin: homebridge-http
[9/29/2016, 10:34:21 AM] Registering accessory 'homebridge-http.Http'
[9/29/2016, 10:34:21 AM] ---
[9/29/2016, 10:34:21 AM] Loaded config.json with 1 accessories and 0 platforms.
[9/29/2016, 10:34:21 AM] ---
[9/29/2016, 10:34:21 AM] Loading 1 accessories...
[9/29/2016, 10:34:21 AM] [Alfresco Lamp] Initializing Http accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[9/29/2016, 10:34:21 AM] Homebridge is running on port 51826.
[9/29/2016, 10:34:22 AM] [Alfresco Lamp] HTTP get power function failed: connect ECONNREFUSED 127.0.0.1:80
C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge-http\index.js:45
                                callback(error);
                                ^

ReferenceError: callback is not defined
    at C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge-http\index.js:45:19
    at Request._callback (C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge-http\index.js:115:4)
    at self.callback (C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge-http\node_modules\request\request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge-http\node_modules\request\request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)

C:\Users\Howard\AppData\Roaming\npm\node_modules\homebridge\bin>`

**Comment by KhaosT** [comment]
It crashes at
```
[9/29/2016, 10:34:22 AM] [Alfresco Lamp] HTTP get power function failed: connect ECONNREFUSED 127.0.0.1:80
```
Try disable all plugins and see if it runs?

**Comment by hageson** [comment]
I wish I weren't so ignorant - how do I disable all plugins?

**Comment by KhaosT** [comment]
@hageson remove the ``accessories`` and ``platforms`` sections in config.json

**Comment by hageson** [comment]
That did it.  Excellent.  Thanks.

**Comment by samsp24** [comment]
sir can you please send me edited config.json file
