### ISSUE TITLE
Cannot find module 'is-property'

### ISSUE THREAD

**Issue by suhajdab** [nfarina/homebridge#84]
Trying to run the server I get the following

```
Loading 6 accessories...
module.js:338
    throw err;
          ^
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/homebridge/node_modules/wemo/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Linux 3.18.11-hypriotos-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
```

Does anyone know how to fix this?

**Comment by nfarina** [comment]
That's a weird one - guessing there's an issue with your `config.json` - could you post yours? (blanking out passwords first)

**Comment by suhajdab** [comment]
You could well be right! I did just get the latest version of homebridge while keeping the old config.json. Will investigate.

**Comment by micha149** [comment]
I think your npm install was not run correctly and `is-property` is just missing. Please check the contents of directory `/home/pi/homebridge/node_modules/wemo/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules`…

**Comment by nfarina** [comment]
Closing this for now; if you're still having this problem please reopen, thanks!
