### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by thechrisreese** [nfarina/homebridge#842]
Can anyone help me with why this is happening? 

[10/10/2016, 6:27:05 PM] Loaded plugin: homebridge-applescript
[10/10/2016, 6:27:05 PM] Registering accessory 'homebridge-applescript.Applescript'
[10/10/2016, 6:27:05 PM] ---
[10/10/2016, 6:27:06 PM] ====================
[10/10/2016, 6:27:06 PM] ERROR LOADING PLUGIN homebridge-wink:
[10/10/2016, 6:27:06 PM] TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
[10/10/2016, 6:27:06 PM] ====================
[10/10/2016, 6:27:06 PM] Loaded config.json with 1 accessories and 1 platforms.
[10/10/2016, 6:27:06 PM] ---
[10/10/2016, 6:27:06 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Wink' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:281:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by frodeaux** [comment]
I have also been getting this error. Ive seen it when I had homebridge-controller installed and configured. Removing that plugin fixed it for me.  Does not look like you have that installed so it makes me wonder if its a homebridge issue and not a plugin issue.

**Comment by thechrisreese** [comment]
This is definitely to do with changes to Homebridge in the past months and plugins that are not updated. I restored back to two days ago before I updated Homebridge and all works again. Has to do with changes to how plugin packages are called.

**Comment by frodeaux** [comment]
what version did you restore to that is working for you?

**Comment by thechrisreese** [comment]
Here is where I am at and all works: 

Brew version - 0.9.9
Node version - v0.12.7
Homebridge version - 0.3.4
