### ISSUE TITLE
Cannot startup on centos

### ISSUE THREAD

**Issue by tudows** [nfarina/homebridge#852]
all the installments are successful (at least I think), but when I startup the homebridge
`homebridge`
then there is wrong
`fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/usr/bin/node'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Function.Plugin.installed (/usr/local/node/lib/node_modules/homebridge/lib/plugin.js:170:15)
    at Server._loadPlugins (/usr/local/node/lib/node_modules/homebridge/lib/server.js:125:10)
    at new Server (/usr/local/node/lib/node_modules/homebridge/lib/server.js:48:24)
    at module.exports (/usr/local/node/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)`

**Comment by tudows** [comment]
```
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/usr/bin/node'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Function.Plugin.installed (/usr/local/node/lib/node_modules/homebridge/lib/plugin.js:170:15)
    at Server._loadPlugins (/usr/local/node/lib/node_modules/homebridge/lib/server.js:125:10)
    at new Server (/usr/local/node/lib/node_modules/homebridge/lib/server.js:48:24)
    at module.exports (/usr/local/node/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```
