### ISSUE TITLE
Error when configuring homebridge-homeassistant 

### ISSUE THREAD

**Issue by oguinjr** [nfarina/homebridge#860]
TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:199:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:49:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)

![img_0185](https://cloud.githubusercontent.com/assets/22947782/19542616/8de4bb98-9624-11e6-8161-bb4dd9ff8d43.PNG)

**Comment by iancorbitt** [comment]
Does the error go away when you remove the HomeAssistant section in platforms?

**Comment by oguinjr** [comment]
No, but It wasn't there until I added HomeAssistant. Homebridge and Siri were working well right before.

**Comment by iancorbitt** [comment]
Have you tried wiping out the config file and starting from scratch with it?

**Comment by oguinjr** [comment]
Yes. I am running NOOBS, could that be an issue?

**Comment by iancorbitt** [comment]
I was able to replicate you error. Change that "B" in bridge to a "b", the config parser is case-sensitive.
