### ISSUE TITLE
can't make homebridge working anymore

### ISSUE THREAD

**Issue by thib5** [nfarina/homebridge#879]
Hi, I mess up something and since I can't start homebridge ... so I delete all homebridge folders on my mac, I reinstall npm and node I reinstall homebridge and the openhab plugin and I still have this : 

`sh-3.2# npm install -g homebridge
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
/usr/local/lib
└─┬ homebridge@0.4.6 
  └─┬ hap-nodejs@0.4.11
    └── srp@0.2.1  (git://github.com/KhaosT/node-srp.git#4bae2bd72e75e594ca671a3574250b447d79e5b9)

sh-3.2# npm install -g homebridge-openhab
/usr/local/lib
└── homebridge-openhab@0.1.31 

sh-3.2# homebridge
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
sh-3.2# npm -g outdated
Package  Current  Wanted  Latest  Location
npm       3.10.8   4.0.1  3.10.9
`

**Comment by mogeryt** [comment]
Update every NPM package.
