### ISSUE TITLE
Error after current update  

### ISSUE THREAD

**Issue by scottyblue77** [nfarina/homebridge#880]
this was the update:

MacMini:~ sebastian$ sudo npm -g update homebridge-homematic
Password:
homebridge-homematic@0.0.50 /usr/local/lib/node_modules/homebridge-homematic
├── debug@2.2.0 (ms@0.7.1)
├── homematic-xmlrpc@1.0.2 (xmlbuilder@0.4.2, sax@0.4.3)
└── request@2.76.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.5.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, qs@6.3.0, combined-stream@1.0.5, mime-types@2.1.12, tough-cookie@2.3.2, form-data@2.1.1, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
MacMini:~ sebastian$ homebridge

and now the error after start:

[2016-10-30 18:24:35] [skhome] Number of mapped devices : 22
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitDimmerService.js:94
          this.onc.updateValue(true,null);
                   ^

TypeError: this.onc.updateValue is not a function
    at HomeMaticHomeKitDimmerService.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitDimmerService.js:94:17)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at HomeMaticHomeKitDimmerService.HomeKitGenericService.cache (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:271:44)
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:186:12
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:169:9
    at callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:67:13)

please help me !

**Comment by scottyblue77** [comment]
i solved it with remove the dimmer HM-LC-Dim1TPBU-FM.

But this is bad, i need this in homebridge, why from one update of the other dimmer are not working anymore....

please fix this
