### ISSUE TITLE
Unhandled rejection RequestError: Error: Invalid URI "GET"

### ISSUE THREAD

**Issue by drewcovi** [nfarina/homebridge#887]
```
Nov  2 01:34:17 raspberrypi homebridge[27888]: Unhandled rejection RequestError: Error: Invalid URI "GET"
Nov  2 01:34:17 raspberrypi homebridge[27888]: at new RequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at self.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at emitOne (events.js:96:13)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Request.emit (events.js:188:7)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Request.init (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:274:17)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Request.RP$initInterceptor [as init] (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/configure/request2.js:45:29)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at new Request (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:128:8)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Object.request (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/index.js:54:10)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Object.getStatus (/usr/local/lib/node_modules/homebridge-vera/lib/types/fan.js:87:31)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Characteristic.On.<anonymous> (/usr/local/lib/node_modules/homebridge-vera/lib/types/fan.js:162:35)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at emitThree (events.js:116:13)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Characteristic.On.emit (events.js:194:7)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Characteristic.On.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:621:20)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Array.forEach (native)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:585:8)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at emitMany (events.js:127:13)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at HAPServer.emit (events.js:201:7)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:920:10)
Nov  2 01:34:17 raspberrypi homebridge[27888]: at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:203:39)
```

**Comment by drewcovi** [comment]
this is in homebridge-vera... need to update fan.js :)
