### ISSUE TITLE
New problem after running several times . . . Now won't start due to TypeError

### ISSUE THREAD

**Issue by mgoblue01** [nfarina/homebridge#889]
Anyone know what is happening with this?  Uninstalled all plugins and homebridge and reinstalled just homebridge and homebridge-http.  Can't get by this Buffer.alloc error.  Any help would be appreciated.

TypeError: Buffer.alloc is not a function
    at new AccessoryInfo (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\model\AccessoryInfo.js:23:24)
    at Function.AccessoryInfo.create (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\model\AccessoryInfo.js:88:23)
    at Bridge.Accessory.publish (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:432:41)
    at Server._publish (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\lib\server.js:111:16)
    at Server.run (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\lib\server.js:88:10)
    at module.exports (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (c:\Users\Office\Appdata\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by KhaosT** [comment]
homebridge 0.4.7 (released yesterday) now requires nodejs v5.10.0 or later.

**Comment by Sico93** [comment]
So I guess homebridge 0.4.6 is the last working release working on RPi 1 B(+), am I right? 😐
I just ran into this issue on a new original RPi B Setup for a friend with only basic functions needed.

Looking forward for an answer on the last working setup for this RPi, thank you 😊

**Comment by KhaosT** [comment]
@Sico93 why do you say RPi 1 B(+) only works with old nodejs?

**Comment by Sico93** [comment]
Because I don't know any better 🙁 
This is what happens if I try to get to Node V5:
`pi@WG_FHEM_Pi:~ $ curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

## Installing the NodeSource Node.js v5.x repo...


## You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js v4 and later.`

I'm sorry, im relatively new to linux / still learning 😐

**Comment by KhaosT** [comment]
You can try manually download pre-compiled binary (https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-armv6l.tar.xz) and put it in right place. Or install ``n`` (https://www.npmjs.com/package/n) and have it switch nodejs version to latest.

**Comment by mgoblue01** [comment]
Thanks much KhaosT.

**Comment by Sico93** [comment]
Thank you KhaosT! 👍  That worked for me 😊
