### ISSUE TITLE
I cant install homebridge on windows 10

### ISSUE THREAD

**Issue by INFINIX98** [nfarina/homebridge#892]
whe in try installing npm install -g hombridge
he give me that :

"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2059: syntax error: '.' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2146: syntax error: missing ';' before identifier 'error' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebri
dge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2146: syntax error: missing ';' before identifier 'open' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebrid
ge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2015: too many characters in constant (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\cur
ve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2146: syntax error: missing ';' before identifier 'such' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebrid
ge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2059: syntax error: ':' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2146: syntax error: missing ';' before identifier 'Microsoft' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\hom
ebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2146: syntax error: missing ';' before identifier 'nodejs' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebr
idge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2059: syntax error: ')' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(5): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(5): error C2059: syntax error: ')' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(6): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(6): error C2059: syntax error: ')' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C2086: 'int Programmes': redefinition (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curv
e25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): note: see declaration of 'Programmes' (compiling source file ..\node_curve.cc)
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C2146: syntax error: missing ';' before identifier 'nodejs' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebr
idge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(307): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.c
c) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(307): error C2143: syntax error: missing ',' before '' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\nod
e_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(313): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(314): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(315): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(316): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(317): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(318): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(319): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(320): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(321): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(322): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2065: 'u8': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2065: 'output': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_mod
ules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2275: 'felem': illegal use of this type as an expression (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\R
oaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(53): note: see declaration of 'felem' (compiling source file ..\node_curve.cc)
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2182: 'fcontract': illegal use of type 'void' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm
node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2448: 'fcontract': function-style initializer appears to be a function definition (compiling source file ..\node_curve.cc
) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(445): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.c
c) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(445): error C2143: syntax error: missing ',' before '' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\nod
e_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(453): error C2065: 'q': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(456): error C2146: syntax error: missing ';' before identifier 'byte' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\R
oaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(456): error C2065: 'byte': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(456): error C2065: 'n': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(458): error C2065: 'byte': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(463): error C2065: 'q': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(469): error C2065: 'q': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(485): error C2065: 'byte': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2065: 'u8': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2065: 'mypublic': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_m
odules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2059: syntax error: 'const' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homeb
ridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2143: syntax error: missing ';' before '{' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\nod
e_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppDat
a\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
..\node_curve.cc(27): error C3861: 'curve25519_donna': identifier not found [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: D:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\Program Files (x86)\nodejs\node.exe" "D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
D:\Users\FDP\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\Program Files (x86)\nodejs\node.exe" "D:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v7.0.0
npm ERR! npm v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.1.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! D:\Users\FDP\npm-debug.log
npm ERR! code 1"

can anyone help me ? i will realy apreciate because i searched with my friend google and i didnt find how to solve it i am a noob :(

**Comment by INFINIX98** [comment]
I tried with ubuntu and i have that > node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 3.10.20-g3d71b77
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rty/node_modules/mdns
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/rty/package.json'
npm WARN rty No description
npm WARN rty No repository field.
npm WARN rty No README data
npm WARN rty No license field.
npm ERR! Linux 3.10.20-g3d71b77
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "homebridge"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rty/npm-debug.log
rty@localhost:~$

**Comment by INFINIX98** [comment]
Sweet jesus its almost worcking :):):):) i have that now
sudo apt-get install build-essential
