### ISSUE TITLE
Problem reading config.json

### ISSUE THREAD

**Issue by stantang986** [nfarina/homebridge#896]
Firstly after install, it ran good.
But after I reboot my Pi, it shows config.json file got problem.
So I rebuild config.json, but still got below issus:

`[11/5/2016, 5:50:06 PM] Loaded plugin: homebridge-yeelight
[11/5/2016, 5:50:06 PM] Registering platform 'homebridge-yeelight.yeelight'
[11/5/2016, 5:50:06 PM] ---
[11/5/2016, 5:50:06 PM] There was a problem reading your config.json file.
[11/5/2016, 5:50:06 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[11/5/2016, 5:50:06 PM] 
/usr/lib/node_modules/homebridge/lib/server.js:194
    throw err;
    ^

SyntaxError: Unexpected token } in JSON at position 155
    at Object.parse (native)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:188:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:49:23)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

**Comment by stantang986** [comment]
2nd time, i mean rebuild config.json is ttl same as 1st time

**Comment by lagunacomputer** [comment]
you have a bad character or extra ' ] ' in your file etc
