### ISSUE TITLE
I have a dns error and I dont know how to fix it!

### ISSUE THREAD

**Issue by INFINIX98** [nfarina/homebridge#899]
I tried to installation it on ubuntu but i have this problème now ! rty@localhost:~$ sudo homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
[11/5/2016, 4:34:26 PM] Loaded plugin: homebridge-http
[11/5/2016, 4:34:27 PM] Registering accessory 'homebridge-http.Http'
[11/5/2016, 4:34:27 PM] ---
[11/5/2016, 4:34:27 PM] Loaded config.json with 1 accessories and 0 platforms.
[11/5/2016, 4:34:27 PM] ---
[11/5/2016, 4:34:27 PM] Loading 0 platforms...
[11/5/2016, 4:34:27 PM] Loading 1 accessories...
[11/5/2016, 4:34:27 PM] [Chambre] Initializing Http accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

┌────────────┐
│ 031-45-154 │
└────────────┘
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
^

Error: dns service error: unknown
at Error (native)
at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
at Object.create as createAdvertisement
at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:526:20)
at emitOne (events.js:96:13)
at HAPServer.emit (events.js:188:7)
at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
at emitOne (events.js:96:13)
at EventedHTTPServer.emit (events.js:188:7)

**Comment by jonathanweinberg** [comment]
Check out #527 ?

**Comment by danijelst** [comment]
I had the same issue but didn't find anything how to solve it. At the end I figured out as I run homebridge inside of a docker with the commandline including --net=host that the Bonjour service port **5353** was already occupied by some other process. You can check if the port is already taken by some process with 

`netstat -anp | grep 5353`

This will list something like:

`
[~] # netstat -anp | grep 5353

netstat: /proc/net/tcp6: No such file or directory
udp   533760      0 0.0.0.0:5353            0.0.0.0:*                           13315/python
udp   533760      0 0.0.0.0:5353            0.0.0.0:*                           13315/python
udp   533760      0 0.0.0.0:5353            0.0.0.0:*                           13315/python
udp   533760      0 0.0.0.0:5353            0.0.0.0:*                           13315/python
`

the 13315 is the pid which you then can check what the process is.

**Comment by Anuj79** [comment]
can you let me know how you figured out it was the port. i am getting the same error and i disabled the avahi demon running on the nas but i still get this error 

[/share/Docker/homebridge] # netstat -plunt | grep 5353
netstat: /proc/net/tcp6: No such file or directory
netstat: /proc/net/udp6: No such file or directory

**Comment by Anuj79** [comment]
i had to log into the container to run the avahi manually by giving following command.. in case its helpful to anyone else 


/etc/init.d/dbus start
avahi-daemon --debug --no-drop-root
