### ISSUE TITLE
Error LogitechHarmony.js

### ISSUE THREAD

**Issue by ChrisKoh83** [nfarina/homebridge#90]
If try to use this shim I get an error during the startup:

/home/pi/homebridge/platforms/LogitechHarmony.js:174
      this.log('TODO: Support onRead for devices');
           ^
TypeError: undefined is not a function
    at Object.LogitechHarmonyAccessory.getPowerState [as onRead] (/home/pi/homebridge/platforms/LogitechHarmony.js:174:12)
    at Object.valueForUpdate (/home/pi/homebridge/node_modules/HAP-NodeJS/Characteristic.js:136:9)
    at Object.jsonForCharacteristicUpdate (/home/pi/homebridge/node_modules/HAP-NodeJS/AccessoryController.js:48:30)
    at Object.responseCharacteristic (/home/pi/homebridge/node_modules/HAP-NodeJS/Server.js:110:29)
    at Object.<anonymous> (/home/pi/homebridge/node_modules/HAP-NodeJS/Server.js:69:13)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)

npm ERR! Linux 4.0.8-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

**Comment by madmod** [comment]
Hmm I just tried it with the latest build and I don't get that error. I'm not sure how it could even get to that code because it currently only creates accessories for activities. I think somehow `this` is not set properly when onRead is called. I have created a possible fix in [my fork here](https://github.com/madmod/homebridge). If it works I will create a PR.

**Comment by ChrisKoh83** [comment]
I`m sorry, the error occurs not during the start-up. It occurs during the pairing procedure. 

Anyway, I tested your fix but I still get an error during the pairing procedure:

/home/pi/homebridge/platforms/LogitechHarmony.js:166
      hub.getCurrentActivity().then(function (currentActivity) {
      ^
ReferenceError: hub is not defined
    at Object.LogitechHarmonyAccessory.getPowerState (/home/pi/homebridge/platforms/LogitechHarmony.js:166:7)
    at Object.valueForUpdate (/home/pi/homebridge/node_modules/HAP-NodeJS/Characteristic.js:136:9)
    at Object.jsonForCharacteristicUpdate (/home/pi/homebridge/node_modules/HAP-NodeJS/AccessoryController.js:48:30)
    at Object.responseCharacteristic (/home/pi/homebridge/node_modules/HAP-NodeJS/Server.js:110:29)
    at Object.<anonymous> (/home/pi/homebridge/node_modules/HAP-NodeJS/Server.js:69:13)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)

npm ERR! Linux 4.0.8-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

**Comment by benjaml4** [comment]
I'm having this issue too with the fix. It crashes the Homebridge so I have to restart it again. 

Users/benjaminlee/Scripts/homebridge/platforms/LogitechHarmony.js:166
      hub.getCurrentActivity().then(function (currentActivity) {
      ^
ReferenceError: hub is not defined
    at Object.LogitechHarmonyAccessory.getPowerState (/Users/benjaminlee/Scripts/homebridge/platforms/LogitechHarmony.js:166:7)
    at Object.valueForUpdate (/Users/benjaminlee/Scripts/homebridge/node_modules/HAP-NodeJS/Characteristic.js:136:9)
    at Object.jsonForCharacteristicUpdate (/Users/benjaminlee/Scripts/homebridge/node_modules/HAP-NodeJS/AccessoryController.js:48:30)
    at Object.responseCharacteristic (/Users/benjaminlee/Scripts/homebridge/node_modules/HAP-NodeJS/Server.js:110:29)
    at Object.<anonymous> (/Users/benjaminlee/Scripts/homebridge/node_modules/HAP-NodeJS/Server.js:69:13)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benjaminlee/Scripts/homebridge/npm-debug.log
