### ISSUE TITLE
Error: dns service error: name conflict

### ISSUE THREAD

**Issue by mehak-bhatia** [nfarina/homebridge#903]
I'm running homebridge on raspberry pi 3 B

How do I fix this?

`/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)`

Any ideas?

**Comment by KhaosT** [comment]
Give the accessory a different name

**Comment by ddbkva** [comment]
how i can give my pi another name?
have the same problem
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:575:20)
    at emitOne (events.js:115:13)
    at HAPServer.emit (events.js:210:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:115:13)
    at EventedHTTPServer.emit (events.js:210:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)

**Comment by shidevil** [comment]
@ddbkva was it working previously?? Have you update to the latest homebridge ?

sudo apt-get install libavahi-compat-libdnssd-dev

Sudo nano /etc/avahi/avahi-daemon.conf 

Check if this line is uncommented 

enable-dbus=yes

**Comment by ddbkva** [comment]
that image that i used is from 8/20/17
and i did this 
sudo npm install -g --unsafe-perm homebridge@latest
so its the latest

**Comment by shidevil** [comment]
@ddbkva Can you post your config.json?

**Comment by ddbkva** [comment]
homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-8-23 10:26:24] No plugins found. See the README for information on installing plugins.
[2017-8-23 10:26:24] config.json (/home/pi/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:611:20)
    at emitOne (events.js:115:13)
    at HAPServer.emit (events.js:210:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:115:13)
    at EventedHTTPServer.emit (events.js:210:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)

**Comment by shidevil** [comment]
@ddbkva i mean your config.json not the log.

**Comment by shidevil** [comment]
config.json (/home/pi/.homebridge/config.json) not found.

you did not create a config.json file.

Please create it. 
https://github.com/nfarina/homebridge/blob/master/config-sample.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "manufacturer": "@nfarina",
        "model": "Homebridge",
        "serialNumber": "0.4.20"
    },
    "accessories": [],
    "platforms": []
}

**Comment by ddbkva** [comment]
there is nothing
i set this system brand new

{
        "bridge" : {
                "name" : "Homebridge",
                "username" : "CC:22:3D:E3:CE:30",
                "port" : 51826,
                "pin" : "031-45-154"
        },

        "accessories" : [

        ],

        "platforms" : [

        ]
}

**Comment by shidevil** [comment]
@ddbkva Can u run again? Ur log states 

config.json (/home/pi/.homebridge/config.json) not found.

**Comment by ddbkva** [comment]
sudo tail -f /var/log/syslog | grep homebridge
Aug 23 12:28:22 hbridge2 homebridge[603]: └────────────┘
Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:22] Homebridge is running on port 51826.

**Comment by ddbkva** [comment]
i dont know perhaps i ignore that because homebridge is running ?!

**Comment by ddbkva** [comment]
perhaps there is an error because is set the system 4 times new ?

**Comment by shidevil** [comment]
Seems like it's running. Could you check?

**Comment by ddbkva** [comment]
how ?

**Comment by ddbkva** [comment]
sudo systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Mi 2017-08-23 12:27:54 CEST; 33min ago
 Main PID: 603 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─603 homebridge

Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:21] No plugins fo....
Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:22] Loaded config....
Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:22] ---
Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:22] Loading 0 pla....
Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:22] Loading 0 acc....
Aug 23 12:28:22 hbridge2 homebridge[603]: Scan this code with your HomeKit A...:
Aug 23 12:28:22 hbridge2 homebridge[603]: ┌────────────┐
Aug 23 12:28:22 hbridge2 homebridge[603]: │ 031-45-154 │
Aug 23 12:28:22 hbridge2 homebridge[603]: └────────────┘
Aug 23 12:28:22 hbridge2 homebridge[603]: [2017-8-23 12:28:22] Homebridge is....
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by shidevil** [comment]
Yes it's running well now

**Comment by ddbkva** [comment]
thank you

**Comment by darrylhodgins** [comment]
For anyone else coming across this issue, this:

> Give the accessory a different name

…appears to mean that the `hostname` of the Pi needs to be different from the `name` of the bridge in the configuration.  For example, this will fail:

```bash
$ hostname
raspberry-pi-homebridge
```

`config.json`:
```json
{
	"bridge": {
		"name": "Raspberry Pi Homebridge",
		...
	},
	...
}
```

Change either the `hostname` or the `bridge.name` to make it work :)
