### ISSUE TITLE
Cannot find module '../build/Release/dns_sd_bindings'

### ISSUE THREAD

**Issue by Jun-long** [nfarina/homebridge#905]
$homebridge

module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/.homebridge_npminstall/node_modules/.2.3.3@mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

macOS 10.12.1

**Comment by KhaosT** [comment]
please make sure ``npm install`` finishes without error.

**Comment by xstrex** [comment]
Same exact error on ubuntu 16.04 x64. 
```
module.js:328
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```
@KhaosT Does it matter where "npm install" is run from?

**Comment by jacobleilei** [comment]
I've encountered the same problem.

@raspberrypi:~# homebridge
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by JunlongZhao** [comment]
Solved, mDNS/DNS-SD Daemon need Avahi services.

[Install Avahi and other Dependencies](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-avahi-and-other-dependencies)

and  avahi-daemon requires dbus daemon to be started, do it manually.

/etc/init.d/dbus start
/etc/init.d/avahi-daemon start

**Comment by jacobleilei** [comment]
I tried your way.
Still can't run Homebridge
@JunlongZhao

**Comment by leolobato** [comment]
Same issue trying to install on Raspberry Pi 3 running Raspbian Jessie following [these instructions](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi).

**Comment by emericspiroux** [comment]
No one was find a solution ? i've the same issue on a RPI3. 

Raspbian Jessie
Node v7.2.0

```
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by emericspiroux** [comment]
Ok i found a solution ! You need to do `sudo npm install mdns` at `/usr/local/lib/node_modules/homebridge`. Enjoy !

**Comment by tokamac** [comment]
thanks @emericspiroux it works
but for whatever reason mine was at /usr/lib/node_modules/homebridge
(not in /usr/local/…)

**Comment by mwarkentin** [comment]
@emericspiroux fix worked for me too on OSX 10.12.

**Comment by ihatetoregister** [comment]
@emericspiroux fix worked for me as well on Raspberry Pi Zero W with:
node 6.11.0
homebridge 0.4.29

**Comment by 20Koen02** [comment]
@emericspiroux fix worked on Raspberry Pi 3 B (running Raspbian Stretch November 2017)
node 8.10.0
homebridge 0.4.38

**Comment by mourraille** [comment]
Worked for me as well ! applying those commands at /usr/lib/node_modules/homebridge
(not in /usr/local/…)

**Comment by tomldickson** [comment]
Same problem here; the docs should be updated .....

**Comment by ChicBrother** [comment]
thx ,solved to .

**Comment by hieutt5** [comment]
I have below error when `sudo npm install --unsafe-perm mdns`

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module                           s/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                           s.js:225:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy                           p/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                           ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-04T09_27_27_352Z-debug.log

**Comment by Nedryland** [comment]
Make sure you have the latest version of npm and nodejs installed.. there are many tutorials on how to do this
