### ISSUE TITLE
Homebridge is working but no accessories

### ISSUE THREAD

**Issue by DiederikDeConinck** [nfarina/homebridge#908]
Hi!

I installed homebridge and two plugins and it seems to work but unfortunately I don't see any accessories in the Home app when I try to add one. 

root@raspberrypi:/home/pi# homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[11/9/2016, 11:32:52 AM] Loaded plugin: homebridge-gardendoor
[11/9/2016, 11:32:53 AM] Registering accessory 'homebridge-gpio.GPIO'
[11/9/2016, 11:32:53 AM] ---
[11/9/2016, 11:32:55 AM] Loaded plugin: homebridge-nefit-easy
[11/9/2016, 11:32:55 AM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[11/9/2016, 11:32:55 AM] ---
[11/9/2016, 11:32:55 AM] Loaded config.json with 2 accessories and 0 platforms.
[11/9/2016, 11:32:55 AM] ---
[11/9/2016, 11:32:55 AM] Loading 2 accessories...
[11/9/2016, 11:32:55 AM] [Thermostaat] Initializing NefitEasy accessory...
[11/9/2016, 11:32:55 AM] [GPIO4] Initializing GPIO accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[11/9/2016, 11:32:55 AM] Homebridge is running on port 51826.

and here's my config.json:

{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "accessories": [{
                "accessory": "NefitEasy",
                "name": "Thermostaat",
                "options": {
                        "serialNumber": "619XXX",
                        "accessKey": "SEt2gXXX",
                        "password": "BuXXX"
                }
    },
        { "accessory": "GPIO",
                "name": "GPIO4",
                "pin": 7,
                "duration": 4000
        }]
}

How is this possible? It worked two hours ago when I had only installed the nefit-easy plugin.
I also tried to run it when the pi boots but I have undone all those things.
Kind regards!

**Comment by rhapsfx** [comment]
Hello
I have the same issue on my side. All plugin loaded. Nest thermostat is detected. Scan HomeKit code is shown, home bridge running, Temperature set... but no accessory found

**Comment by DiederikDeConinck** [comment]
Autostart doesn't work, but if you're having the same issue, you have to reinstall raspbian and install homebridge again. Don't forget to copy your config.json file. If I use the Homebridge system service, it starts but I can't use my relay board (through homebridge-gpio-wpi). Have you running it yet?

**Comment by mogeryt** [comment]
Try running 'sudo DEBUG=* homebridge' and post the logs please.

**Comment by jeylites** [comment]
I'm aware that I had two of the same names and that led to Homebridge crashing. Since then I have fixed the issue but I'm unable to get it to work again. Below are my logs. Moving forward, what is the fix?


pi@raspberrypi:~ $ sudo DEBUG=* homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[4/25/2017, 1:48:11 PM] Loaded plugin: homebridge-edomoticz
[4/25/2017, 1:48:11 PM] Registering accessory 'homebridge-edomoticz.eDomoticz'
[4/25/2017, 1:48:11 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[4/25/2017, 1:48:11 PM] ---
[4/25/2017, 1:48:11 PM] Loaded plugin: homebridge-mqtt-switch-tasmota
[4/25/2017, 1:48:11 PM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[4/25/2017, 1:48:11 PM] ---
[4/25/2017, 1:48:11 PM] config.json (/root/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +14ms
  EventedHTTPServer Server listening on port 34039 +39ms
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:539:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:189:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:189:7)
    at EventedHTTPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
pi@raspberrypi:~ $

**Comment by jeylites** [comment]
Nevermind. Found a fix thanks to @Wildcat1
[](https://github.com/nfarina/homebridge/issues/725#issuecomment-236718573)
