### ISSUE TITLE
Error - Homebridge Crash

### ISSUE THREAD

**Issue by farberm** [nfarina/homebridge#913]
Any help with this error would be great. Node js 6.7, npm3. plugins - sonos, indigo, nest and alarmdotcom

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETDOWN 192.168.1.33:1400 - Local (192.168.1.22:54365)
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at connect (net.js:874:16)
    at net.js:963:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by KhaosT** [comment]
"ENETDOWN: A socket operation failed because the network was down." It looks like the network is down.
