### ISSUE TITLE
Error after upgrading to Node 7.1 and NPM 3.10.9

### ISSUE THREAD

**Issue by farberm** [nfarina/homebridge#916]
Any help would be terrific.

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:369:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at IndigoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/index.js:215:13)
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:269:32
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/homebridge-indigo/index.js:240:29
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:269:32
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:44:16
    at IndigoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/index.js:288:17)
    at IndigoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/index.js:362:17)
    at /usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:906:35
    at _arrayEach (/usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:85:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:898:17)
    at Request._callback (/usr/local/lib/node_modules/homebridge-indigo/node_modules/async/lib/async.js:44:16)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-indigo/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)

**Comment by cflurin** [comment]
Try reinstalling homebridge
```sh
sudo npm install -g homebridge --unsafe-perm
```

**Comment by farberm2** [comment]
I did. It appears that I somehow have auto launch running and there are two versions of it running. Working on solving that
