### ISSUE TITLE
How to change homebridge name and pincode ?

### ISSUE THREAD

**Issue by khazaee** [nfarina/homebridge#919]
Hi !
i want change homebridge name in add accessory and pincode please help me !!!

Tnx

**Comment by maragelis** [comment]
It's in the config file under home/.homebridge/config.json

**Comment by alexlabs** [comment]
edit  ~/.homebridge/config.json
example:

{
"bridge":
{
"name": "**## Homebridge changehere**",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "## **031-45-154changehere**"
},

**Comment by cerniuk** [comment]
@alexlabs doesn't that rewire the closure after the 
},

of 

}

?

**Comment by cerniuk** [comment]
@alexlabs although the JSON was not valid, I tried it anyway and the Homebridge server gave me errors:

[9/5/2017, 12:48:46 AM] Registering platform 'homebridge-server.Server'
[9/5/2017, 12:48:46 AM] ---
[9/5/2017, 12:48:46 AM] There was a problem reading your config.json file.
[9/5/2017, 12:48:46 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[9/5/2017, 12:48:46 AM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


Here is valid JSON version of what you had (don't promise it works and in fact it doesn't..., its just a valid JSON format of the original):

{
	"bridge": {
		"name": "Homebridge changehere",
		"username": "CC:22:3D:E3:CE:30",
		"port": "51826",
		"pin": " 031-45-154 changehere"
	}
}

**Comment by shidevil** [comment]
Change here means u change the digit. Not to copy and paste everything.

**Comment by VinnieSims** [comment]
Ok, when I type in  ~/.homebridge/config.json to edit my pin, I get a "bash: /home/pi/.homebridge/config.json: Permission denied" statement. How do I fix this?

**Comment by maragelis** [comment]
sudo nano ~/.homebridge/config.json

**Comment by VinnieSims** [comment]
Thank you @maragelis - I will try this tonight. Can I just put any number I want in for the pin?

**Comment by VinnieSims** [comment]
Ok, now I'm having an issue with the plugins. I type in 'homebridge" and get this error:
<img width="704" alt="screen shot 2018-07-16 at 1 16 14 pm" src="https://user-images.githubusercontent.com/29235817/42773166-71f87328-88fa-11e8-997c-432dbbe1c78f.png">

**Comment by alessandrocroci** [comment]
copy here your config.json..

**Comment by VinnieSims** [comment]
Thank you, I got it to work so far. If I have issues I will contact you guys again.
