### ISSUE TITLE
Homebridge builds but then doesn't run

### ISSUE THREAD

**Issue by shokk** [nfarina/homebridge#929]
$ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Camera.js:28
  let options = {
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
$

**Comment by shokk** [comment]
npm is set to use python2.7 by default. I'm currently at python 2.7.8
OS is CentOS 6.8

**Comment by shokk** [comment]
Fixed. Nodejs version needed to be above 5.0. Installed nodejs from git and used "n stable" to set it to 7.0. Everything compiles and runs now.

**Comment by Shugabuga** [comment]
By the way you should close this, since it's resolved.
