### ISSUE TITLE
FreeNas 9.3 - Jail Installation

### ISSUE THREAD

**Issue by dasoutherland** [nfarina/homebridge#933]
Ive followed this quick tutorial and everything seemed to go smoothly. 
https://github.com/nfarina/homebridge/wiki/FreeNAS-9.3-and-9.10-Jail-Installation

Im and now at a point where I do not see the ~/.hombridge directory in Finder when browsing the file system on the freenas machine. I can however find the installation here...
smb://homeserver/mediashare/jails/homekitjail/usr/local/lib/node_modules/homebridge
In there I can see the config-sample.json but I don't have the correct permissions to rename and/or change the contents.

I am new to this so any help would be appreciated. I am trying to get connected to Wink.
Thanks again.

**Comment by dasoutherland** [comment]
I found the correct directory for ~/.homebridge
Now I'm having to figure out how to change permissions so that I can edit the config.json file.

**Comment by dasoutherland** [comment]
Here is where Im at now.

`[11/19/2016, 4:40:58 PM] No plugins found. See the README for information on ins
talling plugins.                                                                
[11/19/2016, 4:40:58 PM] Loaded config.json with 0 accessories and 1 platforms. 
[11/19/2016, 4:40:58 PM] ---                                                    
[11/19/2016, 4:40:58 PM] Loading 1 platforms...                                 
/usr/local/lib/node_modules/homebridge/lib/api.js:118                           
      throw new Error("The requested platform '" + name + "' was not registered 
by any plugin.");                                                               
      ^                                                                         
                                                                                
Error: The requested platform 'Wink' was not registered by any plugin.          
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)  
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.
js:281:45)                                                                      
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)  
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10) 
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge
:17:22)                                                                         
    at Module._compile (module.js:570:32)                                       
    at Object.Module._extensions..js (module.js:579:10)                         
    at Module.load (module.js:487:32)                                           
    at tryModuleLoad (module.js:446:12)                                         
    at Function.Module._load (module.js:438:3)                                  
root@homekitjail:/ #                                `

**Comment by dasoutherland** [comment]
An that is with 
npm install -g homebridge-wink
installed.

**Comment by dasoutherland** [comment]
Any help would be appreciated. 

This is where Im currently at..
`homebridge` pulls this..
<img width="571" alt="screen shot 2016-11-21 at 10 02 29 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509369/3fd25d30-b036-11e6-9bf4-acbdb40a8d75.png">

`pm2 start homebridge -- -D` pulls this..
<img width="578" alt="screen shot 2016-11-21 at 10 04 22 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509394/880ad71c-b036-11e6-872f-dd72c970b242.png">

`npm install -g homebridge-wink` pulls this, and I have a homebridge-wink directory.
<img width="574" alt="screen shot 2016-11-21 at 10 05 42 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509437/c3aeb626-b036-11e6-9647-b84371e33ad8.png">

My node version is 6.9.1
My npm version is 3.10.9

`pm2 list` shows the service not running.
<img width="569" alt="screen shot 2016-11-21 at 10 07 50 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509475/037a60b6-b037-11e6-9002-3a2dd6cf9d30.png">

**Comment by KhaosT** [comment]
Try edit your config file and change "wink" to "Wink"?

**Comment by dasoutherland** [comment]
Same error.
`[11/21/2016, 10:13:47 PM] No plugins found. See the README for information on in
stalling plugins.                                                               
[11/21/2016, 10:13:47 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/21/2016, 10:13:47 PM] ---                                                   
[11/21/2016, 10:13:47 PM] Loading 1 platforms...                                
/usr/local/lib/node_modules/homebridge/lib/api.js:118                           
      throw new Error("The requested platform '" + name + "' was not registered 
by any plugin.");
Error: The requested platform 'Wink' was not registered by any plugin.          
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)  
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.
js:281:45)                                                                      
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)  
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10) 
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge
:17:22)                                                                         
    at Module._compile (module.js:570:32)                                       
    at Object.Module._extensions..js (module.js:579:10)                         
    at Module.load (module.js:487:32)                                           
    at tryModuleLoad (module.js:446:12)                                         
    at Function.Module._load (module.js:438:3)`

**Comment by dasoutherland** [comment]
I was missin some code.

`root@HKJail:/ # homebridge                                                                                                          
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.                                             
*** WARNING *** Please fix your application to use the native API of Avahi!                                                         
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>                                       
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple B
onjour compatibility layer of Avahi.                                                                                                
*** WARNING *** Please fix your application to use the native API of Avahi!                                                         
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>                  
[11/21/2016, 10:18:14 PM] ====================                                                                                      
[11/21/2016, 10:18:14 PM] ERROR LOADING PLUGIN homebridge-wink:                                                                     
[11/21/2016, 10:18:14 PM] TypeError: Path must be a string. Received null                                                           
    at assertPath (path.js:7:11)                                                                                                    
    at Object.dirname (path.js:1324:5)                                                                                              
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)                     
    at Module._compile (module.js:570:32)                                                                                           
    at Object.Module._extensions..js (module.js:579:10)                                                                             
    at Module.load (module.js:487:32)                                                                                               
    at tryModuleLoad (module.js:446:12)                                                                                             
    at Function.Module._load (module.js:438:3)                                                                                      
    at Module.require (module.js:497:17)                                                                                            
    at require (internal/module.js:20:19)                                                                                           
[11/21/2016, 10:18:14 PM] ====================                                                                                      
[11/21/2016, 10:18:14 PM] No plugins found. See the README for information on installing plugins.                                   
[11/21/2016, 10:18:14 PM] Loaded config.json with 0 accessories and 1 platforms.                                                    
[11/21/2016, 10:18:14 PM] ---                                                                                                       
[11/21/2016, 10:18:14 PM] Loading 1 platforms...                                                                                    
/usr/local/lib/node_modules/homebridge/lib/api.js:118                                                                               
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");                                                                                                                                    
Error: The requested platform 'Wink' was not registered by any plugin.                                                              
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)                                                      
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:281:45)                                          
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)                                                      
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)                                                     
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)                                             
    at Module._compile (module.js:570:32)                                                                                           
    at Object.Module._extensions..js (module.js:579:10)                                                                             
    at Module.load (module.js:487:32)                                                                                               
    at tryModuleLoad (module.js:446:12)                                                                                             
    at Function.Module._load (module.js:438:3)`

**Comment by KhaosT** [comment]
Can you try run homebridge with ``homebridge -P /usr/local/lib/node_modules/``? Also can you post content of ``ls -al /usr/local/lib/node_modules/``

**Comment by dasoutherland** [comment]
I was missing some code..

<img width="925" alt="screen shot 2016-11-21 at 10 20 35 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509731/cb033102-b038-11e6-83b0-9b57430eaa91.png">

**Comment by KhaosT** [comment]
Ah, so it found wink plugin but due to configuration problem it crashes 😅

**Comment by dasoutherland** [comment]
`homebridge -P /usr/local/lib/node_modules/`

pulls this..

<img width="919" alt="screen shot 2016-11-21 at 10 21 48 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509759/fc3673c4-b038-11e6-806a-37dd7c5fa778.png">

**Comment by dasoutherland** [comment]
`ls -al /usr/local/lib/node_modules/`

<img width="917" alt="screen shot 2016-11-21 at 10 22 57 pm" src="https://cloud.githubusercontent.com/assets/23044278/20509776/1d8fb6fc-b039-11e6-8079-7abd45535cda.png">

**Comment by dasoutherland** [comment]
Think it has something to do with the client id or api?

**Comment by KhaosT** [comment]
@dasoutherland it's a problem with homebridge-wink. You can try workarounds at [there](https://github.com/KraigM/homebridge-wink/issues/65#issuecomment-260552781) or open a new issue with them. Homebridge is function correctly. I'll close this issue now.

**Comment by dasoutherland** [comment]
Plugin Issue? Thanks!
I appreciate your help!!
