### ISSUE TITLE
issue with loading on boot with init.d

### ISSUE THREAD

**Issue by vincentblokker** [nfarina/homebridge#942]
Ive got Homebridge working nicely. Login with SSH and type the command 'homebridge' and it starts with all the stuff I want. Everything works.
The only thing not working is to start at boot. Ive got the feeling that the start script is already running but my DHCP server have not given a ip adres. But Im not a technical guy, im the UX'er ;)

Below is the homebridge.log and the init.d/homebridge script

Love to hear what is going wrong

Content from homebridge.log:
[11/22/2016, 12:58:55 PM] Loaded plugin: homebridge-evohome
[11/22/2016, 12:59:03 PM] Registering platform 'homebridge-evohome.Evohome'
[11/22/2016, 12:59:03 PM] ---
[11/22/2016, 12:59:04 PM] Loaded plugin: homebridge-ifttt
[11/22/2016, 12:59:04 PM] Registering platform 'homebridge-ifttt.IFTTT'
[11/22/2016, 12:59:04 PM] ---
[11/22/2016, 12:59:05 PM] Loaded plugin: homebridge-nest
[11/22/2016, 12:59:06 PM] Registering platform 'homebridge-nest.Nest'
[11/22/2016, 12:59:06 PM] ---
[11/22/2016, 12:59:07 PM] Loaded plugin: homebridge-netatmo
[11/22/2016, 12:59:07 PM] Registering platform 'homebridge-netatmo.netatmo'
[11/22/2016, 12:59:07 PM] ---
[11/22/2016, 12:59:11 PM] Loaded plugin: homebridge-sonos
[11/22/2016, 12:59:11 PM] Registering accessory 'homebridge-sonos.Sonos'
[11/22/2016, 12:59:11 PM] ---
[11/22/2016, 12:59:11 PM] Loaded config.json with 1 accessories and 4 platforms.
[11/22/2016, 12:59:11 PM] ---
[11/22/2016, 12:59:11 PM] Loading 4 platforms...
[11/22/2016, 12:59:11 PM] [netatmo platform] Initializing netatmo platform...
[11/22/2016, 12:59:11 PM] [netatmo platform] Creating NetatmoPlatform...
[11/22/2016, 12:59:11 PM] Initializing Nest platform...
[11/22/2016, 12:59:11 PM] Fetching Nest devices.
[11/22/2016, 12:59:11 PM] [IFTTT] Initializing IFTTT platform...
[11/22/2016, 12:59:11 PM] [IFTTT] Loading accessories...
[11/22/2016, 12:59:11 PM] [IFTTT] Found: Accessory 1
[11/22/2016, 12:59:11 PM] [IFTTT] Loading service: A1-1, subtype: T1-1OnT1-1Off
[11/22/2016, 12:59:11 PM] [IFTTT] Loading service: A1-2, subtype: T1-2OnT1-2Off
[11/22/2016, 12:59:11 PM] [IFTTT] Loading service: A1-3, subtype: T1-3
[11/22/2016, 12:59:11 PM] [IFTTT] Loading service: A1-4, subtype: T1-4
[11/22/2016, 12:59:11 PM] [IFTTT] Initializing platform accessory 'Accessory 1'...
[11/22/2016, 12:59:11 PM] [Evohome] Initializing Evohome platform...
[11/22/2016, 12:59:11 PM] [Evohome] Logging into Evohome...
[11/22/2016, 12:59:11 PM] Loading 1 accessories...
[11/22/2016, 12:59:11 PM] [Woonkamer Speakers] Initializing Sonos accessory...
[11/22/2016, 12:59:32 PM] [Woonkamer Speakers] Found a playable coordinator device at 192.168.2.81 in zone 'Huiskamer' for accessory 'Woonkamer Speakers' in accessory room 'Huiskamer'
[11/22/2016, 12:59:55 PM] Software version for Upstairs Nest Protect is: 3.1rc9
[11/22/2016, 12:59:55 PM] Software version for Downstairs Nest Protect is: 3.1rc9
[11/22/2016, 12:59:55 PM] Initializing platform accessory 'Upstairs Nest Protect'...
[11/22/2016, 12:59:55 PM] Initializing platform accessory 'Downstairs Nest Protect'...
[11/22/2016, 1:00:03 PM] [Evohome] Error during Login: { Error: getaddrinfo ENOTFOUND tccna.honeywell.com tccna.honeywell.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'tccna.honeywell.com',
  host: 'tccna.honeywell.com',
  port: 443 }
[11/22/2016, 1:00:03 PM] [netatmo platform] ERROR - Netatmo: Error: Authenticate error: No response

Code from init.d/homebridge

#!/bin/sh
### BEGIN INIT INFO
# Provides: homebridge
# Required-Start: $network $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge"
user="pi"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

**Comment by crzcrz** [comment]
Do you have systemd on your Pi? If so, consider installing homebridge as a systemd service, as explained [here](https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/). It has a benefit of being much easier to understand than horrendous init.d scripts. (And it waits for the network to be up).

Alternatively, you may set up homebridge as an ifup.d script, which will also ensure, that it's started after the network is fully up, see the first answer [here](http://stackoverflow.com/questions/20478516/how-to-detect-when-networking-initialized-in-etc-init-d-script).

**Comment by vincentblokker** [comment]
changed the setting of my Raspberry Pi3 from a dynamic IP (DHCP) to a static IP and the problem was fixed.
