### ISSUE TITLE
Unexpected Failure. Homebridge Running??

### ISSUE THREAD

**Issue by dasoutherland** [nfarina/homebridge#950]
I add two new light bulbs to my wink setup. 
I restarted homebridge by running the command `homebridge`
Once did that I received this error in the screen shot and now the accessories, nest and hombridge hub are not responding the in the HomeKit Home App.

<img width="943" alt="screen shot 2016-11-25 at 8 03 35 pm" src="https://cloud.githubusercontent.com/assets/23044278/20637125/af48ee06-b34a-11e6-99e3-ca0fc75fdfb3.png">

**Comment by dasoutherland** [comment]
@KhaosT @tekuonline

**Comment by dasoutherland** [comment]
Based on the info below, I assume Homebridge isn't running.

`root@homekitjail:/ # homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/25/2016, 11:07:23 PM] Loaded plugin: homebridge-nest
[11/25/2016, 11:07:23 PM] Registering platform 'homebridge-nest.Nest'
[11/25/2016, 11:07:23 PM] ---
[11/25/2016, 11:07:23 PM] Loaded plugin: homebridge-wink
[11/25/2016, 11:07:23 PM] Registering platform 'homebridge-wink.Wink'
[11/25/2016, 11:07:23 PM] ---
[11/25/2016, 11:07:23 PM] Loaded config.json with 0 accessories and 2 platforms.
[11/25/2016, 11:07:23 PM] ---
[11/25/2016, 11:07:23 PM] Loading 2 platforms...
[11/25/2016, 11:07:23 PM] [Wink] Initializing Wink platform...
[11/25/2016, 11:07:23 PM] [Wink] Fetching Wink devices.
[11/25/2016, 11:07:23 PM] Initializing Nest platform...
[11/25/2016, 11:07:23 PM] Fetching Nest devices.
[11/25/2016, 11:07:24 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 521782, Name Hub
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146095, Name Master Bedroom Lamp
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146099, Name Front Porch Light
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146104, Name Living Room Lamp
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146109, Name Bryce's Lamp
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146163, Name Kitchen Can Lights
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146186, Name Hallway Can Light
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2146275, Name Kitchen Sink Light
[11/25/2016, 11:07:24 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 521893, Name Wink Relay
[11/25/2016, 11:07:24 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 521893, Name Gang
[11/25/2016, 11:07:24 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 521893, Name Wink Relay's Bottom Button
[11/25/2016, 11:07:24 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 521893, Name Wink Relay's Top Button
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group binary_switches, ID 296550, Name Top Light Load
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group binary_switches, ID 296549, Name Bookshelf
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2185632, Name Christmas Tree
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group binary_switches, ID 310802, Name TV
[11/25/2016, 11:07:24 PM] [Wink] Device Added - Group light_bulbs, ID 2195859, Name Kitchen Table Light
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Master Bedroom Lamp'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Front Porch Light'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Living Room Lamp'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Bryce's Lamp'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Kitchen Can Lights'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Hallway Can Light'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Kitchen Sink Light'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Top Light Load'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Bookshelf'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Christmas Tree'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'TV'...
[11/25/2016, 11:07:24 PM] [Wink] Initializing platform accessory 'Kitchen Table Light'...
[11/25/2016, 11:07:24 PM] Software version for Hallway Thermostat (Home) is: 5.6-7
[11/25/2016, 11:07:24 PM] Temperature unit for Hallway Thermostat (Home) is: Fahrenheit
[11/25/2016, 11:07:24 PM] Current temperature for Hallway Thermostat (Home) is: 74 F
[11/25/2016, 11:07:24 PM] Current humidity for Hallway Thermostat (Home) is: 40%
[11/25/2016, 11:07:24 PM] Target temperature for Hallway Thermostat (Home) is: 72 F
[11/25/2016, 11:07:24 PM] Target heating for Hallway Thermostat (Home) is: Heating/Cooling
[11/25/2016, 11:07:24 PM] Away for Hallway Thermostat (Home) is: 0
[11/25/2016, 11:07:24 PM] Initializing platform accessory 'Hallway Thermostat (Home)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1283:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by KhaosT** [comment]
Yeah homebridge crashes because mdns failed to register service. Please make sure you installed avahi before using homebridge. Also try reboot the device, sometime avahi got put into strange state.

**Comment by prappe** [comment]
I'm getting the same issue, even after reinstalling avahi (and everything that goes with it), reinstalling homebridge, etc. several times, rebooting, making sure the dbus daemon was running, everything. Just for reference, I'm running this on the Windows 10 Ubuntu subsystem, since it's all I have, and node-gyp on Windows itself hates me.
Taking a look at the open other issues, it seems like a fairly common problem; understandably so, since the error message seems pretty unhelpful. However, if there's anything that someone finds out that could fix it, I'm happy to try.

**Comment by dasoutherland** [comment]
Avahi is installed. After my initial post I tried the common fix of
Stopping homebridge
Deleting persist & accessories folder
Delete my home from the home app. 
Reboot the server running homebridge. 
Start homebridge. 

Still getting the error.

**Comment by KhaosT** [comment]
If that's the case, I'd encourage filling an issue at [node-mdns](https://github.com/agnat/node_mdns) and hopefully the author will be able to help.

**Comment by dasoutherland** [comment]
Thanks @KhaosT . I've created an issue there.
