### ISSUE TITLE
Please help config.json file written in this way, why is it wrong?

### ISSUE THREAD

**Issue by lylus** [nfarina/homebridge#973]
> {
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        "platforms": [{
                "platform": "AqaraPlatform",
                "sid": ["f0b429997e53"],
                "password": ["1ED3390E39594BAC"]
        }]
}

**This is the result of the operation.**

[12/4/2016, 8:15:06 AM] Loaded plugin: homebridge-homeassistant
[12/4/2016, 8:15:06 AM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[12/4/2016, 8:15:06 AM] ---
[12/4/2016, 8:15:06 AM] Loaded config.json with 0 accessories and 1 platforms.
[12/4/2016, 8:15:06 AM] ---
[12/4/2016, 8:15:06 AM] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'AqaraPlatform' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by KhaosT** [comment]
If this is all the logs then you didn't install the "AqaraPlatform". Please follow the plugin instruction to install the plugin and try again.

**Comment by lylus** [comment]
All right, thanks for your reply.

**Comment by mogeryt** [comment]
Type 'npm install -g homebridge-aqara' and try running again.
