### ISSUE TITLE
There was a problem reading your config.json file

### ISSUE THREAD

**Issue by saqoos** [nfarina/homebridge#979]
hello there,
It is my first time using node js, can anyone help me with this issue.
when i type homebridge on my terminal i get this message:

[12/6/2016, 1:30:09 PM] Loaded plugin: homebridge-harmonyhub
[12/6/2016, 1:30:09 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[12/6/2016, 1:30:09 PM] ---
[12/6/2016, 1:30:09 PM] There was a problem reading your config.json file.
[12/6/2016, 1:30:09 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[12/6/2016, 1:30:09 PM]
/usr/local/lib/node_modules/homebridge/lib/server.js:197
throw err;
^

SyntaxError: Unexpected token “
at Object.parse (native)
at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:974:3

I followed the instructions on https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-OSX and have succesfully installed homebridge and and harmonyhub plug ins as you can see. And i have placed my config.json file in /usr/local/lib/node_modules/homebridge and i have validated the file on
http://jsonlint.com.

my config.json file:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"description": "This .",
"platforms": [{
	"platform": "HarmonyHub",
	"name": "Harmony Hub"
}]
}

I cant find the issue here, if anyone had this before can you please help me.
just to clarify Im installing homebridge on macos Sierra and using atom for text edit. my homebridge file is in node_modules (exact path /usr/local/lib/node_modules/)

**Comment by Neelrp12** [comment]
Try this
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}]
}

**Comment by saqoos** [comment]
I've tried it, it didnt work :(

**Comment by snowdd1** [comment]
If it complains about curly quotes `“` use straight ones `"` (and another editor if yours is auto-changing those)  
See your original post. The quotes there are slanted, while the config.json (you obviously modified for privacy purposes) had none of those.

**Comment by saqoos** [comment]
I went ahead and deleted homebridge and reinstalled it, I get this message when i type homebridge.


[12/8/2016, 1:50:24 PM] No plugins found. See the README for information on installing plugins.
[12/8/2016, 1:50:24 PM] There was a problem reading your config.json file.
[12/8/2016, 1:50:24 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[12/8/2016, 1:50:24 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token “ in JSON at position 125
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


I dont know why im getting this error term ( SyntaxError: Unexpected token “ in JSON at position 125 ) although i deleted all my config.json file even the sample.

after that i went ahead and used another editor and checked it with jsonlint.com save it in /usr/local/lib/node_modules/homebridge , and ran homebridge in terminal again with no result.

**Comment by Neelrp12** [comment]
copy this into terminal 
launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist

then run homebridge by typing homebridge in terminal

**Comment by saqoos** [comment]
i got this message : /Users/Tom/Library/LaunchAgents/com.homebridge.server.plist: No such file or directory

nothing changed when i typed homebridge afterwards.

**Comment by Slip7000** [comment]
@saqoos  did you manage to resolve you error? because I'm having the same problem.
