### ISSUE TITLE
Homebridge crashing .. Nest issue?

### ISSUE THREAD

**Issue by monty77uk** [nfarina/homebridge#980]
First time poster so sorry if I'm in the wrong place...

Homebridge starts fine but after several hours I get a crash, this is the error:

```
[12/7/2016, 5:41:58 AM] Target heating for Nest02AA01AC09140032 is: 1
[12/7/2016, 5:41:58 AM] Target temperature for Nest02AA01AC09140032 is: 19.332
undefined:1
<html>redirect to <a href="https://czfe21-front01-iad01.transport.home.nest.com/v2/subscribe">https://czfe21-front01-iad01.transport.home.nest.com/v2/subscribe</html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:167:40)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

JSON looks like:

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": "51826",
		"pin": "xxxxxxx"
	},
	"platforms": [{

		"platform": "Nest",
		"username": "xxxxxxxxx",
        "password": "xxxxxxx"
	},
{
         "platform": "BelkinWeMo",
         "name": "WeMo Platform",
         "noMotionTimer": 60,
         "ignoredDevices": []
       }
]
}
```
 
Ideas? TIA
M

**Comment by antypko** [comment]
You got HTML page in response instead of JSON. So, code fails when trying to parse it.

**Comment by KhaosT** [comment]
This is an issue with homebridge-nest.
