### ISSUE TITLE
Weird error on events.js:160 - Any idea how to fix it?

### ISSUE THREAD

**Issue by inzlabs** [nfarina/homebridge#982]
I got this after loading Homebridge, any idea how to fix it?

--

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:10)

--

**Comment by KhaosT** [comment]
It’s either you runs homebridge twice or another problem uses port 51826.

Best Wishes,
Tian

**Comment by inzlabs** [comment]
Hey KhaosT! Thank you for coming so fast to help! I new guy here, quick and final question -I hope- once I boot up the Pi, with Homebridge as a "screen" from the terminal how could I "open homebridge" in order to see what's happening?

**Comment by KhaosT** [comment]
screen -r to recover the detached screen session.

**Comment by SofienAbdeddaim** [comment]
Hello, in windows open task manager and close nodejs after run it again it's work with me.

**Comment by jimmybrawn** [comment]
@SofienAbdeddaim Windows was bugging indeed and I suspected it was a ninja service to be blocking in background. Tried to kill MAMP services and PHPStorm, but your solution actually worked!
