### ISSUE TITLE
Fails when scanning for plugins and finds linked npm package

### ISSUE THREAD

**Issue by apexskier** [nfarina/homebridge#990]
Error log below. Looking at the actual directory it's breaking on, it's a symlink because I've `npm link`ed the package for development. I'm going to do some debugging and see if I can't fix this.

```
$ npm start

> apexskier-homebridge@0.0.1 start /Users/cameronlittle/Projects/homebridge
> homebridge -D -U config/ -P lib/plugins/

fs.js:906
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Users/cameronlittle/node_modules/bootcamp'
    at Object.fs.statSync (fs.js:906:18)
    at Function.Plugin.installed (/Users/cameronlittle/Projects/homebridge/node_modules/homebridge/lib/plugin.js:170:15)
    at Server._loadPlugins (/Users/cameronlittle/Projects/homebridge/node_modules/homebridge/lib/server.js:108:10)
    at new Server (/Users/cameronlittle/Projects/homebridge/node_modules/homebridge/lib/server.js:43:24)
    at module.exports (/Users/cameronlittle/Projects/homebridge/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/Users/cameronlittle/Projects/homebridge/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/cameronlittle/.nvm/versions/node/v7.2.0/bin/node" "/Users/cameronlittle/.nvm/versions/node/v7.2.0/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! apexskier-homebridge@0.0.1 start: `homebridge -D -U config/ -P lib/plugins/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apexskier-homebridge@0.0.1 start script 'homebridge -D -U config/ -P lib/plugins/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apexskier-homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     homebridge -D -U config/ -P lib/plugins/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apexskier-homebridge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apexskier-homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cameronlittle/Projects/homebridge/npm-debug.log
1 ↩ 
```

**Comment by apexskier** [comment]
Nevermind, my symlink was broken.
