### ISSUE TITLE
Stops running after a few days

### ISSUE THREAD

**Issue by MatGriffin** [nfarina/homebridge#991]
Been monitoring this for a few weeks and after a few days Homebridge stops with the following int he error log, any ideas?

`    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)`

**Comment by snowdd1** [comment]
That means after a few days of running the harmonyhub plugin becomes unstable and fails. This has been reported here multiple times. Recommendation to run harmonyhub in a separated instance, so the rest of your home automation stays online.

**Comment by MatGriffin** [comment]
Thanks, appreciate the reply

**Comment by craigdent** [comment]
@snowdd1 how do you go about running it in a separate instance on a raspberry pi3 alongside running the normal homebridge?

**Comment by snowdd1** [comment]
You can start it using a different user or pass it a directory for the configuration files.

**Comment by snowdd1** [comment]
See Readme under *plugin development*
